;〈注意〉
; テープはサポートしません。
; #PRCNT（1F7AH）はサポートしません。

; ;	ＤＯＳモジュール内部エントリ
; ERROR	EQU	286CH

;	バッチ処理バッファ
; BATBF	EQU	2D00H	;バッチ･ファイル用リード･バッファ（2D00H～2DFFH）
; BPRBF	EQU	204BH	;バッチ変数バッファ（204BH～20FEH）


;
; CRTC ports
;
VRAM_TXT_TOP EQU 0F800H ; VRAM上で画面左上を指すアドレス
VRAM_ATR_TOP EQU 0F000H ; アトリビュートの先頭アドレス
CRTC_ADD EQU 0F0H ; CRTCアドレス･ポート
CRTC_VAL EQU 0F1H ; CRTCデータ･ポート
WIDTH_SCREEN EQU 50H ; 80文字モードの1行のバイト数
CURSOR_XY_ADDR EQU FF00H ; カーソルのX,Y座標を保存するアドレス

; Ascii code Constants
CR	EQU	0DH ; Carriage Return
LF	EQU	0AH ; Line Feed
BS	EQU	08H ; Back Space
DEL	EQU	7FH ; Delete
HT  EQU 09H ; Horizontal Tab
VT  EQU 0BH ; Vertical Tab
BEL EQU 07H ; Bell
NP  EQU 0CH ; Formfeed (also: New page NP)
ESC EQU 1BH ; Escape

;〈SLANGについて〉
; SLANGは、特殊ワークのサイズによっては動作しません。
;SLANGの3014H～3015H番地の内容が、
;特殊ワーク上の大局テーブルの先頭アドレスをさしているので、
;特殊ワークのサイズのために動かない場合は、
;若い番地へ移動して対応してください。

	ORG	0000H
	JP	START	;初期化
	ORG	0066H
	JP	START	;NMIでリスタート

	ORG	0100H


;=======================
;汎用バッファ
;=======================


;	0100H（256バイト）
BUFFER:	DS	256


;=======================
;文字列入力バッファ
;=======================


;	0100Hバイト
keyboard_buffer:	DS	256


;=======================
;キー入力バッファ
;=======================


;	0080H（128バイト）
input_key_buffer:	DS	127	;キー入力バッファ（127文字分）
pointer_for_write_key_buffer:	DS	1	;キーを書き込むポインタ（＝0でカラ、＝7FHでいっぱい）

;=======================================
;コントロール･コード･ジャンプ･テーブル
;=======================================


;	0040H（64バイト）
control_code_jump_tabel:
	DW	control_code_NULL	;^＠
	DW	CTL01				;^A 'カーソルを論理行頭へ（-^V）
	DW	control_code_NULL	;^B '前のワードの先頭へ（－^F） '非サポート
	DW	CTLCAN				;^C ^STOP（論理改行＆インサート解除）
	DW	control_code_DELETEL;^D '論理行のカーソル位置の文字の削除（DELキー）
	DW	CTL05				;^E '論理行のカーソル以降削除（－^U）
	DW	control_code_NULL	;^F '次のワードの先頭へ（－^B） '非サポート
	DW	BELL				;^G BELL
	DW	control_code_BS		;^H BS
	DW	control_code_TAB	;^I TAB
	DW	control_code_NULL	;^J LF
	DW	control_code_HOME	;^K HOME
	DW	control_code_CLS	;^L CLR
	DW	CTLCR				;^M CR＋LF
	DW	control_code_NULL	;^N '論理行分割（－^W） '非サポート
	DW	control_code_NULL	;^O '物理行注入（－^Y） '非サポート
	DW	control_code_NULL	;^P
	DW	control_code_NULL	;^Q
	DW	control_code_INS	;^R INS
	DW	control_code_ROLL_UP	;^S 'スクロール･アップ（－^S）
	DW	control_code_ROLL_DOWN	;^T 'スクロール･ダウン（－^T）
	DW	control_code_NULL	;^U '論理行のカーソルより前削除（－^E） '非サポート
	DW	control_code_NULL	;^V 'カーソルを論理行末へ（－^A、最後の文字の次のカーソル位置) '非サポート
	DW	control_code_NULL	;^W '次の行と連結（－^N、,論理行末と次の行の行頭をつなぐ) '非サポート
	DW	control_code_NULL	;^X SELECT
	DW	control_code_NULL	;^Y '物理行削除（－^O） '非サポート
	DW	control_code_NULL	;^Z
	DW	CTLCAN				;^［ ESC
	DW	control_code_Right	;^￥ →
	DW	control_code_Left	;^］ ←
	DW	control_code_Up		;^＾ ↑
	DW	control_code_Down	;^＿ ↓


;=======================================
;カーソル･オフセット計算用テーブル下位
;=======================================
;y座標に対応するカーソル･オフセットを得ます
;カーソル･オフセット←[cursor_offset_for_Y_table＋256＋y座標]×256＋[cursor_offset_for_Y_table＋y座標]


;	0020H（32バイト）
cursor_offset_for_Y_table:	DS	32


;===============================
;システム･スタック･エリア
;===============================


;	00CCH（204バイト）
	DS	256-52
system_stack_area:


;*******	256バイト境界	********


;=======================================
;カーソル･オフセット計算用テーブル上位
;=======================================
; y座標に対応するカーソル･オフセットを得ます。
;カーソル･オフセット←[cursor_offset_for_Y_table＋256＋y座標]×256＋[cursor_offset_for_Y_table＋y座標]


;	0020H（32バイト）
	DS	32


;=======================
;内部ワーク･エリア
;=======================


;	0050H（80バイト）
fcb_buffer:	DS	32	;S-OSのFCBバッファ（[_IBFAD]でポイント）

;	通常（42バイト）
total_number_of_character_display:	DS	2	;画面の表示文字数
cursor_offset_last_top_of_line:	DS	2	;最終行先頭のカーソル･オフセット
vram_address_of_top:	DS	2	;テキストVRAM先頭アドレス（未使用の場合あり）
vram_address_of_top_of_last_line:	DS	2	;最終行先頭のテキストVRAMアドレス（未使用の場合あり）
locate_of_cursor_overlap_character:	DS	1	;カーソルと重なった位置の文字の保存（未使用の場合あり）
screen_width:	DS	1	;＝00Hで40桁、＝FFHで80桁 -> M23では80桁固定なので、常にscreen_width=FFHとなる。
CSRADD:	DS	2	;（行数－1）×256＋桁数
CSRNXI:	DS	1	;256－桁数 '[CSRNX]の初期値 -> M23では桁数80固定なので、CSRNXI=CSRNXとなる。
CSRNYI:	DS	1	;256－行数 '[CSRNY]の初期値-> M23では行数25固定なので、CSRNYI=CSRNYとなる。
CSRNX:	DS	1	;x座標-[_WIDTH] _WIDTHは80
CSRNY:	DS	1	;y座標-[_MXLIN] _MXLINは25
display_cursor_XY_not_use:	DS	2	;カーソル座標（使用しません）
number_of_character_after_CR:	DS	1	;改行してからの文字数（未使用）
insert_mode_flag:	DS	1	;＝00Hで通常、＝FFHでインサート･モード
foreground_color:	DS	1	;前景色
background_color:	DS	1	;背景色
BDR_color:	DS	1	;周辺色
attribute_data:	DS	1	;画面のアトリビュートRAMへ書き込むデータ
real_time_key:	DS	1	;リアル･タイム･キー（未使用の場合あり）
GRAFLG:	DS	1	;＝FFHでグラフィック表示（未使用の場合あり）

vram_size:	DS	2	;VRAMのサイズ÷100H
top_of_special_work_of_vram:	DS	2	;VRAM上の特殊ワークの先頭÷100H
size_of_special_work_of_vram:	DS	1	;VRAM上の特殊ワークのサイズ÷100H
top_of_ram_disk_of_vram:	DS	2	;VRAM上のRAMディスクの先頭÷100H
size_of_ram_disk_of_vram:	DS	2	;VRAM上のRAMディスクのサイズ÷100H
top_of_special_work_of_memory:	DS	1	;メモリ上の特殊ワークの先頭÷100H
size_of_special_work_of_memory:	DS	1	;メモリ上の特殊ワークのサイズ÷100H

;	機種独自（6バイト）
KEYDAT:	DS	2	;ファンクション、アスキー･コードの生データ
IO1FD0:	DS	1	;I／O 1FD0Hのバッファ


	ORG	(($+7FH) & 0FF80H)
;-----------------------
;割り込みルーチン
;-----------------------

;=======================
;キー･スキャン･ルーチン
;=======================

;キー入力割り込み処理
KEYINT:
; 	LD	(KYIRSP),SP
; 	LD	SP,INTSTK	;割り込み用スタック
; 	PUSH	AF
; 	PUSH	HL
; 	PUSH	DE
; 	PUSH	BC

; ;	キーが有効かチェックします
; 	LD	A,(KEYDAT)	;ファンクション
; 	BIT	6,A
; 	JR	NZ,KYIRET	;キーがはなされた
; 	AND	00100000B	;b5
; 	JR	NZ,KYISKP
; 	LD	A,(pointer_for_write_key_buffer)
; 	OR	A
; 	JR	NZ,KYIRET	;バッファにカラでないときは、リピート禁止
KYISKP:
;	キー入力バッファに書き込みます
	; LD	A,(real_time_key)	;Acc←入力文字
	; CALL	write_one_character_to_key_buffer
	; JR	C,KYIRET	;バッファがいっぱいだった

KYIRET:
	; POP	BC
	; POP	DE
	; POP	HL
	; POP	AF
	; DB	31H	;「LD SP,」
KYIRSP:	DS	2
	; EI
	RETI


;キー入力バッファに1文字書き込みます
;入力	Acc←文字
;出力	キー入力バッファ←文字
;	CY＝1でバッファがいっぱいだった
;破壊	AF，HL，DE，BC
;注：
; 割り込み禁止して実行してください。
; キー入力バッファは、00xxHから始まる127バイトで、
;＋127の部分がpointer_for_write_key_bufferにあたります。
write_one_character_to_key_buffer:
	; LD	HL,pointer_for_write_key_buffer
	; LD	E,(HL)
	; LD	D,H	;DE←書き込みポイント
	; LD	(DE),A	;キー入力バッファ←文字
	; INC	E
	; JP	M,PKYBRK
	; LD	(HL),E	;[pointer_for_write_key_buffer]のカウント･アップ
	; OR	A	;CY←0
	RET
PKYBRK:
	; LD	(HL),L	;[pointer_for_write_key_buffer]を元に戻します
	; SCF
	RET


	ORG	(($+0FFH) & 0FF00H)


;*******	256バイト境界	********


;===============================
;ライン･ターミナル･テーブル
;===============================


; 先頭行の行連結情報はxx00Hのアドレスに格納されます。
;行連結情報←LINTTB＋y座標（0～）
; FFHで次の行と連結。
;	0020H（32バイト）
LINTTB:	DS	32


;-----------------------
;S-OSルーチン
;-----------------------

;=======================
;システム･ルーチン
;=======================


;#COLD（1FFDH）の本体
; コールド･スタートして、[_USR]のアドレスにジャンプします。
;[_USR]の内容は、「_HOT」に初期化します。
;注：
; プリンタ非出力モードにします。
; 「RET」命令で、「_HOT」にジャンプします。
; キー入力バッファをカラにして、そのアドレスをDEで渡す。
; 固有の初期化ルーチンの cold_start_entity（全レジスタ破壊）を呼び出します。
; 固有のメッセージ「title_message」を参照します。
COLD:
;	初期化
	LD	SP,(_STKAD)
	DI
	; IM	2
	CALL CRT_INIT			;CRTCの初期化
	EI

;	スタックの設定など
	LD	HL,FFFFH
	LD	(_MEMAX),HL	;使用可能メモリの上限
	LD	HL,system_stack_area
	LD	(_STKAD),HL

;	特殊ワークのサイズの初期化
	LD	A,(size_of_special_work_of_vram)
	LD	L,0
	LD	H,A	;HL←特殊ワークのサイズ
	LD	(_WKSIZ),HL	;[_WKSIZ]の初期化


;	キー入力バッファのクリア
	CALL	clear_key_buffer ; インデックスポインタを0にしているだけ。

;	ディスクのパラメータの初期化
	; LD	HL,000EH ; 
	; LD	(_FATPS),HL
	; LD	HL,0010H ; ディレクトリ情報が記録されているトラック番号
	; LD	(_DIRPS),HL
	; LD	HL,2E00H
	; LD	(_FATBF),HL
	; LD	HL,2F00H ; ディスクI／Oバッファ
	; LD	(_DTBUF),HL
	; LD	A,80 ; 最大トラック数
	; LD	(_MXTRK),A

;	ディスクI／O初期化
	; CALL	SOSSI



;	タイトル表示
	LD	DE,title_message
	CALL _MSX

;	メモリの情報を表示
	CALL _MPRNT
	DB	'MAIN 3000H-',00H
	LD	HL,(_MEMAX)
	DEC	HL
	CALL _print_hex_4_digit
	CALL _MPRNT
	DB	'H',0DH,00H
	CALL _MPRNT
	DB	'WORK 0000H-',00H
	LD	HL,(_WKSIZ)
	DEC	HL
	CALL _print_hex_4_digit
	CALL _MPRNT
	DB	'H',0DH,00H

;	文字列入力バッファの80バイトをクリア
	LD	HL,(_KBFAD)
	LD	E,L
	LD	D,H
	INC	DE	;DE←[_KBFAD]＋1
	LD	BC,79
	LD	(HL),B	;[_KBFAD]←0
	LDIR

;	ホット･スタートへ
	LD	HL,(_USR)
	EX	DE,HL	;DE←ジャンプ先
	LD	HL,_HOT
	PUSH HL	;戻りアドレス（_HOT）
	LD	(_USR),HL	;[_USR]の再設定
	EX	DE,HL	;HL←ジャンプ先
	LD	DE,(_KBFAD)	;DE←[_KBFAD]
	XOR	A
	JP	(HL)	;旧[_USR]の内容にジャンプ

;#BOOT（2036H）の本体
; S-OSを終えます。
;注：フィジカル･ルーチンboot_entity（全レジスタ破壊）を呼び出します。

	DS	3

;コールド･スタート時のメッセージ
title_message:
	DB	'<<<<< S-OS  SWORD >>>>>',CR
	DB	00H


BOOT:
	JP	boot_entity


;===============================
;バージョン･ナンバーの取り出し
;===============================

;#VER（1FF7H）の本体
; Hに機種別情報、LにS-OSのバージョンを返します。
;入力	なし
;出力	H←機種別情報、L←S-OSのバージョン
;破壊	HL
;〈機種別情報〉
;00H	MZ-80K／C／1200
;01H	MZ-700
;02H	MZ-1500
;10H	MZ-80B
;11H	MZ-2000／2200
;12H	MZ-2500
;20H	X1
;21H	X1turbo
;22H	X1（筑紫版）
;30H	PC-8801（ROM）
;31H	PC-8001
;32H	PC-8801（オールRAM）
;40H	FM-7／77
;50H	SMC-777
;60H	PASOPIA
;61H	PASOPIA7
;70H	PC-286
;80H	X68000
;90H	MSX／2／2＋／turboR（ANK専用版）
;91H	MSX／2／2＋／turboR（漢字対応版）
;95H	SORD M23
;〈S-OSのバージョン〉
; SWORDでは、「20H」。
VER:
	PUSH	AF
	PUSH	DE
	PUSH	BC
	LD	HL,9520H	;SORD M23，S-OS V2.0
	POP	BC
	POP	DE
	POP	AF
	RET


;===============
;表示ルーチン
;===============



;#PRNTS（1FF1H）の本体
; スペースを1つ表示します。
;入力	なし
;出力	なし
;破壊	F（実際なし）
PRNTS:
	PUSH	AF
	LD	A,' '
	CALL _PRINT
	POP	AF
	RET


;#LTNL（1FFEH）の本体
; 改行します。
;入力	なし
;出力	なし
;破壊	なし
LTNL:
	PUSH	AF
	LD	A,0DH
	CALL _PRINT
	POP	AF
	RET


;#NL（1FEBH）の本体
; 行頭でなければ、改行します。
;入力	なし
;出力	なし
;破壊	なし
;注：
; 行頭でなければ改行します。
; このサブルーチンを書いて下さい。
NL:
	PUSH DE
	PUSH BC

	CALL CALC_CURSOR_XY ; CURSOR_LOCATEからX,Y座標を計算して、cursor_XY_ADDRに保存する。
	; cursor_XY_ADDRからX座標を取得
	LD	HL,(cursor_XY_ADDR+2)		; HLにX座標をロード (2バイト)
	; cursor_XY_ADDR+2からY座標を取得
	LD	DE,(cursor_XY_ADDR)		; DEにY座標をロード (2バイト)
	OR	A ; フラグをクリア
	CP	L ; X座標が0かチェック
	JR	Z,NLRET	; X座標が0ならリターン
	CALL LTNL ; 改行を実行
NLRET:
	POP	BC
	POP	DE
	RET


;
;#MSG（1FE8H）の本体
; DEレジスタの示すアドレスから0DHが出現するまでアスキーコードとみなし文字列表示する。
;入力	DE←文字列先頭アドレス
;出力	なし
;破壊	F（実際なし）
;注：0DHは表示しません。
; このサブルーチンを完成させてください。
MSG:
	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
MSGLP:
	LD	A,(DE) ; 文字を取得
	CP	0DH ; 改行コードか？
	JR	Z,MSGSKP	; 改行コードなら終了へ
	CALL _PRINT ; 文字を表示
	INC	DE	; アドレスを一つ進める
	JR	MSGLP
MSGSKP:	
	POP	BC
	POP	DE
	POP	HL
	POP	AF
	RET

;#MSX（1FE5H）の本体
; DEレジスタの示すアドレスから00Hが出現するまでアスキーコードとみなし文字列表示する。
;入力	DE←文字列先頭アドレス
;出力	なし
;破壊	F（実際なし）
;注：00Hは表示しません。
MSX:
	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
MSXLP:
	LD	A,(DE) ; 文字を取得
	CP	00H ; 終了コードか？
	JR	Z,MSXSKP	; 終了コードなら終了へ

	CALL PRINT ; 文字を表示
	INC	DE	; アドレスを一つ進める
	JR	MSXLP
MSXSKP:	
	POP	BC
	POP	DE
	POP	HL
	POP	AF
	RET

;#MPRNT（1FE2H）本体
; このサブルーチンをコールした次のアドレスから00Hが出現するまでアスキーコードとみなし、文字列表示する。
;入力	「CALL ＃MPRNT」の次のアドレス～←文字列とみなす
;出力	なし
;破壊	AF，DE（実際AF）
;注：
; 00Hは表示しません。
; 「REDA」などがDE保存を期待しているので、DEを保存します。
; このサブルーチンを完成させてください。
MPRNT:
	EX	(SP),HL	;HL←インライン･パラのアドレス，スタック←HL
	PUSH DE
	PUSH BC
	EX	DE,HL ; DE←インライン･パラのアドレス
	CALL MSX ; DEの指す文字列を表示
MPRRET:
	EX	DE,HL ; HL←インライン･パラのアドレス，DE←元の値
	POP	BC
	POP	DE
	EX	(SP),HL	;スタック←インライン･パラの次のアドレス，HL←元の値
;	XOR	A
	RET

; TAB(1FDFH)の本体
; Bレジスタの値と、カーソルのX座標との差を計算して、その結果の数だけスペースを表示する。
TAB:
	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	CALL CALC_CURSOR_XY ; CURSOR_LOCATEからX,Y座標を計算して、cursor_XY_ADDRに保存する。
	; cursor_XY_ADDRからX座標を取得
	LD	HL,(cursor_XY_ADDR+2)		; HLにX座標をロード (2バイト)
	; Bレジスタの値とX座標との差を計算
	LD	A,B
	SUB	L	; A = B - X座標
	JR	C,TABERR	; 結果が負ならエラー
	LD	L,A	; Lにスペース数をセット
	TABLP2:
	LD	A,' '
	CALL	_PRINT
	DEC	L
	JR	NZ,TABLP2 ; スペース数分ループ
	XOR	A	; CY=0
	JR	TABRET
TABERR:
	SCF	; CY=1
TABRET:
	POP	BC
	POP	DE
	POP	HL
	POP	AF
	RET

; #LPRINT(1FDCH)の本体
; 未実装
LPRINT:
	RET

;===============
;16進数
;===============

;#PRTHX print_hex_2_digit（1FC1H）の本体
; Aレジスタの値を16進2桁で画面に表示する
;入力	Acc←データ
;出力	なし
;破壊	AF
; このサブルーチンを完成させてください。
print_hex_2_digit:
	PUSH AF	;保存
	LD	B,A	;Bにデータを保存
	SRL	A	;上位4ビットを取得
	SRL	A	; さらに1ビット右シフト
	SRL	A	; さらに1ビット右シフト
	SRL	A	; さらに1ビット右シフト
	CALL	ASC	; 上位4ビットを16進数アスキーコードに変換
	CALL	_PRINT	; 文字表示
	LD	A,B	;Bから元のデータを取得
	AND	0FH	; 下位4ビットを取得
	CALL	ASC	; 下位4ビットを16進数アスキーコードに変換
	CALL	_PRINT	; 文字表示
	POP	AF	;復元
	RET


;#print_hex_4_digit（1FBEH）の本体
; HLレジスタの値を16進4桁で表示する。
;入力	HL←データ
;出力	なし
;破壊	AF
; このサブルーチンを完成させてください。
print_hex_4_digit:
	LD	A,H ; HLの上位バイトをAにロード
	CALL	_print_hex_2_digit ; 2桁表示
	LD	A,L ; HLの下位バイトをAにロード
	JP	_print_hex_2_digit ; 2桁表示


;#ASC（1FBBH）の本体
; Aレジスタの下位4ビットの値を16進数で表したときのアスキーコードに変換してAレジスタに格納する。
;入力	Acc下位4ビット←データ
;出力	Acc←16進数表示のアスキーコード
;破壊	AF
; このサブルーチンを書いてください。
ASC:
	AND	0FH	; 下位4ビットを取得
	CP	10
	JR	C,ASCNUM
	ADD	A,'A'-10	; 10以上なら'A'～'F'に変換
	JR	ASCRET ; リターン
ASCNUM:
	ADD	A,'0'	; 0～9なら'0'～'9'に変換
ASCRET:
	RET

;#HEX（1FB8H）の本体
; Aレジスタの内容を16進数で表したときのアスキーコードとしてバイナリに変換し、Aレジスタに格納する。
;入力	Acc←16進数文字(アスキーコードで表現)
;出力	Acc←データ（0～15）
;	CY＝1（Acc＝14）ならエラー
;破壊	AF
;注：
; 小文字に対応。
; 汎用ルーチンconvert_lower_case_to_upper_case（AF破壊）を呼び出します。
HEX:
	CALL	convert_lower_case_to_upper_case
	SUB	'0' ; '0'のコードを引く
	JR	C,HEXERR ; '0'未満はエラー
	CP	10 ; 10未満か？
	JR	C,HEXESC ; 10未満なら正常終了
	CP	10+7	;7＝「A」－（「9」＋1）
	JR	C,HEXERR
	SUB	7 ; 10以上なら'A'～'F'を0～5に変換
	CP	16 ; 16以上はエラー
	JR	NC,HEXERR
HEXESC:	OR	A ; CY←0
	RET

HEXERR:	LD	A,14	;Bad Data
	SCF ; CY←1
	RET

;#2HEX（1FB5H）の本体
; DEレジスタの示すアドレスから2バイトの内容を、2桁の16進数で表現するアスキーコードとして、バイナリに変換し、HLに格納する。エラーがあればキャリフラグがセットされる。
;入力	[DE～]←16進文字2桁
;出力	Acc←データ
;	DEはカウント･アップ（エラーを発生した時点でカウント･アップは停止）
;	CY＝1ならエラー
;破壊	AF，DE
;注：小文字に対応。
; このサブルーチンを完成させてください。
AHEX:
	LD	A,(DE) ; 16進1桁目取得
	CALL	HEX ; 1桁目変換
	JR	C,HEXERR ; エラーならリターン
	INC	DE ; DEカウントアップ
	LD	H,A ; Hに格納
	LD	A,(DE) ; 16進2桁目取得
	CALL	HEX ; 2桁目変換
	JR	C,HEXERR ; エラーならリターン
	INC	DE ; DEカウントアップ
	LD	L,A ; Lに格納
	RET


;#HLHEX（1FB2H）の本体
; DEレジスタの示すアドレスから4バイトの内容を、4桁の16進数で表現するアスキーコードとして、バイナリに変換し、HLに格納する。エラーがあればキャリフラグがセットされる。
;入力	[DE～]←16進文字4桁
;出力	HL←データ
;	DEはカウント･アップ（エラーを発生した時点でカウント･アップは停止）
;	CY＝1ならエラー
;破壊	AF，HL，DE
;注：小文字に対応。
; このサブルーチンを完成させてください。
HLHEX:
	CALL	_2HEX ; 先頭2桁を変換
	JR	C,HEXERR ; エラーならリターン
	LD	H,L ; HLの上位に格納
	CALL	_2HEX ; 次の2桁を変換
	JR	C,HEXERR ; エラーならリターン
	LD	L,A ; HLの下位に格納
	RET



;===============
;スクリーン制御
;===============


;#CSR（2018H）の本体
; カーソル座標を読み出します。
;入力	なし
;出力	L←x座標、H←y座標
;破壊	HL
;注：CALC_CURSOR_XYを呼び出します。
CSR:
	PUSH	AF
	PUSH	DE
	PUSH	BC
	CALL CALC_CURSOR_XY ; CURSOR_LOCATEからX,Y座標を計算して、cursor_XY_ADDRに保存する。
	LD	HL,(cursor_XY_ADDR)		; LにX座標をロード (2バイト)
	POP	BC
	POP	DE
	POP	AF
	RET


;#LOC（201EH）の本体
; HLレジスタの値(L=X座標、H=Y座標)で指定するXY座標へカーソルの位置をセットする。
;入力	L←x座標、H←y座標
;出力	なし
;破壊	AF（実際F）
;注：
; 「WALRUS」がAccの保存を期待しているので、Accは保存します。
; 「ELFES IV」「TANGERINE」などでCYクリアが必要。
; このサブルーチンを完成させてください。
LOC:
	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	; 現在HLが移動したいカーソルの位置を指さしている。
	; PRINT_CURSORはDEに現在のカーソルの位置が入っていることを期待している。
	EX DE,HL	; DE←移動先カーソル位置
	CALL	PRINT_CURSOR ; カーソル位置を設定
	POP	BC
	POP	DE
	POP	HL
	POP	AF
	OR A	;CY←0
	RET


;#SCRN（201BH）の本体
; HレジスタにY座標、LレジスタにX座標を格納してコールすると、画面上におけるその座標の文字を読み込み、Aレジスタに格納する。
;入力	L←x座標、H←y座標
;出力	Acc←文字
;破壊	AF
;注：
; CYをクリアします。
; このサブルーチンを完成させてください。
SCRN:
	PUSH	HL
	PUSH	DE
	PUSH	BC
; VRAMにアクセスして、カーソル位置DEにある通常文字のアスキーコードを得る。
	OUT (0D2H),A ; access to RAM page 1
	LD A,(DE) ; get character
	POP	BC
	POP	DE
	POP	HL
	OR	A	;CY←0
	RET


;#WIDCH（2030H）の本体
; 表示桁数を変更します。SORD M23ではサポートしません。
;入力	Acc←桁数
;出力	なし
;破壊	AF，HL，DE，BC
; CY＝0でリターンします（ディスク･モジュールのため）。
WIDCH:
	OR A	;CY←0
	RET

;LINCH（203CH）の本体
; 表示行数を変更します。 SORD M23ではサポートしません。
;入力	Acc←行数
;	[_WIDTH]参照
;出力	なし
;破壊	AF，HL，DE，BC
LINCH0:
	RET

;=======================
;ビープ音を鳴らします
;=======================


;#BELL（1FC4H）の本体
; ビープ音を鳴らします。
;入力	なし
;出力	なし
;破壊	AF
BELL:
	RET


;=======================
;プリンタ･ルーチン
;=======================


;#LPRNT（1FDCH）本体
; プリンタ1文字出力。SORD M23ではサポートしません。
;入力	Acc←文字
;出力	CY＝1ならエラー（Acc＝1）
;破壊	AF
;注：
; 0DHは、0DH＋0AHに変換します。
; 00H、0AH、1AHは、無視します。
LPRNT:
	RET

;#LPTON（1FD9H）の本体
; 表示をプリンタ出力モードにします。SORD M23ではサポートしません。
;入力	なし
;出力	[_LPSW]←1
;破壊	なし
;注：
LPTON:
	RET

;#LPTOF（1FD6H）の本体
; 表示を非プリンタ出力モードにします。SORD M23ではサポートしません。
;入力	なし
;出力	[_LPSW]←0
;破壊	なし
LPTOF:
	RET


;===============
;入力ルーチン
;===============

;#GETKY（1FD0H）の本体
; キー入力（入力待ちなし、エコー･バックなし）。
;入力	なし
;出力	Acc←文字
;破壊	AF
;注：
; 常にオート･リピートがかかっています。
; フィジカル･ルーチンreal_time_input_key_entity（AF，HL，DE，BC破壊）を呼び出します。
GETKY:
	RET

;#BRKEY（1FCDH）の本体
; ^Cチェックします（入力待ちなし、エコー･バックなし）。
;入力	なし
;出力	ZF＝1なら^Cが押されています
;破壊	AF
;注：
; 常にオート･リピートがかかっています。
; フィジカル･ルーチンreal_time_input_key_entity（AF，HL，DE，BC破壊）を呼び出します。
; ^C（03H）とESC（1BH）をブレイク･キーとみなします。
BRKEY:
	PUSH	HL
	PUSH	DE
	PUSH	BC
	CALL	real_time_input_key_entity
	CP	03H	;^C
	JR	Z,BRKRET
	CP	1BH	;ESC
	JR	Z,BRKRET
	OR	0FFH	;ZF←0，CY←0
BRKRET:
	POP	BC
	POP	DE
	POP	HL
	RET


;#PAUSE（1FC7H）の本体
; ポーズ処理。
; どのタイミングでも、
;^Cが入力されればインライン･パラのアドレスにジャンプします。
;何もキーが押されていなければ、そのままリターンします。
; スペースが押されれば一時停止し、他のキーが押されればリターンします。
;入力	「CALL ＃PAUSE」の次のアドレス←^C入力時の飛び先
;出力	なし
;破壊	AF
PAUSE:
	EX	(SP),HL	;スタック←HL，HL←インライン･パラのアドレス
	PUSH	DE
	PUSH	BC
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	LD	(PAURET),HL	;リターン･アドレス
	LD	(PAUREB),DE	;インライン･パラ
	CALL	_BRKEY
	JR	Z,PAUBRK
	CALL	_GETKY
	CP	' '
	JR	NZ,PAUESC

PAULP:	CALL	_BRKEY
	JR	Z,PAUBRK
	CALL	_GETKY
	OR	A
	JR	Z,PAULP
	CP	' '
	JR	Z,PAULP

PAUESC:	POP	BC
	POP	DE
	POP	HL
	XOR	A
	DB	0C3H	;「JP」
PAURET:	DS	2

PAUBRK:	POP	BC
	POP	DE
	POP	HL
	XOR	A
	DB	0C3H	;「JP」
PAUREB:	DS	2


;#INKEY（1FCAH）の本体
; キー入力（入力待ちあり、エコー･バックなし）。
;入力	なし
;出力	Acc←文字
;破壊	AF
;注：
; フィジカル･ルーチンINKEY_entity（AF，HL，DE，BC破壊）を呼び出します。
INKEY:
	RET


;#FLGET（2021H）の本体
; カーソル表示つき、キー入力（入力待ちあり、エコー･バックなし）。
;入力	なし
;出力	Acc←文字
;破壊	AF
;注：フィジカル･ルーチンinput_one_character_entity（AF，HL，DE，BC破壊）を呼び出します。
FLGET:
	RET

;#GETL（1FD3H）の本体
; 文字列入力。
;入力	DE←キー入力バッファの先頭アドレス
;出力	[DE～]←文字列
;破壊	AF
;注：
; エンド･コードは00H。
; 入力がキャンセルされた場合、「1BH、00H」がバッファに格納されます。
; 入力待ちあり、エコー･バックあり。
; フィジカル･ルーチンinput_line_character_entity（AF，HL，DE，BC破壊)を呼び出します。
GETL:
	RET

;===============================
;ファイル操作（ファイル名処理）
;===============================


;#FPRNT（1F9DH）の本体
; S-OSのFCBバッファのファイル名を表示します（改行しません）。
; ポーズ機能あり。
;入力	S-OSのFCBバッファ（fcb_buffer～）参照
;出力	なし
;破壊	AF，HL，DE，BC
FPRNT:
	LD	DE,fcb_buffer+1

;	プライマリ名の表示
	LD	B,13
FPRLP1:	LD	A,(DE)
	INC	DE
	CALL	_PRINT
	DJNZ	FPRLP1

;	ピリオドの表示
	LD	A,'.'
	CALL	_PRINT

;	拡張子の表示
	LD	B,3
FPRLP2:	LD	A,(DE)
	INC	DE
	CALL	_PRINT
	DJNZ	FPRLP2

	CALL	_PAUSE
	DW	$+2
	RET


;#FSAME（1FA0H）の本体
; ＃FILE（1FA3H）でセットされたファイル名、ファイル属性と、
;DE～にセットされた解析されてないないファイル名（エンド･コード00H）、
;ファイル属性（Acc）を比較します。
;入力	Acc←ファィル属性、DE←文字列（ファイル名）の先頭
;	S-OSのFCBバッファ（fcb_buffer～）参照
;出力	一致すればZF＝1（Acc←0）、不一致ならZF＝0（Acc←8）
;破壊	AF，HL，DE，BC
;注：
; 入力パラメータに、ファイル属性（Acc）が必要。
; CYは常にリセットされています。
FSAME:
;	ファイル属性の比較
	AND	10000111B	;マスク
	LD	B,A	;B←マスクされたファイル属性
	LD	A,(_FTYPE)	;Acc←セットされたFCBのファイル属性
	AND	10000111B	;マスク
	CP	B
	JP	NZ,FSMERR	;ファイル属性が一致しない

;	[BUFFER～]にデバイス名とファイル名を解析してセットします
	CALL	FNAME	;ファイル名を解析します
	RET	C	;デバイス名が異常（エラー3）

;	デバイス名の比較
	LD	A,(_DSK)
	LD	HL,BUFFER
	CP	(HL)
	JR	NZ,FSMERR

;	ファイル名（プライマリ，拡張子）の比較
	LD	DE,fcb_buffer+1	;比較されるファイル名
	LD	HL,BUFFER+1	;比較するファイル名
	LD	A,16
	CALL	CMPFNM	;ファイル名を比較します
	RET	Z

;	一致しませんでした
FSMERR:	LD	A,8	;File not Found
	OR	A	;ZF←0
	SCF
	RET


;#FILE（1FA3H）の本体
; ファイル名を解析して、各ワークにパラメータをセットします。
;入力	Acc←ファィル属性、DE←文字列（ファイル名）の先頭
;出力	[_DSK]←デバイス名、[_FTYPE]←ファイル属性、
;	S-OSのFCBバッファ←変換されたファイル名
;	DEは00Hか「:」のアドレスを示しています。
;	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
;注：
; CY＝0でリターンしています。
; ファイル名はコントロール･コードなどがカットされ、
;「*」は「?」に展開されます。
FILE:
	LD	(_FTYPE),A	;ファイル属性（ファイル名の解析でセットされます）
	LD	(fcb_buffer),A	;FCBのファイル属性部分（＋0）
	CALL	FNAME	;ファイル名を解析します
	RET	C	;デバイス名が異常（エラー3）
	PUSH	DE
	LD	A,(BUFFER)	;Acc←デバイス名
	LD	(_DSK),A
	LD	HL,BUFFER+1	;解析されたファイル名
	LD	DE,fcb_buffer+1	;FCBのファイル名フィールド
	LD	BC,16
	LDIR		;FCBのファイル名部分（＋1～＋16）
	LD	A,20H
	LD	(DE),A	;FCBのパスワード部分（＋17）
	POP	DE
	CALL	SPSKIP	;文字列の空白を読み飛ばします
	XOR	A	;CY←0
	RET


;===============================
;ファイル名処理補助ルーチン
;===============================


;ファイル名を比較します
;入力	DE←比較されるファイル名の先頭、HL←比較するファイル名の先頭、
;	Acc←カウンタ
;出力	ZF＝1なら一致
;破壊	AF，HL，DE，BC
;注：ワイルド･カードの「?」は常に一致とみなします。
CMPFNM:
	LD	B,A	;B←カウンタ
	EX	DE,HL

;	比較ループ
CPFLP:	LD	A,(DE)	;Acc←比較する文字
	CP	'?'
	JR	Z,CPFSKP	;常に一致させます
	CP	(HL)
	RET	NZ	;一致しませんでした
CPFSKP:	INC	DE
	INC	HL
	DJNZ	CPFLP

;	すべて一致
	XOR	A	;ZF←1
	RET


;ファイル名を解析します
;入力	DE←文字列（ファイル名）の先頭
;出力	[BUFFER]←デバイス名、[BUFFER＋1～]←変換されたファイル名
;	DEはカウント･アップされます（区切りでストップ）
;	CY＝1（Acc←エラー･コード）ならエラー
;破壊	AF，HL，DE，BC
FNAME:
;	デバイス名の転送
	CALL	MGETDV	;文字列からデバイス名を取り出します
	CALL	_DVCHK	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	RET	C	;Acc←3 'Bad File Descripter
	LD	HL,BUFFER
	LD	(HL),A	;[BUFFER]←デバイス名
	INC	HL	;HL←BUFFER＋1

;	ファイル名の転送
	CALL	CLRWFG
	LD	B,13	;プライマリ名
FNML11:	CALL	GTFLTR
	LD	(HL),A
	INC	HL
	DJNZ	FNML11
	CALL	SKPPRD
	CALL	CLRWFG
	LD	B,3	;拡張子
FNML12:	CALL	GTFLTR
	LD	(HL),A
	INC	HL
	DJNZ	FNML12
	CALL	SKPPRD

	XOR	A	;CY←0
	RET


;文字列からデバイス名を取り出します
;入力	DE←文字列の先頭アドレス
;出力	Acc←デバイス名（省略時はデフォルト、小文字は大文字に変換）
;	CY＝1ならデバイス名が省略されていました
;	DEはカウント･アップされます
;破壊	AF，DE
MGETDV:
	CALL	SPSKIP	;文字列の空白を読み飛ばします
	LD	A,(DE)
	OR	A
	JR	Z,MGTDV1	;文字列の終わりに達していました
	INC	DE
	LD	A,(DE)
	DEC	DE
	CP	':'
	JR	NZ,MGTDV1	;デバイスが指定されていません

;	デバイスが指定されています
	LD	A,(DE)
	CALL	convert_lower_case_to_upper_case
	INC	DE
	INC	DE
	OR	A	;CY←0
	RET

;	デバイスが指定されていません
MGTDV1:	CALL	_RDVSW
	SCF		;CY←1
	RET


;GTFLTRルーチンの「*」モードを初期化します
;入力	なし
;出力	[WASFLG]←0
;破壊	AF
CLRWFG:
	XOR	A
	LD	(WASFLG),A
	RET


;文字列からファイル名（プライマリ，拡張子）を1文字取り出します
;入力	DE←文字列のアドレス
;出力	Acc←変換された文字（区切りに達した場合はスペースに変換されます）
;	DEはカウント･アップされます（区切りでストップ）
;破壊	AF，DE
;注：
; 00H、0DH、「:」、「.」を区切りとみなします。
; コントロール･コードやスペースはスキップします。
; 「*」フェイズでは「?」を返します。
GFLLP:	INC	DE

GTFLTR:
;	「*」フェイズかチェックします
	LD	A,(WASFLG)
	OR	A
	JR	NZ,GFLWLD

	LD	A,(DE)	;Acc←1文字

;	区切りに達したか調べます
	OR	A	;NUL
	JR	Z,GFLESC
	CP	0DH	;RET
	JR	Z,GFLESC
	CP	':'
	JR	Z,GFLESC
	CP	'.'
	JR	Z,GFLESC

;	コントロール･コードとスペースをスキップします
	LD	A,(DE)
	CP	7FH	;DEL
	JR	Z,GFLLP
	CP	21H	;00H～20H
	JR	C,GFLLP

;	「*」かチェックします
	CP	'*'
	JR	Z,GFLAST

;	通常終了
	INC	DE	;DEのカウント･アップ
	JP	convert_lower_case_to_upper_case

;	「*」を発見しました
GFLAST:	LD	A,0FFH
	LD	(WASFLG),A
	INC	DE

;	「*」フェイズ
GFLWLD:	LD	A,'?'
	RET

;	ピリオドかファイル名の最後に達しました
GFLESC:	LD	A,' '
	RET

;	ワイルド･カード関係
WASFLG:	DS	1	;＝FFHで「*」フェイズ中


;ファイル名のピリオド部（プライマリと拡張子の区切り）をスキップします
;入力	DE←文字列のアドレス
;出力	DEはカウント･アップされます（区切りでストップ）
;破壊	AF，DE
;注：
; 00H、0DH、「:」を区切りとみなします。
; コントロール･コードやスペースはスキップします。
SKPLP:	INC	DE

SKPPRD:
	LD	A,(DE)	;Acc←1文字

;	区切りに達したか調べます
	OR	A	;NUL
	RET	Z
	CP	0DH	;RET
	RET	Z
	CP	':'
	RET	Z

;	ピリオドに達したか調べます
	CP	'.'
	JR	NZ,SKPLP

;	ピリオドをスキップ
	INC	DE
	RET


;=======================
;ファイル操作（テープ）
;=======================
; サポートしません。


;%RDI（2900H）
;テープのインフォメーション･ファイルをロードします
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
RDI:
	LD	A,2
	SCF
	RET


;%TROPN（2903H）
;テープのリード･オープン
;入力	[_DSK]←デバイス名
;出力	ZF＝1（Acc←0）ならファイルが見つかりました
;	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
;注：
; ファイル名解析後呼び出すこと。
; ファイル名の先頭が20Hか0DHの場合は、常に一致とみなします。
TROPN:
	LD	A,2
	SCF
	RET


;%WRI（2906H）
;テープにインフォメーション･ファイルをセーブします
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
WRI:
	LD	A,2
	SCF
	RET


;%TWRD（2909H）
;テープにデータ･ファイルをセーブします
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
TWRD:
	LD	A,2
	SCF
	RET


;%TRDD（290CH）
;テープのデータ･ファイルをロードします
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
TRDD:
	LD	A,2
	SCF
	RET


;%TDIR（290FH）
;テープのディレクトリを表示します
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
TDIR:
	LD	A,2
	SCF
	RET


;-----------------------
;フィジカル･ルーチン
;-----------------------


;===============================
;フィジカル･ルーチン表示関係
;===============================


;1文字入力ルーチン（入力待ちあり、エコー･バックあり、カーソル表示あり）
;入力	なし
;出力	Acc←文字
;破壊	AF，HL，DE，BC
input_one_character_entity:
	CALL	display_cursor
	CALL	_INKEY
	PUSH	AF
	CALL	erase_cursor
	POP	AF
	RET


;===============================
;フィジカル･ルーチン入力関係
;===============================


;文字列入力ルーチン（入力待ちあり、エコー･バックあり、カーソル表示あり）
;入力	DE←入力バッファの先頭アドレス
;出力	[DE～]←入力文字列
;破壊	AF，HL，DE，BC
;注：
; ブレイク･キーが押された場合、入力バッファの先頭に、1BH（，00H）が入ります。
; リターン･キー（0DH）は含まれません。
; 文字列の最後には00Hが入ります。
; バッファは256バイトまで使用します。
; ルーチンの最初と最後で、インサート･モードをクリアします。
; 画面出力時のインサート処理は、高速化のため、このルーチンで処理します。
input_line_character_entity:
	XOR	A
	LD	(insert_mode_flag),A	;[insert_mode_flag]のクリア
	PUSH	DE

GTLP:	CALL	_FLGET
	CP	0DH	;CR
	JR	Z,GTCR
	CP	03H	;^C
	JR	Z,GTBRK
	CP	1BH	;ESC
	JR	Z,GTBRK
	CP	09H	;TAB
	JR	Z,GTTAB
	CALL	GTINS
	CALL	_PRINT
	JR	GTLP

;	ブレイクしました
GTBRK:	CALL	_PRINT
	POP	DE
	LD	A,1BH
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	RET

;	1行入力がありました
GTCR:	POP	DE
	CALL	INPUTL	;カーソル位置は論理行の最後の物理行へ
	XOR	A
	LD	(insert_mode_flag),A
	JP	_LTNL	;改行します

;	タブ処理
GTTAB:	LD	A,(_WIDTH)
	LD	C,A	;C←桁数
	LD	A,(CSRNX)
	ADD	A,C	;Acc←x座標
	LD	B,A	;B←x座標
	AND	11111000B
	ADD	A,8	;Acc←次のタブ位置（仮）
	CP	C
	JR	C,$+3
	LD	A,C	;Acc←次のタブ位置（実際）
	SUB	B	;Acc←次のタブ位置-x座標
	LD	B,A	;B←表示スペース数
	LD	A,' '

GTTLP:	PUSH	BC
	CALL	GTINS
	POP	BC
	DJNZ	GTTLP

	LD	A,09H	;TAB
	CALL	_PRINT
	JR	GTLP

;	インサート･モードなら、1文字インサートします
GTINS:	CP	20H
	RET	C	;コントロール･コードだった
	LD	C,A
	LD	A,(insert_mode_flag)
	OR	A
	LD	A,C
	RET	Z	;インサート･モードでなかった

;	インサート･モードだった
	PUSH	AF

;	初期設定
	LD	A,(_WIDTH)
	LD	L,A
	LD	H,0
	LD	(line_length),HL
	LD	A,(_MXLIN)
	LD	L,0
	LD	H,A
	LD	(final_plus_one_cursor_XY),HL
	CALL	get_offset_from_cursor_XY
	LD	(offset_plus_one_cursor_XY),HL
	CALL	get_Y_next_logical_line
	LD	(next_cursor_XY_top_of_next_logical_line),HL
	CALL	get_offset_from_cursor_XY
	LD	(next_cursor_offset_top_of_next_logical_line),HL
	CALL	_CSR
	LD	(now_cursor_XY),HL
	CALL	get_offset_from_cursor_XY
	LD	(now_cursor_offset),HL
	LD	HL,(next_cursor_offset_top_of_next_logical_line)
	DEC	HL	;HL←行末のカーソル･オフセット
	CALL	read_character_offset_address
	LD	(line_end_character),A
	SUB	' '	;0，0以外
	ADD	A,0FFH	;CY＝0， CY＝1
	SBC	A,A	;00H，FFH
	LD	(cursor_line_end),A
	LD	DE,(now_cursor_offset)
	LD	HL,(next_cursor_offset_top_of_next_logical_line)
	DEC	HL	;HL←行末のカーソル･オフセット
	OR	A
	SBC	HL,DE
	LD	A,H
	OR	L	;0以外，0
	ADD	A,0FFH	;CY＝1，CY＝0
	SBC	A,A	;FFH，00H
	CPL		;00H，FFH
	LD	HL,cursor_line_end
	OR	(HL)
	LD	(HL),A

;	転送します
	LD	DE,(now_cursor_offset)
	LD	HL,(next_cursor_offset_top_of_next_logical_line)
	DEC	HL	;HL←行末のカーソル･オフセット
	OR	A
	SBC	HL,DE
	LD	C,L
	LD	B,H	;BC←転送文字数
	LD	HL,(now_cursor_offset)	;HL←転送元カーソル･オフセット
	LD	E,L
	LD	D,H
	INC	DE	;DE←転送先カーソル･オフセット
	JR	Z,$+5
	; CALL	VBTRNS
	CALL	_CSR
	CALL	get_offset_from_cursor_XY
	LD	A,' '
	CALL	write_character_offset_address
	LD	A,(cursor_line_end)
	OR	A
	JR	NZ,$+4
	POP	AF
	RET

;	1物理行を注入する必要がある場合
	LD	A,(_MXLIN)
	LD	HL,next_cursor_XY_top_of_next_logical_line+1
	SUB	(HL)	;Acc←画面残り物理行数
	JR	Z,GTIRU	;論理的に綱がっている最終物理行が、画面最終物理最終行と等しい
	DEC	A
	JR	Z,write_new_line	;論理的に綱がっている最終物理行が、画面最終物理行の上の行
;	ライン･ターミナル･テーブルの転送
	LD	C,A
	LD	B,0	;BC←転送行数－1
	LD	HL,next_cursor_XY_top_of_next_logical_line+1
	ADD	A,(HL)
	LD	E,A
	LD	D,LINTTB/100H	;DE←転送先
	LD	L,E
	LD	H,D
	DEC	L	;HL←転送元
	LDDR
	EX	DE,HL
	LD	(HL),B	;新行と次の行の連結解除
;	画面の転送
	LD	DE,(next_cursor_offset_top_of_next_logical_line)
	LD	HL,(offset_plus_one_cursor_XY)
	OR	A
	SBC	HL,DE
	LD	DE,(line_length)
;	OR	A
	SBC	HL,DE
	LD	C,L
	LD	B,H	;BC←転送バイト数
	LD	HL,(next_cursor_offset_top_of_next_logical_line)
	EX	DE,HL	;HL←[line_length]，DE←[next_cursor_offset_top_of_next_logical_line]
	ADD	HL,DE
	EX	DE,HL	;HL←転送元，DE←転送先
	; CALL	VBTRNS

;	新行を書き込みます
write_new_line:	LD	HL,(next_cursor_offset_top_of_next_logical_line)
	LD	BC,(line_length)
	LD	A,' '
	; CALL	FILVRM
write_new_line_1:	LD	HL,next_cursor_XY_top_of_next_logical_line+1
	LD	L,(HL)
	DEC	L
	LD	H,LINTTB/100H
	LD	(HL),0FFH	;新物理行と前の物理行を連結
	LD	HL,(next_cursor_offset_top_of_next_logical_line)
	LD	A,(line_end_character)
	CALL	write_character_offset_address
	POP	AF
	RET

;	論理的に綱がっている最終物理行が、画面最終物理最終行と等しい場合
GTIRU:	CALL	control_code_ROLL_UP
	LD	HL,(now_cursor_XY)
	DEC	H
	JP	M,$+6
	CALL	_LOC
	LD	HL,(next_cursor_XY_top_of_next_logical_line)
	DEC	H
	LD	(next_cursor_XY_top_of_next_logical_line),HL
	CALL	get_offset_from_cursor_XY
	LD	(next_cursor_offset_top_of_next_logical_line),HL
	JR	write_new_line_1

line_end_character:	DS	1	;行末の文字
cursor_line_end:	DS	1	;＝FFH（≠0）で行末の文字がスペースでないか、カーソルが行末にあります
line_length:	DS	2	;1行の桁数
now_cursor_XY:	DS	2	;現在カーソル座標
now_cursor_offset:	DS	2	;現在カーソル･オフセット
next_cursor_XY_top_of_next_logical_line:	DS	2	;次の論理行頭カーソル座標
next_cursor_offset_top_of_next_logical_line:	DS	2	;次の論理行頭のカーソル･オフセット
final_plus_one_cursor_XY:	DS	2	;最終＋1のカーソル座標
offset_plus_one_cursor_XY:	DS	2	;最終＋1のカーソル･オフセット


;=======================================
;フィジカル･ルーチン･プリンタ関係
;=======================================


;プリンタ出力モードをオンします
;入力	なし
;出力	[_LPSW]←1
;破壊	AF，HL，DE，BC
;注：旧X1版SWORDと同じく、[#LPSW]に1を書きます。
printer_output_mode_on_entity:
	LD	A,1
	LD	(_LPSW),A

;	#PRINT（1FF4H）のため'
	LD	HL,LPPR
	LD	(_PRINT+1),HL
	LD	HL,LPPR
	LD	(BPRNT+1),HL

	RET


;プリンタ出力モードをオフします
;入力	なし
;出力	[_LPSW]←0
;破壊	AF，HL，DE，BC
printer_output_mode_off_entity:
	XOR	A
	LD	(_LPSW),A

;	#PRINT（1FF4H）のため'
	; LD	HL,PRINT
	; LD	(_PRINT+1),HL
	; LD	HL,BPRNT0
	; LD	(BPRNT+1),HL

	RET


;1文字プリント前処理
LPREB:
	; PUSH	HL
	; LD	HL,PRINT
	; LD	(_PRINT+1),HL
	; LD	HL,BPRNT0
	; LD	(BPRNT+1),HL
	; POP	HL
;	JP	LPPR


;#LPSW（1F7CH）がオンなら、通常表示ルーチンと置き代わります
LPPR:
	CALL	PRINT
	PUSH	AF
	; CALL	_LPRNT
	POP	AF
	RET


;===============================
;フィジカル･ルーチン補助
;===============================


;1行入力します
;入力	DE←バッファのアドレス
;出力	[DE～]←入力文字列
;	カーソルを論理的に綱がっている最後の物理行へ
;破壊	AF，HL，DE，BC
;注：
; 文字列の最後には00Hが入ります。
; バッファは256バイトまで使用します。
INPUTL:
	PUSH	DE	;スタック←入力バッファ

;	一時バッファのクリア
	LD	HL,BUFFER
	LD	DE,BUFFER+1
	LD	BC,255
	LD	(HL),B
	LDIR

;	読み出しアドレスの設定
;出力	DE←現在行の行頭のカーソル･オフセット、BC←現在行の最大文字数
	CALL	get_Y_top_of_logical_line	;論理行頭の座標を得ます
	CALL	get_offset_from_cursor_XY
	EX	DE,HL	;DE←現在行の行頭のカーソル･オフセット
	CALL	get_Y_next_logical_line	;次の論理行の座標を得ます
	DEC	H
	CALL	_LOC	;カーソルを論理的に綱がっている最後の物理行へ
	INC	H
	CALL	get_offset_from_cursor_XY
	OR	A
	SBC	HL,DE
	LD	C,L
	LD	B,H	;BC←現在行の最大文字数

;	一時バッファへ転送します
;入力	DE←現在行の行頭のカーソル･オフセット、BC←現在行の最大文字数
	LD	A,B
	OR	A
	JR	Z,$+5
	LD	BC,255
	LD	HL,BUFFER
	; CALL	INVRM

;	ターミネート処理
; 後ろの00H～20Hの文字は00Hに変換します。
	LD	HL,BUFFER+100H
	LD	BC,0	;B←ループ･カウンタ256，C←ターミネータ00H
INLLP1:	DEC	HL
	LD	A,(HL)
	CP	21H
	JR	NC,INL1ES	;21H～の文字を発見しました
	LD	(HL),C
	DJNZ	INLLP1
INL1ES:

;	入力バッファに転送します
	LD	HL,BUFFER
	POP	DE	;DE←入力バッファ
INLLP2:	LD	A,(HL)
	INC	HL
	LD	(DE),A
	INC	DE
	OR	A
	JR	NZ,INLLP2

	JP	SETPRN


;=======================
;1文字表示ルーチン
;=======================


;^R インサート･モードのオン／オフ
control_code_INS:
	RET


;^＠ 何もしません
control_code_NULL:
	RET


;^I TAB タブ処理
;〈レジスタ･マップ〉
;HL	CSRNX
;D	[_WIDTH]
;E	定数00000111B
;C	現在x負座標
control_code_TAB:
	RET

;	最終桁の場合
CTLTAE:


;^L CLR 画面クリア
;注：フィジカル･ルーチンCLS（AF，HL，DE，BC破壊）を呼び出します。
control_code_CLS:
;	行連結情報のクリア
;	画面のクリア
	CALL	CLS
;	JP	control_code_HOME


;^K HOME カーソル･ホーム位置
control_code_HOME:
	RET


;^￥ → カーソル右移動
control_code_Right:
	RET


;^］ ← カーソル左移動
control_code_Left:
	RET


;^＾ ↑ カーソル上移動
control_code_Up:
	RET


;^＿ ↓ カーソル下移動
control_code_Down:
	RET


;^S スクロール･アップします
control_code_ROLL_UP:
	RET

;^T スクロール･ダウンします
control_code_ROLL_DOWN:
	RET

;^C STOP カーソルを次の行の行頭へ（論理改行）
CTLCAN:
	RET

;^M CR カーソルを次の行の行頭へ（物理改行）
CTLCR:
	RET

;^H BS バック･スペース
control_code_BS:
	RET

;7EH DEL デリート･コード
control_code_DELETEL:
	RET

;^E カーソル位置から行末までクリア
CTL05:
	RET


;^A カーソルを論理行頭へ（－^V）
CTL01:
	RET

;---------------
;独自ルーチン
;---------------


;=======================
;表示ルーチン前処理
;=======================


;表示ルーチンを初期飛び先へジャンプするように設定します
;入力	なし
;出力	なし
;破壊	HL
SETPRN:
	RET


;=======================
;スクリーン制御補助
;=======================


;論理桁位置を得ます
;入力	x座標、桁数参照
;出力	HL←論理桁位置
;破壊	AF，HL，DE，BC
;〈レジスタ･マップ〉
;E	桁数
;C	現在y座標
;BC	ライン･ターミナル･テーブルの先頭＋y座標
;HL	論理桁位置カウンタ
get_logical_column:
	;テキストVRAMのスタートアドレスがF800Hであり、一行の桁数は80dであるので、
	;論理桁位置は、(y座標×80d)+x座標で求められます。
	CALL CALC_CURSOR_XY ; CURSOR_LOCATEからX,Y座標を計算して、cursor_XY_ADDRに保存する。
	LD	HL,(cursor_XY_ADDR) ; 
	RET

;論理行頭の座標を得ます
;入力	なし
;出力	L←0、H←論理行頭のy座標
;破壊	AF，HL
get_Y_top_of_logical_line:
	CALL CALC_CURSOR_XY ; CURSOR_LOCATEからX,Y座標を計算して、cursor_XY_ADDRに保存する。
	LD	HL,(cursor_XY_ADDR+2) ;
	RET


;次の論理行の座標を得ます
;入力	なし
;出力	L←0、H←論理行頭のy座標
;破壊	AF，HL
get_Y_next_logical_line:
	RET


;カーソル座標からオフセット･アドレスを求めます
;入力	L←x座標、H←y座標
;出力	HL←オフセット
;破壊	AF，HL
;注：cursor_offset_for_Y_tableは、y座標→カーソル･オフセット対応表。
get_offset_from_cursor_XY:
	RET


;オフセット･アドレスからカーソル座標を求めます
;入力	HL←カーソル･オフセット
;出力	L←x座標,H←y座標
;破壊	AF，HL
get_cursor_XY_from_offset_address:
	RET


;カーソルのオフセット計算用テーブルを生成します
;入力	[_WIDTH]参照
;出力	[cursor_offset_for_Y_table～]←オフセット
;破壊	AF，HL，DE，BC
;〈レジスタ･マップ〉
;DE	テーブル･アドレス
;BC	定数[_WIDTH]
;HL	カーソル･オフセット
;Acc	ループ･カウンタ
generate_cursor_offset_table:
	RET


;カーソル制御用ワークの初期化
;入力	[_WIDTH]、[_WIDTH]、[_MXLIN]、[vram_address_of_top]参照
;出力	[CSRADD]、[CSRNXI]、[CSRNYI]、[cursor_offset_last_top_of_line]、[total_number_of_character_display]、[vram_address_of_top_of_last_line]、
;	ライン･ターミナル･テーブル初期化
;破壊	AF，HL，DE，BC
initialize_cursor_control_work_area:
	RET


;-------------------------------
;S-OSルーチン（機種依存）
;-------------------------------


;===============
;I／O入出力
;===============


;#INP（202AH）の本体
; I／Oポートにデータを出力。
;入力	なし
;出力	Acc←データ
;破壊	AF
INP:
	PUSH BC
	LD	B,0
	IN	A,(C)
	POP	BC
	RET


;#OUT（202DH）の本体
; I／Oポートからデータを入力。
;入力	Acc←データ
;出力	なし
;破壊	なし
OUTP:
	PUSH BC
	LD	B,0
	OUT	(C),A
	POP	BC
	RET


;=======================
;特殊ワーク（機種依存）
;=======================


;#POKE（1F9AH）の本体
; 特殊ワーク･エリアに1バイト書き込みます。
;入力	HL←アドレス、Acc←データ
;出力	なし
;破壊	なし
;〈旧SWORDとの速度比較〉
;POKE	 97ts→ 83ts	1.169倍
;#POKE	107ts→ 93ts	1.151倍
;＋CALL	124ts→110ts	1.127倍
POKE:
	PUSH	BC	;11ts
	PUSH	AF	;11ts
	LD	C,L	; 4ts
	LD	A,40H	; 7ts '特殊ワーク先頭（4000H）
	ADD	A,H	; 4ts 'CY←0
	LD	B,A	; 4ts 'BC←実アドレス
	POP	AF	;10ts
	OUT	(C),A	;12ts '特殊ワークへの書き込み
	POP	BC	;10ts
	RET		;10ts


;#PEEK（1F94H）の本体
; 特殊ワーク･エリアから1バイト読み込みます。
;入力	HL←アドレス
;出力	Acc←データ
;破壊	AF
;〈旧SWORDとの速度比較〉
;POKE	109ts→ 62ts	1.758倍
;#POKE	119ts→ 72ts	1.653倍
;＋CALL	136ts→ 89ts	1.528倍
;注：CYをクリアします。
PEEK:
	PUSH	BC	;11ts
	LD	C,L	; 4ts
	LD	A,40H	; 7ts '特殊ワーク先頭（4000H）
	ADD	A,H	; 4ts 'CY←0
	LD	B,A	; 4ts 'BC←実アドレス
	IN	A,(C)	;12ts '特殊ワークからの読み込み
	POP	BC	;10ts
	RET		;10ts


;#poke_entity（1F97H）の本体
; 特殊ワーク･エリアにブロック書き込みします。
;入力	HL←メモリ先頭アドレス、DE←特殊ワーク先頭アドレス、
;	BC←転送バイト数
;出力	なし
;破壊	AF，HL，DE，BC
;〈旧SWORDとの速度比較〉
;ループ	 57ts→ 40ts	1.425倍
;注：「WINER」などでCYクリアが必要。
poke_entity:
	LD	A,40H	;特殊ワーク先頭（4000H）
	ADD	A,D	;CY←0
	LD	D,A
	PUSH	DE

;	高速ループ･カウンタの設定（BC→AD版）
	XOR	A
	CP	C	;下位カウンタ＝0ならCY＝0
	ADC	A,B	;Acc←新上位ループ･カウンタ
	LD	D,C	;D←下位ループ･カウンタ

	POP	BC	;BC←実アドレス

POKE_LP:	INC	B	; 4ts '先行デクリメントのため
	OUTI		;16ts '特殊ワークへの書き込み
	INC	BC	; 6ts
	DEC	D	; 4ts
	JP	NZ,POKE_LP	;10ts
	DEC	A
	JR	NZ,POKE_LP

;	OR	A	;CY←0
	RET


;#peek_entity（1F91H）の本体
; 特殊ワーク･エリアからブロック読み込みします。
;入力	HL←メモリ先頭アドレス、DE←特殊ワーク先頭アドレス、
;	BC←転送バイト数
;出力	なし
;破壊	AF，HL，DE，BC
;〈旧SWORDとの速度比較〉
;ループ	 57ts→ 40ts	1.425倍
;注：「WINER」などでCYクリアが必要。
peek_entity:
	LD	A,40H	;特殊ワーク先頭（4000H）
	ADD	A,D	;CY←0
	LD	D,A
	PUSH	DE

;	高速ループ･カウンタの設定（BC→AD版）
	XOR	A
	CP	C	;下位カウンタ＝0ならCY＝0
	ADC	A,B	;Acc←新上位ループ･カウンタ
	LD	D,C	;D←下位ループ･カウンタ

	POP	BC	;BC←実アドレス

PEEK_LP:	INC	B	; 4ts '先行デクリメントのため
	INI		;16ts '特殊ワークからの読み込み
	INC	BC	; 6ts
	DEC	D	; 4ts
	JP	NZ,peek_lp	;10ts
	DEC	A
	JR	NZ,peek_lp

;	OR	A	;CY←0
	RET


;---------------------------------------
;フィジカル･ルーチン（機種依存）
;---------------------------------------


;===============================
;システム･ルーチン（機種依存）
;===============================

;ブートします
;入力	なし
;出力	なし
;破壊	AF，HL，DE，BC
boot_entity:
	CALL	SOSSF		;仮想ディスク全クローズ

	LD	HL,00D3H	;「OUT (0),A」
	LD	(0FFFEH),HL
	LD	A,1DH
	JP	0FFFEH


;===============================================
;フィジカル･ルーチン･プリンタ関係（機種依存）
;===============================================


;プリンタへ1文字出力します
;入力	Acc←文字
;出力	エラーが起こればCY＝1
;破壊	AF
lprint_entity:
	PUSH	HL
	PUSH	BC
	LD	L,A	;L←文字（保存用）
	LD	H,A	;H←文字
	LD	BC,1A01H

;	プリンタREADYを待ちます
lplp_entity:	IN	A,(C)
	RRCA
	JR	NC,lpbrk_entity	;^C
	IN	A,(C)
	AND	00001000B
	JR	NZ,lplp_entity

	OR	A	;CY←0

;	文字を出力
;注：CYは保存します。
lp1_entity:	DEC	C	;BC←1A00H
	OUT	(C),H
;	受け取り指示
	LD	C,3	;BC←1A03H
	LD	A,00001110B	;b7リセット
	OUT	(C),A
	INC	A	;b7セット
	OUT	(C),A

;	終了
	LD	A,L	;Acc←文字
	POP	BC
	POP	HL
	RET

;	^C処理
lpbrk_entity:	LD	H,0DH	;RET
	SCF
	JR	lp1_entity


;=======================
;音声（機種依存）
;=======================


;ビープ音を鳴らします
;入力	なし
;出力	なし
;破壊	AF，HL，DE，BC
bell_entity:
	DI
	EI
	RET

;===============================
;スクリーン関係（機種依存）
;===============================


;カーソル座標を読み出します
;入力	なし
;出力	L←x座標、H←y座標
;破壊	AF，HL，DE，BC
get_cursor_XY_entity:
	LD	DE,(CSRADD) ; CSRADDの値をDEへ
	LD	HL,(CSRNX) ; CSRNXの値をHLへ
	ADD	HL,DE
	RET

;カーソルを指定座標へ移動します
;入力	L←x座標、H←y座標
;出力	なし
;破壊	AF，HL，DE，BC
move_cursor_XY_entity:
	LD	DE,(CSRNXI)	;256-桁数 '[CSRNX]の初期値
	ADD	HL,DE
	LD	(CSRNX),HL ;ｘ座標-[_WIDTH]
	JP	SETPRN

;指定座標の文字を読み込みます
;入力	L←x座標、H←y座標
;出力	Acc←文字
;破壊	AF，HL，DE，BC
get_character_XY_entity:
	CALL get_offset_from_cursor_XY
	JP read_character_offset_address

;画面のクリア
;入力	[screen_width]、[total_number_of_character_display]、[attribute_data]参照
;出力	なし
;破壊	AF，HL，DE，BC
;〈レジスタ･マップ〉
;E	クリア･データ（定数）
;BC	現在アトリビュートVRAMアドレス
;AD	高速ループ･カウンタ
; 画面左上のアドレスはf800hです。
; そこから、ffd0hまでをスペースキャラクタ(アスキーコード20h)で埋めて、画面をクリアするコードを書いて下さい。

CLS:
	PUSH HL
	PUSH BC

	LD HL,0F000H
	LD BC,0800H

	LD B,050H
	LD DE,0FFFFH
	LD A,20H ; スペースキャラクタ
; CLEAR_ALL_LINE_CLS:
.LOOP
	OUT (0D2H),A ; VRAMへアクセスするためのポート
	LD (HL),A ; VRAMへ20Hデータを書き込む
	INC HL ; 書き込むべきアドレスをインクリメント
	SBC HL,DE ; HL - DE
	; JR NZ,CLEAR_ALL_LINE_CLS ; 全てのアドレスを書き込むまでループ
	JR NZ,.LOOP ; 全てのアドレスを書き込むまでループ

	LD DE, VRAM_TXT_TOP ; 最初の文字列表示位置(左上隅)
	LD (CURSOR_LOCATE),DE ; カーソル位置を左上隅に設定 F800H
	LD (TOP_VIEW),DE
	LD DE, 0FFD0H ; 画面最終文字位置
	LD (NEED_DO_SCROLL_POINT),DE ; スクロールポイントを設定

	RET


;===============================
;1文字表示ルーチン（機種依存）
;===============================


;コントロール･コード制御（PRINTルーチンの一部）
;入力	Acc←コントロール･コード（00H～1FH）
PRNCTL:
	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	HL,control_code_jump_tabel
	ADD	A,A	;Acc←コントロール･コード×2
	ADD	A,L
	LD	L,A	;HL←control_code_jump_tabel＋コントロール･コード×2
	LD	A,(HL)
	INC	L
	LD	H,(HL)
	LD	L,A	;HL←[control_code_jump_tabel＋コントロール･コード×2]

	LD	DE,PRCRET
	PUSH	DE	;リータン･アドレスの設定
	JP	(HL)	;「CALL コントロール制御」相当
PRCRET:	CALL	SETPRN
	POP	BC
	POP	DE
	POP	HL
	POP	AF
	OR	A	;CY←0
	RET

;1文字プリント前処理
PREPR:	PUSH	HL
	POP	HL

;#PRINT（1FF4H）本体
; 1文字プリント･ルーチン。
;入力	Acc←文字
;出力	なし
;破壊	F
;注：
; [#LPSW]がオンならプリンタにも出力します。
; インサート･モードと論理改行は、1行入力ルーチンで制御します。
; CYフラグをクリアします。
;〈実行時間〉
;PRINT	149ts（37.250μs）
;#PRINT	159ts（39.750μs）
;＋CALL	176ts（44.000μs）
PRINT:
	PUSH AF
	PUSH HL
	PUSH DE
	PUSH BC

	CALL PUTCHAR

	POP	BC
	POP	DE
	POP	HL
	POP	AF

	; PUSH HL
	; PUSH BC
	; PUSH DE
	; LD	HL,CSRNX ;10t
	; INC (HL) ;4ts	
	; POP	BC
	; POP	DE
	; POP	HL
	RET


;===============================
;文字列表示ルーチン（機種依存）
;===============================

;文字のブロック表示（非コントロール･コードのみ表示します）
;入力	DE←文字列の先頭アドレス
;出力	DE←次の文字の位置
;破壊	AF，HL，DE，BC
;〈レジスタ･マップ〉
;SP	現在文字列のアドレス
;E	文字読み込み1
;D	文字読み込み2
;BC	現在テキストVRAMアドレス
;HL	現在文字変換テーブルのアドレス
;IXL	ループ･カウンタ
;IXH	定数桁数÷2（ループ用）
;Acc	定数20H－1（コントロール･コード･チェック用）
;注：
; プリンタには出力しません。
; インサート･モードと論理改行は、1行入力ルーチンで制御します。
; [number_of_character_after_CR]は無視します。
; 桁数は、必ず偶数であること。
;〈実行時間〉
;最内ループ53ts（13.250μs）
BPRNT0:
; 	PUSH	IX
; ;	共通の設定
; 	LD	A,(_WIDTH)
; 	SRL	A
; 	DB	0DDH
; 	LD	H,A	;「LD IXH,A」 'IXH←桁数÷2 '定数
; 	LD	BC,(TXTADR)	;BC←現在テキストVRAMアドレス
; 	LD	(BPRRSP),SP
; ;	最初の行の設定
; 	LD	A,(CSRNX)
; 	CPL
; 	ADD	A,2	;Acc←現在行の残り文字数＋1，CY←0
; 	RRA		;Acc←現在行の残り文字数÷2切り上げ，CY←端数の反転
; 	DB	0DDH
; 	LD	L,A	;「LD IXL,A」 'IXL←初期ループ･カウンタ
; 	EX	DE,HL
; 	DI
; 	LD	SP,HL	;SP←文字列の先頭
; 	LD	H,LSXTBL/100H	;HL←文字変換テーブルのアドレス
; 	LD	A,20H-1	;コントロール･コード･チェック用
; 	JR	C,BPRL12
; ;	端数処理
; 	DEC	SP
; 	POP	DE	;D←最初の文字
; 	JR	BPRL1J

; BPRL11:
; 	DB	0DDH
; 	LD	L,H	;「LD IXL,IXH」 'IXL←ループ･カウンタ（桁数÷2）
; 	LD	H,LSXTBL/100H	;HL←文字変換テーブルのアドレス
; 	LD	A,20H-1	;コントロール･コード･チェック用

; ;	1ループ106ts（53ts×2）
; BPRL12:
; 	POP	DE	;10ts
; 	CP	E	; 4ts
; 	JR	NC,BPRRE1	; 7ts 'コントロール･コードがきました
; 	LD	L,E	; 4ts
; 	LD	E,(HL)	; 7ts
; 	OUT	(C),E	;12ts
; 	INC	C	; 4ts
; BPRL1J:
; 	CP	D	; 4ts
; 	JR	NC,BPRRE2	; 7ts 'コントロール･コードがきました
; 	LD	L,D	; 4ts
; 	LD	D,(HL)	; 7ts
; 	OUT	(C),D	;12ts
; 	INC	BC	; 6ts
; 	DB	0DDH
; 	DEC	L	; 8ts
; 	JP	NZ,BPRL12	;10ts

; 	LD	HL,CSRNX
; 	LD	A,(CSRNXI)
; 	LD	(HL),A	;カーソルを行頭へ
; 	INC	L	;HL←CSRNY
; 	LD	A,(_MXLIN)
; 	ADD	A,(HL)	;Acc←y座標 '（y座標－行数）＋行数
; 	LD	L,A
; 	LD	H,LINTTB/100H	;HL←対応するターミナル･テーブルのアドレス
; 	LD	(HL),0FFH	;行を連結します
; 	LD	HL,CSRNY
; 	INC	(HL)	;[CSRNY]のカウント･アップ
; 	JR	NZ,BPRL11

; ;	最終行の場合
; 	LD	(HL),0FFH	;最終行
; 	LD	(BPRLSP),SP
; 	EI
; 	LD	SP,(BPRRSP)
; 	CALL	control_code_ROLL_UP
; 	LD	BC,(vram_address_of_top_of_last_line)	;BC←最終行先頭のVRAMアドレス
; 	DI
; 	DB	31H	;「LD SP,n」
; BPRLSP:
; 	DS	2
; 	JR	BPRL11

; ;	コントロール･コードがきた場合（偶数）
; BPRRE1:
; 	XOR	A
; 	DB	0DDH
; 	SUB	L	;「SUB IXL」
; 	DB	0DDH
; 	SUB	L	;「SUB IXL」 'Acc←x座標－桁数
; 	LD	HL,-2
; 	JR	BPRRET
; ;	コントロール･コードがきた場合（端数）
; BPRRE2:
; 	LD	A,1
; 	DB	0DDH
; 	SUB	L	;「SUB IXL」
; 	DB	0DDH
; 	SUB	L	;「SUB IXL」 'Acc←x座標－桁数
; 	LD	HL,-1
; BPRRET:
; 	LD	(TXTADR),BC	;[TXTADR]の更新
; 	LD	(CSRNX),A	;[CSRNX]を更新
; 	ADD	HL,SP
; 	OR	A	;CY←0
; 	EX	DE,HL	;DE←コントロール･コードのアドレス
; 	EI
; 	DB	31H	;「LD SP,」
; BPRRSP:
; 	DS	2
; 	POP	IX
	RET


;===============================
;キー入力関係（機種依存）
;===============================


;1文字入力ルーチン（入力待ちあり、エコー･バックなし、カーソル表示なし）
;入力	なし
;出力	Acc←アスキー･コード
;破壊	AF，HL，DE，BC
;注：DEL（7FH）コードは、^D（04H）に変換します。
INKEY_entity:

;	キー入力バッファに文字が溜るまで待ちます
INKLP_entity:
	EI
	; CALL	INJOY
	OR	A
	RET	NZ
	EI		;念のため
	LD	A,(pointer_for_write_key_buffer)
	OR	A
	JR	Z,INKLP_entity

;	文字入力バッファから1文字取り出します
	LD	HL,pointer_for_write_key_buffer
	DI
	LD	A,(HL)
	OR	A	;念のためもう1度チェック
	JR	Z,INKLP_entity
	DEC	(HL)	;[pointer_for_write_key_buffer]をデクリメントします
	LD	C,(HL)
	LD	B,0	;BC←バッファに溜った文字数－1（0～254）
	LD	E,B
	LD	D,H	;DE←input_key_buffer
	LD	L,1	;HL←input_key_buffer+1
	LD	A,(DE)	;Acc←入力文字
	JR	Z,INKRT
	LDIR
INKRT:
	EI
	RET


;リアル･タイム･キー入力（入力待ちなし、エコー･バックなし、カーソル表示なし）
;入力	なし
;出力	Acc←アスキー･コード
;破壊	AF，HL，DE，BC
;注：ジョイスティック対応。
real_time_input_key_entity:
	OR	A
	RET	NZ

	DI
	CALL	clear_key_buffer
	EI
	LD	A,(real_time_key)
	RET


;キー入力バッファをクリアします
;入力	なし
;出力	なし
;破壊	AF，HL，DE，BC
;注：割り込み禁止して実行してください。
clear_key_buffer:
	XOR	A
	LD	(pointer_for_write_key_buffer),A	;キー入力バッファをクリアします
	RET



;===============================
;スクリーン制御補助（機種依存）
;===============================


;指定オフセット･アドレスに文字を書き込みます
;入力	HL←オフセット･アドレス、Acc←文字
;出力	なし
;破壊	AF，HL，DE，BC
write_character_offset_address:
	RET


;指定カーソル･オフセットの文字を読み込みます
;入力	HL←カーソル･オフセット
;出力	Acc←文字
;破壊	AF，HL，DE，BC
read_character_offset_address:
	RET


;カーソルを表示します
;入力	[insert_mode_flag]参照
;出力	[locate_of_cursor_overlap_character]←カーソル位置の文字
;破壊	AF，HL，DE，BC
display_cursor:
	CALL	get_cursor_XY_entity
	CALL	get_offset_from_cursor_XY
	LD	C,L
	LD	A,20H	;アトリビュートVRAM先頭（2000H）
	ADD	A,H
	LD	B,A	;BC←アトリビュートVRAMアドレス
	IN	A,(C)
	XOR	00001000B	;b3を反転
	LD	L,A
	LD	A,(insert_mode_flag)
	AND	00010000B	;b4
	XOR	L	;[insert_mode_flag]＝FFHなら、ブリンク
	OUT	(C),A
	RET


;カーソルを消去します
;入力	[locate_of_cursor_overlap_character]、[insert_mode_flag]参照
;出力	なし
;破壊	AF，HL，DE，BC
erase_cursor:
	CALL	get_cursor_XY_entity
	CALL	get_offset_from_cursor_XY
	LD	C,L
	LD	A,20H	;アトリビュートVRAM先頭（2000H）
	ADD	A,H
	LD	B,A	;BC←アトリビュートVRAMアドレス
	IN	A,(C)
	XOR	00001000B	;b3を反転
	AND	11101111B	;b4をクリア
	OUT	(C),A
	RET


;表示色を変更します
;入力	[foreground_color]、[background_color]、[BDR_color]参照
;出力	[attribute_data]←アトリビュート･データ
;破壊	AF，HL，DE，BC
change_color:
	LD	A,(foreground_color)
	CALL	CCLSUB
	LD	L,A	;L←前景色
	LD	A,(background_color)
	CALL	CCLSUB
	LD	H,A	;H←後景色
	OR	A
	JR	Z,CCLBK0	;背景色が0の場合
	LD	A,H
	CP	7
	JR	Z,CCLBK7	;反転色指定

;	後景色が0の場合
CCLBK0:	LD	A,L
CCLRET:	LD	(attribute_data),A
	RET

;	反転で、色を指定します
CCLBK7:	LD	A,L
	XOR	111B
	OR	1000B	;色反転
	JR	CCLRET

;色コードを0～7に圧縮します
;入力	Acc←色コード
;出力	Acc←色コード（0～7）
;破壊	AF
CCLSUB:	CP	8
	RET	C
	LD	A,7
	RET


;===============================
;スクリーン制御転送（機種依存）
;===============================




;===============================
;特殊ルーチン（機種依存）
;===============================


;60分の1秒単位で時間待ちします
;入力	Acc←カウンタ
;出力	なし
;破壊	AF
;注：割り込み禁止して実行してください。
WAIT60:
	PUSH	BC
	LD	B,A

W60LP:
	CALL	VBLANK
	DJNZ	W60LP

	POP	BC
	RET


;垂直帰線信号の立ち下がりを待ちます
;入力	なし
;出力	なし
;破壊	AF
;注：割り込み禁止して実行してください。
VBLANK:
; 垂直帰線信号が無効になる場合があるので、CPU実行速度依存に書き直します。
; 1／60秒、66,667ステートの15／16、62,500ステート待ちます。
	PUSH	BC	;11ts
	LD	BC,2402	;10ts

;	1ループ26ts
VBLLP:	DEC	BC	; 6ts
	LD	A,C	; 4ts
	OR	B	; 4ts
	JR	NZ,VBLLP	;12ts

	POP	BC	;10ts
	RET		;10ts


;-----------------------
;機種固有ルーチン
;-----------------------


;===============================
;スクリーン制御補助（機種固有）
;===============================


;カーソルのテキストVRAMアドレスを求めます
;入力	L←x座標、H←y座標
;出力	BC←テキストVRAMアドレス
;破壊	AF，HL，BC
get_vram_address_from_cursor_XY:
	CALL	get_offset_from_cursor_XY
	LD	C,L
	LD	A,30H	;テキストVRAM先頭（3000H）
	ADD	A,H
	LD	B,A	;BC←テキストVRAMアドレス
	RET


;=======================
;CRTC（機種固有）
;=======================


;CRTCのレジスタにデータを書き込みます
;入力	D←レジスタ番号、Acc←値
;出力	Dはカウント･アップされます
;破壊	AF，D
;注：割り込み禁止して実行してください。
write_data_to_CRTC:
	PUSH	BC
	LD	BC,1800H
	OUT	(C),D	;レジスタ
	INC	D
	INC	C	;BC←1801H
	OUT	(C),A	;データ
	POP	BC
	RET



;---------------
;汎用ルーチン
;---------------


;文字列から文字を取り出します（スペースはスキップ）
;入力	DE←文字列の先頭アドレス
;出力	Acc←文字
;	DEはカウント･アップ
;破壊	AF，DE
;注：小文字を大文字に変換します。
get_character_from_line:
	CALL	SPSKIP
	LD	A,(DE)
	OR	A
	RET	Z	;文字列の終わりの達した
	INC	DE
	JP	convert_lower_case_to_upper_case


;文字列のスペース･キャラをスキップします
;入力	DE←文字列の先頭アドレス
;出力	DE←カウント･アップ
;破壊	AF，DE
SPSLP:
	INC	DE

SPSKIP:
	LD	A,(DE)
	CP	' '
	JR	Z,SPSLP
	CP	09H	;TAB
	JR	Z,SPSLP

	RET


;小文字を大文字に変換します
;入力	Acc←アスキー･コード
;出力	Acc←変換したアスキー･コード
;破壊	AF
convert_lower_case_to_upper_case:
	CP	'a'
	RET	C
	CP	'z'+1
	RET	NC
	SUB	20H
	RET


;convert_decimal_character_to_number V1.00  Copyright (C) T.Chikushi  1994-06-18
;10進文字を数値に変換します
;入力	Acc←文字
;出力	AL←数値、CY←変換状態
;CF=0	AL←数値（0～9）
;CF=1	10進文字ではなかった（ALは、呼び出し前の値）
;破壊	AF
convert_decimal_character_to_number:
	CP	'0'
	RET	C
	CP	'9'+1
	CCF
	RET	C
;	「0」～「9」
	SUB	'0'	;Acc←0～9，CY←0
	RET


;Copyright (C) T.Chikushi  1991-01-04
;HL÷Acc→商HL...余りAcc
;入力	HL←被除数、Acc←除数
;出力	HL←商、Acc←余り
;破壊	AF，HL，DE，BC
DIV68:
	PUSH	BC
	LD	C,A	;C←除数
	XOR	A
	LD	B,16

DIV68L:	ADD	HL,HL
	RLA
	CP	C
	JR	C,DIV681
	SUB	C
	INC	L
DIV681:	DJNZ	DIV68L

	POP	BC
	RET


;Copyright (C) T.Chikushi  1990
;DEHL÷BC→商DEHL...余りBC
;入力	DEHL←被除数、BC←除数
;出力	DEHL←商、BC←余り
;破壊	インデックス･レジスタ以外
;	min 3,452ts max 3,600ts s1
DIV26:
	PUSH	BC
	EXX
	POP	BC	;BC'←除数
	LD	HL,0	;HL'←0
	EXX
	LD	B,32
DIV26L:	ADD	HL,HL
	EX	DE,HL
	ADC	HL,HL
	EX	DE,HL
	EXX
	ADC	HL,HL	;HL'DEHLを左シフト
	JR	C,DIV262	;必ず引けます
	SBC	HL,BC	;HL←HL－BC
	JR	NC,DIV263	;引けた
	ADD	HL,BC	;引けない場合はHL'を元に戻します
	EXX
	DJNZ	DIV26L
DIV261:	EXX
	PUSH	HL
	EXX
	POP	BC
	RET
;	必ず引ける場合
DIV262:	OR	A
	SBC	HL,BC
;	引けた場合
DIV263:	EXX
	INC	L	;INC HL'DEHL
	DJNZ	DIV26L
	JR	DIV261


;-----------------------
;割り込みルーチン
;-----------------------


; 省メモリのため、テーブル･エリアに移動しました。


;-----------------------
;オリジナル･モニタ
;-----------------------


;#MON（1F8EH）の本体
;CY＝0でリターンします（ディスク･モジュールのため）
MON:
	LD	(monitor_reserve_stack_pointer),SP
	LD	HL,(_MEMAX)
	LD	DE,3000H
	OR	A
	SBC	HL,DE
	LD	(monitor_size_of_user_area),HL	;ユーザー･エリアのサイズ

;	コマンド待ちループ
monitor_command_waiting_loop:
	LD	SP,0100H	;オリジナル･モニタのスタック･トップ
	LD	A,'*'
	CALL	_PRINT
	LD	DE,(_KBFAD)
	CALL	_GETL
	CALL	get_character_from_line

; コマンドを解析して、それぞれの処理ルーチンへ。
;出力	DE←次の文字のアドレス
MON2:
	CP	':'
	JP	Z,monitor_memory_edit	;メモリ･エディト
	CP	'*'
	CALL Z,get_character_from_line
	CP	'R'
	JP	Z,terminate_monitor	;モニタを終えます
	CP	'#'
	JP	Z,monitor_dump_memory	;ダンプ
	CP	'F'
	JP	Z,monitor_search_data	;サーチ
	CP	'A'
	JP	Z,monitor_go_command		;ジャンプ
	CP	'I'
	JP	Z,monitor_initialize_disk	;ディスク初期化
	CP	'M'
	JP	Z,monitor_set_data_to_memory	;メモリ･セット
	DS	4,00H	;ダミー
	CALL _BELL
	JP	monitor_command_waiting_loop

;オリジナル･モニタを終えます
terminate_monitor:
	XOR	A	;CY←0（Acc←0）
	LD	SP,(monitor_reserve_stack_pointer)
	RET


;オリジナル･モニタ サブルーチン･コール
monitor_go_command:
	CALL SPSKIP
	CALL _HLHEX
	JR	C,monitor_go_commandE
	LD	BC,monitor_command_waiting_loop
	PUSH	BC	;スタック←monitor_command_waiting_loop
	JP	(HL)

monitor_go_commandE:
	CALL _BELL
	JP	monitor_command_waiting_loop


;オリジナル･モニタ サーチ･ルーチン
;〈使用法〉
;「F 先頭アドレス 最終アドレス データ…」
;〈サーチするデータ列〉
;keyboard_buffer～
monitor_search_data:
;	アドレス情報を取り出します
	CALL SPSKIP
	CALL _HLHEX
	JR	C,MONFIE
	LD	(MONFTP),HL	;先頭アドレス
	CALL SPSKIP
	CALL _HLHEX
	JR	C,MONFIE
	INC	HL
	LD	(MONFEN),HL	;最終アドレス＋1

;	データの取り出します
	LD	HL,keyboard_buffer	;データ列の先頭

MONFL1:
	CALL SPSKIP
	CALL _2HEX
	JR	C,MNFL1E
	LD	(HL),A	;←データ
	INC	L	;現在アドレス＆現在データ数
	JR	MONFL1

MNFL1E:	LD	A,L
	OR	A
	JR	Z,MONFIE	;データがなかった
	LD	(MONFCT),A	;データ数（1～）
	LD	HL,(MONFEN)
	LD	DE,(MONFTP)
;	OR	A
	SBC	HL,DE
	DEC	HL	;HL←サイズ－1 '0～65,535
	LD	E,A
	LD	D,0
	DEC	DE	;DE←データ数－1 '0～
	OR	A
	SBC	HL,DE	;HL←サイズ－データ数
	JR	C,MONFIE
	INC	HL
	LD	(MONFSZ),HL	;検索カウンタ（1～）

;	検索します
	LD	HL,(MONFTP)	;先頭アドレス
	LD	BC,(MONFSZ)	;検索カウンタ
	LD	A,(keyboard_buffer)	;最初の検索バイト

MONFL2:	CPIR
	PUSH	AF
	PUSH	HL
	PUSH	BC
	CALL	Z,MONFSB	;最初のバイトが一致しました
	POP	BC
	POP	HL
	POP	AF
	JP	PE,MONFL2

MONFES:
	LD	A,0DH
	CALL	_PRINT
MONFRT:
	JP	monitor_command_waiting_loop

MONFIE:
	CALL	_BELL
	JR	MONFRT


;最初のバイト以降を比較し、一致すれば、そのアドレスを表示します
;入力	HL←最初のバイトが一致した次のアドレス
;出力	なし
;破壊	全レジスタ
MONFSB:
	PUSH	HL	;スタック←比較されるアドレス＋1
	LD	DE,keyboard_buffer+1	;データ列先頭＋1
	LD	A,(MONFCT)
	LD	B,A
	DEC	B	;B←チェックする残りのバイト数
	JR	Z,MNFSBR	;比較は1バイトのみで、一致しました

MNFSBL:
	LD	A,(DE)
	INC	E
	CP	(HL)
	INC	HL
	JR	NZ,MNFSBB
	DJNZ	MNFSBL

MNFSBR:
	CALL	_PAUSE
	DW	MONFES
	LD	A,' '
	CALL	_PRINT
	POP	HL	;HL←比較されるアドレス＋1
	DEC	HL
	JP	print_hex_4_digit

MNFSBB:
	POP	HL
	RET


;	サーチ･コマンド用ワーク
MONFTP:	DS	2	;検索先頭アドレス
MONFEN:	DS	2	;検索最終アドレス＋1
MONFSZ:	DS	2	;検索バイト数（[MONFEN]－[MONFTP]－[MONFCT]＋1）
MONFCT:	DS	1	;データ数


;オリジナル･モニタ ダンプ（可変行、可変桁対応）
;〈ダンプの桁数〉
; ダンプの桁数は、「横バイト数×4＋7」文字。
;72桁以上、71文字
;「:AAAA=HH HH HH HH HH HH HH HH HH HH HH HH HH HH HH HH /CCCCCCCCCCCCCCCC」
;40桁以上、39文字
;「:AAAA=HH HH HH HH HH HH HH HH /CCCCCCCC」
;24桁以上、23文字
;「:AAAA=HH HH HH HH /CCCC」
;〈レジスタ･マップ〉
;HL	メモリのアドレス
;B	汎用カウンタ
;C	横バイト数
;DE	縦表示数
;注：DIV26（インデックス･レジスタ以外破壊）を呼び出します。
monitor_dump_memory:
	CALL	SPSKIP
	CALL	_HLHEX
	JR	C,$+5
	LD	(monitor_operation_address),HL
	CALL	SPSKIP
	CALL	_HLHEX
	LD	(MONDE),HL
	CCF
	SBC	A,A	;最終アドレスが指定されていたらAcc＝FFH
	LD	(MONDF),A
	CALL	MNDINI	;初期化
	JP	C,monitor_command_waiting_loop	;初期化失敗
	CALL	MNDILC	;表示ライン数の設定
	EX	DE,HL	;DE←縦ライン数
	LD	A,(MONDX)
	LD	C,A	;C←横バイト数

;入力	C←横バイト数、DE←縦ライン数
;	[monitor_operation_address]参照
;出力	[monitor_operation_address]更新
;破壊	AF，HL，DE，B
;〈レジスタ･マップ〉
;HL	現在メモリのアドレス
;B	横ループ･カウンタ
;DE	縦ループ･カウンタ
MDPLP1:
	LD	A,':'
	CALL	_PRINT
	LD	HL,(monitor_operation_address)
	PUSH	HL	;スタック←アドレス（行頭）
	CALL	_print_hex_4_digit
	LD	A,'='
	CALL	_PRINT
	LD	B,C	;B←横バイト数

;入力	HL←メモリのアドレス、B←横バイト数
;出力	HLはカウント･アップされます
;破壊	AF，HL，B
;〈レジスタ･マップ〉
;HL	現在メモリのアドレス
;B	ループ･カウンタ
MDPL21:
	LD	A,(HL)	;Acc←メモリのデータ
	INC	HL
	CALL	_print_hex_2_digit
	LD	A,' '
	CALL	_PRINT
	DJNZ	MDPL21

	LD	A,'/'
	CALL	_PRINT
	POP	HL	;HL←アドレス（行頭）
	LD	B,C	;B←横バイト数

;入力	HL←メモリのアドレス、B←横バイト数
;出力	HLはカウント･アップされます
;破壊	AF，HL，B
;〈レジスタ･マップ〉
;HL	現在メモリのアドレス
;B	ループ･カウンタ
MDPL22:
	LD	A,(HL)	;Acc←メモリのデータ
	INC	HL
;	CP	7FH
;	JR	Z,$+6	;DELコードだった
	CP	20H
	JR	NC,$+4	;コントロール･コードだった
	LD	A,' '	;Acc←「 」
	CALL	_PRINT
	DJNZ	MDPL22

	LD	(monitor_operation_address),HL
	CALL	_LTNL
	CALL	_PAUSE
	DW	monitor_command_waiting_loop
	DEC	DE
	LD	A,E
	OR	D
	JR	NZ,MDPLP1

	JP	monitor_command_waiting_loop


;表示ライン数を得ます
;入力	[MONDE]←最終アドレス、[MONDF]←[MONDE]有効のフラグ
;出力	HL←ライン数
;破壊	全レジスタ
MNDILC:
	LD	A,(MONDF)
	OR	A
	JR	NZ,MNDLC1

;	最終アドレスが設定されていない場合
	LD	A,(MONDY)
	LD	L,A
	LD	H,0	;HL←縦ライン数（1画面分）
	RET

;	最終アドレスが設定されている場合
MNDLC1:
	LD	A,(MONDX)
	LD	C,A
	LD	B,0	;BC←横バイト数（2～）
	LD	HL,(MONDE)
	LD	DE,(monitor_operation_address)
	XOR	A
	SBC	HL,DE	;HL←ダンプするバイト数－1
	ADD	HL,BC
	RLA		;Acc←CY
	LD	E,A
	LD	D,B	;DEHL←ダンプするバイト数＋横バイト数－1
	JP	DIV26


;ダンプ･コマンドの初期化処理
;入力	[_MXLIN]、[_WIDTH]参照
;出力	[MONDX]、[MONDY]設定
;	CY＝1なら初期化に失敗しました
;破壊	全レジスタ
MNDINI:
;	[MONDXの設定]
	LD	A,(_WIDTH)
	SUB	8	;アドレスなどの8文字を除きます
	RET	C
	CP	4*2
	RET	C	;2バイト分の表示にも足りない
	AND	11111100B
	RRCA
	RRCA		;Acc←表示可能横バイト数
	CALL	MNDN2
	LD	(MONDX),A	;[MONDY]←横バイト数（2～）

;	[MONDYの設定]
	LD	A,(_MXLIN)
	SUB	1	;1行のアキを作るため
	RET	C
	CP	2
	RET	C	;2行分の表示にも足りない
	CALL	MNDN2
	LD	(MONDY),A	;[MONDY]←縦ライン数（2～）

	XOR	A
	RET


;データをn^2化します
;入力	Acc←処理するデータ（0～255）
;出力	Acc←n^2化されたデータ（8、16など）
;破壊	全レジスタ
MNDN2:
	LD	BC,8*100H	;B←8，C←0

MNDN21:
	RLCA
	INC	C	;カウント･アップ
	JR	C,$+4
	DJNZ	MNDN21

	LD	A,0	;CYA←1_00000000B
	LD	B,C

MNDN22:
	RRA
	DJNZ	MNDN22

	RET


;	ダンプ･コマンド用ワーク
MONDE:	DS	2	;ユーザーが指定したダンプの最終アドレス
MONDF:	DS	1	;＝FFHで、[MONDE]が有効
MONDX:	DS	1	;ダンプする横バイト数（2～）
MONDY:	DS	1	;ダンプする縦バイト数（2～）


;オリジナル･モニタ メモリ･セット
monitor_set_data_to_memory:
	CALL	SPSKIP
	CALL	_HLHEX
	JR	C,$+5
	LD	(monitor_operation_address),HL

MMSLP:	LD	A,':'
	CALL	_PRINT
	LD	HL,(monitor_operation_address)
	CALL	_print_hex_4_digit
	LD	A,'='
	CALL	_PRINT
	LD	A,(HL)
	CALL	_print_hex_2_digit
	LD	A,1DH	;Acc←「←」
	CALL	_PRINT
	CALL	_PRINT
	CALL	MEMEDT
	JP	C,MON2
	JR	MMSLP


;オリジナル･モニタ メモリ･エディト
monitor_memory_edit:
	CALL	MEMED1
	JP	C,monitor_command_waiting_loop

MONELP:	CALL	MEMEDT
	JP	C,MON2
	JR	MONELP


;1行メモリ･エディト･ルーチン
;入力	[monitor_operation_address]参照
;出力	CY＝1ならエディトを終了しました
;破壊	AF，HL，DE
MEMEDT:
	LD	DE,(_KBFAD)
	CALL	_GETL
	CALL	get_character_from_line

;	既に先頭1文字を取り出した時のエントリ
MEMED1:
	CP	':'	;メモリ･エディト用ヘッダ
	SCF
	RET	NZ	;ヘッダが不正
	CALL	SPSKIP
	CALL	_HLHEX
	RET	C	;アドレスが不正
	CALL	get_character_from_line
	CP	'='
	SCF
	RET	NZ	;セパレータが不正

MEMELP:	CALL	SPSKIP
	LD	A,(DE)
	CP	'.'
	SCF
	RET	Z	;エディト終了
	CALL	_2HEX
	CCF
	RET	NC	;入力終了
	LD	(HL),A
	INC	HL
	LD	(monitor_operation_address),HL
	JR	MEMELP


;===============================================
;オリジナル･モニタ Ok、Errorメッセージ
;===============================================


;処理が正常終了しました
monitor_normal_end:
	CALL	_MPRNT
	DB	'Ok',0DH,00H
MNOKRT:
	JP	monitor_command_waiting_loop


;処理が異常終了しました
monitor_error_termination:
	CALL	_MPRNT
	DB	'Error !',0DH,00H
	JR	MNOKRT


;=======================================
;オリジナル･モニタ･ディスク初期化処理
;=======================================


;S-OSディスク･イメージの初期化
monitor_initialize_disk:
	CALL	SPSKIP
	CALL	MONDEV
	OR	A
	JR	NZ,MONIDI

;	S-OSディスク･イメージのクローズ
	CALL SOSSF
	JP	C,monitor_error_termination
	JP	monitor_normal_end

;	論理フォーマット
MONIDI:	DEC	A	;Acc←ユニット番号
	LD	(disk_unit_number),A
	ADD	A,'A'
	LD	C,A	;C←デバイス名
	CALL	_MPRNT
	DB	'ﾃﾞﾊﾞｲｽ ',00H
	LD	A,C
	CALL	_PRINT
	CALL	_MPRNT
	DB	': ｦ ｼｮｷｶ ｼﾃ ﾖﾛｼｲ ﾃﾞｽｶ(Y/N)?',00H
	CALL	_FLGET
	CALL	convert_lower_case_to_upper_case
	CP	'Y'
	JR	Z,MONIDY

;	初期化しません
	LD	A,'N'
	CALL	_PRINT
	LD	A,0DH
	CALL	_PRINT
	JP	monitor_command_waiting_loop

;	初期化します
MONIDY:
	CALL	_PRINT
	LD	A,0DH
	CALL	_PRINT

	CALL	SOSDI
	JP	NC,monitor_normal_end

;	物理的フォーマット（論理フォーマットに失敗しました）
	CALL	SOSDF
	JP	NC,monitor_normal_end

;	物理的フォーマットにも失敗しました
	JP	monitor_error_termination


;=======================================
;オリジナル･モニタ･ディスク･ルーチン
;=======================================


;ファイル名からデバイスを抜き出します
;入力	DE←ファイル名の先頭アドレス
;出力	Acc←デバイス（0，1～）、DE←カウント･アップ
;破壊	AF，DE
;注：デフォルト･デバイスは0、ドライブAは1に対応します。
MONDEV:
	LD	A,(DE)
	OR	A
	RET	Z	;文字列の終わりに達していました

	INC	DE
	LD	A,(DE)
	DEC	DE
	CP	':'
	LD	A,0	;Acc←デフォルト･デバイス
	RET	NZ	;デバイスが指定されています

;	デバイスが指定されています
	LD	A,(DE)
	CALL	convert_lower_case_to_upper_case
	SUB	'A'-1	;Acc←1～
	INC	DE
	INC	DE
	RET



;-------------------------------
;オリジナル･モニタ ワーク
;-------------------------------


monitor_operation_address:	DW	0	;操作アドレス
monitor_reserve_stack_pointer:	DW	0	;SPの保存
monitor_size_of_user_area:	DW	0	;ユーザー･エリアの大きさ


;---------------------------------------
;SWXCDIOを使わないための処理
;---------------------------------------


SOSSI:
SOSSF:
	OR	A
	RET
SOSDI:
SOSDF:
	SCF
	RET
DIOETP:
	DS	2


CRT_INIT:
	LD HL,0F000H ; VRAMの左上のアトリビュートアドレス
	LD BC,0800H
; カーソル座標を00Hに設定する。
; 注：画面左上がカーソル座標では0000Hになる。VRAMにおけるテキスト画面左上(F800H)ではないことに注意。
	LD A,0EH ; R14 (cursor H)
	OUT (CRTC_ADD),A
	LD A,0H
	OUT (CRTC_VAL),A
	LD A,0FH ; R15 (cursor L)
	OUT (CRTC_ADD),A
	LD A,00H
	OUT (CRTC_VAL),A

; カーソルの形状と点滅の設定
	LD A,0AH ; R10 (cursor start address)
	OUT (CRTC_ADD),A
;	LD A,C0H ; 点滅、豆腐カーソル
	LD A,C7H ; 点滅、アンスコカーソル
;	LD A,0H ; 表示せず。
	OUT (CRTC_VAL),A
	LD A,0BH ; R11 (cursor end address)
	OUT (CRTC_ADD),A
	LD A,0AH
;	LD A,0H ; 表示せず。
	OUT (CRTC_VAL),A

;
; 	一度画面全てを消す(スペースで埋める)。
;
	LD B,050H
	LD DE,0FFFFH
	LD A,20H ; 20Hはアスキーコードでスペース
.CLEAR_LOOP
; CLEAR_ALL_LINE:
	OUT (0D2H),A ; D2Hポートになにか書くと次の命令は別のページ(この場合はVRAMのページ)に行う。
	LD (HL),A ; F000H～FFFFHまで20Hで埋めている。アトリビュートに20H書いても問題ないみたい。
	INC HL
	SBC HL,DE
	; JR NZ,CLEAR_ALL_LINE
	JR NZ,.CLEAR_LOOP

	LD DE, VRAM_TXT_TOP ; 最初の文字列表示位置(左上隅)
	LD (CURSOR_LOCATE),DE
	LD (TOP_VIEW),DE
	LD DE, 0FFD0H
	LD (NEED_DO_SCROLL_POINT),DE

	RET ; 初期化処理終了

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; CRTCコントロールサブルーチン群
;

;
; VRAM_TXT_TOP : VRAMテキストエリアの先頭(F800H)
; CURSOR_LOCATE : 現在のカーソル位置
; CR_NOW_CURSOR_LOCATE : CRコードが入った時のカーソル位置
; TOP_VIEW : 画面左上端のアドレス(スクロールによって動的に変化する)
; CR_BASE_ADDRESS : CR後のカーソル位置
; CR_NEW_ORIGIN : FFFFHの境界を越え、更に画面右端を超えた時にCRアドレス計算の原点になるアドレス

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; １文字表示サブルーチン
; A regに表示するアスキーコードが入っている。
;

PUTCHAR:
	PUSH HL
	PUSH AF
	PUSH DE

	AND A
	JR Z, PUTCHAR_RET ; NULL文字なら何もしないで戻る
	LD DE,(CURSOR_LOCATE) ; 現在のカーソル位置をDEにロード
	CP CR ; キャリッジリターンか？
	JP Z, DO_CR ; CRの処理
	CP LF ; ラインフィードか？
	JP Z, DO_LF ; LFの処理
	CP BS ; バックスペースか？
	JP Z, DO_BS ; BSの処理
	CP HT ; タブか？
	JP Z, DO_HT ; HTの処理
	CP ESC ; エスケープか？
	JP Z, DO_ESC ; ESCの処理

; 通常文字の表示処理
DO_NORMAL:
	OUT (0D2H),A ; access to RAM page 1
	LD (DE),A ; put character
;
; 越境判定。FFFFHの次はF800Hになる
;
	PUSH AF
	LD A,D ; DEの上位バイト
	CP 0FFH
	JR NZ,CURSOR_BOUNDARY_END ; オーバーフローしていなければジャンプ
	LD A,E ; DEの下位バイト
	CP 0FFH
	JR NZ,CURSOR_BOUNDARY_END ; オーバーフローしていなければジャンプ
	LD DE, VRAM_TXT_TOP-1	  ; 現在のカーソル位置 = F800H - 1 
CURSOR_BOUNDARY_END:
	POP AF
	INC DE ; カーソル位置を1つ進める
DO_CR_LF_BS_RETURN: ; CR,LF,BSの処理で戻ってくる
	CALL DO_SCROLL ; 1行スクロール処理
	LD (CURSOR_LOCATE),DE ; 現在のカーソル位置を更新。
	CALL PRINT_CURSOR ; カーソル表示
	CALL CALC_CURSOR_XY ; カーソルのX,Y座標計算
PUTCHAR_RET:
	POP DE
	POP AF
	POP HL
	RET

;
; カーソルをCURSOR_LOCATE=DEの位置に表示する(HD46505Sの機能)
;
PRINT_CURSOR:
	PUSH AF
	PUSH DE
	PUSH HL
	EX DE,HL ; HL=CURSOR_LOCATE
	LD A,0EH ; R14 (cursor H)
	OUT (CRTC_ADD),A
	LD A,H
	OUT (CRTC_VAL),A ; カーソルの上位アドレス設定
	LD A,0FH ; R15 (cursor L)
	OUT (CRTC_ADD),A
	LD A,L
	OUT (CRTC_VAL),A ; カーソルの下位アドレス設定
	POP HL
	POP DE
	POP AF
	RET

;
; CURSOR_LOCATE=DEから、カーソルのX,Y座標を計算して、特定のメモリ領域に保存する。
;
CALC_CURSOR_XY:
	PUSH AF
	PUSH BC
	PUSH DE
	PUSH HL
	LD HL,VRAM_TXT_TOP ; 画面左上端アドレスをHLにロード
	EX DE,HL ; DEとHLを交換。HL=CURSOR_LOCATE, DE=VRAM_TXT_TOP
	SBC HL,DE ; HL = CURSOR_LOCATE - VRAM_TXT_TOP
	OR A ; フラグをクリア
	LD BC,0 ; B=Y座標カウンタ初期化
Y_CALC_LOOP:
	LD DE,WIDTH_SCREEN ; 50H = 画面の桁数(80d)
	SBC HL,DE ;	HL - 50H
	JR C,Y_CALC_END ; HLが負ならループ終了
	INC B ; Y座標カウンタをインクリメント
	JR Y_CALC_LOOP
Y_CALC_END:
	ADD HL,DE ; 余り復元（これがX座標）
    LD A,B
    LD (cursor_XY_ADDR),A   ; Y座標保存
    LD A,L
    LD (cursor_XY_ADDR+2),A   ; X座標保存
	POP HL
	POP DE
	POP BC
	POP AF
	RET

;
; 
;


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; CR処理ルーチン(スクロール処理対応版)
;

DO_CR:
	PUSH HL
	PUSH BC
	XOR A ; A=0にする
	LD (CR_NOW_CURSOR_LOCATE),DE ; 現在のカーソル位置保存
	LD HL,(TOP_VIEW) ; 左上端をロード
	EX DE,HL
	SBC HL,DE ; 左上端アドレス - 現在のカーソル位置
	JR NC,CONTINUE_CR ; オーバーフローしていないなら単純処理
;
;   TOP_VIEWがCR_NOW_CURSOR_LOCATEよりも大きいとき。
;	この状況は、スクロールされた時に発生する。
;	つまり、殆どの場合、この処理が実行される。
;
	LD HL,(TOP_VIEW)
	LD DE,(CR_NOW_CURSOR_LOCATE) ; CRコードが入った時のカーソル位置
	LD BC,WIDTH_SCREEN ;  50H =  画面の桁数(80d)
	LD (CR_BASE_ADDRESS),HL ; 初期値は左上端アドレス
CR_SCAN_0:
	LD HL,(CR_BASE_ADDRESS)
	LD (CR_BASE_ADDRESS_PRE),HL
	ADD HL,BC ; 50H(80d)づつ足していく
	LD (CR_BASE_ADDRESS),HL
	JP NC,CR_SCAN_0 	; 越境をチェックしている。
						; オーバーフローまでループする。
	LD HL,(CR_BASE_ADDRESS_PRE) ; ループを抜けたときHLはオーバーフロー後の値になっている。
								; 足し算前の値に戻す
	; FFFFHを超えた値がいくつかを調べる。
	; FFFFHまでの値と合わせて、それが1行の桁数50H(80d)を
	; 超えたなら、CR後の現在カーソル位置は
	; その新しい行の先頭アドレスにならなくてはならない。
	; 
	LD DE,0FFFFH ; 境界値
	EX DE,HL
	SBC HL,DE ; FFFFH - CR_BASE_ADDRESS_PRE = A
			  ; オーバーフローする一つ前の値でFFFFHを引く
	LD DE,WIDTH_SCREEN ; 50H(80d)
	EX DE,HL
	SBC HL,DE ; 50H(80d) - A = X ; Xは境界を越えた数
	LD DE,VRAM_TXT_TOP ; VRAM_TXT_TOP = F800H
	ADD HL,DE ; F800H + X ; この値が境界を含む行の右端のアドレス
	DEC HL 	; -1する
	DEC HL 	; この引き算二回の処理がないと正しい左端のアドレスが出ない。
			; これはCP/Mでは常にプロンプト(a>)の2文字が出ているため。
	LD (CR_NEW_ORIGIN),HL ; 新しいCR評価位置になる
	LD (CR_BASE_ADDRESS),HL ; CR_BASE_ADDRESSに新しい値を入れる
	LD DE,(CR_NOW_CURSOR_LOCATE) ; CR命令を受けた時のカーソル位置

	;
	; 例えば現在カーソル位置がF819Hで新しいCR評価位置がF820Hのときに、
	; CR_2_NEW_SCAN_0のループを通ると+50Hされてしまうので、バイパスする処理。
	SBC HL,DE ; (CR_NEW_ORIGIN) > CR_NOW_CURSOR_LOCATE ?
	JP P,CR_BOUNDARY_RETURN ; 正であれば、ジャンプ
	;
	;
	LD HL,(CR_NEW_ORIGIN) ; 負であれば、そのまま処理を進める。
	LD BC,WIDTH_SCREEN ;  50H(80d)
CR_NEW_SCAN_0:
	LD HL,(CR_BASE_ADDRESS)
	LD (CR_BASE_ADDRESS_PRE),HL ; HL=CR_NEW_ORIGIN
	ADD HL,BC ; CR_NEW_ORIGIN + 50H +...
	LD (CR_BASE_ADDRESS),HL
	SBC HL,DE ; (CR_NEW_ORIGIN + 50H +...) > CR_NOW_CURSOR_LOCATE ?
	JP M, CR_NEW_SCAN_0 ; DEの方が大きければループ
	JP Z, CR_NEW_SCAN_0 ; 完全に一致したときも1回ループを回す
	LD HL,(CR_BASE_ADDRESS_PRE) ; HL>DE。50Hを足す一つ前の値をHLに入れる。
	LD (CR_BASE_ADDRESS),HL
	LD DE,(CR_BASE_ADDRESS) ; CR後のアドレスをDEに入れる。
	JR CR_END
;
;	TOP_VIEWがCR_NOW_CURSOR_LOCATEよりも小さいとき
;
CONTINUE_CR:
	LD HL,(TOP_VIEW)
	LD DE,(CR_NOW_CURSOR_LOCATE)
	LD BC,WIDTH_SCREEN ; 50H(80d) 
	LD (CR_BASE_ADDRESS),HL
CR_SCAN_1:
	LD HL,(CR_BASE_ADDRESS)
	LD (CR_BASE_ADDRESS_PRE),HL
	ADD HL,BC ; 50H(80d)づつ足していく
	LD (CR_BASE_ADDRESS),HL
	SBC HL,DE	; HLが現在のカーソル位置を超えるかチェック
	JP M,CR_SCAN_1 ; 超えていなければループ
	JP Z,CR_SCAN_1 ; 完全に一致したときも1回ループを回す。
	LD HL,(CR_BASE_ADDRESS_PRE) ; HLが現在のカーソル位置を超えたので、1つ前の値に戻す
	LD (CR_BASE_ADDRESS),HL
	LD DE,(CR_BASE_ADDRESS)
CR_END:
	POP BC
	POP HL
	JP DO_CR_LF_BS_RETURN; CR,LF,BSの処理の終了

CR_BOUNDARY_RETURN:
	LD DE,(CR_BASE_ADDRESS_PRE) ; DEに現在のカーソル位置を超える前の値(CR_BASE_ADDRESS_PRE)を戻す
	JR CR_END

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; LINE_FEED 処理(スクロール処理対応版)
;

DO_LF:
	PUSH HL
	PUSH BC
	EX DE,HL ; HL <-> DE DE=現在のカーソル位置
	LD BC,WIDTH_SCREEN ; 50H(80d)
	ADD HL,BC ; HL = DE + 50H
	JR NC,CONTINUE_LF ; オーバーフローしていなければジャンプ
;
;	BEYOND FFFFH BOUNDARY
;
	LD HL,(CURSOR_LOCATE)
	LD DE,0FFFFH
	EX DE,HL ; HL - CURSOR_LOCATE
	SBC HL,DE ; FFFFH - CURSOR_LOCATE = A
	LD DE,50H ; 50H(80d)
	EX DE,HL ; DE - A
	SBC HL,DE ; 50H - A = X
;
	DEC HL ; この引き算二回の処理がないと正しい左端のアドレスが出ない。
	DEC HL ; これはCP/Mでは常にプロンプト(a>)の2文字が出ているため。
;
	LD DE,VRAM_TXT_TOP
	ADD HL,DE
CONTINUE_LF:
	EX DE,HL ; DE <-> HL
	POP BC
	POP HL
	JP DO_CR_LF_BS_RETURN

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; BACK SPACE 処理
;
DO_BS:
	LD A, 20H ; 20H -> Space ASCII CODE
	DEC DE ; カーソル位置を1つ戻す
	OUT (0D2H),A ; access to RAM page 1
	LD (DE),A ; 20H(スペース)を表示させる。
	JP DO_CR_LF_BS_RETURN ; BSの為の復帰点に戻る。

;
; Horizontal Tab
;
DO_HT:
	PUSH AF
	PUSH HL
	PUSH BC

	; PUTCHARルーチンを4回呼び出してスペースを表示させる。
	LD A,20H ; 20H is Space CODE
	LD B,04H	; 4回ループ
HT_LOOP:
		PUSH AF
		CALL PUTCHAR
		POP AF
		DEC B
		JR NZ, HT_LOOP
	POP BC
	POP HL
	POP AF
	RET

DO_VT:
	RET

DO_NP:
	RET

DO_ESC:
	RET

DO_BEL:
	RET


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; スクロール処理
; SORD M23のCRTCであるHD4650SPはスクロール機能がある。
; 具体的には表示したい画面左上端のアドレスを、R12、R13に上位、下位アドレスとして入れることで実行される。
; SORD M23のVRAMのテキストエリアはF800H～FFFFHであるが、画面に表示される文字は80桁×25行の2000(7D0H)文字である。
; よって、余りが生じるため、スクロール処理は殆どがこの余りの処理に費やされる。
;

DO_SCROLL:
	LD (CURSOR_LOCATE),DE ; 現在のカーソル位置を更新
	LD HL,(TOP_VIEW) ; 左上端アドレス
	LD DE,7D0H ; 全画面文字数
	ADD HL,DE ; TOP_VIEW + 7D0H ; 
	JR C,SCROLL_POINT_BEYOND_FFFF ; 境界値をまたいでいる、オーバーフローしたらジャンプ
	JR SCROLL_POINT ; スクロールすべきカーソル位置の更新へ
SCROLL_POINT_BEYOND_FFFF:
	LD HL,(TOP_VIEW)
	LD DE,0FFFFH
	EX DE,HL ; HL - TOP_VIEW
	SBC HL,DE ; FFFFH - TOP_VIEW = A
	LD DE,7CEH ; 7D0H - 2H = 7CEH
	EX DE,HL ; DE - A
	SBC HL,DE ; 7CEH - A = X
	LD DE,VRAM_TXT_TOP
	ADD HL,DE ; X + F800H = 新しいTOP_VIEW
	;
SCROLL_POINT:
	; update need_do_scroll_point
	LD (NEED_DO_SCROLL_POINT),HL ; need_do_scroll_point = 新しいTOP_VIEW
	LD DE,(CURSOR_LOCATE) ; 現在のカーソル位置
	LD A,D ; need_do_scroll_point == CURSOR_LOCATE?
	CP H
	RET NZ
	LD A,E ; need_do_scroll_point == CURSOR_LOCATE?
	CP L
	RET NZ ; スクロール不要なら終了
;
; TOP_VIEWの更新
;

; スクロールから外れた行をスペースで埋める。
	LD HL,(TOP_VIEW) ; スクロール直前の左上端アドレス
	PUSH BC
	PUSH DE
	PUSH AF
	LD B,04FH ; 4FH=79d
	LD DE,0FFFFH ; 境界値
	LD A,20H ; 20H is Space CODE
CLEAR_1_LINE:
	OUT (0D2H),A
	LD (HL),A ; スペースで埋める
	PUSH HL ; HL < FFFFHのとき、下の引き算はオーバーフローするが、
			; HL=F800Hの時に実行すると、HL=F801となり、
			; その後INC HLでF802Hになるため、スペースによる穴埋めがF801Hのみ実行されないことになる。
			; なので、一度、HLを退避して、引き算してFFFFHでないか判定したのち、POPして戻している。
			; このコードは遅いが、現状、これを採用する。20221229
	SBC HL,DE ; HL - FFFFH = HL
	POP HL
	JR Z, CLEAR_BEYOND_BOUNDARY ; HL = FFFFHのときは境界を越えた
	INC HL
	DJNZ CLEAR_1_LINE
	JR CLEAR_1_LINE_END
	; 越境時の処理
CLEAR_BEYOND_BOUNDARY:
	LD HL,VRAM_TXT_TOP ; HLをVRAMの先頭(F800H)にセット
CLEAR_1_LINE_BOUNDARY: ; B回ループする
	OUT (0D2H),A
	LD (HL),A
	INC HL
	DJNZ CLEAR_1_LINE_BOUNDARY
CLEAR_1_LINE_END:
	POP AF
	POP DE
	POP BC
;
;
	LD HL,(TOP_VIEW) ; TOP_VIEWの更新
	LD DE,50H ; 50H=80d
	ADD HL,DE ; TOP_VIEW + 50H
	JR NC,UPDATE_TOP_VIEW
;
;	BEYOND FFFFH BOUNDARY
;
	LD DE,0FFFFH ; 境界値
	LD HL,(TOP_VIEW) ; TOP_VIEW
	EX DE,HL
	SBC HL,DE ; FFFFH - TOP_VIEW = A
	LD DE,50H ; 50H(80d)
	EX DE,HL ; DE - A
	SBC HL,DE ; 50H - A = X
	LD DE,VRAM_TXT_TOP ; VRAM_TXT_TOP
	ADD HL,DE ; F800H + X = TOP_VIEW
;
	DEC HL ; この引き算二回の処理がないと正しい左端のアドレスが出ない。
	DEC HL ; これはCP/Mでは常にプロンプト(a>)の2文字が出ているため。
;
UPDATE_TOP_VIEW:
	LD (TOP_VIEW),HL
	;
	; 1行スクロール
	;
	PUSH AF
	LD A,0CH ; START ADDRESS HIGH
	OUT (CRTC_ADD),A
	LD A,H ; スクロールしたときに左隅になるVRAMの上位アドレス
	OUT (CRTC_VAL),A
	LD A,0DH ; START ADDRESS LOW
	OUT (CRTC_ADD),A
	LD A,L ; スクロールしたときに左隅になるVRAMの下位アドレス
	OUT (CRTC_VAL),A
	POP AF
SCROLL_END:
	RET



;
; for CRT control
;

CURSOR_LOCATE: ; カーソル位置を保存する変数
	DS 02H

TOP_VIEW: ; 画面左上端のアドレスを保存する変数
	DS 02H

NEED_DO_SCROLL_POINT: ;	スクロールすべきポイントアドレスを保存する変数
	DS 02H

CR_BASE_ADDRESS: ; CRTコントローラのベースアドレス保存変数
	DS 02H

CR_BASE_ADDRESS_PRE: ; CRTコントローラのベースアドレス保存変数（前回値）
	DS 02H

CR_NOW_CURSOR_LOCATE: ; 現在のカーソル位置保存変数
	DS 02H

CR_NEW_ORIGIN: ; 新しい表示開始アドレス保存変数
	DS 02H


	ORG	2B00H

;===============
;エントリ
;===============


DREAD:	JP	read_disk_entity	;ディスク読み込み
DWRITE:	JP	write_disk_entity	;ディスク書き込み
disk_unit_number:	DS	1	;0～


;===============
;サブルーチン
;===============


;DREAD本体
;入力	HL←読み込みアドレス、DE←レコード番号、Acc←レコード数
;	[disk_unit_number]参照
;出力	CY＝0（Acc←0）なら成功、
;	CY＝1（Acc←エラー･コード）なら失敗
;破壊	AF，AF'
read_disk_entity:
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	DRDSB	;ディスクから読み込みます
	POP	HL
	POP	DE
	POP	BC
	RET


;ディスクから読み込みます
;入力	HL←読み込みアドレス、DE←レコード番号、Acc←レコード数
;	[disk_unit_number]参照
;出力	CY＝0（Acc←0）なら成功、
;	CY＝1（Acc←エラー･コード）なら失敗
;破壊	AF，HL，DE，BC，AF'
DRDSB:
	LD	(SPBUFF),SP	;リターン･スタック･ポインタ
	CALL	get_track_number_and_sector_number_from_record_number	;レコード番号より、トラック番号とセクタ番号を得ます
	CALL	get_ready_to_access_disk	;ディスクをアクセス可能にします
AGNRDY:
	CALL	SEEK	;目的のシリンダへシークします（V1，20ms） '0msに改
REDAGN:
	LD	A,5	;リトライ･カウンタ
REDRTY:
	PUSH	AF
	PUSH	HL
	LD	A,10000000B	;リード･データ（サイド比較なし）
	CALL	set_sector_number_and_execute_FDC_coomand	;FDCにセクタ番号をセットして、FDCコマンドを実行します
	PUSH	DE
	LD	DE,0F8FBH
	LD	C,E	;BC←0FFBH 'データ･レジスタ
	IN	A,(C)
	LD	C,D	;BC←0FF8H

MPNYMI:	IN	A,(C)
	RRCA		;BUSY
	JR	NC,ENDRED
	RRCA		;DATA REQUEST
	JR	NC,MPNYMI
	LD	C,E	;BC←0FFBH 'データ･レジスタ
	IN	A,(C)	;FDより1バイト読みます
	LD	(HL),A	;メモリに書き込みます
	INC	HL
	LD	C,D	;BC←0FF8H
	JR	MPNYMI

;	NOT READY，RECORD NOT FOUND，CRC ERROR，LOST DATA
ENDRED:	AND	01001110B	;10011100B
	POP	DE
	JR	Z,CNTRED
;	エラー
	POP	HL	;HL←読み込み先頭アドレス
	POP	AF	;Acc←リトライ･カウンタ
	DEC	A
	JP	Z,device_io_error	;リトライでも回復不能
	CALL	restore_and_seek	;リストアして、目的のシリンダへシークします
	JR	REDRTY	;リトライします

;	ノー･エラー
CNTRED:	POP	AF	;読み込み先頭アドレスを捨てます
	POP	AF	;リトライ･カウンタを捨てます
	EX	AF,AF'	;Acc←レコード数
	DEC	A
	JP	Z,fdd_motor_off	;モータをオフします
	EX	AF,AF'
	CALL	count_up_sector	;セクタ番号のカウント･アップ
	JR	NC,REDAGN
	JR	AGNRDY


;DWRITE本体
;入力	HL←書き込みアドレス、DE←レコード番号、Acc←レコード数
;	[disk_unit_number]参照
;出力	CY＝0（Acc←0）なら成功、
;	CY＝1（Acc←エラー･コード）なら失敗
;破壊	AF，AF'
write_disk_entity:
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	DWTSB	;ディスクへ書き込みます
	POP	HL
	POP	DE
	POP	BC
	RET


;ディスクへ書き込みます
;入力	HL←書き込みアドレス、DE←レコード番号、Acc←レコード数
;	[disk_unit_number]参照
;出力	CY＝0（Acc←0）なら成功、
;	CY＝1（Acc←エラー･コード）なら失敗
;破壊	AF，HL，DE，BC，AF'
DWTSB:
	LD	(SPBUFF),SP	;リターン･スタック･ポインタ
	CALL	get_track_number_and_sector_number_from_record_number	;レコード番号より、トラック番号とセクタ番号を得ます
	CALL	get_ready_to_access_disk	;ディスクをアクセス可能にします
AGNWRT:
	CALL	SEEK	;目的のシリンダへシークします（V1，20ms） '0msに改
WRTAGN:
	LD	A,5	;リトライ･カウンタ
WRTRTY:
	PUSH	AF
	PUSH	HL
	LD	A,10100000B	;ライト･データ（サイド比較なし）
	CALL	set_sector_number_and_execute_FDC_coomand	;FDCにセクタ番号をセットして、FDCコマンドを実行します
	PUSH	DE
	LD	DE,0F8FBH

MPNWRT:	IN	A,(C)
	RRCA		;BUSY
	JR	NC,ENDWRT
	RRCA		;DATA REQUEST
	JR	NC,MPNWRT
	LD	A,(HL)	;メモリから読みます
	LD	C,E	;BC←0FFBH 'データ･レジスタ
	OUT	(C),A	;FDに1バイト書き込みます
	INC	HL
	LD	C,D	;BC←0FF8H
	JR	MPNWRT

ENDWRT:
	BIT	5,A	;b6 WRITE PROTECT
	JP	NZ,write_protect_error	;エラー
;	NOT READY，WRITE PROTECT，WRITE FAULT，RECORD NOT FOUND，CRC ERROR，LOST DATA
	AND	01111110B	;11111100B
	POP	DE
	JR	Z,CNTWRT
;	エラー
	POP	HL	;HL←読み込み先頭アドレス
	POP	AF	;Acc←リトライ･カウンタ
	DEC	A
	JR	NZ,WTRTYL
	JP	device_io_error	;リトライでも回復不能
WTRTYL:
	CALL restore_and_seek	;リストアして、目的のシリンダへシークします
	JR	WRTRTY	;リトライします

;	ノー･エラー
CNTWRT:
	POP	AF	;読み込み先頭アドレスを捨てます
	POP	AF	;リトライ･カウンタを捨てます
	EX	AF,AF'	;Acc←レコード数
	DEC	A
	JP	Z,fdd_motor_off	;モータをオフします
	EX	AF,AF'
	CALL	count_up_sector	;セクタ番号のカウント･アップ
	JR	NC,WRTAGN
	JR	AGNWRT


;レコード番号より、トラック番号とセクタ番号を得ます
;入力	DE←レコード番号、Acc←レコード数
;	[disk_unit_number]参照
;出力	D←トラック番号、E←セクタ番号、Acc'←レコード数
;破壊	AF，DE，AF'
get_track_number_and_sector_number_from_record_number:
	PUSH HL
	LD	L,A	;L←レコード数
	EX	AF,AF'	;AF'
	LD	H,4
	LD	A,0FFH	;H A'←04FFH
	DEC	L	;L←レコード数－1
	SUB	L	;H A'←04FFH－（レコード数－1）
	LD	L,A	;HL←0500H－レコード数
	OR	A
	SBC	HL,DE	;（0500H－レコード数）－レコード番号
	POP	HL
	JP	C,bad_sector_error
	LD	A,E
RLLOP:
	RLCA
	RL	D
	RLCA
	RL	D
	RLCA
	RL	D
	RLCA
	RL	D	;D←トラック番号
	LD	A,E
	AND	0FH
	INC	A
	LD	E,A	;E←セクタ番号
	RET


;ディスクをアクセス可能にします
;入力	D←トラック番号
;出力	D←シリンダ番号、[disk_unit_number b4]←サイド、B←0FH
;破壊	AF，BC
get_ready_to_access_disk:
	PUSH	HL
	DI
	CALL check_FDC	;FDCをチェックします
	LD	A,(disk_unit_number)
	AND	00000011B
	SRL	D	;D←シリンダ番号
	JR	NC,J1
	OR	00010000B
J1:	OR	10000000B
	LD	(disk_unit_number),A	;[disk_unit_number]←I／O 0FFCHに書き込む値
	LD	C,0FCH	;BC←0FFCH
	OUT	(C),A	;モータ･オン
	PUSH	DE
DBSY:	LD	E,3
	LD	HL,0
	LD	BC,0FF8H

;	ディスクが正常回転するまで、196,608ループまで待ちます
RDYWT1:
	IN	A,(C)
	AND	10000001B
	JR	Z,RTRDYS	;POPリターン
	DEC	HL
	LD	A,H
	OR	L
	JR	NZ,RDYWT1
	DEC	E
	JR	NZ,RDYWT1
	JP	device_offline_error


;目的のシリンダへシークします（V1，20ms） '0msに改
;入力	D←シリンダ番号、B←0FH
;出力	なし
;破壊	AF，C
SEEK:
	LD	C,0FBH	;BC←0FFBH 'データ･レジスタ
	OUT	(C),D	;FDCデータ･レジスタ←シリンダ番号
	PUSH HL
	CALL get_cylinder_buffer_address	;シリンダ･バッファのアドレスを得ます
	LD	A,(HL)
	LD	C,0F9H	;BC←0FF9H 'トラック･レジスタ
	OUT	(C),A	;FDCシリンダ･レジスタ←現在シリンダ番号
	LD	(HL),D	;シリンダ･バッファの更新
	POP	HL
	LD	C,0F8H	;BC←0FF8H
;	LD	A,00011110B	;シーク（V1，20ms）
	LD	A,00011100B	;シーク（V1， 0ms）
	OUT	(C),A


;FDCレディ待ち
;出力	なし
;破壊	AF，BC
wait_for_FDC_ready:
;	115.5μs（462ts）待ちます
	PUSH	HL	;11ts
	PUSH	DE	;11ts
	LD	B,32	; 7ts
SELF:
	DJNZ	SELF	;411ts
	LD	BC,0FF8H	;10ts

BSYLP1:
	IN	A,(C)	;12ts
	RRCA		;BUSY
	JR	C,BSYLP1

RTRDYS:
	POP	DE
	POP	HL
	RET


;FDCをチェックします
;出力	B←0FH
;破壊	AF，BC
check_FDC:
	PUSH	DE
	LD	D,255

check_FDCL:	LD	BC,0FFBH	;データ･レジスタ
	LD	A,0A5H
	OUT	(C),A
;	139.5μs待ちます
	LD	A,16
	CALL wait_8usec	;8μs単位で待ちます
	IN	A,(C)
	CP	0A5H
	JR	NZ,J2
	POP	DE
	RET		;FDCが正常動作
J2:	DEC	D
	JR	NZ,check_FDCL

;	FDCが正常でない
	POP	DE
	JP	device_offline_error


;8μs単位で待ちます
;入力	Acc←カウンタ
;出力	32×Acc＋10ts待ちます
;破壊	AF
wait_8usec:
;	1ループ32ts
	DEC	A	; 4ts
	LD	HL,(1234H)	;16ts
	JR	NZ,wait_8usec	;12ts
	RET		;10ts


;シリンダ･バッファのアドレスを得ます
;入力	[disk_unit_number b3～b0]←ユニット番号（0～3）
;出力	HL←対応するシリンダ･バッファのアドレス
;破壊	AF，HL
get_cylinder_buffer_address:
	LD	HL,DSKTRK	;シリンダ･バッファ
	PUSH	DE
	LD	A,(disk_unit_number)
	AND	00001111B
	LD	E,A
	LD	D,0
	ADD	HL,DE
	POP	DE
	RET


;FDCにセクタ番号をセットして、FDCコマンドを実行します
;入力	E←セクタ番号、Acc←FDCコマンド、B←0FH
;出力	C←F8H
;破壊	AF，C
set_sector_number_and_execute_FDC_coomand:
	EI
	LD	C,0FAH	;BC←0FFAH 'セクタ･レジスタ
	DI
	OUT	(C),E	;FDCセクタ･レジスタ←セクタ番号
	LD	C,0F8H	;BC←0FF8H
	OUT	(C),A
;	31μs（124ts）待ちます
	LD	A,7	;7ts
J3:	DEC	A	;---ts
	JR	NZ,J3	;107ts
	RET		;10ts


;モータをオフします
;出力	CY＝0
fdd_motor_off:
	PUSH	AF
	LD	BC,0FFCH
	LD	A,(disk_unit_number)
	AND	00000011B
	OUT	(C),A
	POP	AF
	EI
	OR	A
	RET


;リストアして、目的のシリンダへシークします
;出力	D←シリンダ番号、B←0FH
;破壊	BC
restore_and_seek:
	PUSH	AF
	PUSH	HL
	PUSH	DE
	CALL	get_cylinder_buffer_address	;シリンダ･バッファのアドレスを得ます
	LD	(HL),0
	XOR	A
	LD	BC,0FF9H	;トラック･レジスタ
	OUT	(C),A	;FDCシリンダ･レジスタ←0
	DEC	C	;BC←0FF8H
;	LD	A,00000010B	;リストア（V0，20ms）
	LD	A,00000000B	;リストア（V0， 0ms）
	OUT	(C),A
	CALL	wait_for_FDC_ready	;FDCレディ待ち
	POP	DE
	CALL	SEEK	;目的のシリンダへシークします（V1，20ms） '0msに改
	POP	HL
	POP	AF
	RET


;セクタ番号のカウント･アップ
;入力	E←セクタ番号、D←シリンダ番号、B←0FH
;出力	CY＝1ならシリンダの更新が必要
;破壊	AF，DE，C
count_up_sector:
	INC	E
	LD	A,16
	CP	E
	RET	NC	;セクタ番号2～16

;	トラックのカウント･アップ
	LD	E,1
	PUSH	HL
	LD	HL,disk_unit_number
	LD	A,(HL)
	XOR	00010000B
	LD	(HL),A
	AND	00010000B
	JR	NZ,BFIOST	;サイド0へ
	INC	D	;シリンダ番号のカウント･アップ
	SCF
BFIOST:
	LD	C,0FCH	;BC←0FFCH
	LD	A,(HL)
	OUT	(C),A	;サイドの更新
	POP	HL
	RET


;=======================
;エラー･ジャンプ
;=======================


bad_sector_error:	LD	A,5	;Bad Record
	DB	01H	;「LD BC,」
device_offline_error:	LD	A,2	;Device Offline
	DB	01H	;「LD BC,」
write_protect_error:	LD	A,4	;Write Protected
	DB	01H	;「LD BC,」
device_io_error:	LD	A,1	;Device I/O Error
	CALL	fdd_motor_off	;モータをオフします
	LD	SP,(SPBUFF)	;リターン･スタック･ポインタ
	SCF
	RET


;===============
;内部ワーク
;===============


DSERJP:	DS	2	;未使用
SPBUFF:	DS	2	;リターン･スタック･ポインタ
DSKTRK:	DS	4	;各ユニットのシリンダ･バッファ


;	RUN＆SUBMITルーチン組み込み

;　ファイルの先頭が3000Hで、サイズが7Kバイト（1C00H）
;以内のファイルは、RAMディスク（デバイスE:）に、
;メモリの3000H～4BFFHの内容が待避されます。
;その場合は、RAMディスクのレコード0～13、18～31が使用されます。
;よって、RAMディスクのディレクトリ領域は2レコードしか使えません。
;このことは、RAMディスク（デバイスE:）を64Kバイト以内とみなしています。

	ORG	1CC0H ; RUN&SUBMITルーチン･エリア


;DOSモジュール、2152H番地よりジャンプしてきます（コマンドの拡張）
execute_expanded_command:
	CP	';'	;REMコマンド
	RET	Z
	CP	'P'	;ポーズ･コマンド
	JR	Z,RSPAU
	CP	' '	;RUNコマンド
	JR	Z,RUN
	LD	A,13	;Syntax Error
	SCF
	RET


;モニタ 「;」コマンド処理
RSPAU:
	CALL	_MPRNT
	DB	'HIT KEY',0DH,00H

;	キーがはなされるまで待ちます
PAU0:	CALL	_GETKY
	OR	A
	JR	NZ,PAU0

;	CALL	_INKEY
	CALL	PAU1	;バッチ･ファイルなどからキー入力させないため
	CP	1BH	;ESC
	JP	Z,BOFF	;[BATFLG]をクリアします
	OR	A
	RET


;モニタ Rコマンド処理
;注：DEは、コマンドまたはバッチ変数の次のアドレスを示しています。
RUN:
	LD	A,1
	CALL	_FILE
	LD	A,(DE)
	OR	A
	JR	Z,RUN0
	INC	DE	;パラメータの区切りをとばします
RUN0:	PUSH	DE
	CALL	_ROPEN
	JP	C,BATCH	;ファイル属性が違った（バッチ･ファイル）かも知れない
;	CALL	CMNDQ	;コマンド･ファイルならRAMディスクにメモリを待避します
	DS	3,00H
	CALL	_RDD
	POP	DE
	JR	C,RUN1
	LD	HL,(_EXADR)
	CALL	_HL
RUN1:	PUSH	AF
	LD	A,(COMF)	;メモリ待避フラグ
	OR	A
	CALL	NZ,CWRT	;待避したメモリを元に戻します
	POP	AF
	RET


;コマンド･ファイル（先頭3000Hで、サイズ7Kバイト以下）ならRAMディスクにメモリを待避します
;入力	[_DTADR]、[_SIZE]参照
;出力	なし
;破壊	AF，HL，DE，AF'
CMNDQ:
	XOR	A
	LD	(COMF),A	;メモリ待避フラグ
	LD	HL,(_DTADR)
	LD	DE,3000H
	SBC	HL,DE
	RET	NZ	;先頭アドレスが3000H以外だった

;	先頭アドレスが3000H
	LD	HL,(_SIZE)
;	LD	DE,-1C00H
	LD	DE,-1C01H	;深谷崇さんより
	ADD	HL,DE
	RET	C	;サイズが1C00Hより大きい

;	サイズが7Kバイト（1C00H）以下
;	メモリを待避します
	LD	A,(_DSK)
	PUSH	AF
	CALL	SET1	;アクセスするデバイスをRAMディスクにして、メモリ待避用のパラメータ（前半）を得ます
	CALL	_DWTSB
	CALL	SET2	;メモリ待避用のパラメータ（後半）を得ます
	CALL	_DWTSB
	POP	AF
	LD	(_DSK),A
	LD	A,1
	LD	(COMF),A	;メモリ待避フラグ
	RET


;待避したメモリを元に戻します
;入力	なし
;出力	[_DSK]←「E」、HL←3000H、DE←0、Acc←14
;破壊	AF，HL，DE，AF'
CWRT:
	CALL	SET1	;アクセスするデバイスをRAMディスクにして、メモリ待避用のパラメータ（前半）を得ます
	CALL	_DRDSB
	CALL	SET2	;メモリ待避用のパラメータ（後半）を得ます
	JP	_DRDSB


;アクセスするデバイスをRAMディスクにして、メモリ待避用のパラメータ（前半）を得ます
;入力	なし
;出力	[_DSK]←「E」、HL←3000H、DE←0、Acc←14
;破壊	A，HL，DE
SET1:
	LD	A,'E'
	LD	(_DSK),A
	LD	HL,3000H
	LD	DE,0
	LD	A,14
	RET


;メモリ待避用のパラメータ（後半）を得ます
;入力	なし
;出力	HL←3E00H、DE←18、Acc←14
;破壊	A，HL，DE
SET2:
	LD	HL,3E00H
	LD	DE,18
	LD	A,14
	RET


;=======================
;#HOT（1F7EH）のっとり
;=======================


;AUTOEXEC.BATの自動実行
run_auto_execute_batch:
	LD	HL,_HOT
	LD	(_USR),HL
	LD	DE,AUTNAM
	CALL	_BRKEY
	CALL	NZ,RUN
	JP	_HOT


;モニタ Rコマンド処理の続き（バッチ･ファイル）
;入力	スタック←ファイル名のあとにあるパラメータのアドレス
;注：
;　バッチ変数があれば、バッチ変数バッファに格納します。
;　DEは、コマンドまたはバッチ変数の次のアドレスを示しています。
BATCH:
; 	POP	DE	;DE←パラメータのアドレス
; 	CALL	BOFF	;[BATFLG]をクリアします
; 	CP	6	;ファイル属性の不一致
; 	SCF
; 	RET	NZ

; ;	01H以外のファイル属性のファイル
; 	LD	HL,(_IBFAD)
; 	LD	A,(HL)	;Acc←ファイル属性
; ;注：
; ;　ここはソースとコメントのリセットするビットが違います。
; ;ソースはb6（書き込み禁止属性）、コメントはb5（ベリファイON属性）。
; 	AND	0BFH	;「1101 1111」←オリジナルのコメント（多分間違い）
; 	CP	4
; 	LD	A,6	;Bad File Mode
; 	SCF
; 	RET	NZ	;アスキー･ファイルでなかった

; ;	アスキー･ファイルだった
; 	LD	BC,1EH
; 	ADD	HL,BC	;HL←FCBバッファのクラスタ番号の部分
; 	CALL	STTRK	;[BTRK]と[BREC]を設定します
; 	CALL	STPARA	;バッチ変数をバッチ変数バッファを読み込みます
; 	LD	A,(_DSK)
; 	LD	(BDEV),A	;バッチ･ファイルのあるデバイス
; 	LD	A,16+1
; 	LD	(BCNT),A	;バッチ･ファイルの現在クラスタの残りレコード数＋1
; 	XOR	A
; 	DEC	A	;Acc←FFH
; 	LD	(BTPNT),A	;バッチ･ファイルのバッファの前回のリード位置
; 	LD	(BATFLG),A	;＝FFH（0以外）でバッチ･ファイル実行中
	RET


;[BTRK]と[BREC]を設定します
;入力	[HL]←クラスタ番号
;出力	[BTRK]←クラスタ番号、[BREC]←レコード番号
;破壊	AF，HL
STTRK:
	LD	A,(HL)	;Acc←クラスタ番号
	LD	(BTRK),A	;バッチ･ファイルの現在クラスタ番号
	LD	L,A
	LD	H,0	;HL←クラスタ番号
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL	;HL←クラスタ番号×16
	LD	(BREC),HL	;バッチ･ファイルのあるレコード番号
	RET


;バッチ変数をバッチ変数バッファを読み込みます
;入力	DE←パラメータのアドレス
;出力	[BPRBF～]←バッチ変数
;破壊	AF，HL，DE，BC
STPARA:
;	バッチ変数バッファをクリアします
; 	LD	HL,BPRBF	;バッチ変数バッファ
; 	LD	(HL),0
; 	PUSH	DE
; 	PUSH	HL
; 	LD	D,H
; 	LD	E,L
; 	INC	DE	;DE←BPRBF＋1
; 	LD	BC,179
; 	LDIR		;[BPRBF～BPRBF＋179]をクリア
; 	POP	HL	;HL←BPRBF
; 	POP	DE	;DE←パラメータのアドレス

; 	LD	A,(DE)	;Acc←パラメータの先頭
; 	CP	':'
; 	JR	NZ,STP0
; 	INC	DE	;「:」をスキップ
; STP0:	LD	C,9	;バッチ変数は￥1～￥9の9個

; STPAR0:	LD	B,19	;バッチ変数1個につき20バイト

; ;	バッチ変数をバッチ変数バッファに転送します
; STPAR1:	LD	A,(DE)
; 	OR	A
; 	RET	Z
; 	CP	' '	;バッチ変数の区切り
; 	JR	Z,STPAR3	;区切りに達した
; 	LD	(HL),A
; 	INC	HL
; 	INC	DE
; 	DJNZ	STPAR1

; STPAR2:	INC	HL
; 	DEC	C
; 	JR	NZ,STPAR0

	RET

;	アドレスをスキップします
; STPAR3:	INC	DE
; STPAR4:	INC	HL
; 	DJNZ	STPAR4
; 	JR	STPAR2


;バッチ･ファイルから1文字を得ます
;入力	なし
;出力	CY＝0ならバッチ･ファイル実行中でAcc←キャラ
;	CY＝1ならバッチ･ファイル実行中でないか、バッチ変数￥0が来た
;破壊	AF，AF'
BGET:
	LD	A,(BATFLG)	;＝FFH（0以外）でバッチ･ファイル実行中
	OR	A
	SCF
	RET	Z

;	バッチ･ファイル実行中
	PUSH	BC
	PUSH	HL
	LD	A,(PARAF)	;＝1（0以外）でバッチ変数アクセス中
	OR	A
	JR	Z,BGET0	;バッチ変数アクセス中でない

;	バッチ変数アクセス中
BPARA:	LD	HL,(BTPNT2)	;バッチ変数の現在アドレス
	LD	A,(HL)
	OR	A
	JR	NZ,BPARA0	;バッチ変数の終わりに達していない

;	バッチ変数の終わりに達した（[PARAF]のクリア）
	LD	(PARAF),A	;＝1（0以外）でバッチ変数アクセス中

;	バッチ･ファイルから1バイト取り出します
BGET0:	CALL	get_one_byte_fro_batch_file	;バッチ･ファイルから1バイト取り出します
	OR	A
	JR	Z,BEND	;バッチ･ファイルからリード終了
	CP	'\\'	;バッチ変数
	JR	NZ,BGET1

;	バッチ変数
	CALL	PARAQ	;バッチ変数のアクセスを設定
	JR	NC,BPARA	;バッチ変数だった

;	リターンします（Acc←キャラ）
BGET1:	OR	A	;CY←0
	POP	HL
	POP	BC
	RET

;	バッチ変数バッファより1バイト取り出してリターンします
BPARA0:	INC	HL
	LD	(BTPNT2),HL	;バッチ変数の現在アドレス
	JR	BGET1

;	バッチ･ファイルを終わります
;出力	CY←1、Acc←0
BEND:	CALL	BOFF	;[BATFLG]をクリアします
	SCF
	POP	HL
	POP	BC
	RET


;バッチ･ファイルから1バイト取り出します
;入力	なし
;出力	Acc←キャラ
;	Acc＝0なら、バッチ･ファイルから読み込めなかった
;破壊	AF，HL，AF'
get_one_byte_fro_batch_file:
; 	CALL	_BRKEY
; 	LD	A,0
; 	RET	Z	;ブレイク･キーを押されていた

; 	LD	HL,BTPNT	;バッチ･ファイルのバッファの前回のリード位置
; 	INC	(HL)
; 	JR	NZ,read_one_byte_from_buffer_of_batch_file	;バッチ･ファイルのバッファから読み込み可能

; ;	バッチ･ファイルのリード･バッファが空
; 	LD	HL,BCNT	;バッチ･ファイルの現在クラスタの残りレコード数＋1
; 	DEC	(HL)
; 	JR	NZ,read_next_record_from_batch_file	;次のレコードを読みます

; ;	次のクラスタを読みます
; 	LD	(HL),16	;[BCNT]←16
; 	PUSH	DE
; 	LD	DE,(_FATPS)
; 	LD	HL,BATBF	;バッチ･ファイル用リード･バッファ（2D00H～2DFFH）
; 	CALL	RSREAD	;バッチ･ファイルを読みます
; 	JR	C,error_read_from_buffer_of_batch_file	;リード･エラー
; 	LD	A,(BTRK)	;バッチ･ファイルの現在クラスタ番号
; 	LD	E,A
; 	LD	D,0	;DE←バッチ･ファイルの現在クラスタ番号
; 	ADD	HL,DE	;HL←バッチ･ファイルのバッファの次のクラスタ番号の部分
; 	CALL	STTRK	;[BTRK]と[BREC]を設定します
; 	POP	DE

; ;	次のレコードを読みます
; read_next_record_from_batch_file:
; 	PUSH	DE
; 	LD	DE,(BREC)	;バッチ･ファイルの現在レコード番号
; 	LD	HL,BATBF	;バッチ･ファイル用リード･バッファ（2D00H～2DFFH）
; 	CALL	RSREAD	;バッチ･ファイルを読みます
; 	JR	C,error_read_from_buffer_of_batch_file	;リード･エラー
; 	INC	DE
; 	LD	(BREC),DE	;バッチ･ファイルの現在レコード番号
; 	POP	DE

; ;	バッチ･ファイルのバッファより、1バイト取り出します
; read_one_byte_from_buffer_of_batch_file:
; 	LD	HL,(BTPNT)	;バッチ･ファイルのバッファの前回のリード位置
; 	LD	A,(HL)
	RET

;	バッチ･ファイルから読み込めなかった
error_read_from_buffer_of_batch_file:
	POP	DE
	XOR	A	;Acc←0
	RET


;バッチ･ファイルを読みます
;入力	HL←読み込みアドレス、DE←レコード番号
;出力	CY＝1（Acc←エラー･コード）ならエラー
;破壊	AF，AF'
RSREAD:
	LD	A,(_DSK)
	PUSH	AF	;スタック←もとのデバイス
	LD	A,(BDEV)	;バッチ･ファイルのあるデバイス
	LD	(_DSK),A	;一時的にバッチ･ファイルのデバイスに
	LD	A,1	;1レコード
	CALL	_DRDSB
	EX	AF,AF'
	POP	AF	;Acc←もとのデバイス
	LD	(_DSK),A	;デバイスをもとに戻します
	EX	AF,AF'
	RET


;バッチ変数のアクセスを設定
;入力	なし
;出力	CY＝1ならバッチ変数でなかった（Acc←キャラ）
;破壊	AF，HL，BC，AF'
PARAQ:
; 	CALL	get_one_byte_fro_batch_file	;バッチ･ファイルから1バイト取り出します
; 	CP	'0'
; 	RET	C
; 	CP	'9'+1
; 	CCF
; 	RET	C

; ;	バッチ変数￥0～￥9
; 	SUB	'0'
; 	JR	Z,PAR00	;「\0」だった

; ;	バッチ変数￥1～￥9
; 	LD	L,A
; 	LD	H,0	;HL←1～9
; 	ADD	HL,HL
; 	ADD	HL,HL	;HL←(1～9)×4
; 	LD	B,H
; 	LD	C,L	;BC←(1～9)×4
; 	ADD	HL,HL
; 	ADD	HL,HL	;HL←(1～9)×16
; 	ADD	HL,BC	;HL←(1～9)×20
; 	LD	BC,BPRBF-20	;バッチ変数バッファ
; 	ADD	HL,BC	;HL←バッチ変数に対応するバッファのアドレス
; 	LD	(BTPNT2),HL	;バッチ変数の現在アドレス
; 	XOR	A	;CY←0
; 	INC	A	;Acc←1
; 	LD	(PARAF),A	;＝1（0以外）でバッチ変数アクセス中
; 	RET

; ;	バッチ変数￥0（BGETルーチンを呼び出したルーチンにCY＝1で戻ります）
; PAR00:	CALL	get_one_byte_fro_batch_file	;バッチ･ファイルから1バイト取り出します
; 	OR	A
; 	JR	Z,PAR01
; 	CP	0DH	;RET
; 	JR	NZ,PAR00	;CRコードのスキップ
; PAR01:	POP	HL	;戻り番地のキャンセル

; ;	BGETルーチンのスタックに保存したレジスタをもとに戻します
; 	POP	HL
; 	POP	BC

; 	CALL	_BELL
; 	SCF
	RET


;[BATFLG]をクリアします
;破壊	なし
BOFF:
	PUSH	AF
	XOR	A
	LD	(BATFLG),A	;＝FFH（0以外）でバッチ･ファイル実行中
	POP	AF
	RET


;===============================
;#FLGET（2021H）のっとり
;===============================


BFLGET:
	CALL	BGET	;バッチ･ファイルから1文字を得ます
	RET	NC
;	ここのジャンプ先は、機種によって違います
;	JP	1CA0H	;本来の#FLGETルーチンへ（バグ処理ルーチン経由）
	JP	_INKEY


;=======================
;#GETL（1FD3H）のっとり
;=======================


;1F2CH番地よりジャンプして来る（バグ回避のため）
;破壊	AF，BC
BGETL:
;	論理行頭にカーソルがあるかを、カーソルx座標でチェックします（少し問題あり）
	PUSH	DE
	PUSH	HL
	CALL	_CSR
	LD	A,L
	OR	A
	JR	Z,BGETL0	;x座標が0

;	x座標が0でなかった
	LD	B,A	;B←文字数
	LD	L,0	;L←0（x座標）

;	画面からカーソル位置までのキャラを1行入力バッファに転送します
BGTLL:	CALL	_SCRN
	LD	(DE),A
	INC	DE
	INC	L
	DJNZ	BGTLL

;	バッチ･ファイルからの入力
BGETL0:	CALL	BGET	;バッチ･ファイルから1文字を得ます
	JR	NC,BGETL1	;バッチ･ファイルから入力があった
	POP	HL
	POP	DE
;	ここのジャンプ先は機種によって違います
;	JP	1610H	;本来の#GETL
	JP	_GETL

;
BGETL1:	CALL	print_one_character	;画面に1文字表示します（プリンタには出力しません）
	CP	0DH	;RET
	JR	Z,BGETL2
	LD	(DE),A	;1行入力バッファ←キャラ
	INC	DE
	JR	BGETL0

;	1行入力された
BGETL2:	XOR	A	;Acc←ターミネータ
	LD	(DE),A	;1行入力バッファ←ターミネータ
	POP	HL
	POP	DE
	RET


;画面に1文字表示します（プリンタには出力しません）
;入力	Acc←キャラ
;出力	なし
;破壊	F，AF'
print_one_character:
	EX	AF,AF'
	LD	A,(_LPSW)
	EX	AF,AF'
	CALL	_LPTOF
	CALL	_PRINT
	EX	AF,AF'
	OR	A
	CALL	NZ,_LPTON
	EX	AF,AF'
	RET


;===============================
;#ERROR（2033H）のっとり
;===============================


RSERR:
	CALL	BOFF	;[BATFLG]をクリアします
	OR	A
	RET	Z	;Acc＝0ならエラー表示をしません
	JP	ERROR


;=======
;フラグ
;=======


COMF:	DS	1	;＝1で、RAMディスクへメモリ3000H～4BFFHの待避が行われた
BDEV:	DS	1	;バッチ･ファイルのあるデバイス
BTRK:	DS	1	;バッチ･ファイルの現在クラスタ番号
BREC:	DS	2	;バッチ･ファイルの現在レコード番号
BCNT:	DS	1	;バッチ･ファイルの現在クラスタの残りレコード数＋1
; BTPNT:	DW	BATBF	;下位はバッチ･ファイルのバッファの前回のリード位置
BTPNT2:	DS	2	;バッチ変数の現在アドレス
BATFLG:	DS	1	;＝FFH（0以外）でバッチ･ファイル実行中
PARAF:	DS	1	;＝1（0以外）でバッチ変数アクセス中
;AUTNAM:	DB	'A:AUTOEXEC.BAT'	;自動実行ファイル名
;	DS	4
AUTNAM:	DB	'AUTOEXEC.BAT',00H	;自動実行ファイル名（カレント･ドライブより）
	DS	5


;===============
;バグ回避
;===============


;#GETL（1FD3H）のっとり
;1F2CH
BGETLX:
	PUSH	BC
	EX	AF,AF'
	PUSH	AF
	EX	AF,AF'
	CALL	BGETL
	EX	AF,AF'
	POP	AF
	EX	AF,AF'
	POP	BC
	RET


;#FLGET（2021H）のっとり
;1F38H
BFLGTX:
	EX	AF,AF'
	PUSH	AF
	EX	AF,AF'
	CALL	BFLGET
	EX	AF,AF'
	POP	AF
	EX	AF,AF'
	RET


;バッチ･ファイルなどからキー入力させないため（キーが押されるまで待ちます）
PAU1:	CALL	_GETKY
	OR	A
	JR	Z,PAU1
	RET


;=======================
;S-OSワーク･エリア
;=======================


	ORG	1F5BH
_MXLIN:	DB	25	;1F5BH 画面の行数。SORD M23版では25。
_WIDTH:	DB	80	;1F5CH 画面の桁数。SOR M23版では80。
_DSK:	DB	'A'	;1F5DH アクセスしようとするデバイス名
_FATPS:	DW	000EH	;1F5EH FATのあるレコード番号。デフォルトは000Eh (トラック0セクタ15)。
_DIRPS:	DW	0010H	;1F60H ディレクトリの始まるレコード番号。デフォルトは0010h(1Dではトラック1セクタ1)。
_FATBF:	DW	2E00H	;1F62H '2E00H～2EFFH FATリード用バッファ(256Byte)の先頭アドレス。デフォルトは2E00h。
_DTBUF:	DW	2F00H	;1F64H '2F00H～2FFFH ディスクリード用バッファ(256Byte)の先頭アドレス。デフォルトは2F00h。
_MXTRK:	DB	80	;1F66H 80トラック
_DIRNO:	DS	1	;1F67H _FCBで使用するワーク。何番目のファイルか。
_WKSIZ:	DW	0	;1F68H 256バイト単位 特殊ワークのサイズ。P6版では2800hがデフォルト。
_MEMAX:	DS	2	;1F6AH メモリの上限 	ユーザエリアの上限 (最終アドレス+1)。P6版ではD000hがデフォルト。
_STKAD:	DW	0100H	;1F6CH '通常のスタック スタックの初期値。P6版ではF900hがデフォルト。
_EXADR:	DS	2	;1F6EH ファイルの実行アドレス。
_DTADR:	DS	2	;1F70H ファイルの先頭アドレス。
_SIZE:	DS	2	;1F72H ファイルサイズ。
_IBFAD:	DW	fcb_buffer	;1F74H ファイルのインフォメーションブロックの先頭アドレス。同時にファイル属性のアドレスでもある。
_KBFAD:	DW	keyboard_buffer	;1F76H キー入力に使えるバッファのアドレス。LD DE,(#KBFAD) CALL #GETLなどとする。P6版では内部ワークに81バイトの領域を確保してある。
_XYADR:	DW	display_cursor_XY_not_use	;1F78H 'ダミー カーソル座標が格納してあるアドレス。
_PRCNT:	DW	number_of_character_after_CR	;1F7AH '未使用 改行後に表示した文字数を格納してあるアドレス。
_LPSW:	DB	0	;1F7CH 0以外なら、表示ルーチンを呼ぶとプリンタにも出力する。
_DVSW:	DB	0	;1F7CH 'S-OS 2400bps 'ダミー テープフォーマット。0:共通 1:各機種 3:QD。P6版では1がデフォルト。
_USR:	DW	_HOT;1F7EH '通常_HOTが入ります コールドスタート後にジャンプするアドレス。デフォルトは#HOT。
;NEXT	1F82H


;===============================
;S-OSジャンプ･テーブル
;===============================
	ORG	1F80H
_GETPC:			POP HL		;1F80H
_HL:			JP	(HL)	;1F81H

	DS	3	;1F82H 'MSXでは「MBIOS」
	DS	3	;1F85H
	DS	3	;1F88H
BPRNT:			JP	BPRNT0	;1F8BH

	ORG	1F8EH
_MON:			JP	MON		;1F8EH
_peek_entity:	JP	peek_entity	;1F91H
_PEEK:			JP	PEEK	;1F94H
_poke_entity:	JP	poke_entity	;1F97H
_POKE:			JP	POKE	;1F9AH
_FPRNT:			JP	FPRNT	;1F9DH
_FSAME:			JP	FSAME	;1FA0H
_FILE:			JP	FILE	;1FA3H
_RDD:			JP	RDD		;1FA6H
_FCB:			JP	GETFCB	;1FA9H 'MACE #RDI
_WRD:			JP	WRD		;1FACH
_WOPEN:			JP	WOPEN	;1FAFH 'MACE #WRI
_HLHEX:			JP	HLHEX	;1FB2H
_2HEX:			JP	AHEX	;1FB5H
_HEX:			JP	HEX		;1FB8H
_ASC:			JP	ASC		;1FBBH
_print_hex_4_digit:			JP	print_hex_4_digit	;1FBEH
_print_hex_2_digit:			JP	print_hex_2_digit	;1FC1H
_BELL:			JP	BELL	;1FC4H
_PAUSE:			JP	PAUSE	;1FC7H
_INKEY:			JP	INKEY	;1FCAH
_BRKEY:			JP	BRKEY	;1FCDH
_GETKY:			JP	GETKY	;1FD0H
_GETL:			JP	GETL	;1FD3H
_LPTOF:			JP	LPTOF	;1FD6H
_LPTON:			JP	LPTON	;1FD9H
_LPRNT:			JP	LPRNT	;1FDCH
_TAB:			JP	TAB		;1FDFH
_MPRNT:			JP	MPRNT	;1FE2H
_MSX:			JP	MSX		;1FE5H
_MSG:			JP	MSG		;1FE8H
_NL:			JP	NL		;1FEBH
_LTNL:			JP	LTNL	;1FEEH
_PRNTS:			JP	PRNTS	;1FF1H
_PRINT:			JP	PRINT	;1FF4H
_VER:			JP	VER		;1FF7H 
_HOT:			JP	sos_monitor	;1FFAH SOSのモニタ
_COLD:			JP	COLD	;1FFDH
;	SWORDで拡張された部分
_DRDSB:			JP	read_disk	;2000H
_DWTSB:			JP	write_disk	;2003H
_DIR:			JP	DIR		;2006H
_ROPEN:			JP	ROPEN	;2009H
_SET:			JP	SETP	;200CH
_RESET:			JP	RESET	;200FH
_NAME:			JP	NAME	;2012H
_KILL:			JP	KILL	;2015H
_CSR:			JP	CSR		;2018H
_SCRN:			JP	SCRN	;201BH
_LOC:			JP	LOC		;201EH
_FLGET:			JP	FLGET	;2021H
_RDVSW:			JP	RDVSW	;2024H
_SDVSW:			JP	SDVSW	;2027H
_INP:			JP	INP		;202AH
_OUT:			JP	OUTP	;202DH
_WIDCH:			JP	WIDCH	;2030H
_ERROR:			JP	RSERR	;2033H
; Oh! MZ 1986/2に載っているのはここまで

_BOOT:			JP	BOOT	;2036H
;NEXT	2039H
GTPRC:			JP	get_logical_column	;2039H
LINCH:			JP	LINCH0	;203CH
;NEXT	203FH

;	204BH～20FEHはバッチ変数バッファ

;	_ETRK（20FFH）はデバイス「E:」のクラスタ数

;	共通DOSモジュール組み込み（20FFH～28CCH）
	; INCLUDE	SWEMDOS

	ORG	20FFH
_ETRK:	DS	1	;RAMディスクのクラスタ数

;
; DOSモジュールの始まり
;
	ORG	2100H

;〈セーブ動作〉
;　「_FILE」「_WOPEN」「_WRD」の順で呼び出します。

;〈ロード動作〉
;　「_FILE」「_ROPEN」「_RDD」の順で呼び出します。


;===============
;モニタ処理
;===============


sos_monitor:
	LD	SP,(_STKAD)
	CALL	_LPTOF
	LD	A,'#'
	CALL	_PRINT
	LD	DE,(_KBFAD)
	CALL	_GETL
	CALL	sos_monitor_command_routine
	CALL	C,_ERROR
	JR	sos_monitor


;コマンド･ライン･ルーチン
;出力	CY＝1でエラー
sos_monitor_command_routine:
	LD	A,(DE)
	CP	'#'
	JR	Z,$+4
	OR	A
	RET
;	INC	DE
;	LD	A,(DE)
;	INC	DE
	CALL	sos_monitor_command_routine1
	OR	A
	RET	Z
	CP	'!'
	JP	Z,_BOOT	;ブート
	CP	'J'
	JP	Z,JUMP	;ジャンプ
	CP	'L'
	JP	Z,LOAD	;ロード
	CP	'K'
	JP	Z,MKILL	;デリート
	CP	'N'
	JP	Z,MNAME	;リネーム
	CP	'M'
	JP	Z,DOSMON	;モニタ
	CP	'W'
	JP	Z,MWIDTH	;表示桁
	CP	'S'
	JR	Z,CMDSB1	;プロテクト（ST），セーブ（S）
	CP	'D'
	JR	Z,CMDSB2	;デフォルト･デバイス（DV），ディレクトリ（D）
;	LD	A,13	;Syntax Error
;	SCF
;	RET
	JP	execute_expanded_command
	DS	1


;モニタ Sxコマンド処理
CMDSB1:
	LD	A,(DE)
	CALL	convert_lower_case_to_upper_case	;小文字→大文字変換
	INC	DE
	CP	'T'
	JP	Z,MSET	;モニタ STコマンド処理
	DEC	DE
	JP	SAVE	;モニタ Sコマンド処理


;モニタ Dxコマンド処理
CMDSB2:
	LD	A,(DE)
	CALL	convert_lower_case_to_upper_case	;小文字→大文字変換
	INC	DE
	CP	'V'
	JP	Z,DEVST	;モニタ DVコマンド処理
	DEC	DE
	JP	MDIR	;モニタ Dコマンド処理


;モニタ Jコマンド処理
JUMP:	CALL	SPCUT	;文字列の空白を読み飛ばします
	CALL	_HLHEX
	LD	A,13	;Syntax Error
	RET	C
;	6バイト
	; IF	0
	; EX	DE,HL
	; LD	HL,sos_monitor
	; EX	(SP),HL
	; EX	DE,HL
	; JP	(HL)
	; ENDIF
;	DE保存のための改定
	EX	(SP),HL	;スタック←ジャンプ先
	LD	HL,sos_monitor
	EX	(SP),HL	;スタック←sos_monitor，HL←ジャンプ先
	JP	(HL)
	DS	1


;モニタ Mコマンド処理
DOSMON:	JP	_MON


;モニタ Dコマンド処理
MDIR:
	CALL	SPCUT	;文字列の空白を読み飛ばします
	CALL	GETDEV	;文字列からデバイス名を得ます
	LD	(_DSK),A
	CALL	_DIR
	RET


;モニタ Sコマンド処理
SAVE:
	CALL	SPCUT	;文字列の空白を読み飛ばします
	LD	A,1
	CALL	_FILE
	LD	A,(DE)
	CP	':'
	JR	NZ,SNERR
	INC	DE

	CALL	_HLHEX
	JR	C,SNERR
	LD	(_DTADR),HL	;先頭アドレス
	LD	(_EXADR),HL	;仮実行アドレス
	INC	DE	;「:」をスキップ

	CALL	_HLHEX
	JR	C,SNERR
	PUSH	DE
	LD	DE,(_DTADR)
	OR	A
	SBC	HL,DE
	POP	DE
	JR	C,SNERR
	INC	HL
	LD	(_SIZE),HL	;サイズ
	INC	DE	;「:」などをスキップ

;	実行アドレスが指定されているときだけ
	CALL	_HLHEX
	JR	C,SAVE1
	LD	(_EXADR),HL	;実行アドレス

SAVE1:	CALL	_WOPEN
	RET	C	;エラー
	CALL	_WRD
	RET	C
	CALL	_NL
	LD	DE,OK
	CALL	_MSG
	JP	_NL
SNERR:	LD	A,13	;Syntax Error
	SCF
	RET


;モニタ Lコマンド処理
LOAD:
	LD	A,1
	CALL	_FILE
	LD	A,(DE)
	OR	A
	LD	(LDWORK+2),A	;ロード･アドレス存在フラグ
	JR	Z,LOAD1	;ロード･アドレスの指定なし
;	ロード･アドレスの指定あり
	INC	DE
	CALL	_HLHEX
	JR	C,SNERR	;ロード･アドレスが不正
	LD	(LDWORK),HL	;←ロード･アドレス

LOAD1:	CALL	_ROPEN
	RET	C	;エラー
	CALL	NZ,SKPRT	;テープのスキップしているファイル名を表示します
	JR	NZ,LOAD1

	CALL	_MPRNT
	DB	'Loading ',00H
	CALL	_FPRNT
	CALL	_NL

;	ロード･アドレスの設定
	LD	A,(LDWORK+2)
	OR	A
	JR	Z,LOAD3
	LD	HL,(LDWORK)
	LD	(_DTADR),HL

;	ロードします
LOAD3:	JP	_RDD

LDWORK:	DS	2	;ロード･アドレス
	DS	1	;ロード･アドレス･フラグ（＝0でロード･アドレスが無効）


;テープのスキップしているファイル名を表示します
;破壊	DE
SKPRT:
	PUSH	AF
	CALL	_MPRNT
	DB	'Found   ',00H
	CALL	_FPRNT
	CALL	_NL
	POP	AF
	RET


;モニタ Kコマンド処理
MKILL:
	CALL	SPCUT	;文字列の空白を読み飛ばします
	CALL	_FILE
	RET	C	;エラー
	CALL	_KILL
	RET


;モニタ STコマンド処理
MSET:
	CALL	SPCUT	;文字列の空白を読み飛ばします
	CALL	_FILE
	INC	DE
;	CALL	SPCUT	;文字列の空白を読み飛ばします
;	LD	A,(DE)
	CALL	MSET1	;小文字受け付けのため
	NOP
	CP	'P'
	JP	Z,_SET
	CP	'R'
	JP	Z,_RESET
;	パラメータが「P」でも「R」でもない
	LD	A,13	;Syntax Error
	SCF
	RET


;モニタ DVコマンド処理
DEVST:
	CALL	SPCUT	;文字列の空白を読み飛ばします
	LD	A,(DE)
	CALL	convert_lower_case_to_upper_case	;小文字→大文字変換
	CALL	_DVCHK	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	JR	NC,DEVST1
	LD	A,3	;Bad File Descripter
	RET
DEVST1:	LD	(_DSK),A
	JP	_SDVSW


;モニタ Nコマンド処理
MNAME:
	CALL	SPCUT	;文字列の空白を読み飛ばします
	CALL	_FILE
	LD	A,(DE)
	INC	DE
	CP	':'
	JP	Z,_NAME
	LD	A,13	;Syntax Error
	SCF
	RET


;モニタ Wコマンド処理
;注：80桁モード以外なら40桁モードにしています。
MWIDTH:	LD	A,(_WIDTH)
	CP	80
	JR	NZ,MWDTH1
	LD	A,40
	JP	_WIDCH
MWDTH1:	LD	A,80
	JP	_WIDCH


;文字列の空白を読み飛ばします
;入力	DE←文字列の先頭アドレス
;出力	DE←カウント･アップ
;破壊	AF，DE
	INC	DE
SPCUT:
	LD	A,(DE)
	CP	' '
	JR	Z,SPCUT-1
	RET


;=======================================
;拡張されたS-OSファンクション本体
;=======================================


;文字列からデバイス名を得ます
;入力	DE←文字列のアドレス
;出力	Acc←デバイス名、DE←カウント･アップ
;破壊	AF，DE
;注：
;　小文字は大文字に変換されます。
;　デバイス名が省略された場合、デフォルト･デバイスが採用されます。
GETDEV:
	CALL	SPCUT	;文字列の空白を読み飛ばします
;	INC	DE
;	LD	A,(DE)	;Acc←2文字目
;	DEC	DE
	CALL	GDVPAT	;GETDEVのバグ回避
	CP	':'
	JR	Z,$+5
	JP	RDVSW	;＝#RDVSW（2024H）

	LD	A,(DE)
	INC	DE
	INC	DE


; ;小文字→大文字変換
; ;入力	Acc←アスキー･コード
; ;出力	Acc←変換されたアスキー･コード
; ;破壊	AF
; convert_lower_case_to_upper_case:
; 	CP	'a'
; 	RET	C
; 	CP	'z'+1
; 	RET	NC
; 	AND	11011111B	;b5リセット
; 	RET


;#WOPEN（1FAFH）の本体
;注：
;　仕様と違いAF'が破壊されます。
;　テープではインフォメーション･ファイルを書き込み、
;ディスクでは空きエリアをチェックします。
;　正常終了CY＝0（Acc←0）。
WOPEN:
	CALL	CLOSE	;[_OPNFG]←0
	LD	A,(_DSK)
	CALL	check_device_name	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	RET	C	;エラー
	JP	Z,_WRI	;カセットにインフォメーション･ファイルをセーブします

;	テープ以外
	CALL	check_FD_device_name	;デバイス名がFDかチェックします
	JR	NC,WOPEN1
	RET		;エラー（テープ，ディスク以外）

WOPEN1:	CALL	FATRED	;FATを読みます
	RET	C	;エラー
	CALL	FCBSCH	;ファイルを検索します（属性は無視）
	JR	NZ,WOPEN2

;	同じファイル名のファイルがあった
	LD	A,(HL)
	CALL	check_write_protect	;ファイルのライト･プロテクトのチェック
	RET	C	;エラー
	CALL	FMCHK	;属性をチェックします
	RET	C	;エラー
;
	PUSH	HL
	LD	BC,30
	ADD	HL,BC
	LD	A,(HL)	;Acc←ファイルの開始クラスタ
	POP	HL
	CALL	ERAFAT	;FATバッファから指定のクラスタ･チェインをカットします
	RET	C	;エラー
	JR	WOPEN3

;	同じファイル名のファイルがなかった
WOPEN2:	CALL	FRESCH	;ディスクに空きエリアがあるかチェックします
	LD	A,9	;Bad Record
	RET	C	;エラー

WOPEN3:	LD	(DEBUF),DE	;アクセスするレコード番号の一時保存場所
	LD	(HLBUF),HL	;参照FCBのアドレスの一時保存場所
	CALL	_PARCS	;S-OSのカセットのアドレス情報を、機種依存のワークに転送します
	CALL	OPEN	;[_OPNFG]←1
	XOR	A	;CY←0，Acc←0
	RET


;#ROPEN（2009H）の本体
;注：
;　仕様と違いAF'が破壊されます。
;　テープではインフォメーション･ファイルの読み込み、
;ディスクではファイルの存在のチェック。
;　正常終了CY＝0（Acc←0）。
ROPEN:
	CALL	CLOSE	;[_OPNFG]←0
	LD	A,(_DSK)
	CALL	check_device_name	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	RET	C	;エラー
	JP	Z,_TROPN	;テープのリード･オープン

;	テープ以外
	CALL	check_FD_device_name	;デバイス名がFDかチェックします
	JR	NC,ROPEN1
	RET		;エラー（テープ，ディスク以外）

;	ディスクの場合
ROPEN1:	CALL	FCBSCH	;ファイルを検索します（属性は無視）
	RET	C	;エラー
	LD	A,8	;File not Found
	SCF
	RET	NZ	;エラー（ファイルが見つからなかった）

;	一致したFCBを、FCBバッファに転送します
	PUSH	HL
	LD	DE,(_IBFAD)
	LD	BC,32
	LDIR
	POP	HL

;	属性を比較します
	LD	A,(HL)
	CALL	FMCHK	;属性をチェックします
	RET	C	;エラー

;	アドレス情報の転送など
ROPEN2:	CALL	_PARSC	;機種依存のカセットのアドレス情報を、S-OSのワークに転送します
	CALL	OPEN	;[_OPNFG]←1
	XOR	A	;CY←0，Acc←0
	RET


;#WRD（1FACH）の本体
;注：
;　仕様と違いAF'が破壊されます。
;　正常終了CY＝0（Acc←0）。
WRD:
	LD	A,(_DSK)
	CALL	check_device_name	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	RET	C	;エラー
	JP	Z,_TWRD	;カセットにデータ･ファイルをセーブします

;	テープ以外
	LD	A,(_OPNFG)
	OR	A
	JR	NZ,WRD1
	SCF
	LD	A,12	;File not Open
	RET		;オープンされてなかった
WRD1:	CALL	CLOSE	;[_OPNFG]←0
	LD	A,(_DSK)
	CALL	check_FD_device_name	;デバイス名がFDかチェックします
	RET	C	;エラー（テープ，ディスク以外）

;	ディスクの場合
	CALL	DSAVE	;ディスクにファイルを書き込みます
	RET


;#RDD（1FA6H）の本体
;注：
;　仕様と違いAF'が破壊されます。
;　正常終了CY＝0（Acc←0）。
;　[_DIRNO]、[RETPOI]をクリアします。
RDD:
	LD	A,(_DSK)
	CALL	check_device_name	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	RET	C	;エラー
	JP	Z,_TRDD	;カセットのデータ･ファイルをロードします

;	テープ以外
	XOR	A
	LD	(_DIRNO),A	;クローズ処理
	LD	(RETPOI),A	;以前正しいFCBがロードされたかのフラグ
	LD	A,(_OPNFG)
	OR	A
	JR	NZ,RDD1
	SCF
	LD	A,12	;File not Open
	RET		;オープンされてなかった
RDD1:	CALL	CLOSE	;[_OPNFG]←0
	LD	A,(_DSK)
	CALL	check_FD_device_name	;デバイス名がFDかチェックします
	RET	C	;エラー（テープ，ディスク以外）

;	ディスクの場合
	CALL	FATRED	;FATを読みます
	RET	C	;エラー
	CALL	DLOAD	;ディスクからファイルを読み込みます
	RET


;#FCB（1FA9H）の本体
;〈解説〉
;　ESCキーが押されていれば、CY＝1（Acc←8）で戻ります
;（[_DIRNO]はクリア）。
;　RETキーが押されていれば、[_DIRNO]をカウント･ダウン
;（以前正しくロードされたFCB）。
;注：
;　仕様と違いAF'が破壊されます。
;　ファイルのオープンと同等。
;　正常終了CY＝0（Acc←0）。
GETFCB:
	CALL	CLOSE	;[_OPNFG]←0
	LD	A,(_DSK)
	CALL	check_device_name	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	RET	C	;エラー
	JR	NZ,GETFC1	;テープ以外

;	テープの場合
	CALL	TRDVSW	;#DVSWからテープのデバイス名を求めます
	LD	(_DSK),A
	JP	_RDI	;カセットのインフォメーション･ファイルをロードします

;	テープ以外
GETFC1:	CALL	_GETKY
	CP	1BH	;ESC
	JP	Z,DEND	;[_DIRNO]と[RETPOI]をクリアしてエラーNo.8でリターン
	CP	0DH	;RET
	JR	NZ,GETFC2

;	RETキーが押された場合
	LD	A,(RETPOI)	;以前正しいFCBがロードされたかのフラグ
	OR	A
	JR	NZ,DECPOI	;[_DIRNO]をカウント･ダウンして、[RETPOI]をクリアしてエラーNo.8でリターン

;	[_DIRNO]に対応するレコードを読み込みます
GETFC2:	LD	A,(_DIRNO)
	LD	C,A	;C←[_DIRNO]
	LD	B,3
SFR41:	SRL	A	;Acc←[_DIRNO]÷8
	DJNZ	SFR41
	LD	HL,(_DIRPS)
	LD	D,0
	LD	E,A	;DE←[_DIRNO]÷8
	ADD	HL,DE
	EX	DE,HL	;DE←[_DIRNO]に対応するFCBが存在するディスクのレコード番号
	LD	HL,(_DTBUF)
	LD	A,1
	CALL	read_disk	;=#DRDSB（2000H）
	JR	C,ERRRET	;[_DIRNO]と[RETPOI]をクリア（AF保存）

;	有効なFCBかチェック
	LD	A,C	;Acc←[_DIRNO]
	AND	00000111B
	LD	B,5
SFL51:	ADD	A,A	;Acc←[_DIRNO]の下位3ビット×32
	DJNZ	SFL51
	LD	HL,(_DTBUF)
	ADD	A,L
	LD	L,A
	JR	NC,$+3
	INC	H	;HL←[_DTBUF]＋[_DIRNO]の下位3ビット×32
	LD	A,(HL)	;Acc←[_DIRNO]に対応するFCBの属性
	OR	A
	JR	Z,NEXT1	;未使用FCB
	CP	0FFH	;最後のFCBを通過したか
	JR	Z,DEND	;[_DIRNO]と[RETPOI]をクリアしてエラーNo.8でリターン

	LD	DE,(_IBFAD)
	LD	BC,32
	LDIR
	CALL	INCPOI	;[_DIRNO]をカウント･アップして、[RETPOI]に[_DIRNO]をコピーします
	JP	ROPEN2	;アドレス情報の転送など

;	未使用FCBだった
NEXT1:	CALL	INCPOI	;[_DIRNO]をカウント･アップして、[RETPOI]に[_DIRNO]をコピーします
	JR	NC,GETFC1
	RET


;[_DIRNO]をカウント･アップして、[RETPOI]に[_DIRNO]をコピーします
;入力	なし
;出力	CY＝1なら、[_MXTRK]に達した、
;	[_DIRNO]と[RETPOI]をクリアしてエラーNo.8でリターン
;破壊	AF，HL
INCPOI:
	LD	HL,_DIRNO
	INC	(HL)
	LD	A,(HL)
	LD	HL,_MXTRK
	CP	(HL)
	JR	Z,DEND	;[_DIRNO]と[RETPOI]をクリアしてエラーNo.8でリターン
	LD	(RETPOI),A
	OR	A
	RET


;[_DIRNO]と[RETPOI]をクリア（AF保存）
;入力	なし
;出力	[_DIRNO]←0、[RETPOI]←0
;破壊	なし
ERRRET:
	PUSH	AF
	CALL	DEND	;[_DIRNO]と[RETPOI]をクリアしてエラーNo.8でリターン
	POP	AF
	RET


;[_DIRNO]をカウント･ダウンして、[RETPOI]をクリアしてエラーNo.8でリターン
;入力	なし
;出力	[_DIRNO]をカウント･ダウン、[RETPOI]←0
;破壊	AF，HL
DECPOI:
	LD	HL,_DIRNO
	LD	A,(HL)
	OR	A
	JR	Z,$+3
	DEC	(HL)
	XOR	A
	JR	DEND1


;[_DIRNO]と[RETPOI]をクリアしてエラーNo.8でリターン
;入力	なし
;出力	[_DIRNO]←0、[RETPOI]←0
;破壊	AF
DEND:
	XOR	A
	LD	(_DIRNO),A
DEND1:	LD	(RETPOI),A
	LD	A,8	;File not Found
	SCF
	RET

;注：
;　00H以外で、以前に正しいFCBがロードされたことをあらわします。
;　#RDDを実行すると、クリアされます。
RETPOI:	DB	0	;以前正しいFCBがロードされたかのフラグ


;#DIR（2006H）の本体
;注：仕様と違いAF'が破壊されます。
DIR:
	LD	A,(_DSK)
	CALL	check_device_name	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	RET	C	;正しくなかった
	JP	Z,_TDIR	;テープのディレクトリを表示します

;	テープ以外
	CALL	check_FD_device_name	;デバイス名がFDかチェックします
	RET	C	;エラー（テープ，ディスク以外）

;	ディスク
	CALL	FATRED	;FATを読みます
	RET	C	;エラー
	LD	A,'$'
	CALL	_PRINT
	CALL	FRECLU	;空きクラスタ数を得ます
	CALL	_print_hex_2_digit
	LD	DE,cluster_free_message	;「 Clusters Free」
	CALL	_MSX
	LD	B,16
	LD	DE,(_DIRPS)

DIRL:	LD	HL,(_DTBUF)
	LD	A,1
	CALL	read_disk	;=#DRDSB（2000H）
	RET	C	;エラー
	CALL	DIRPRT	;ディレクトリを1セクタ分表示します
	RET	Z
	INC	DE
	DJNZ	DIRL

	XOR	A
	RET


;ディレクトリを1セクタ分表示します
;入力	HL←ディレクトリのアドレス（256バイト)
;出力	ZF＝1ならブレイクされた
;破壊	AF，HL
DIRPRT:
	PUSH	BC
	PUSH	DE
	LD	B,8

DIRPL:	LD	A,(HL)
	OR	A	;＝00Hで未使用
	JR	Z,DIRN
	CP	0FFH	;＝FFHで未使用領域
	JR	Z,DIRPE
	CALL	PFNAM	;ファイル情報を表示します
	CALL	_LTNL
	CALL	_PAUSE
	DW	DIRPE
DIRN:	LD	DE,20H
	ADD	HL,DE
	DJNZ	DIRPL

	DB	3EH
DIRPE:	XOR	A
	POP	DE
	POP	BC
	OR	A
	RET


;#KILL（2015H）の本体
;注：仕様と違いAF'が破壊されます。
KILL:
	LD	A,(_DSK)
	CALL	ALCHK	;デバイス名がFDかチェックします
	RET	C
	CALL	check_FD_device_name	;デバイス名がFDかチェックします
	RET	C

;	FATを読みます
	CALL	FATRED	;FATを読みます
	RET	C

;	ファイル名を検索
	CALL	FCBSCH	;ファイルを検索します（属性は無視）
	RET	C
	LD	A,8	;File not Found
	SCF
	RET	NZ	;ファイルが見つからない
	LD	A,(HL)
	CALL	check_write_protect	;ファイルのライト･プロテクトのチェック
	RET	C	;エラー

;	ディレクトリ･バッファとFATバッファを書き換えます
	LD	(HL),0	;未使用をあらわします
	PUSH	HL
	LD	BC,30
	ADD	HL,BC
	LD	A,(HL)	;Acc←ファイルの開始クラスタ
	POP	HL
	CALL	ERAFAT	;FATバッファから指定のクラスタ･チェインをカットします
	RET	C	;エラー

;	ディスクを書き換えます（先にディレクトリを）
	LD	HL,(_DTBUF)
	LD	A,1
	CALL	write_disk	;=#DWRSB（2003H）の本体
	CALL	NC,FATWRT	;FATを書き込みます
	RET


;#NAME（2012H）の本体
;注：仕様と違いAF'が破壊されます。
NAME:
	LD	A,(_DSK)
	CALL	ALCHK	;デバイス名がFDかチェックします
	RET	C
	CALL	check_FD_device_name	;デバイス名がFDかチェックします
	RET	C

;	変更前のファイル名を検索
	PUSH	DE
	CALL	FCBSCH	;ファイルを検索します（属性は無視）
	LD	(DEBUF),DE	;アクセスするレコード番号の一時保存場所
	LD	(HLBUF),HL	;参照FCBのアドレスの一時保存場所
	POP	DE
	RET	C	;エラー
	LD	A,8	;File not Found
	SCF
	RET	NZ	;ファイルが見つからない
	LD	A,(HL)
	CALL	check_write_protect	;ファイルのライト･プロテクトのチェック
	RET	C	;エラー

;	変更後のファイル名を検索
	LD	A,(_DSK)
	PUSH	AF
	CALL	_FILE
	POP	AF
	LD	(_DSK),A
	CALL	FCBSCH	;ファイルを検索します（属性は無視）
	RET	C	;エラー
	LD	A,10	;File Already Exists
	SCF
	RET	Z	;変更しようとしたファイル名が既に存在した

;	ディレクトリを再読み込み（変更後のファイル名検索で、バッファ破壊のため）
	LD	DE,(DEBUF)	;アクセスするレコード番号の一時保存場所
	LD	HL,(_DTBUF)
	LD	A,1
	CALL	read_disk	;=#DRDSB（2000H）
	RET	C	;エラー

;	ディレクトリ･バッファのファイル名を変更します
	LD	HL,(_IBFAD)
	INC	HL
	LD	DE,(HLBUF)	;参照FCBのアドレスの一時保存場所
	INC	DE
	LD	BC,17
	LDIR

	LD	DE,(DEBUF)	;アクセスするレコード番号の一時保存場所
	LD	HL,(_DTBUF)
	LD	A,1
	CALL	write_disk	;=#DWRSB（2003H）の本体
	RET


;#SET（200CH）の本体
;注：仕様と違いAF'が破壊されます。
SETP:
	LD	A,(_DSK)
	CALL	ALCHK	;デバイス名がFDかチェックします
	RET	C
	CALL	check_FD_device_name	;デバイス名がFDかチェックします
	RET	C

;	ファイル名を検索
	CALL	FCBSCH	;ファイルを検索します（属性は無視）
	RET	C
	LD	A,8	;File not Found
	SCF
	RET	NZ	;ファイルが見つからない

;	ディレクトリ･バッファを書き換えます
	SET	6,(HL)	;属性b6←1

;	ディレクトリを書き換えます
	LD	HL,(_DTBUF)
	LD	A,1
	CALL	write_disk	;=#DWRSB（2003H）の本体
	RET


;#RESET（200FH）の本体
;注：仕様と違いAF'が破壊されます。
RESET:
	LD	A,(_DSK)
	CALL	ALCHK	;デバイス名がFDかチェックします
	RET	C
	CALL	check_FD_device_name	;デバイス名がFDかチェックします
	RET	C

;	ファイル名を検索
	CALL	FCBSCH	;ファイルを検索します（属性は無視）
	RET	C
	LD	A,8	;File not Found
	SCF
	RET	NZ	;ファイルが見つからない

;	ディレクトリ･バッファを書き換えます
	RES	6,(HL)	;属性b6←0

;	ディレクトリを書き換えます
	LD	HL,(_DTBUF)
	LD	A,1
	CALL	write_disk	;=#DWRSB（2003H）の本体
	RET


;#DRDSB（2000H）の本体
;入力	HL←読み込みアドレス、DE←レコード番号、Acc←レコード数
;出力	CY＝0(Acc←0)なら成功、
;	CY＝1（Acc←エラー･コード）なら失敗
;破壊	AF，AF'
read_disk:
	EX	AF,AF'	;AF'
	LD	A,(_DSK)
	CALL	ALCHK	;デバイス名がFDかチェックします
	RET	C
	CALL	check_FD_device_name	;デバイス名がFDかチェックします
	RET	C
	SUB	'A'
	LD	(disk_unit_number),A	;ディスクのユニット番号（0～）
	EX	AF,AF'
	CALL	DREAD	;ディスク読み込み
	RET


;#DWRSB（2003H）の本体
;入力	HL←書き込みアドレス、DE←レコード番号、Acc←レコード数
;出力	CY＝0（Acc←0）なら成功、
;	CY＝1（Acc←エラー･コード）なら失敗
;破壊	AF，AF'
write_disk:
	EX	AF,AF'	;AF'
	LD	A,(_DSK)
	CALL	ALCHK	;デバイス名がFDかチェックします
	RET	C
	CALL	check_FD_device_name	;デバイス名がFDかチェックします
	RET	C
	SUB	'A'
	LD	(disk_unit_number),A	;ディスクのユニット番号（0～）
	EX	AF,AF'
	CALL	DWRITE	;ディスク書き込み
	RET


;[_OPNFG]←1
;入力	なし
;出力	[_OPNFG]←1
;破壊	なし
OPEN:
	PUSH	AF
	LD	A,1
	JR	CLOSE1


;[_OPNFG]←0
;入力	なし
;出力	[_OPNFG]←0
;破壊	なし
CLOSE:
	PUSH	AF
	XOR	A
CLOSE1:	LD	(_OPNFG),A
	POP	AF
	RET


;ファイルのライト･プロテクトのチェック
;入力	Acc←属性（b6）
;出力	CY＝1ならライト･プロテクト（Acc←4）
;破壊	F，（AF）
check_write_protect:
	OR	A	;CY←0
	BIT	6,A
	RET	Z
	LD	A,4	;Write Protected
	SCF
	RET


;属性をチェックします
;入力	Acc←属性（b7b2b1b0）
;	[_FTYPE]参照
;出力	CY＝1（Acc←6）なら一致しない
;破壊	AF
FMCHK:
	PUSH	HL
	AND	10000111B
	LD	HL,_FTYPE
	CP	(HL)
	POP	HL
	RET	Z
	LD	A,6	;Bad File Mode
	SCF
	RET


;デバイス名がFDかチェックします
;入力	Acc←デバイス名
;出力	CY＝1ならFDでない
;破壊	F（AF）
check_FD_device_name:
	CP	'A'
	JR	C,DSKCH1
;	CP	'D'+1
	CP	'E'+1	;RAMディスク対応のための改定
	CCF
	RET	NC
DSKCH1:	LD	A,11	;Reserved Feature
	RET


;デバイス名がFDかチェックします
;入力	Acc←デバイス名
;出力	CY＝1ならFDでない
;破壊	F（AF）
;注：デバイス名が不正なら、Acc←エラー･コード。
ALCHK:
	CALL	check_device_name	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	RET	C
	CALL	check_tape_device_name	;デバイス名がテープ（QD）かチェックします
	JR	NZ,$+6
	LD	A,3	;Bad File Descripter
	SCF
	RET
	CALL	check_FD_device_name	;デバイス名がFDかチェックします
	RET


;#RDVSW（2024H）の本体
RDVSW:
	LD	A,(_DFDV)	;デフォルト･デバイス
	CALL	check_tape_device_name	;デバイス名がテープ（QD）かチェックします
	RET	NZ	;テープ以外ならそのままリターン


;#DVSWからテープのデバイス名を求めます
;入力	なし
;出力	Acc←テープのデバイス名
;破壊	AF
TRDVSW:
	LD	A,(_DVSW)
	OR	A
	JR	NZ,$+4
	LD	A,'T'	;S-OS 2400bps
	CP	1
	JR	NZ,$+4
	LD	A,'S'	;システム依存
	CP	3
	JR	NZ,$+4
	LD	A,'Q'	;QD
	RET


;#SDVSW（25C9H）の本体
SDVSW:
	PUSH	AF
	LD	(_DFDV),A	;デフォルト･デバイス
	CP	'T'	;0
	JR	NZ,$+3
	XOR	A
	CP	'S'	;1
	JR	NZ,$+4
	LD	A,1
	CP	'Q'	;3
	JR	NZ,$+4
	LD	A,3
	LD	(_DVSW),A
	POP	AF
	RET


;ディスクからファイルを読み込みます
;入力	[_IBFAD]～,[_FATBF]～etc参照
;出力	CY＝0（Acc←0）なら成功、
;	CY＝1（Acc←エラー･コード）なら失敗
;破壊	AF，HL，DE，BC，AF'
DLOAD:
	LD	HL,(_IBFAD)
	LD	BC,30
	ADD	HL,BC
	LD	A,(HL)	;Acc←ファイルの開始クラスタ
	LD	(NXCLST),A	;アクセスするクラスタの一時保存場所
	LD	BC,(_SIZE)
	LD	HL,(_DTADR)

;	ロード･ループ
DLOAD1:	PUSH	HL
	LD	A,(NXCLST)	;アクセスするクラスタの一時保存場所
	LD	HL,(_FATBF)
	LD	E,A
	LD	D,0	;DE←アクセスするクラスタ番号
	ADD	HL,DE	;HL←FATバッファのアクセスするクラスタの位置
	LD	A,(HL)	;次のクラスタへのチェイン情報
	LD	(NXCLST),A	;アクセスするクラスタの一時保存場所
	EX	DE,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	EX	DE,HL	;DE←アクセスするレコード位置（空きクラスタ番号×16）
	POP	HL	;HL←[_DTADR]
	OR	A
	JR	Z,DLOAD2	;FATが不正
	CP	80H
	JR	NC,DLOAD3	;最後のクラスタ
	LD	A,16	;4Kバイト読み込みます
	CALL	read_disk	;=#DRDSB（2000H）
	RET	C	;エラー
	LD	DE,1000H
	ADD	HL,DE	;メモリのカウント･アップ
	PUSH	HL
	LD	L,C
	LD	H,B
	OR	A
	SBC	HL,DE
	LD	C,L
	LD	B,H	;サイズのカウント･ダウン
	POP	HL	;HL←次のメモリ
	JR	NC,DLOAD1

;	エラー
DLOAD2:	LD	A,7	;Bad Allocation Table
	SCF
	RET

;	最後のクラスタ
DLOAD3:	SUB	7FH	;Acc←読み込みセクタ数
	CP	16+1
	JR	NC,DLOAD2	;FATが不正
	DEC	A	;Acc←読み込みセクタ数－1（0～15）
	DEC	BC	;B←読み込む最後のセクタ－1（0～15）
	CP	B
	JR	NZ,DLOAD2	;FATが不正
	LD	B,0
	INC	BC	;BC←最後のセクタのバイト数
	OR	A
	JR	Z,DLOAD4	;最後のクラスタは、セクタを1つだけ使用

;	最後のセクタ以外を読み込みます
	PUSH	AF
	CALL	read_disk	;=#DRDSB（2000H）
	JR	C,DLOAD5
	POP	AF	;Acc←読み込みセクタ数－1（0～15）

DLOAD4:	PUSH	DE
	LD	E,0
	LD	D,A	;DE←次に読み込むアドレスの変移
	ADD	HL,DE	;メモリのカウント･アップ
	EX	(SP),HL	;HL←最後のクラスタの先頭レコード番号，スタック←最後に読み込むメモリのアドレス
	LD	E,A
	LD	D,0	;DE←次に読み込むレコードの変移
	ADD	HL,DE

;	最後のセクタ以外を読み込みます
	EX	DE,HL	;DE←最後に読み込むレコード番号
	LD	HL,(_DTBUF)
	LD	A,1
	CALL	read_disk	;=#DRDSB（2000H）
DLOAD5:	POP	DE	;DE←最後に読み込むメモリのアドレス
	RET	C

;	[_DTBUF]～から最後のセクタの内容を正しいメモリに転送します
	LDIR
	XOR	A	;Acc←0
	RET


;ディスクにファイルを書き込みます
;入力	[DEBUF]、[HLBUF]、[_FATBF]～etc参照
;出力	CY＝0（Acc←0）なら成功、
;	CY＝1（Acc←エラー･コード）なら失敗
;破壊	AF，HL，DE，BC，AF'
DSAVE:
	LD	DE,(DEBUF)	;アクセスするレコード番号の一時保存場所
	LD	HL,(HLBUF)	;参照FCBのアドレスの一時保存場所
	LD	BC,(_SIZE)
	PUSH	BC
	DEC	BC
	SRL	B
	SRL	B
	SRL	B
	SRL	B
	INC	B	;B←占有クラスタ数
	CALL	FRECLU	;空きクラスタ数を得ます
	CP	B
	POP	BC	;BC←[_SIZE]
	LD	A,9	;Device Full
	RET	C	;空き領域が足りない

;	タイム･スタンプとクラスタ値をクリア
	LD	HL,(_IBFAD)
	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	DE,24
	ADD	HL,DE
	LD	E,L
	LD	D,H
	INC	DE
	LD	(HL),0
	LD	BC,7
	LDIR
	POP	BC	;BC←[_SIZE]
	POP	DE	;DE←[DEBUF]
	POP	HL	;HL←[_IBFAD]

;	FCBのクラスタ値の設定
	LD	A,30
	ADD	A,L
	LD	L,A
	JR	NC,$+3
	INC	H	;HL←[_IBFAD]＋30
	CALL	FCGET	;空きクラスタを得ます
	LD	(HL),A	;FCBのクラスタ値←空きクラスタ番号
	LD	HL,(_DTADR)

;	セーブ･ループ
DSAVE1:	PUSH	HL
	LD	HL,(_FATBF)
	LD	E,A
	LD	D,0	;DE←空きクラスタ番号
	ADD	HL,DE	;HL←FATバッファの空きクラスタの位置
	EX	DE,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	EX	DE,HL	;DE←空きレコード位置（空きクラスタ番号×16）
	DEC	BC
	LD	A,B
	INC	BC
	CP	16
	JR	C,DSAVE3	;最後のクラスタ
	LD	(HL),80H	;FCGETルーチンでスキップさせるため
	CALL	FCGET	;空きクラスタを得ます
	LD	(HL),A	;次のクラスタへのチェイン情報
	POP	HL	;HL←[_DTADR]
	PUSH	AF
	LD	A,16	;4Kバイト書き込みます
	CALL	write_disk	;=#DWRSB（2003H）の本体
	JR	C,DSAVE2	;エラー
	LD	DE,1000H
	ADD	HL,DE	;メモリのカウント･アップ
	PUSH	HL
	LD	L,C
	LD	H,B
	OR	A
	SBC	HL,DE
	LD	C,L
	LD	B,H	;サイズのカウント･ダウン
	POP	HL	;HL←次のメモリ
	POP	AF	;Acc←次のクラスタ
	JR	DSAVE1

;	エラー
DSAVE2:	POP	HL	;スタック位置調整のため
	RET

;	最後のクラスタ
DSAVE3:	INC	A	;Acc←書き込みセクタ数
	PUSH	AF
	ADD	A,7FH	;Acc←80H～8FH
	LD	(HL),A	;チェインの終わりを示す
	POP	AF	;Acc←書き込みセクタ数
	POP	HL	;HL←メモリのアドレス
	CALL	write_disk	;=#DWRSB（2003H）の本体
	RET	C	;エラー

;	FATの更新
	CALL	FATWRT	;FATを書き込みます
	RET	C	;エラー

;	ディレクトリの更新
	LD	HL,(_IBFAD)
	LD	DE,(HLBUF)	;参照FCBのアドレスの一時保存場所
;	INC	DE	;無意味？
	LD	BC,32
	LDIR
	LD	HL,(_DTBUF)
	LD	DE,(DEBUF)	;アクセスするレコード番号の一時保存場所
	LD	A,1
	CALL	write_disk	;=#DWRSB（2003H）の本体
	RET	C
	XOR	A	;Acc←0
	RET


;FATを読みます
;入力	[_FATPS]、[_FATBF]参照
;出力	CY＝0（Acc←0）なら成功、
;	CY＝1（Acc←エラー･コード）なら失敗
;破壊	AF，AF'
FATRED:
	PUSH	DE
	PUSH	HL
	LD	DE,(_FATPS)
	LD	HL,(_FATBF)
	LD	A,1
	CALL	read_disk	;=#DRDSB（2000H）
	POP	HL
	POP	DE
	RET


;FATを書き込みます
;入力	[_FATPS]、[_FATBF]～参照
;出力	CY＝0（Acc←0）なら成功、
;	CY＝1（Acc←エラー･コード）なら失敗
;破壊	AF，AF'
FATWRT:
	PUSH	DE
	PUSH	HL
	LD	DE,(_FATPS)
	LD	HL,(_FATBF)
	LD	A,1
	CALL	write_disk	;=#DWRSB（2003H）の本体
	POP	HL
	POP	DE
	RET


;空きクラスタ数を得ます
;入力	[_FATBF]～参照
;出力	Acc←空きクラスタ数
;破壊	AF
FRECLU:
	PUSH	BC
	PUSH	HL
	LD	B,80H
	LD	C,0
	LD	HL,(_FATBF)

FRECL1:	LD	A,(HL)
	OR	A	;00Hが未使用
	JR	NZ,FRECL2
	INC	C
FRECL2:	INC	HL
	DJNZ	FRECL1

	LD	A,C
	POP	HL
	POP	BC
	RET


;空きクラスタを得ます
;入力	なし
;出力	Acc←空きクラスタ番号
;	CY＝1なら空きクラスタがない
;破壊	AF
FCGET:
	PUSH	BC
	PUSH	HL
	LD	B,80H
	LD	HL,(_FATBF)

FCGET2:	LD	A,(HL)
	OR	A	;00Hは未使用クラスタ
	JR	Z,FCGET3
	INC	HL
	DJNZ	FCGET2

	SCF
	JR	FCGET4
FCGET3:	LD	A,80H
	SUB	B	;Acc←空きクラスタ番号
	OR	A
FCGET4:	POP	HL
	POP	BC
	RET


;FATバッファから指定のクラスタ･チェインをカットします
;入力	Acc←ファイルの開始クラスタ
;出力	CY＝0（Acc←0）なら正常終了、CY＝1（Acc←7）ならエラー
;破壊	AF，DE
ERAFAT:
	PUSH	DE
	PUSH	HL
	LD	DE,(_FATBF)

ERAFA1:	LD	L,A
	LD	H,0	;HL←ファイルの開始クラスタ
	ADD	HL,DE	;HL←対応するFATバッファのアドレス
	LD	A,(HL)	;Acc←チェインしているクラスタ番号
	LD	(HL),0
	CP	80H
	JR	C,ERAFA1	;チェインしていた

;	チェイン終了
	POP	HL
	POP	DE
	CP	90H
	JR	NC,ERAFA2	;90H～のデータがあった
;	正常終了
	XOR	A
	RET

;	存在するはずのない数値があった
ERAFA2:	LD	A,7	;Bad Allocation Table
	SCF
	RET


;ファイルを検索します（属性は無視）
;入力	[_IBFAD]参照
;出力	ZF＝1なら一致した
;	HL←一致したFCBのあるアドレス、DE←一致したFCBのあるレコード番号
;	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，AF'
FCBSCH:
	PUSH	BC
	LD	C,16
	LD	DE,(_DIRPS)

FCBSC1:	LD	HL,(_DTBUF)
	LD	A,1
	CALL	read_disk	;=#DRDSB（2000H）
	JR	C,FCBSC6	;エラー
	LD	B,8

FCBSC2:	LD	A,(HL)
	CP	0FFH
	JR	Z,FCBSC4
	OR	A
	JR	Z,FCBSC3
	PUSH	DE
	LD	DE,(_IBFAD)
;	CALL	FCOMP	;ファイル名を比較します
	CALL	compare_file_name	;ファイル名を比較します
	POP	DE
	JR	Z,FCBSC5	;一致した
FCBSC3:	PUSH	DE
	LD	DE,32
	ADD	HL,DE
	POP	DE
	DJNZ	FCBSC2

	INC	DE
	DEC	C
	JR	NZ,FCBSC1

FCBSC4:	DB	3EH	;「LD A,」
FCBSC5:	XOR	A
	OR	A
FCBSC6:	POP	BC
	RET


;ディスクに空きエリアがあるかチェックします
;入力	なし
;出力	HL←一空きFCBのあるアドレス、DE←空きFCBのあるレコード番号
;	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，AF'
FRESCH:
	PUSH	BC
	LD	C,16
	LD	DE,(_DIRPS)

FRESC1:	LD	HL,(_DTBUF)
	LD	A,1
	CALL	read_disk	;=#DRDSB（2000H）
	JR	C,FRESC3
	LD	B,8

FRESC2:	LD	A,(HL)
	OR	A
	JR	Z,FRESC4
	CP	0FFH
	JR	Z,FRESC4
	PUSH	DE
	LD	DE,32
	ADD	HL,DE
	POP	DE
	DJNZ	FRESC2

	INC	DE
	DEC	C
	JR	NZ,FRESC1

FRESC3:	DB	3EH	;「LD A,」
FRESC4:	XOR	A
	POP	BC
	RET


; 	IF	0
; ;ファイル名を比較します
; ;入力	HL←比較されるFCBの先頭アドレス、
; ;	DE←比較するFCBの先頭アドレス
; ;出力	ZF＝1なら一致した
; ;破壊	AF
; FCOMP:
; 	PUSH	BC
; 	PUSH	DE
; 	PUSH	HL
; 	LD	B,16

; FCOMP1:	INC	DE
; 	INC	HL
; 	LD	A,(DE)
; 	CP	(HL)
; 	JR	NZ,FCOMP2	;不一致
; 	DJNZ	FCOMP1

; FCOMP2:	POP	HL
; 	POP	DE
; 	POP	BC
; 	RET
; 	ENDIF


;	compare_file_nameの一部
FCMPW2:	LD	A,(DE)
	CP	C	;CP ' '
	RET	Z
FCMPW1:	LD	A,(DE)
	CP	'?'	;ワイルド･カード
	RET	Z
	CALL	convert_lower_case_to_upper_case	;小文字→大文字変換
	LD	C,A
	LD	A,(HL)
	CALL	convert_lower_case_to_upper_case	;小文字→大文字変換
	CP	C	;ZF＝1なら一致
	RET


NXCLST:	DS	1	;アクセスするクラスタの一時保存場所（ロード･ルーチンで使用）
DEBUF:	DS	2	;アクセスするレコード番号の一時保存場所
HLBUF:	DS	2	;参照FCBのアドレスの一時保存場所


;P%FNAM（2912H）の本体
;ファイル情報を表示します
;入力	Acc←属性、HL←ファイル情報の先頭アドレス
;出力	なし
;破壊	AF
PFNAM:
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	DE,(_IBFAD)
	LD	BC,0020H
	LDIR
	CALL	ATRPRT	;属性情報を表示します
	LD	A,(_DSK)
	CALL	_PRINT
	LD	A,':'
	CALL	_PRINT
	CALL	_FPRNT
ADRPRT:	CALL	_PARSC	;機種依存のカセットのアドレス情報を、S-OSのワークに転送します
	LD	BC,(_SIZE)
	LD	HL,(_DTADR)
	LD	DE,(_EXADR)
	CALL	PHEX	;インナー･コール
	ADD	HL,BC
	DEC	HL
	CALL	PHEX	;インナー･コール
	EX	DE,HL
	CALL	PHEX	;インナー･コール
	POP	HL
	POP	DE
	POP	BC
	RET

PHEX:	LD	A,':'
	CALL	_PRINT
	CALL	_print_hex_4_digit
	RET


;属性情報を表示します
;入力	Acc←属性
;出力	なし
;破壊	AF，HL，DE
ATRPRT:
	PUSH	AF
	LD	DE,ATRMES
	BIT	7,A
	JR	Z,ATRP1
;	ディレクトリの場合
	LD	A,8
	DB	11H	;「LD DE,」
ATRP1:	AND	07H	;Acc←0～8
	LD	L,A
	LD	H,0
	ADD	HL,HL
	ADD	HL,HL
	LD	DE,ATRMES
	ADD	HL,DE
	EX	DE,HL
	CALL	_MSX
	POP	AF
	BIT	6,A
	LD	A,'*'
	JR	NZ,ATRP2
	LD	A,' '
ATRP2:	CALL	_PRINT
	CALL	_PRNTS
	RET


;%check_device_name（2851H）の本体
;デバイス名が正しいか（A～L，S，T，Q）かチェックします
;入力	Acc←デバイス名（小文字不可）
;出力	ZF＝1ならテープ、CY＝1なら不正
;破壊	F（AF）
;注：デバイス名が不正なら、Acc←エラー･コード。
check_device_name:
	CALL	check_tape_device_name	;デバイス名がテープ（QD）かチェックします
	RET	Z
	CP	'A'
	JR	C,DEVCH1	;「A」未満
;	「A」～
	CP	'L'+1
	CCF
	JR	C,$+4
	OR	A
	RET

DEVCH1:	LD	A,3	;Bad File Descripter
	RET


;%check_tape_device_name（2918H）の本体
;デバイス名がテープ（QD）かチェックします
;入力	Acc←デバイス名（小文字不可）
;出力	ZF＝1ならテープ
;破壊	F
check_tape_device_name:
	CP	'T'
	RET	Z
	CP	'S'
	RET	Z
	CP	'Q'
	RET


;#ERROR（2033H）の本体
ERROR:
	DEC	A
	CP	14
	JR	C,ERROR1
	INC	A
	LD	DE,ER15
	PUSH	AF
	CALL	_MSG
	LD	A,'$'	;16進数ヘッダ
	CALL	_PRINT
	POP	AF
	CALL	_print_hex_2_digit
	JR	ERROR2
ERROR1:	LD	HL,MESTBL
	ADD	A,A
	LD	E,A
	LD	D,0
	ADD	HL,DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	CALL	_MSG
ERROR2:	CALL	_BELL
	CALL	_NL
	RET


;	空きクラスタ表示用メッセージ
cluster_free_message:	DB	' Clusters Free',0DH,00H

;	属性メッセージ
ATRMES:
	DB	'Nul',00H	;000
	DB	'Bin',00H	;001
	DB	'Bas',00H	;010
	DB	'???',00H	;011
	DB	'Asc',00H	;100
	DB	'???',00H	;101
	DB	'???',00H	;110
	DB	'???',00H	;111
	DB	'Dir',00H	;1xxxxxxx


;GETDEVルーチンのバグ回避処理
;ファイル･ディスクリプタのセパレータの位置の文字を得ます
GDVPAT:
	LD	A,(DE)
	OR	A
	RET	Z	;文字列の最後に達していた
	INC	DE
	LD	A,(DE)
	DEC	DE
	RET


;モニタ･コマンドで小文字を受け付けるため
sos_monitor_command_routine1:	INC	DE
	LD	A,(DE)
	INC	DE
	JP	convert_lower_case_to_upper_case	;小文字→大文字変換


;STコマンドで小文字を受け付けるため
MSET1:	CALL	SPCUT	;文字列の空白を読み飛ばします
	LD	A,(DE)
	JP	convert_lower_case_to_upper_case	;小文字→大文字変換


;ファイル名を比較します（小文字、拡張子なしでも一致させるため）
;入力	HL←比較されるFCBの先頭アドレス、
;	DE←比較するFCBの先頭アドレス
;出力	ZF＝1なら一致した
;破壊	AF
compare_file_name:
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	B,13

FCPWL1:	INC	DE
	INC	HL
	CALL	FCMPW1
	JR	NZ,FCMPWE
	DJNZ	FCPWL1

	LD	B,3

FCPWL2:	INC	DE
	INC	HL
	LD	C,' '
	CALL	FCMPW2
	JR	NZ,FCMPWE
	DJNZ	FCPWL2

FCMPWE:	POP	HL
	POP	DE
	POP	BC
	RET


	ORG	2A00H
MESTBL:
	DW	ER1,ER2,ER3,ER4,ER5,ER6,ER7,ER8
	DW	ER9,ER10,ER11,ER12,ER13,ER14

ER1:	DB	'Device I/O Error',0DH
ER2:	DB	'Device Offline',0DH
ER3:	DB	'Bad File Descripter',0DH
ER4:	DB	'Write Protected',0DH
ER5:	DB	'Bad Record',0DH
ER6:	DB	'Bad File Mode',0DH
ER7:	DB	'Bad Allocation Table',0DH
ER8:	DB	'File not Found',0DH
ER9:	DB	'Device Full',0DH
ER10:	DB	'File Already Exists',0DH
ER11:	DB	'Reserved Feature',0DH
ER12:	DB	'File not Open',0DH
ER13:	DB	'Syntax '
ER15:	DB	'Error ',0DH
ER14:	DB	'Bad Data',0DH
OK:	DB	'Complete !',0DH


;=======================================
;内部ワーク＆内部ジャンプ･テーブル
;=======================================


	ORG	2900H
;%RDI（2900H）
;テープのインフォメーション･ファイルをロードします
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
_RDI:	JP	RDI


;%TROPN（2903H）
;テープのリード･オープン
;入力	[_DSK]←デバイス名
;出力	ZF＝1（Acc←0）ならファイルが見つかった
;	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
;注：
; ファイル名解析後呼び出すこと。
; ファイル名の先頭が20Hか0DHの場合は、常に一致とみなします。
_TROPN:	JP	TROPN


;%WRI（2906H）
;テープにインフォメーション･ファイルをセーブします
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
_WRI:	JP	WRI


;%TWRD（2909H）
;テープにデータ･ファイルをセーブします
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
_TWRD:	JP	TWRD


;%TRDD（290CH）
;テープのデータ･ファイルをロードします
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
_TRDD:	JP	TRDD


;%TDIR（290FH）
;テープのディレクトリを表示します
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
_TDIR:	JP	TDIR


;P%FNAM（2912H）
;ファイル情報を表示します
;入力	Acc←ファイル属性、HL←ファイル情報の先頭アドレス
;出力	なし
;破壊	AF
_PFNAM:	JP	PFNAM


;%DVCHK（2915H）
;デバイス名が正しいか（A～L，S，T，Q）かチェックします
;入力	Acc←デバイス名（小文字不可）
;出力	ZF＝1ならテープ
;	CY＝1なら不正（Acc←エラー･コード）
;破壊	AF
_DVCHK:	JP	check_device_name


;%check_tape_device_name（2918H）
;デバイス名がテープ（QD）かチェックします
;入力	Acc←デバイス名（小文字不可）
;出力	ZF＝1ならテープ
;破壊	F
_check_tape_device_name:	JP	check_tape_device_name


;	291BH～291DHは未使用
	DS	3


;%OPNFG（291EH）
;ファイルのオープンの状態（＝0でクローズ,＝1でオープン）
_OPNFG:	DB	0


;%FTYPE（291FH）
;ファイル属性（ファイル名の解析でセットされます）
_FTYPE:	DS	1


;%DFDV（2920H）
;デフォルト･デバイス（初期値「A」）
_DFDV:	DB	'A'


;	2921H～2929Hは未使用
	DS	9


;%PARSC（292AH）
;機種依存のテープのアドレス情報を、S-OSのワークに転送します
;入力	なし
;出力	なし
;破壊	全レジスタ保存
_PARSC:
	PUSH	HL
	LD	HL,(fcb_buffer+18)
	LD	(_SIZE),HL
	LD	HL,(fcb_buffer+20)
	LD	(_DTADR),HL
	LD	HL,(fcb_buffer+22)
	LD	(_EXADR),HL
	POP	HL
	RET


;%PARCS（293FH）
;S-OSのテープのアドレス情報を、機種依存のワークに転送します
;入力	なし
;出力	なし
;破壊	全レジスタ保存
_PARCS:
	PUSH	HL
	LD	HL,(_SIZE)
	LD	(fcb_buffer+18),HL
	LD	HL,(_DTADR)
	LD	(fcb_buffer+20),HL
	LD	HL,(_EXADR)
	LD	(fcb_buffer+22),HL
	POP	HL
	RET


;=======================================
;フィジカル･ディスクI／Oエントリ
;=======================================
;注：本体は、サイズが大きいため、メイン部後ろ移転しました。


;	2D00H～2DFFHはバッチ･ファイル読み込みバッファ


	ORG	2D00H
;=======================
;ブート･プログラム
;=======================


START:
	DI
	LD	SP,0100H	;仮スタック

;	vram_address_of_topの初期化
	LD	HL,F800H ; SORD M23のTXT VRAMの先頭アドレス
	LD	(vram_address_of_top),HL

;	デフォルト･ドライブの設定
	; LD	A,(0FF87H)	;立ち上がったドライブ番号（下位ニブル）
	; AND	1111B
	; CP	4
	; JR	NC,STADVS
	; ADD	A,'A'	;Acc←立ち上がったドライブ名
	; LD	(_DFDV),A	;デフォルト･ドライブ
STADVS:

;	[vram_size]の設定（VRAMのサイズ÷100H）
;〈VRAMのサイズ〉
;00C000Hバイト
	LD	HL,0020H	;002000H
	LD	(vram_size),HL

;	[top_of_special_work_of_vram]の設定（VRAM上の特殊ワークの先頭÷100H）
;〈VRAM特殊ワークの先頭アドレス〉
;004000H番地
	LD	HL,0000H	;004000H
	LD	(top_of_special_work_of_vram),HL

;	[size_of_special_work_of_vram]の設定（VRAM上の特殊ワークのサイズ÷100H）
;〈VRAM特殊ワークのサイズ〉
;4000Hバイト
	LD	A,00H	;4000H
	LD	(size_of_special_work_of_vram),A

;	[top_of_ram_disk_of_vram]の設定（VRAM上のRAMディスクの先頭÷100H）
;〈VRAM上のRAMディスクの先頭〉
;008000H番地
	; LD	HL,0000H	;008000H
	; LD	(top_of_ram_disk_of_vram),HL

;	[size_of_ram_disk_of_vram]の設定（VRAM上のRAMディスクのサイズ÷100H）
;〈VRAM上のRAMディスクのサイズ〉
;008000Hバイト
	; LD	HL,0000H	;008000H
	; LD	(size_of_ram_disk_of_vram),HL

;	[top_of_special_work_of_memory]、[size_of_special_work_of_memory]の設定
;〈メモリ特殊ワークの先頭とサイズ〉
;使用しません
	LD	A,00H	;0000H
	LD	(top_of_special_work_of_memory),A
	LD	A,00H	;0000H
	LD	(size_of_special_work_of_memory),A

;	コールド･スタートします
	LD	HL,0100H	;仮スタック
	LD	(_STKAD),HL
	LD	HL,_COLD
	LD	(0001H),HL
	LD	(0067H),HL
	; JP	0000H
	JP COLD
	END
