;〈注意〉
; テープはサポートしません。
; #PRCNT（1F7AH）はサポートしません。



;	各機種ディスクＩ／Ｏ
DREAD	EQU	2B00H
DWRITE	EQU	2B03H
disk_unit_number	EQU	2B06H


;〈SLANGについて〉
; SLANGは、特殊ワークのサイズによっては動作しません。
;SLANGの3014H～3015H番地の内容が、
;特殊ワーク上の大局テーブルの先頭アドレスをさしているので、
;特殊ワークのサイズのために動かない場合は、
;若い番地へ移動して対応してください。

	ORG	0000H
	JP	START	;初期化
	ORG	0066H
	JP	START	;NMIでリスタート

	ORG	0100H

;-----------------------
;テーブル･エリア
;-----------------------


;*******	256バイト境界	********


;=======================
;汎用バッファ
;=======================


;	0100H（256バイト）
BUFFER:	DS	256


;*******	256バイト境界	********


;=======================
;文字列入力バッファ
;=======================


;	0100Hバイト
keyboard_buffer:	DS	256


;*******	256バイト境界	********


;=======================================
;S-OS文字<->X1文字変換テーブル
;=======================================


;〈変換する文字〉
;5CHと9FH	「\」「＼」
;7BHと87H	「{」「■」
;7DHとF0H	「}」「チェッカー■」
;7FH		「π」
LSXTBL:	DB	 00H, 01H, 02H, 03H, 04H, 05H, 06H, 07H, 08H, 09H, 0AH, 0BH, 0CH, 0DH, 0EH, 0FH	;00
	DB	 10H, 11H, 12H, 13H, 14H, 15H, 16H, 17H, 18H, 19H, 1AH, 1BH, 1CH, 1DH, 1EH, 1FH	;10
	DB	 20H, 21H, 22H, 23H, 24H, 25H, 26H, 27H, 28H, 29H, 2AH, 2BH, 2CH, 2DH, 2EH, 2FH	;20
	DB	 30H, 31H, 32H, 33H, 34H, 35H, 36H, 37H, 38H, 39H, 3AH, 3BH, 3CH, 3DH, 3EH, 3FH	;30
	DB	 40H, 41H, 42H, 43H, 44H, 45H, 46H, 47H, 48H, 49H, 4AH, 4BH, 4CH, 4DH, 4EH, 4FH	;40
	DB	 50H, 51H, 52H, 53H, 54H, 55H, 56H, 57H, 58H, 59H, 5AH, 5BH, 9FH, 5DH, 5EH, 5FH	;50
	DB	 60H, 61H, 62H, 63H, 64H, 65H, 66H, 67H, 68H, 69H, 6AH, 6BH, 6CH, 6DH, 6EH, 6FH	;60
	DB	 70H, 71H, 72H, 73H, 74H, 75H, 76H, 77H, 78H, 79H, 7AH, 87H, 7CH,0F0H, 7EH, 7FH	;70
	DB	 80H, 81H, 82H, 83H, 84H, 85H, 86H, 7BH, 88H, 89H, 8AH, 8BH, 8CH, 8DH, 8EH, 8FH	;80
	DB	 90H, 91H, 92H, 93H, 94H, 95H, 96H, 97H, 98H, 99H, 9AH, 9BH, 9CH, 9DH, 9EH, 5CH	;90
	DB	0A0H,0A1H,0A2H,0A3H,0A4H,0A5H,0A6H,0A7H,0A8H,0A9H,0AAH,0ABH,0ACH,0ADH,0AEH,0AFH	;A0
	DB	0B0H,0B1H,0B2H,0B3H,0B4H,0B5H,0B6H,0B7H,0B8H,0B9H,0BAH,0BBH,0BCH,0BDH,0BEH,0BFH	;B0
	DB	0C0H,0C1H,0C2H,0C3H,0C4H,0C5H,0C6H,0C7H,0C8H,0C9H,0CAH,0CBH,0CCH,0CDH,0CEH,0CFH	;C0
	DB	0D0H,0D1H,0D2H,0D3H,0D4H,0D5H,0D6H,0D7H,0D8H,0D9H,0DAH,0DBH,0DCH,0DDH,0DEH,0DFH	;D0
	DB	0E0H,0E1H,0E2H,0E3H,0E4H,0E5H,0E6H,0E7H,0E8H,0E9H,0EAH,0EBH,0ECH,0EDH,0EEH,0EFH	;E0
	DB	 7DH,0F1H,0F2H,0F3H,0F4H,0F5H,0F6H,0F7H,0F8H,0F9H,0FAH,0FBH,0FCH,0FDH,0FEH,0FFH	;F0


;*******	256バイト境界	********


;=======================
;キー入力バッファ
;=======================


;	0080H（128バイト）
input_key_buffer:	DS	127	;キー入力バッファ（127文字分）
pointer_for_write_key_buffer:	DS	1	;キーを書き込むポインタ（＝0でカラ、＝7FHでいっぱい）


;=======================================
;コントロール･コード･ジャンプ･テーブル
;=======================================


;	0040H（64バイト）
CTLTBL:	DW	CTLNUL	;^＠
	DW	CTL01	;^A 'カーソルを論理行頭へ（-^V）
	DW	CTLNUL	;^B '前のワードの先頭へ（－^F） '非サポート
	DW	CTLCAN	;^C ^STOP（論理改行＆インサート解除）
	DW	CTLDEL	;^D '論理行のカーソル位置の文字の削除（DELキー）
	DW	CTL05	;^E '論理行のカーソル以降削除（－^U）
	DW	CTLNUL	;^F '次のワードの先頭へ（－^B） '非サポート
	DW	BELL	;^G BELL
	DW	CTLBS	;^H BS
	DW	CTLTAB	;^I TAB
	DW	CTLNUL	;^J LF
	DW	CTLHOM	;^K HOME
	DW	CTLCLS	;^L CLR
	DW	CTLCR	;^M CR＋LF
	DW	CTLNUL	;^N '論理行分割（－^W） '非サポート
	DW	CTLNUL	;^O '物理行注入（－^Y） '非サポート
	DW	CTLNUL	;^P
	DW	CTLNUL	;^Q
	DW	CTLINS	;^R INS
	DW	ROLUP	;^S 'スクロール･アップ（－^S）
	DW	ROLDWN	;^T 'スクロール･ダウン（－^T）
	DW	CTLNUL	;^U '論理行のカーソルより前削除（－^E） '非サポート
	DW	CTLNUL	;^V 'カーソルを論理行末へ（－^A、最後の文字の次のカーソル位置) '非サポート
	DW	CTLNUL	;^W '次の行と連結（－^N、,論理行末と次の行の行頭をつなぐ) '非サポート
	DW	CTLNUL	;^X SELECT
	DW	CTLNUL	;^Y '物理行削除（－^O） '非サポート
	DW	CTLNUL	;^Z
	DW	CTLCAN	;^［ ESC
	DW	CTLRHT	;^￥ →
	DW	CTLLFT	;^］ ←
	DW	CTLUP	;^＾ ↑
	DW	CTLDWN	;^＿ ↓


;===============================
;割り込みルーチン用スタック
;===============================


;	0040H（64バイト）
	DS	64
INTSTK:


;*******	256バイト境界	********


;=======================================
;カーソル･オフセット計算用テーブル下位
;=======================================
;y座標に対応するカーソル･オフセットを得ます
;カーソル･オフセット←[cursol_offset_for_Y_table＋256＋y座標]×256＋[cursol_offset_for_Y_table＋y座標]


;	0020H（32バイト）
cursol_offset_for_Y_table:	DS	32



;===============================
;システム･スタック･エリア
;===============================


;	00CCH（204バイト）
	DS	256-52
system_stack_area:


;*******	256バイト境界	********


;=======================================
;カーソル･オフセット計算用テーブル上位
;=======================================
; y座標に対応するカーソル･オフセットを得ます。
;カーソル･オフセット←[cursol_offset_for_Y_table＋256＋y座標]×256＋[cursol_offset_for_Y_table＋y座標]


;	0020H（32バイト）
	DS	32


;=======================
;内部ワーク･エリア
;=======================


;	0050H（80バイト）
fcb_buffer:	DS	32	;S-OSのFCBバッファ（[_IBFAD]でポイント）

;	通常（42バイト）
total_number_of_character_display:	DS	2	;画面の表示文字数
cursol_offset_last_top_of_line:	DS	2	;最終行先頭のカーソル･オフセット
vram_address_of_top:	DS	2	;テキストVRAM先頭アドレス（未使用の場合あり）
vram_address_of_top_of_last_line:	DS	2	;最終行先頭のテキストVRAMアドレス（未使用の場合あり）
locate_of_cursol_overlap_character:	DS	1	;カーソルと重なった位置の文字の保存（未使用の場合あり）
screen_width:	DS	1	;＝00Hで40桁、＝FFHで80桁
CSRADD:	DS	2	;（行数－1）×256＋桁数
CSRNXI:	DS	1	;256－桁数 '[CSRNX]の初期値
CSRNYI:	DS	1	;256－行数 '[CSRNY]の初期値
CSRNX:	DS	1	;x座標-[_WIDTH]
CSRNY:	DS	1	;y座標-[_MXLIN]
display_cursol_XY_not_use:	DS	2	;カーソル座標（使用しません）
number_of_character_after_CR:	DS	1	;改行してからの文字数（未使用）
insert_mode_flag:	DS	1	;＝00Hで通常、＝FFHでインサート･モード
foreground_color:	DS	1	;前景色
background_color:	DS	1	;背景色
BDRCLR:	DS	1	;周辺色
attribute_data:	DS	1	;画面のアトリビュートRAMへ書き込むデータ

real_time_key:	DS	1	;リアル･タイム･キー（未使用の場合あり）
	DS	1
CLKFLG:	DS	1	;＝FFHで、クリック音を鳴らします（無効の場合あり）
JOYFLG:	DS	1	;＝FFHでジョイスティックをサポート

GRAFLG:	DS	1	;＝FFHでグラフィック表示（未使用の場合あり）
KNJFLG:	DS	1	;＝FFHで漢字モード（未使用の場合あり）

vram_size:	DS	2	;VRAMのサイズ÷100H
top_of_special_work_of_vram:	DS	2	;VRAM上の特殊ワークの先頭÷100H
size_of_special_work_of_vram:	DS	1	;VRAM上の特殊ワークのサイズ÷100H
	DS	1
top_of_ram_disk_of_vram:	DS	2	;VRAM上のRAMディスクの先頭÷100H
size_of_ram_disk_of_vram:	DS	2	;VRAM上のRAMディスクのサイズ÷100H
top_of_special_work_of_memory:	DS	1	;メモリ上の特殊ワークの先頭÷100H
size_of_special_work_of_memory:	DS	1	;メモリ上の特殊ワークのサイズ÷100H

;	機種独自（6バイト）
KEYDAT:	DS	2	;ファンクション、アスキー･コードの生データ
X1TFLG:	DS	1	;＝FFHでX1turbo
IO1FD0:	DS	1	;I／O 1FD0Hのバッファ
RESMOD:	DS	1	;0：スイッチに従います，1：低解像度，2：高解像度，3：疑似高解像度
RESFLG:	DS	1	;＝FFHで24kHzモード


	ORG	(($+7FH) & 0FF80H)
;-----------------------
;割り込みルーチン
;-----------------------


; 省メモリのため、テーブル･エリアに移動してきました。


;=======================
;キー･スキャン･ルーチン
;=======================


;キー入力割り込み処理
KEYINT:
	LD	(KYIRSP),SP
	LD	SP,INTSTK	;割り込み用スタック
	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC

;	キーが有効かチェックします
	LD	A,(KEYDAT)	;ファンクション
	BIT	6,A
	JR	NZ,KYIRET	;キーがはなされた
	AND	00100000B	;b5
	JR	NZ,KYISKP
	LD	A,(pointer_for_write_key_buffer)
	OR	A
	JR	NZ,KYIRET	;バッファにカラでないときは、リピート禁止
KYISKP:
;	キー入力バッファに書き込みます
	LD	A,(real_time_key)	;Acc←入力文字
	CALL	write_one_character_to_key_buffer
	JR	C,KYIRET	;バッファがいっぱいだった
	CALL	CLICK	;クリック音を鳴らします

KYIRET:
	POP	BC
	POP	DE
	POP	HL
	POP	AF
	DB	31H	;「LD SP,」
KYIRSP:	DS	2
	EI
	RETI


;キー入力バッファに1文字書き込みます
;入力	Acc←文字
;出力	キー入力バッファ←文字
;	CY＝1でバッファがいっぱいだった
;破壊	AF，HL，DE，BC
;注：
; 割り込み禁止して実行してください。
; キー入力バッファは、00xxHから始まる127バイトで、
;＋127の部分がpointer_for_write_key_bufferにあたります。
write_one_character_to_key_buffer:
	LD	HL,pointer_for_write_key_buffer
	LD	E,(HL)
	LD	D,H	;DE←書き込みポイント
	LD	(DE),A	;キー入力バッファ←文字
	INC	E
	JP	M,PKYBRK
	LD	(HL),E	;[pointer_for_write_key_buffer]のカウント･アップ
	OR	A	;CY←0
	RET
PKYBRK:	LD	(HL),L	;[pointer_for_write_key_buffer]を元に戻します
	SCF
	RET


	ORG	(($+0FFH) & 0FF00H)
;*******	256バイト境界	********


;===============================
;ライン･ターミナル･テーブル
;===============================


; 先頭行の行連結情報はxx00Hのアドレスに格納されます。
;行連結情報←LINTTB＋y座標（0～）
; FFHで次の行と連結。
;	0020H（32バイト）
LINTTB:	DS	32


;-----------------------
;S-OSルーチン
;-----------------------


;	ORG	$+7FH and 0FF80H
;=======================
;システム･ルーチン
;=======================


;#COLD（1FFDH）の本体
; コールド･スタートして、[_USR]のアドレスにジャンプします。
;[_USR]の内容は、「_HOT」に初期化します。
;注：
; プリンタ非出力モードにします。
; 「RET」命令で、「_HOT」にジャンプします。
; キー入力バッファをカラにして、そのアドレスをDEで渡す。
; 固有の初期化ルーチンの cold_start_entity（全レジスタ破壊）を呼び出します。
; 固有のメッセージ「TTLMSG」を参照します。
COLD:
;	初期化
	LD	SP,(_STKAD)
	CALL	 cold_start_entity	;固有の初期化
	LD	SP,(_STKAD)
	CALL	_LPTOF
	LD	A,255
	CALL	_WIDCH	;表示幅の初期化 'LINCHを先に呼び出すように改良
	LD	A,255
	CALL	LINCH	;表示行数の初期化

;	ディスクのパラメータの初期化
	LD	HL,000EH
	LD	(_FATPS),HL
	LD	HL,0010H
	LD	(_DIRPS),HL
	LD	HL,2E00H
	LD	(_FATBF),HL
	LD	HL,2F00H
	LD	(_DTBUF),HL
	LD	A,80
	LD	(_MXTRK),A

;	タイトル
	LD	DE,TTLMSG
	CALL	_MSX

;	メモリの情報を表示
	CALL	_MPRNT
	DB	'MAIN 3000H-',00H
	LD	HL,(_MEMAX)
	DEC	HL
	CALL	_PRTHL
	CALL	_MPRNT
	DB	'H',0DH,00H
	CALL	_MPRNT
	DB	'WORK 0000H-',00H
	LD	HL,(_WKSIZ)
	DEC	HL
	CALL	_PRTHL
	CALL	_MPRNT
	DB	'H',0DH,00H

;	文字列入力バッファの80バイトをクリア
	LD	HL,(_KBFAD)
	LD	E,L
	LD	D,H
	INC	DE	;DE←[_KBFAD]＋1
	LD	BC,79
	LD	(HL),B	;[_KBFAD]←0
	LDIR

;	ホット･スタートへ
	LD	HL,(_USR)
	EX	DE,HL	;DE←ジャンプ先
	LD	HL,_HOT
	PUSH	HL	;戻りアドレス（_HOT）
	LD	(_USR),HL	;[_USR]の再設定
	EX	DE,HL	;HL←ジャンプ先
	LD	DE,(_KBFAD)	;DE←[_KBFAD]
	XOR	A
	JP	(HL)	;旧[_USR]の内容にジャンプ


;#BOOT（2036H）の本体
; S-OSを終えます。
;注：フィジカル･ルーチンboot_entity（全レジスタ破壊）を呼び出します。
BOOT:
	JP	boot_entity


;===============================
;バージョン･ナンバーの取り出し
;===============================


;#VER（1FF7H）の本体
; Hに機種別情報、LにS-OSのバージョンを返します。
;入力	なし
;出力	H←機種別情報、L←S-OSのバージョン
;破壊	HL
;〈機種別情報〉
;00H	MZ-80K／C／1200
;01H	MZ-700
;02H	MZ-1500
;10H	MZ-80B
;11H	MZ-2000／2200
;12H	MZ-2500
;20H	X1
;21H	X1turbo
;22H	X1（筑紫版）
;30H	PC-8801（ROM）
;31H	PC-8001
;32H	PC-8801（オールRAM）
;40H	FM-7／77
;50H	SMC-777
;60H	PASOPIA
;61H	PASOPIA7
;70H	PC-286
;80H	X68000
;90H	MSX／2／2＋／turboR（ANK専用版）
;91H	MSX／2／2＋／turboR（漢字対応版）
;95H	SORD M23
;〈S-OSのバージョン〉
; SWORDでは、「20H」。
; フィジカル･ルーチン vertion_entity（AF，HL，DE，BC破壊）を呼び出します。
VER:
	PUSH	AF
	PUSH	DE
	PUSH	BC
	CALL	vertion_entity	;フィジカル･ルーチン vertion_entity
	POP	BC
	POP	DE
	POP	AF
	RET


;===============
;表示ルーチン
;===============


;#TAB（1FDFH）の本体
; 指定論理桁位置まで、スペースを表示します。
;入力	B←論理桁位置
;出力	CY＝1（Acc＝14）なら、値が不正だった
;破壊	AF
;注：[_PRCNT]を参照しません。
TAB:
	PUSH	HL
	PUSH	DE
	PUSH	BC
	CALL	GTPRC
	POP	BC
	EX	DE,HL	;DE←現在の論理桁位置
	LD	L,B
	LD	H,0	;HL←新しい論理桁位置
	OR	A
	SBC	HL,DE	;HL←表示するスペース数（1～255）
	JR	Z,TABRE1	;スペース数0だった
	JR	C,TABRE2	;値が不正だった 'CY＝1
	LD	A,' '

TABLP:	CALL	_PRINT
	DEC	L
	JR	NZ,TABLP

TABRE1:	XOR	A	;CY←0
TABRE2:	POP	DE
	POP	HL
	RET


;#PRNTS（1FF1H）の本体
; スペースを1つ表示します。
;入力	なし
;出力	なし
;破壊	F（実際なし）
PRNTS:
	PUSH	AF
	LD	A,' '
	CALL	_PRINT
	POP	AF
	RET


;#LTNL（1FFEH）の本体
; 改行します。
;入力	なし
;出力	なし
;破壊	なし
LTNL:
	PUSH	AF
	LD	A,0DH
	CALL	_PRINT
	POP	AF
	RET


;#NL（1FEBH）の本体
; 論理行頭でなければ、改行します。
;入力	なし
;出力	なし
;破壊	なし
;注：
; 論理行頭でなければ改行します。
; #PRCNT（1F7AH）は無視します。
NL:
	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	CALL	GTPRC
	LD	A,H
	OR	L
	LD	A,0DH
	CALL	NZ,_PRINT
NLJMP:	POP	BC	;#MSG（1FE8H）などからジャンプしてきます
	POP	DE
	POP	HL
	POP	AF
	RET


;#MSG（1FE8H）の本体
; 文字列出力（エンド･コード0DH）。
;入力	DE←文字列先頭アドレス
;出力	なし
;破壊	F（実際なし）
;注：0DHは表示しません。
MSG:
	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC

MSGLP:	LD	A,(DE)
	CP	20H
	JR	C,MSGSKP
	CALL	BPRNT
	JR	MSGLP
MSGSKP:	CP	0DH
	JR	Z,NLJMP	;#NL（1FEBH）の一部へジャンプします
	CALL	_PRINT
	INC	DE
	JR	MSGLP


;#MSX（1FE5H）の本体
; 文字列出力（エンド･コード00H）。
;入力	DE←文字列先頭アドレス
;出力	なし
;破壊	F（実際なし）
;注：00Hは表示しません。
MSX:
	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC

MSXLP:	LD	A,(DE)
	CP	20H
	JR	C,MSXSKP
	CALL	BPRNT
	JR	MSXLP
MSXSKP:	OR	A
	JR	Z,NLJMP	;#NL（1FEBH）の一部へジャンプします
	CALL	_PRINT
	INC	DE
	JR	MSXLP


;#MPRNT（1FE2H）本体
; インライン文字列出力（エンド･コード00H）。
;入力	「CALL ＃MPRNT」の次のアドレス～←文字列
;出力	なし
;破壊	AF，DE（実際AF）
;注：
; 00Hは表示しません。
; 「REDA」などがDE保存を期待しているので、DEを保存します。
MPRNT:
	EX	(SP),HL	;HL←インライン･パラのアドレス，スタック←HL
	PUSH	DE
	PUSH	BC
	EX	DE,HL

MPRLP:	LD	A,(DE)
	CP	20H
	JR	C,MPRSKP
	CALL	BPRNT
	JR	MPRLP
MPRSKP:	OR	A
	JR	Z,MPRRET
	CALL	_PRINT
	INC	DE
	JR	MPRLP

MPRRET:	EX	DE,HL
	POP	BC
	POP	DE
	EX	(SP),HL	;スタック←インライン･パラの次のアドレス，HL←元の値
;	XOR	A
	RET


;===============
;16進数
;===============


;#PRTHX（1FC1H）の本体
; 16進2桁表示。
;入力	Acc←データ
;出力	なし
;破壊	AF
PRTHX:
	PUSH	AF
	RLCA
	RLCA
	RLCA
	RLCA		;上位
	CALL	_ASC
	CALL	_PRINT
	POP	AF	;下位
	CALL	_ASC
	CALL	_PRINT
	OR	A	;CY←0
	RET


;#PRTHL（1FBEH）の本体
; 16進4桁表示。
;入力	HL←データ
;出力	なし
;破壊	AF
PRTHL:
	LD	A,H
	CALL	_PRTHX
	LD	A,L
	JP	_PRTHX


;#ASC（1FBBH）の本体
; 4ビット･バイナリ→16進1文字。
;入力	Acc下位4ビット←データ
;出力	Acc←16進文字
;破壊	AF
ASC:
	AND	0FH
	ADD	A,'0'
	CP	3AH	;「9」＋1
	CCF		;CY＝0でリターンするため
	RET	NC
	ADD	A,'A'-3AH	;CY←0
	RET


;#HEX（1FB8H）の本体
; 16進1文字→4ビット･バイナリ。
;入力	Acc←16進文字
;出力	Acc←データ（0～15）
;	CY＝1（Acc＝14）ならエラー
;破壊	AF
;注：
; 小文字に対応。
; 汎用ルーチンTOUPR（AF破壊）を呼び出します。
HEX:
	CALL	TOUPR
	SUB	'0'
	JR	C,HEXERR
	CP	10
	JR	C,HEXESC
	CP	10+7	;7＝「A」－（「9」＋1）
	JR	C,HEXERR
	SUB	7
	CP	16
	JR	NC,HEXERR
HEXESC:	OR	A
	RET

HEXERR:	LD	A,14	;Bad Data
	SCF
	RET


;#2HEX（1FB5H）の本体
; 文字列の16進2桁→1バイト･バイナリ。
;入力	[DE～]←16進文字2桁
;出力	Acc←データ
;	DEはカウント･アップ（エラーを発生した時点でカウント･アップは停止）
;	CY＝1ならエラー
;破壊	AF，DE
;注：小文字に対応。
AHEX:
	LD	A,(DE)
	CALL	_HEX
	RET	C
	INC	DE
	RLCA
	RLCA
	RLCA
	RLCA
	LD	(AHXPAT+1),A
	LD	A,(DE)
	CALL	_HEX
	RET	C
	INC	DE
AHXPAT:	OR	0
	RET


;#HLHEX（1FB2H）の本体
; 文字列の16進4桁→2バイト･バイナリ。
;入力	[DE～]←16進文字4桁
;出力	HL←データ
;	DEはカウント･アップ（エラーを発生した時点でカウント･アップは停止）
;	CY＝1ならエラー
;破壊	AF，HL，DE
;注：小文字に対応。
HLHEX:
	CALL	_2HEX
	LD	H,A
	CALL	NC,_2HEX
	LD	L,A
	RET


;===============
;スクリーン制御
;===============


;#CSR（2018H）の本体
; カーソル座標を読み出します。
;入力	なし
;出力	L←x座標、H←y座標
;破壊	HL
;注：フィジカル･ルーチンget_cursol_XY_entity（AF，HL，DE，BC破壊）を呼び出します。
CSR:
	PUSH	AF
	PUSH	DE
	PUSH	BC
	CALL	get_cursol_XY_entity
	POP	BC
	POP	DE
	POP	AF
	RET


;#LOC（201EH）の本体
; カーソル位置を指定座標へ。
;入力	L←x座標、H←y座標
;出力	なし
;破壊	AF（実際F）
;注：
; 「WALRUS」がAccの保存を期待しているので、Accは保存します。
; 「ELFES IV」「TANGERINE」などでCYクリアが必要。
; フィジカル･ルーチンmove_cursol_XY_entity（AF，HL，DE，BC破壊）を呼び出します。
LOC:
	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	CALL	move_cursol_XY_entity
	POP	BC
	POP	DE
	POP	HL
	POP	AF
	OR	A	;CY←0
	RET


;#SCRN（201BH）の本体
; 指定座標の文字を読み込みます。
;入力	L←x座標、H←y座標
;出力	Acc←文字
;破壊	AF
;注：
; CYをクリアします。
; フィジカル･ルーチンget_character_XY_entity（AF，HL，DE，BC破壊）を呼び出します。
SCRN:
	PUSH	HL
	PUSH	DE
	PUSH	BC
	CALL	get_character_XY_entity
	POP	BC
	POP	DE
	POP	HL
	OR	A	;CY←0
	RET


;#WIDCH（2030H）の本体
; 表示桁数を変更します。
;入力	Acc←桁数
;出力	なし
;破壊	AF，HL，DE，BC
;注：
; フィジカル･ルーチンchange_width_entity（AF，HL，DE，BC破壊）を呼び出します。
; CY＝0でリターンします（ディスク･モジュールのため）。
WIDCH:
	; SWORDでは、80桁表示をサポートしません。
	XOR	A	;CY←0（Acc←0）
	RET


;LINCH（203CH）の本体
; 表示行数を変更します。
;入力	Acc←行数
;	[_WIDTH]参照
;出力	なし
;破壊	AF，HL，DE，BC
LINCH0:
	; SWORDではサポートしません。
	RET

;=======================
;ビープ音を鳴らします
;=======================


;#BELL（1FC4H）の本体
; ビープ音を鳴らします。
;入力	なし
;出力	なし
;破壊	AF
;注：フィジカル･ルーチンbell_entity（AF，HL，DE，BC破壊）を呼び出します。
BELL:
	RET


;=======================
;プリンタ･ルーチン
;=======================


;#LPRNT（1FDCH）本体
; プリンタ1文字出力。
;入力	Acc←文字
;出力	CY＝1ならエラー（Acc＝1）
;破壊	AF
;注：
; 旧X1版SWORDと同じく、エラーが起これば、[#LPSW]をオフにします。
; フィジカル･ルーチンlprint_entity（AF破壊）を呼び出します。
; 0DHは、0DH＋0AHに変換します。
; 00H、0AH、1AHは、無視します。
LPRNT:
	RET

;#LPTON（1FD9H）の本体
; 表示をプリンタ出力モードにします。
;入力	なし
;出力	[_LPSW]←1
;破壊	なし
;注：
; 旧X1版SWORDと同じく、[#LPSW]に1を書きます。
; フィジカル･ルーチンprinter_output_mode_on_entity（AF，HL，DE，BC破壊）を呼び出します。
LPTON:
	RET

;#LPTOF（1FD6H）の本体
; 表示を非プリンタ出力モードにします。
;入力	なし
;出力	[_LPSW]←0
;破壊	なし
;注：フィジカル･ルーチンprinter_output_mode_off_entity（AF，HL，DE，BC破壊）を呼び出します。
LPTOF:
	RET


;===============
;入力ルーチン
;===============


;#GETKY（1FD0H）の本体
; キー入力（入力待ちなし、エコー･バックなし）。
;入力	なし
;出力	Acc←文字
;破壊	AF
;注：
; 常にオート･リピートがかかっています。
; フィジカル･ルーチンreal_time_input_key_entity（AF，HL，DE，BC破壊）を呼び出します。
GETKY:
	RET

;#BRKEY（1FCDH）の本体
; ^Cチェックします（入力待ちなし、エコー･バックなし）。
;入力	なし
;出力	ZF＝1なら^Cが押されています
;破壊	AF
;注：
; 常にオート･リピートがかかっています。
; フィジカル･ルーチンreal_time_input_key_entity（AF，HL，DE，BC破壊）を呼び出します。
; ^C（03H）とESC（1BH）をブレイク･キーとみなします。
BRKEY:
	PUSH	HL
	PUSH	DE
	PUSH	BC
	CALL	real_time_input_key_entity
	CP	03H	;^C
	JR	Z,BRKRET
	CP	1BH	;ESC
	JR	Z,BRKRET
	OR	0FFH	;ZF←0，CY←0
BRKRET:
	POP	BC
	POP	DE
	POP	HL
	RET


;#PAUSE（1FC7H）の本体
; ポーズ処理。
; どのタイミングでも、
;^Cが入力されればインライン･パラのアドレスにジャンプします。
;何もキーが押されていなければ、そのままリターンします。
; スペースが押されれば一時停止し、他のキーが押されればリターンします。
;入力	「CALL ＃PAUSE」の次のアドレス←^C入力時の飛び先
;出力	なし
;破壊	AF
PAUSE:
	EX	(SP),HL	;スタック←HL，HL←インライン･パラのアドレス
	PUSH	DE
	PUSH	BC
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	LD	(PAURET),HL	;リターン･アドレス
	LD	(PAUREB),DE	;インライン･パラ
	CALL	_BRKEY
	JR	Z,PAUBRK
	CALL	_GETKY
	CP	' '
	JR	NZ,PAUESC

PAULP:	CALL	_BRKEY
	JR	Z,PAUBRK
	CALL	_GETKY
	OR	A
	JR	Z,PAULP
	CP	' '
	JR	Z,PAULP

PAUESC:	POP	BC
	POP	DE
	POP	HL
	XOR	A
	DB	0C3H	;「JP」
PAURET:	DS	2

PAUBRK:	POP	BC
	POP	DE
	POP	HL
	XOR	A
	DB	0C3H	;「JP」
PAUREB:	DS	2


;#INKEY（1FCAH）の本体
; キー入力（入力待ちあり、エコー･バックなし）。
;入力	なし
;出力	Acc←文字
;破壊	AF
;注：
; フィジカル･ルーチンINKEY_entity（AF，HL，DE，BC破壊）を呼び出します。
INKEY:
	RET


;#FLGET（2021H）の本体
; カーソル表示つき、キー入力（入力待ちあり、エコー･バックなし）。
;入力	なし
;出力	Acc←文字
;破壊	AF
;注：フィジカル･ルーチンinput_one_character_entity（AF，HL，DE，BC破壊）を呼び出します。
FLGET:
	RET

;#GETL（1FD3H）の本体
; 文字列入力。
;入力	DE←キー入力バッファの先頭アドレス
;出力	[DE～]←文字列
;破壊	AF
;注：
; エンド･コードは00H。
; 入力がキャンセルされた場合、「1BH、00H」がバッファに格納されます。
; 入力待ちあり、エコー･バックあり。
; フィジカル･ルーチンinput_line_character_entity（AF，HL，DE，BC破壊)を呼び出します。
GETL:
	RET

;===============================
;ファイル操作（ファイル名処理）
;===============================


;#FPRNT（1F9DH）の本体
; S-OSのFCBバッファのファイル名を表示します（改行しません）。
; ポーズ機能あり。
;入力	S-OSのFCBバッファ（fcb_buffer～）参照
;出力	なし
;破壊	AF，HL，DE，BC
FPRNT:
	LD	DE,fcb_buffer+1

;	プライマリ名の表示
	LD	B,13
FPRLP1:	LD	A,(DE)
	INC	DE
	CALL	_PRINT
	DJNZ	FPRLP1

;	ピリオドの表示
	LD	A,'.'
	CALL	_PRINT

;	拡張子の表示
	LD	B,3
FPRLP2:	LD	A,(DE)
	INC	DE
	CALL	_PRINT
	DJNZ	FPRLP2

	CALL	_PAUSE
	DW	$+2
	RET


;#FSAME（1FA0H）の本体
; ＃FILE（1FA3H）でセットされたファイル名、ファイル属性と、
;DE～にセットされた解析されてないないファイル名（エンド･コード00H）、
;ファイル属性（Acc）を比較します。
;入力	Acc←ファィル属性、DE←文字列（ファイル名）の先頭
;	S-OSのFCBバッファ（fcb_buffer～）参照
;出力	一致すればZF＝1（Acc←0）、不一致ならZF＝0（Acc←8）
;破壊	AF，HL，DE，BC
;注：
; 入力パラメータに、ファイル属性（Acc）が必要。
; CYは常にリセットされています。
FSAME:
;	ファイル属性の比較
	AND	10000111B	;マスク
	LD	B,A	;B←マスクされたファイル属性
	LD	A,(_FTYPE)	;Acc←セットされたFCBのファイル属性
	AND	10000111B	;マスク
	CP	B
	JP	NZ,FSMERR	;ファイル属性が一致しない

;	[BUFFER～]にデバイス名とファイル名を解析してセットします
	CALL	FNAME	;ファイル名を解析します
	RET	C	;デバイス名が異常（エラー3）

;	デバイス名の比較
	LD	A,(_DSK)
	LD	HL,BUFFER
	CP	(HL)
	JR	NZ,FSMERR

;	ファイル名（プライマリ，拡張子）の比較
	LD	DE,fcb_buffer+1	;比較されるファイル名
	LD	HL,BUFFER+1	;比較するファイル名
	LD	A,16
	CALL	CMPFNM	;ファイル名を比較します
	RET	Z

;	一致しませんでした
FSMERR:	LD	A,8	;File not Found
	OR	A	;ZF←0
	SCF
	RET


;#FILE（1FA3H）の本体
; ファイル名を解析して、各ワークにパラメータをセットします。
;入力	Acc←ファィル属性、DE←文字列（ファイル名）の先頭
;出力	[_DSK]←デバイス名、[_FTYPE]←ファイル属性、
;	S-OSのFCBバッファ←変換されたファイル名
;	DEは00Hか「:」のアドレスを示しています。
;	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
;注：
; CY＝0でリターンしています。
; ファイル名はコントロール･コードなどがカットされ、
;「*」は「?」に展開されます。
FILE:
	LD	(_FTYPE),A	;ファイル属性（ファイル名の解析でセットされます）
	LD	(fcb_buffer),A	;FCBのファイル属性部分（＋0）
	CALL	FNAME	;ファイル名を解析します
	RET	C	;デバイス名が異常（エラー3）
	PUSH	DE
	LD	A,(BUFFER)	;Acc←デバイス名
	LD	(_DSK),A
	LD	HL,BUFFER+1	;解析されたファイル名
	LD	DE,fcb_buffer+1	;FCBのファイル名フィールド
	LD	BC,16
	LDIR		;FCBのファイル名部分（＋1～＋16）
	LD	A,20H
	LD	(DE),A	;FCBのパスワード部分（＋17）
	POP	DE
	CALL	SPSKIP	;文字列の空白を読み飛ばします
	XOR	A	;CY←0
	RET


;===============================
;ファイル名処理補助ルーチン
;===============================


;ファイル名を比較します
;入力	DE←比較されるファイル名の先頭、HL←比較するファイル名の先頭、
;	Acc←カウンタ
;出力	ZF＝1なら一致
;破壊	AF，HL，DE，BC
;注：ワイルド･カードの「?」は常に一致とみなします。
CMPFNM:
	LD	B,A	;B←カウンタ
	EX	DE,HL

;	比較ループ
CPFLP:	LD	A,(DE)	;Acc←比較する文字
	CP	'?'
	JR	Z,CPFSKP	;常に一致させます
	CP	(HL)
	RET	NZ	;一致しませんでした
CPFSKP:	INC	DE
	INC	HL
	DJNZ	CPFLP

;	すべて一致
	XOR	A	;ZF←1
	RET


;ファイル名を解析します
;入力	DE←文字列（ファイル名）の先頭
;出力	[BUFFER]←デバイス名、[BUFFER＋1～]←変換されたファイル名
;	DEはカウント･アップされます（区切りでストップ）
;	CY＝1（Acc←エラー･コード）ならエラー
;破壊	AF，HL，DE，BC
FNAME:
;	デバイス名の転送
	CALL	MGETDV	;文字列からデバイス名を取り出します
	CALL	_DVCHK	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	RET	C	;Acc←3 'Bad File Descripter
	LD	HL,BUFFER
	LD	(HL),A	;[BUFFER]←デバイス名
	INC	HL	;HL←BUFFER＋1

;	ファイル名の転送
	CALL	CLRWFG
	LD	B,13	;プライマリ名
FNML11:	CALL	GTFLTR
	LD	(HL),A
	INC	HL
	DJNZ	FNML11
	CALL	SKPPRD
	CALL	CLRWFG
	LD	B,3	;拡張子
FNML12:	CALL	GTFLTR
	LD	(HL),A
	INC	HL
	DJNZ	FNML12
	CALL	SKPPRD

	XOR	A	;CY←0
	RET


;文字列からデバイス名を取り出します
;入力	DE←文字列の先頭アドレス
;出力	Acc←デバイス名（省略時はデフォルト、小文字は大文字に変換）
;	CY＝1ならデバイス名が省略されていました
;	DEはカウント･アップされます
;破壊	AF，DE
MGETDV:
	CALL	SPSKIP	;文字列の空白を読み飛ばします
	LD	A,(DE)
	OR	A
	JR	Z,MGTDV1	;文字列の終わりに達していました
	INC	DE
	LD	A,(DE)
	DEC	DE
	CP	':'
	JR	NZ,MGTDV1	;デバイスが指定されていません

;	デバイスが指定されています
	LD	A,(DE)
	CALL	TOUPR
	INC	DE
	INC	DE
	OR	A	;CY←0
	RET

;	デバイスが指定されていません
MGTDV1:	CALL	_RDVSW
	SCF		;CY←1
	RET


;GTFLTRルーチンの「*」モードを初期化します
;入力	なし
;出力	[WASFLG]←0
;破壊	AF
CLRWFG:
	XOR	A
	LD	(WASFLG),A
	RET


;文字列からファイル名（プライマリ，拡張子）を1文字取り出します
;入力	DE←文字列のアドレス
;出力	Acc←変換された文字（区切りに達した場合はスペースに変換されます）
;	DEはカウント･アップされます（区切りでストップ）
;破壊	AF，DE
;注：
; 00H、0DH、「:」、「.」を区切りとみなします。
; コントロール･コードやスペースはスキップします。
; 「*」フェイズでは「?」を返します。
GFLLP:	INC	DE

GTFLTR:
;	「*」フェイズかチェックします
	LD	A,(WASFLG)
	OR	A
	JR	NZ,GFLWLD

	LD	A,(DE)	;Acc←1文字

;	区切りに達したか調べます
	OR	A	;NUL
	JR	Z,GFLESC
	CP	0DH	;RET
	JR	Z,GFLESC
	CP	':'
	JR	Z,GFLESC
	CP	'.'
	JR	Z,GFLESC

;	コントロール･コードとスペースをスキップします
	LD	A,(DE)
	CP	7FH	;DEL
	JR	Z,GFLLP
	CP	21H	;00H～20H
	JR	C,GFLLP

;	「*」かチェックします
	CP	'*'
	JR	Z,GFLAST

;	通常終了
	INC	DE	;DEのカウント･アップ
	JP	TOUPR

;	「*」を発見しました
GFLAST:	LD	A,0FFH
	LD	(WASFLG),A
	INC	DE

;	「*」フェイズ
GFLWLD:	LD	A,'?'
	RET

;	ピリオドかファイル名の最後に達しました
GFLESC:	LD	A,' '
	RET

;	ワイルド･カード関係
WASFLG:	DS	1	;＝FFHで「*」フェイズ中


;ファイル名のピリオド部（プライマリと拡張子の区切り）をスキップします
;入力	DE←文字列のアドレス
;出力	DEはカウント･アップされます（区切りでストップ）
;破壊	AF，DE
;注：
; 00H、0DH、「:」を区切りとみなします。
; コントロール･コードやスペースはスキップします。
SKPLP:	INC	DE

SKPPRD:
	LD	A,(DE)	;Acc←1文字

;	区切りに達したか調べます
	OR	A	;NUL
	RET	Z
	CP	0DH	;RET
	RET	Z
	CP	':'
	RET	Z

;	ピリオドに達したか調べます
	CP	'.'
	JR	NZ,SKPLP

;	ピリオドをスキップ
	INC	DE
	RET


;=======================
;ファイル操作（テープ）
;=======================
; サポートしません。


;%RDI（2900H）
;テープのインフォメーション･ファイルをロードします
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
RDI:
	LD	A,2
	SCF
	RET


;%TROPN（2903H）
;テープのリード･オープン
;入力	[_DSK]←デバイス名
;出力	ZF＝1（Acc←0）ならファイルが見つかりました
;	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
;注：
; ファイル名解析後呼び出すこと。
; ファイル名の先頭が20Hか0DHの場合は、常に一致とみなします。
TROPN:
	LD	A,2
	SCF
	RET


;%WRI（2906H）
;テープにインフォメーション･ファイルをセーブします
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
WRI:
	LD	A,2
	SCF
	RET


;%TWRD（2909H）
;テープにデータ･ファイルをセーブします
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
TWRD:
	LD	A,2
	SCF
	RET


;%TRDD（290CH）
;テープのデータ･ファイルをロードします
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
TRDD:
	LD	A,2
	SCF
	RET


;%TDIR（290FH）
;テープのディレクトリを表示します
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
TDIR:
	LD	A,2
	SCF
	RET


;-----------------------
;フィジカル･ルーチン
;-----------------------


;===============================
;フィジカル･ルーチン表示関係
;===============================


;1文字入力ルーチン（入力待ちあり、エコー･バックあり、カーソル表示あり）
;入力	なし
;出力	Acc←文字
;破壊	AF，HL，DE，BC
input_one_character_entity:
	CALL	display_cursol
	CALL	_INKEY
	PUSH	AF
	CALL	erase_cursol
	POP	AF
	RET


;===============================
;フィジカル･ルーチン入力関係
;===============================


;文字列入力ルーチン（入力待ちあり、エコー･バックあり、カーソル表示あり）
;入力	DE←入力バッファの先頭アドレス
;出力	[DE～]←入力文字列
;破壊	AF，HL，DE，BC
;注：
; ブレイク･キーが押された場合、入力バッファの先頭に、1BH（，00H）が入ります。
; リターン･キー（0DH）は含まれません。
; 文字列の最後には00Hが入ります。
; バッファは256バイトまで使用します。
; ルーチンの最初と最後で、インサート･モードをクリアします。
; 画面出力時のインサート処理は、高速化のため、このルーチンで処理します。
input_line_character_entity:
	XOR	A
	LD	(insert_mode_flag),A	;[insert_mode_flag]のクリア
	PUSH	DE

GTLP:	CALL	_FLGET
	CP	0DH	;CR
	JR	Z,GTCR
	CP	03H	;^C
	JR	Z,GTBRK
	CP	1BH	;ESC
	JR	Z,GTBRK
	CP	09H	;TAB
	JR	Z,GTTAB
	CALL	GTINS
	CALL	_PRINT
	JR	GTLP

;	ブレイクしました
GTBRK:	CALL	_PRINT
	POP	DE
	LD	A,1BH
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	RET

;	1行入力がありました
GTCR:	POP	DE
	CALL	INPUTL	;カーソル位置は論理行の最後の物理行へ
	XOR	A
	LD	(insert_mode_flag),A
	JP	_LTNL	;改行します

;	タブ処理
GTTAB:	LD	A,(_WIDTH)
	LD	C,A	;C←桁数
	LD	A,(CSRNX)
	ADD	A,C	;Acc←x座標
	LD	B,A	;B←x座標
	AND	11111000B
	ADD	A,8	;Acc←次のタブ位置（仮）
	CP	C
	JR	C,$+3
	LD	A,C	;Acc←次のタブ位置（実際）
	SUB	B	;Acc←次のタブ位置-x座標
	LD	B,A	;B←表示スペース数
	LD	A,' '

GTTLP:	PUSH	BC
	CALL	GTINS
	POP	BC
	DJNZ	GTTLP

	LD	A,09H	;TAB
	CALL	_PRINT
	JR	GTLP

;	インサート･モードなら、1文字インサートします
GTINS:	CP	20H
	RET	C	;コントロール･コードだった
	LD	C,A
	LD	A,(insert_mode_flag)
	OR	A
	LD	A,C
	RET	Z	;インサート･モードでなかった

;	インサート･モードだった
	PUSH	AF

;	初期設定
	LD	A,(_WIDTH)
	LD	L,A
	LD	H,0
	LD	(line_length),HL
	LD	A,(_MXLIN)
	LD	L,0
	LD	H,A
	LD	(final_plus_one_cursol_XY),HL
	CALL	CUROFS
	LD	(offset_plus_one_cursol_XY),HL
	CALL	GETLNL
	LD	(next_cursol_XY_top_of_next_logical_line),HL
	CALL	CUROFS
	LD	(next_cursol_offset_top_of_next_logical_line),HL
	CALL	_CSR
	LD	(now_cursol_XY),HL
	CALL	CUROFS
	LD	(now_cursol_offset),HL
	LD	HL,(next_cursol_offset_top_of_next_logical_line)
	DEC	HL	;HL←行末のカーソル･オフセット
	CALL	read_character_offset_address
	LD	(line_end_character),A
	SUB	' '	;0，0以外
	ADD	A,0FFH	;CY＝0， CY＝1
	SBC	A,A	;00H，FFH
	LD	(cursol_line_end),A
	LD	DE,(now_cursol_offset)
	LD	HL,(next_cursol_offset_top_of_next_logical_line)
	DEC	HL	;HL←行末のカーソル･オフセット
	OR	A
	SBC	HL,DE
	LD	A,H
	OR	L	;0以外，0
	ADD	A,0FFH	;CY＝1，CY＝0
	SBC	A,A	;FFH，00H
	CPL		;00H，FFH
	LD	HL,cursol_line_end
	OR	(HL)
	LD	(HL),A

;	転送します
	LD	DE,(now_cursol_offset)
	LD	HL,(next_cursol_offset_top_of_next_logical_line)
	DEC	HL	;HL←行末のカーソル･オフセット
	OR	A
	SBC	HL,DE
	LD	C,L
	LD	B,H	;BC←転送文字数
	LD	HL,(now_cursol_offset)	;HL←転送元カーソル･オフセット
	LD	E,L
	LD	D,H
	INC	DE	;DE←転送先カーソル･オフセット
	JR	Z,$+5
	; CALL	VBTRNS
	CALL	_CSR
	CALL	CUROFS
	LD	A,' '
	CALL	write_character_offset_address
	LD	A,(cursol_line_end)
	OR	A
	JR	NZ,$+4
	POP	AF
	RET

;	1物理行を注入する必要がある場合
	LD	A,(_MXLIN)
	LD	HL,next_cursol_XY_top_of_next_logical_line+1
	SUB	(HL)	;Acc←画面残り物理行数
	JR	Z,GTIRU	;論理的に綱がっている最終物理行が、画面最終物理最終行と等しい
	DEC	A
	JR	Z,write_new_line	;論理的に綱がっている最終物理行が、画面最終物理行の上の行
;	ライン･ターミナル･テーブルの転送
	LD	C,A
	LD	B,0	;BC←転送行数－1
	LD	HL,next_cursol_XY_top_of_next_logical_line+1
	ADD	A,(HL)
	LD	E,A
	LD	D,LINTTB/100H	;DE←転送先
	LD	L,E
	LD	H,D
	DEC	L	;HL←転送元
	LDDR
	EX	DE,HL
	LD	(HL),B	;新行と次の行の連結解除
;	画面の転送
	LD	DE,(next_cursol_offset_top_of_next_logical_line)
	LD	HL,(offset_plus_one_cursol_XY)
	OR	A
	SBC	HL,DE
	LD	DE,(line_length)
;	OR	A
	SBC	HL,DE
	LD	C,L
	LD	B,H	;BC←転送バイト数
	LD	HL,(next_cursol_offset_top_of_next_logical_line)
	EX	DE,HL	;HL←[line_length]，DE←[next_cursol_offset_top_of_next_logical_line]
	ADD	HL,DE
	EX	DE,HL	;HL←転送元，DE←転送先
	; CALL	VBTRNS

;	新行を書き込みます
write_new_line:	LD	HL,(next_cursol_offset_top_of_next_logical_line)
	LD	BC,(line_length)
	LD	A,' '
	; CALL	FILVRM
write_new_line_1:	LD	HL,next_cursol_XY_top_of_next_logical_line+1
	LD	L,(HL)
	DEC	L
	LD	H,LINTTB/100H
	LD	(HL),0FFH	;新物理行と前の物理行を連結
	LD	HL,(next_cursol_offset_top_of_next_logical_line)
	LD	A,(line_end_character)
	CALL	write_character_offset_address
	POP	AF
	RET

;	論理的に綱がっている最終物理行が、画面最終物理最終行と等しい場合
GTIRU:	CALL	ROLUP
	LD	HL,(now_cursol_XY)
	DEC	H
	JP	M,$+6
	CALL	_LOC
	LD	HL,(next_cursol_XY_top_of_next_logical_line)
	DEC	H
	LD	(next_cursol_XY_top_of_next_logical_line),HL
	CALL	CUROFS
	LD	(next_cursol_offset_top_of_next_logical_line),HL
	JR	write_new_line_1

line_end_character:	DS	1	;行末の文字
cursol_line_end:	DS	1	;＝FFH（≠0）で行末の文字がスペースでないか、カーソルが行末にあります
line_length:	DS	2	;1行の桁数
now_cursol_XY:	DS	2	;現在カーソル座標
now_cursol_offset:	DS	2	;現在カーソル･オフセット
next_cursol_XY_top_of_next_logical_line:	DS	2	;次の論理行頭カーソル座標
next_cursol_offset_top_of_next_logical_line:	DS	2	;次の論理行頭のカーソル･オフセット
final_plus_one_cursol_XY:	DS	2	;最終＋1のカーソル座標
offset_plus_one_cursol_XY:	DS	2	;最終＋1のカーソル･オフセット


;=======================================
;フィジカル･ルーチン･プリンタ関係
;=======================================


;プリンタ出力モードをオンします
;入力	なし
;出力	[_LPSW]←1
;破壊	AF，HL，DE，BC
;注：旧X1版SWORDと同じく、[#LPSW]に1を書きます。
printer_output_mode_on_entity:
	LD	A,1
	LD	(_LPSW),A

;	#PRINT（1FF4H）のため'
	LD	HL,LPPR
	LD	(_PRINT+1),HL
	LD	HL,LPPR
	LD	(BPRNT+1),HL

	RET


;プリンタ出力モードをオフします
;入力	なし
;出力	[_LPSW]←0
;破壊	AF，HL，DE，BC
printer_output_mode_off_entity:
	XOR	A
	LD	(_LPSW),A

;	#PRINT（1FF4H）のため'
	LD	HL,PRINT
	LD	(_PRINT+1),HL
	LD	HL,BPRNT0
	LD	(BPRNT+1),HL

	RET


;1文字プリント前処理
LPREB:
	PUSH	HL
	CALL	SETADR
	LD	HL,PRINT
	LD	(_PRINT+1),HL
	LD	HL,BPRNT0
	LD	(BPRNT+1),HL
	POP	HL
;	JP	LPPR


;#LPSW（1F7CH）がオンなら、通常表示ルーチンと置き代わります
LPPR:
	CALL	PRINT
	PUSH	AF
	CALL	_LPRNT
	POP	AF
	RET


;===============================
;フィジカル･ルーチン補助
;===============================


;1行入力します
;入力	DE←バッファのアドレス
;出力	[DE～]←入力文字列
;	カーソルを論理的に綱がっている最後の物理行へ
;破壊	AF，HL，DE，BC
;注：
; 文字列の最後には00Hが入ります。
; バッファは256バイトまで使用します。
INPUTL:
	PUSH	DE	;スタック←入力バッファ

;	一時バッファのクリア
	LD	HL,BUFFER
	LD	DE,BUFFER+1
	LD	BC,255
	LD	(HL),B
	LDIR

;	読み出しアドレスの設定
;出力	DE←現在行の行頭のカーソル･オフセット、BC←現在行の最大文字数
	CALL	GETLHD	;論理行頭の座標を得ます
	CALL	CUROFS
	EX	DE,HL	;DE←現在行の行頭のカーソル･オフセット
	CALL	GETLNL	;次の論理行の座標を得ます
	DEC	H
	CALL	_LOC	;カーソルを論理的に綱がっている最後の物理行へ
	INC	H
	CALL	CUROFS
	OR	A
	SBC	HL,DE
	LD	C,L
	LD	B,H	;BC←現在行の最大文字数

;	一時バッファへ転送します
;入力	DE←現在行の行頭のカーソル･オフセット、BC←現在行の最大文字数
	LD	A,B
	OR	A
	JR	Z,$+5
	LD	BC,255
	LD	HL,BUFFER
	; CALL	INVRM

;	ターミネート処理
; 後ろの00H～20Hの文字は00Hに変換します。
	LD	HL,BUFFER+100H
	LD	BC,0	;B←ループ･カウンタ256，C←ターミネータ00H
INLLP1:	DEC	HL
	LD	A,(HL)
	CP	21H
	JR	NC,INL1ES	;21H～の文字を発見しました
	LD	(HL),C
	DJNZ	INLLP1
INL1ES:

;	入力バッファに転送します
	LD	HL,BUFFER
	POP	DE	;DE←入力バッファ
INLLP2:	LD	A,(HL)
	INC	HL
	LD	(DE),A
	INC	DE
	OR	A
	JR	NZ,INLLP2

	JP	SETPRN


;リアル･タイム･ジョイスティック入力（入力待ちなし、エコー･バックなし、カーソル表示なし）
;入力	[JOYFLG]参照
;出力	Acc←アスキー･コード
;破壊	AF，HL，DE，BC
;〈入力のフォーマット（正論理）〉
;0,0,B,A,→,←,↓,↑
GETJOY:
	RET

;	スティックをチェック
GETJY1:	LD	A,E	;Acc←ジョイスティック･データ
	RET


;ジョイスティックを読みます
;入力	なし
;出力	Acc←フィジカル･データ（ビットが1でオン）
;破壊	AF，HL，DE，BC
;〈入出力のフォーマット（正論理）〉
;0,0,B,A,→,←,↓,↑
GETJYF:
	RET


;=======================
;1文字表示ルーチン
;=======================


;^R インサート･モードのオン／オフ
CTLINS:
	RET


;^＠ 何もしません
CTLNUL:
	RET


;^I TAB タブ処理
;〈レジスタ･マップ〉
;HL	CSRNX
;D	[_WIDTH]
;E	定数00000111B
;C	現在x負座標
CTLTAB:
	RET

;	最終桁の場合
CTLTAE:


;^L CLR 画面クリア
;注：フィジカル･ルーチンCLS（AF，HL，DE，BC破壊）を呼び出します。
CTLCLS:
;	行連結情報のクリア
;	画面のクリア
	CALL	CLS
;	JP	CTLHOM


;^K HOME カーソル･ホーム位置
CTLHOM:
	RET


;^￥ → カーソル右移動
CTLRHT:
	RET


;^］ ← カーソル左移動
CTLLFT:
	RET


;^＾ ↑ カーソル上移動
CTLUP:
	RET


;^＿ ↓ カーソル下移動
CTLDWN:
	RET


;^S スクロール･アップします
ROLUP:
	RET

;^T スクロール･ダウンします
ROLDWN:
	RET

;^C STOP カーソルを次の行の行頭へ（論理改行）
CTLCAN:
	RET

;^M CR カーソルを次の行の行頭へ（物理改行）
CTLCR:
	RET

;^H BS バック･スペース
CTLBS:
	RET

;7EH DEL デリート･コード
CTLDEL:
	RET

;^E カーソル位置から行末までクリア
CTL05:
	RET


;^A カーソルを論理行頭へ（－^V）
CTL01:
	RET

;---------------
;独自ルーチン
;---------------


;=======================
;表示ルーチン前処理
;=======================


;表示ルーチンを初期飛び先へジャンプするように設定します
;入力	なし
;出力	なし
;破壊	HL
SETPRN:
	RET


;=======================
;スクリーン制御補助
;=======================


;論理桁位置を得ます
;入力	x座標、桁数参照
;出力	HL←論理桁位置
;破壊	AF，HL，DE，BC
;〈レジスタ･マップ〉
;E	桁数
;C	現在y座標
;BC	ライン･ターミナル･テーブルの先頭＋y座標
;HL	論理桁位置カウンタ
GTPRC0:
	RET

;論理行頭の座標を得ます
;入力	なし
;出力	L←0、H←論理行頭のy座標
;破壊	AF，HL
GETLHD:
	RET


;次の論理行の座標を得ます
;入力	なし
;出力	L←0、H←論理行頭のy座標
;破壊	AF，HL
GETLNL:
	RET


;カーソル座標からオフセット･アドレスを求めます
;入力	L←x座標、H←y座標
;出力	HL←オフセット
;破壊	AF，HL
;注：cursol_offset_for_Y_tableは、y座標→カーソル･オフセット対応表。
CUROFS:
	RET


;オフセット･アドレスからカーソル座標を求めます
;入力	HL←カーソル･オフセット
;出力	L←x座標,H←y座標
;破壊	AF，HL
OFSCUR:
	RET


;カーソルのオフセット計算用テーブルを生成します
;入力	[_WIDTH]参照
;出力	[cursol_offset_for_Y_table～]←オフセット
;破壊	AF，HL，DE，BC
;〈レジスタ･マップ〉
;DE	テーブル･アドレス
;BC	定数[_WIDTH]
;HL	カーソル･オフセット
;Acc	ループ･カウンタ
COFINI:
	RET


;カーソル制御用ワークの初期化
;入力	[_WIDTH]、[_WIDTH]、[_MXLIN]、[vram_address_of_top]参照
;出力	[CSRADD]、[CSRNXI]、[CSRNYI]、[cursol_offset_last_top_of_line]、[total_number_of_character_display]、[vram_address_of_top_of_last_line]、
;	ライン･ターミナル･テーブル初期化
;破壊	AF，HL，DE，BC
INICUR:
	RET


;-------------------------------
;S-OSルーチン（機種依存）
;-------------------------------


;===============
;I／O入出力
;===============


;#INP（202AH）の本体
; I／Oポートにデータを出力。
;入力	なし
;出力	Acc←データ
;破壊	AF
INP:
	PUSH BC
	LD	B,0
	IN	A,(C)
	POP	BC
	RET


;#OUT（202DH）の本体
; I／Oポートからデータを入力。
;入力	Acc←データ
;出力	なし
;破壊	なし
OUTP:
	PUSH BC
	LD	B,0
	OUT	(C),A
	POP	BC
	RET


;=======================
;特殊ワーク（機種依存）
;=======================


;#POKE（1F9AH）の本体
; 特殊ワーク･エリアに1バイト書き込みます。
;入力	HL←アドレス、Acc←データ
;出力	なし
;破壊	なし
;〈旧SWORDとの速度比較〉
;POKE	 97ts→ 83ts	1.169倍
;#POKE	107ts→ 93ts	1.151倍
;＋CALL	124ts→110ts	1.127倍
POKE:
	PUSH	BC	;11ts
	PUSH	AF	;11ts
	LD	C,L	; 4ts
	LD	A,40H	; 7ts '特殊ワーク先頭（4000H）
	ADD	A,H	; 4ts 'CY←0
	LD	B,A	; 4ts 'BC←実アドレス
	POP	AF	;10ts
	OUT	(C),A	;12ts '特殊ワークへの書き込み
	POP	BC	;10ts
	RET		;10ts


;#PEEK（1F94H）の本体
; 特殊ワーク･エリアから1バイト読み込みます。
;入力	HL←アドレス
;出力	Acc←データ
;破壊	AF
;〈旧SWORDとの速度比較〉
;POKE	109ts→ 62ts	1.758倍
;#POKE	119ts→ 72ts	1.653倍
;＋CALL	136ts→ 89ts	1.528倍
;注：CYをクリアします。
PEEK:
	PUSH	BC	;11ts
	LD	C,L	; 4ts
	LD	A,40H	; 7ts '特殊ワーク先頭（4000H）
	ADD	A,H	; 4ts 'CY←0
	LD	B,A	; 4ts 'BC←実アドレス
	IN	A,(C)	;12ts '特殊ワークからの読み込み
	POP	BC	;10ts
	RET		;10ts


;#poke_entity（1F97H）の本体
; 特殊ワーク･エリアにブロック書き込みします。
;入力	HL←メモリ先頭アドレス、DE←特殊ワーク先頭アドレス、
;	BC←転送バイト数
;出力	なし
;破壊	AF，HL，DE，BC
;〈旧SWORDとの速度比較〉
;ループ	 57ts→ 40ts	1.425倍
;注：「WINER」などでCYクリアが必要。
poke_entity:
	LD	A,40H	;特殊ワーク先頭（4000H）
	ADD	A,D	;CY←0
	LD	D,A
	PUSH	DE

;	高速ループ･カウンタの設定（BC→AD版）
	XOR	A
	CP	C	;下位カウンタ＝0ならCY＝0
	ADC	A,B	;Acc←新上位ループ･カウンタ
	LD	D,C	;D←下位ループ･カウンタ

	POP	BC	;BC←実アドレス

POKE_LP:	INC	B	; 4ts '先行デクリメントのため
	OUTI		;16ts '特殊ワークへの書き込み
	INC	BC	; 6ts
	DEC	D	; 4ts
	JP	NZ,POKE_LP	;10ts
	DEC	A
	JR	NZ,POKE_LP

;	OR	A	;CY←0
	RET


;#peek_entity（1F91H）の本体
; 特殊ワーク･エリアからブロック読み込みします。
;入力	HL←メモリ先頭アドレス、DE←特殊ワーク先頭アドレス、
;	BC←転送バイト数
;出力	なし
;破壊	AF，HL，DE，BC
;〈旧SWORDとの速度比較〉
;ループ	 57ts→ 40ts	1.425倍
;注：「WINER」などでCYクリアが必要。
peek_entity:
	LD	A,40H	;特殊ワーク先頭（4000H）
	ADD	A,D	;CY←0
	LD	D,A
	PUSH	DE

;	高速ループ･カウンタの設定（BC→AD版）
	XOR	A
	CP	C	;下位カウンタ＝0ならCY＝0
	ADC	A,B	;Acc←新上位ループ･カウンタ
	LD	D,C	;D←下位ループ･カウンタ

	POP	BC	;BC←実アドレス

PEEK_LP:	INC	B	; 4ts '先行デクリメントのため
	INI		;16ts '特殊ワークからの読み込み
	INC	BC	; 6ts
	DEC	D	; 4ts
	JP	NZ,peek_lp	;10ts
	DEC	A
	JR	NZ,peek_lp

;	OR	A	;CY←0
	RET


;---------------------------------------
;フィジカル･ルーチン（機種依存）
;---------------------------------------


;===============================
;システム･ルーチン（機種依存）
;===============================


;コールド･スタート時の固有の初期化
; 特殊ワークとRAMディスクの情報の初期化をします。
;入力	なし
;出力	なし
;破壊	全レジスタ
 cold_start_entity:
	DI
	IM	2
	LD	HL,KEYINT	;キー入力割り込み処理エントリ
	LD	(0052H),HL	;X1モニタと同じ
	LD	BC,1A03H
	LD	A,10000010B	;モード0（A出力、B入力、C出力）
	OUT	(C),A
	DEC	C	;BC←1A02H
	IN	A,(C)
	LD	A,01110000B
	OUT	(C),A
	DEC	C	;BC←1A01H
	IN	A,(C)	;？
	XOR	A
	LD	(RESMOD),A
	CALL	CRTINI	;CRTCを初期化します
	CALL	PRIINI	;プライオリティを初期化します
	; CALL	PSGINI	;PSGを初期化します
	; CALL	SCPUIN	;サブCPUを初期化します
	LD	A,00H	;割り込み処理ルーチンのテーブル
	EI
	LD	I,A
;
	LD	A,0E4H	;キー入力割り込みベクタのセット
	; CALL	SCPUTR	;データ送信（Z80→サブCPU）
	LD	A,52H	;キー入力割り込みベクタ
	; CALL	SCPUTR	;データ送信（Z80→サブCPU）

;	スタックの設定など
	LD	HL,0FFFFH
	LD	(_MEMAX),HL	;使用可能メモリの上限
	LD	HL,system_stack_area
	LD	(_STKAD),HL

;	「SWEMDIO2」のワークの初期化
;	LD	A,(VDPR)
;	LD	(DIOVDR),A
;	LD	A,(VDPW)
;	LD	(DIOVDW),A
	LD	HL,(top_of_ram_disk_of_vram)
	LD	(DIOETP),HL	;RAMディスクのVRAMアドレス先頭（256バイト単位）

;	特殊ワークのサイズの初期化
	LD	A,(size_of_special_work_of_vram)
	LD	L,0
	LD	H,A	;HL←特殊ワークのサイズ
	LD	(_WKSIZ),HL	;[_WKSIZ]の初期化

;	RAMディスクのクラスタ数の初期化
	; LD	HL,(size_of_ram_disk_of_vram)	;HL←VRAM上のRAMディスクのサイズ÷100H
	; LD	A,10H	;1000H '4Kバイト
	; CALL	DIV68
	; LD	A,L	;Acc←RAMディスクのクラスタ数
	; LD	(_ETRK),A	;[_ETRK]の初期化

;	文字色の初期化
	LD	A,7
	LD	(foreground_color),A
	LD	A,0
	LD	(background_color),A
	LD	A,0
	LD	(BDRCLR),A
	CALL	change_color

;	グラフィック、オフ
	XOR	A
	LD	(GRAFLG),A
	DI
	CALL	GRAONF	;グラフィック表示をオン、オフします
	EI

;	ディスクI／O初期化
	CALL	SOSSI

;	キー入力バッファのクリア
	DI
	CALL	clear_key_buffer
	EI

	RET
	DS	3

;コールド･スタート時のメッセージ
TTLMSG:	DB	'<<<<< S-OS  SWORD >>>>>',0DH
	DB	'SWX1TC V1.10  1994-06-29',0DH
	DB	'Programmed by Takahiro Chikushi & Oh!X(Oh!MZ)',0DH
	DB	'MAIN		(C)T.Chikushi	1994-06-29',0DH
	DB	'DOS MODULE	(C)T.T. 	1985-10-25',0DH
	DB	'RUN&SUBMIT	(C)TITY SOFT	1987-02-22',0DH
	DB	'DISK I/O	Oh!MZ 1987-02	?',0DH
	DB	'RAM DISK I/O	(C)T.T.		1987-03-02',0DH
	DB	00H


;ブートします
;入力	なし
;出力	なし
;破壊	AF，HL，DE，BC
boot_entity:
	CALL	SOSSF		;仮想ディスク全クローズ

	LD	HL,00D3H	;「OUT (0),A」
	LD	(0FFFEH),HL
	LD	A,1DH
	JP	0FFFEH


;Hに機種別情報、LにS-OSのバージョンを返します
;入力	なし
;出力	H←機種別情報、L←S-OSのバージョン
;破壊	AF，HL，DE，BC
 vertion_entity:
	LD	HL,9520H	;SORD M23，S-OS V2.0
	RET


;===============================================
;フィジカル･ルーチン･プリンタ関係（機種依存）
;===============================================


;プリンタへ1文字出力します
;入力	Acc←文字
;出力	エラーが起こればCY＝1
;破壊	AF
lprint_entity:
	PUSH	HL
	PUSH	BC
	LD	L,A	;L←文字（保存用）
	LD	H,A	;H←文字
	LD	BC,1A01H

;	プリンタREADYを待ちます
lplp_entity:	IN	A,(C)
	RRCA
	JR	NC,lpbrk_entity	;^C
	IN	A,(C)
	AND	00001000B
	JR	NZ,lplp_entity

	OR	A	;CY←0

;	文字を出力
;注：CYは保存します。
lp1_entity:	DEC	C	;BC←1A00H
	OUT	(C),H
;	受け取り指示
	LD	C,3	;BC←1A03H
	LD	A,00001110B	;b7リセット
	OUT	(C),A
	INC	A	;b7セット
	OUT	(C),A

;	終了
	LD	A,L	;Acc←文字
	POP	BC
	POP	HL
	RET

;	^C処理
lpbrk_entity:	LD	H,0DH	;RET
	SCF
	JR	lp1_entity


;=======================
;音声（機種依存）
;=======================


;ビープ音を鳴らします
;入力	なし
;出力	なし
;破壊	AF，HL，DE，BC
bell_entity:
	DI
	EI
	RET

;クリック音を鳴らします
;入力	[CLKFLG]参照
;出力	なし
;破壊	AF，HL，DE，BC
;注：割り込み禁止して実行してください。
CLICK:
	RET


;===============================
;スクリーン関係（機種依存）
;===============================


;カーソル座標を読み出します
;入力	なし
;出力	L←x座標、H←y座標
;破壊	AF，HL，DE，BC
get_cursol_XY_entity:
	LD	DE,(CSRADD)
	LD	HL,(CSRNX)
	ADD	HL,DE
	RET

;カーソルを指定座標へ移動します
;入力	L←x座標、H←y座標
;出力	なし
;破壊	AF，HL，DE，BC
move_cursol_XY_entity:
	LD	DE,(CSRNXI)
	ADD	HL,DE
	LD	(CSRNX),HL
	JP	SETPRN


;指定座標の文字を読み込みます
;入力	L←x座標、H←y座標
;出力	Acc←文字
;破壊	AF，HL，DE，BC
get_character_XY_entity:
	CALL CUROFS
	JP read_character_offset_address


;桁数と行数を表示可能な値に変更します
;入力	L←桁数、H←行数
;出力	L←修正された桁数、H←修正された行数
;破壊	AF，HL，DE，BC
;〈修正された桁数、行数〉
;桁数	40，80
;行数	25
WLCHK:
	LD	A,40
	CP	L	;桁数0～40→CY＝0、桁数41～255→CY＝1
	JR	NC,$+3
	ADD	A,A	;Acc←80
	LD	L,A
	LD	H,25	;25行固定
	RET


;表示桁数を変更します
;入力	[_WIDTH]、[_MXLIN]、[screen_width]、[RESFLG]参照
;出力	なし
;破壊	AF，HL，DE，BC
change_width_entity:
	DI
	EI
	RET


;表示行数を変更します
;入力	[_WIDTH]、[_MXLIN]、[screen_width]参照
;出力	なし
;破壊	AF，HL，DE，BC
change_line_number:
	CALL	INICUR
	JP	SETPRN


;画面のクリア
;入力	[screen_width]、[total_number_of_character_display]、[attribute_data]参照
;出力	なし
;破壊	AF，HL，DE，BC
;〈レジスタ･マップ〉
;E	クリア･データ（定数）
;BC	現在アトリビュートVRAMアドレス
;AD	高速ループ･カウンタ
CLS:
	RET

;===============================
;表示ルーチン前処理（機種依存）
;===============================


;表示ルーチンを初期化します
;入力	なし
;出力	なし
;破壊	HL
INIPRN:
	RET


;カーソル位置へ書き込める状態にする前処理
;入力	[CSRADD]、[CSRNX]参照
;出力	なし
;破壊	F，HL
; [#LPSW]がオンならプリンタにも出力。
;注：
; インサート･モードと論理改行は、1行入力ルーチンで制御します。
SETADR:
	RET


;===============================
;1文字表示ルーチン（機種依存）
;===============================


;コントロール･コード制御（PRINTルーチンの一部）
;入力	Acc←コントロール･コード（00H～1FH）
PRNCTL:
	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	HL,CTLTBL
	ADD	A,A	;Acc←コントロール･コード×2
	ADD	A,L
	LD	L,A	;HL←CTLTBL＋コントロール･コード×2
	LD	A,(HL)
	INC	L
	LD	H,(HL)
	LD	L,A	;HL←[CTLTBL＋コントロール･コード×2]

	LD	DE,PRCRET
	PUSH	DE	;リータン･アドレスの設定
	JP	(HL)	;「CALL コントロール制御」相当
PRCRET:	CALL	SETPRN
	POP	BC
	POP	DE
	POP	HL
	POP	AF
	OR	A	;CY←0
	RET

;1文字プリント前処理
PREPR:	PUSH	HL
	CALL	SETADR
	CALL	INIPRN
	POP	HL

;#PRINT（1FF4H）本体
; 1文字プリント･ルーチン。
;入力	Acc←文字
;出力	なし
;破壊	F
;注：
; [#LPSW]がオンならプリンタにも出力します。
; インサート･モードと論理改行は、1行入力ルーチンで制御します。
; CYフラグをクリアします。
;〈実行時間〉
;PRINT	149ts（37.250μs）
;#PRINT	159ts（39.750μs）
;＋CALL	176ts（44.000μs）
PRINT:
	CP	20H	; 7ts
	JR	C,PRNCTL	; 7ts 'コントロール･コード

PRNPA0:
	PUSH	HL	;11ts
	PUSH	BC	;11ts
	LD	L,A	; 4ts
	LD	H,LSXTBL/100H	; 7ts
	DB	01H	;10ts '「LD BC,n」
TXTADR:
	DS	2	;3000H～37FFH
	INC	B	; 4ts
	OUTI		;16ts
	INC	BC	; 6ts
	LD	(TXTADR),BC	;14ts '[TXTADR]のカウント･アップ
	LD	HL,CSRNX	;10t
	INC	(HL)	;11t '[CSRNX]のカウント･アップ
	POP	BC	;10ts
	POP	HL	;10ts
	RET	NZ	;11ts

;	最終桁の場合
	PUSH	AF
	PUSH	HL
	LD	HL,CSRNX
	LD	A,(CSRNXI)
	LD	(HL),A	;カーソルを行頭へ
	INC	L	;HL←CSRNY
	LD	A,(_MXLIN)
	ADD	A,(HL)	;Acc←y座標 '（y座標－行数）＋行数
	LD	L,A
	LD	H,LINTTB/100H	;HL←対応するターミナル･テーブルのアドレス
	LD	(HL),0FFH	;行を連結します
	LD	HL,CSRNY
	INC	(HL)	;[CSRNY]のカウント･アップ
	JR	Z,PRNLL	;最終行だった
	POP	HL
	POP	AF
	RET

;	最終行の場合
PRNLL:
	LD	(HL),0FFH	;最終行
	PUSH	DE
	PUSH	BC
	CALL	ROLUP
	CALL	SETADR
	POP	BC
	POP	DE
	POP	HL
	POP	AF
	RET


;===============================
;文字列表示ルーチン（機種依存）
;===============================


;ブロック表示ルーチン前処理
PREBP:
	CALL	SETADR
	CALL	INIPRN

;文字のブロック表示（非コントロール･コードのみ表示します）
;入力	DE←文字列の先頭アドレス
;出力	DE←次の文字の位置
;破壊	AF，HL，DE，BC
;〈レジスタ･マップ〉
;SP	現在文字列のアドレス
;E	文字読み込み1
;D	文字読み込み2
;BC	現在テキストVRAMアドレス
;HL	現在文字変換テーブルのアドレス
;IXL	ループ･カウンタ
;IXH	定数桁数÷2（ループ用）
;Acc	定数20H－1（コントロール･コード･チェック用）
;注：
; プリンタには出力しません。
; インサート･モードと論理改行は、1行入力ルーチンで制御します。
; [number_of_character_after_CR]は無視します。
; 桁数は、必ず偶数であること。
;〈実行時間〉
;最内ループ53ts（13.250μs）
BPRNT0:
	PUSH	IX
;	共通の設定
	LD	A,(_WIDTH)
	SRL	A
	DB	0DDH
	LD	H,A	;「LD IXH,A」 'IXH←桁数÷2 '定数
	LD	BC,(TXTADR)	;BC←現在テキストVRAMアドレス
	LD	(BPRRSP),SP
;	最初の行の設定
	LD	A,(CSRNX)
	CPL
	ADD	A,2	;Acc←現在行の残り文字数＋1，CY←0
	RRA		;Acc←現在行の残り文字数÷2切り上げ，CY←端数の反転
	DB	0DDH
	LD	L,A	;「LD IXL,A」 'IXL←初期ループ･カウンタ
	EX	DE,HL
	DI
	LD	SP,HL	;SP←文字列の先頭
	LD	H,LSXTBL/100H	;HL←文字変換テーブルのアドレス
	LD	A,20H-1	;コントロール･コード･チェック用
	JR	C,BPRL12
;	端数処理
	DEC	SP
	POP	DE	;D←最初の文字
	JR	BPRL1J

BPRL11:
	DB	0DDH
	LD	L,H	;「LD IXL,IXH」 'IXL←ループ･カウンタ（桁数÷2）
	LD	H,LSXTBL/100H	;HL←文字変換テーブルのアドレス
	LD	A,20H-1	;コントロール･コード･チェック用

;	1ループ106ts（53ts×2）
BPRL12:
	POP	DE	;10ts
	CP	E	; 4ts
	JR	NC,BPRRE1	; 7ts 'コントロール･コードがきました
	LD	L,E	; 4ts
	LD	E,(HL)	; 7ts
	OUT	(C),E	;12ts
	INC	C	; 4ts
BPRL1J:
	CP	D	; 4ts
	JR	NC,BPRRE2	; 7ts 'コントロール･コードがきました
	LD	L,D	; 4ts
	LD	D,(HL)	; 7ts
	OUT	(C),D	;12ts
	INC	BC	; 6ts
	DB	0DDH
	DEC	L	; 8ts
	JP	NZ,BPRL12	;10ts

	LD	HL,CSRNX
	LD	A,(CSRNXI)
	LD	(HL),A	;カーソルを行頭へ
	INC	L	;HL←CSRNY
	LD	A,(_MXLIN)
	ADD	A,(HL)	;Acc←y座標 '（y座標－行数）＋行数
	LD	L,A
	LD	H,LINTTB/100H	;HL←対応するターミナル･テーブルのアドレス
	LD	(HL),0FFH	;行を連結します
	LD	HL,CSRNY
	INC	(HL)	;[CSRNY]のカウント･アップ
	JR	NZ,BPRL11

;	最終行の場合
	LD	(HL),0FFH	;最終行
	LD	(BPRLSP),SP
	EI
	LD	SP,(BPRRSP)
	CALL	ROLUP
	LD	BC,(vram_address_of_top_of_last_line)	;BC←最終行先頭のVRAMアドレス
	DI
	DB	31H	;「LD SP,n」
BPRLSP:
	DS	2
	JR	BPRL11

;	コントロール･コードがきた場合（偶数）
BPRRE1:
	XOR	A
	DB	0DDH
	SUB	L	;「SUB IXL」
	DB	0DDH
	SUB	L	;「SUB IXL」 'Acc←x座標－桁数
	LD	HL,-2
	JR	BPRRET
;	コントロール･コードがきた場合（端数）
BPRRE2:
	LD	A,1
	DB	0DDH
	SUB	L	;「SUB IXL」
	DB	0DDH
	SUB	L	;「SUB IXL」 'Acc←x座標－桁数
	LD	HL,-1
BPRRET:
	LD	(TXTADR),BC	;[TXTADR]の更新
	LD	(CSRNX),A	;[CSRNX]を更新
	ADD	HL,SP
	OR	A	;CY←0
	EX	DE,HL	;DE←コントロール･コードのアドレス
	EI
	DB	31H	;「LD SP,」
BPRRSP:
	DS	2
	POP	IX
	RET


;===============================
;キー入力関係（機種依存）
;===============================


;1文字入力ルーチン（入力待ちあり、エコー･バックなし、カーソル表示なし）
;入力	なし
;出力	Acc←アスキー･コード
;破壊	AF，HL，DE，BC
;注：DEL（7FH）コードは、^D（04H）に変換します。
INKEY_entity:

;	キー入力バッファに文字が溜るまで待ちます
INKLP_entity:
	EI
	CALL	INJOY
	OR	A
	RET	NZ
	EI		;念のため
	LD	A,(pointer_for_write_key_buffer)
	OR	A
	JR	Z,INKLP_entity

;	文字入力バッファから1文字取り出します
	LD	HL,pointer_for_write_key_buffer
	DI
	LD	A,(HL)
	OR	A	;念のためもう1度チェック
	JR	Z,INKLP_entity
	DEC	(HL)	;[pointer_for_write_key_buffer]をデクリメントします
	LD	C,(HL)
	LD	B,0	;BC←バッファに溜った文字数－1（0～254）
	LD	E,B
	LD	D,H	;DE←input_key_buffer
	LD	L,1	;HL←input_key_buffer+1
	LD	A,(DE)	;Acc←入力文字
	JR	Z,INKRT
	LDIR
INKRT:
	EI
	RET


;リアル･タイム･キー入力（入力待ちなし、エコー･バックなし、カーソル表示なし）
;入力	なし
;出力	Acc←アスキー･コード
;破壊	AF，HL，DE，BC
;注：ジョイスティック対応。
real_time_input_key_entity:
;	ジョイスティックを読み出します
	CALL	GETJOY
	OR	A
	RET	NZ

	DI
	CALL	clear_key_buffer
	EI
	LD	A,(real_time_key)
	RET


;キー入力バッファをクリアします
;入力	なし
;出力	なし
;破壊	AF，HL，DE，BC
;注：割り込み禁止して実行してください。
clear_key_buffer:
	XOR	A
	LD	(pointer_for_write_key_buffer),A	;キー入力バッファをクリアします
	RET


;※VBLANK版
;ジョイスティック入力（入力待ちなし、エコー･バックなし、カーソル表示なし）
;入力	なし
;出力	Acc←アスキー･コード
;破壊	AF，HL，DE，BC
INJOY:
	CALL	GETJOY

INJY1:	OR	A
	JR	NZ,INJY2

;	入力がなかった
	LD	(OLDJOY),A
	LD	L,A
	LD	H,A	;HL←0
	LD	(JOYREP),HL	;[JOYREP]、[JOYCNT]のクリア
	RET

;	入力があった場合
INJY2:	LD	HL,OLDJOY
	CP	(HL)
	JR	Z,INJY3

;	前回と違うキーが入力された
	LD	(HL),A	;[OLDJOY]←入力キー
	LD	HL,0
	LD	(JOYREP),HL	;[JOYREP]、[JOYCNT]のクリア
	JR	INJRET

;	前回と同じキーが入力されていた
INJY3:	LD	B,A	;B←入力キー
	LD	A,(JOYREP)
	OR	A
	JR	NZ,INJY4

;	リピート中でなかった
	LD	HL,JOYCNT
	INC	(HL)
	LD	A,(HL)
	CP	10	;3分の1秒
	JR	NC,INJY31	;リピート開始
	DI
	CALL	VBLANK
	CALL	VBLANK
	EI
	XOR	A
	RET

;	リピート開始
INJY31:	LD	HL,00FFH
	LD	(JOYREP),HL	;[JOYREP]←FFH、[JOYCNT]←00H

;	前回と同じキーが入力されていて、リピート中だった
INJY4:	PUSH	BC
	DI
	CALL	VBLANK
	CALL	VBLANK
	EI
	CALL	GETJOY
	POP	BC	;B←入力キー
	CP	B
	JR	NZ,INJY1

;	キー入力が有効
INJRET:	PUSH	AF
	DI
	CALL	CLICK	;クリック音を鳴らします
	EI
	POP	AF
	RET

OLDJOY:	DB	0	;旧入力キー
JOYREP:	DB	0	;＝FFHでリピート中
JOYCNT:	DB	0	;リピート開始までのカウンタ（30分の1秒単位）


;===============================
;スクリーン制御補助（機種依存）
;===============================


;指定オフセット･アドレスに文字を書き込みます
;入力	HL←オフセット･アドレス、Acc←文字
;出力	なし
;破壊	AF，HL，DE，BC
write_character_offset_address:
	RET


;指定カーソル･オフセットの文字を読み込みます
;入力	HL←カーソル･オフセット
;出力	Acc←文字
;破壊	AF，HL，DE，BC
read_character_offset_address:
	RET


;カーソルを表示します
;入力	[insert_mode_flag]参照
;出力	[locate_of_cursol_overlap_character]←カーソル位置の文字
;破壊	AF，HL，DE，BC
display_cursol:
	CALL	get_cursol_XY_entity
	CALL	CUROFS
	LD	C,L
	LD	A,20H	;アトリビュートVRAM先頭（2000H）
	ADD	A,H
	LD	B,A	;BC←アトリビュートVRAMアドレス
	IN	A,(C)
	XOR	00001000B	;b3を反転
	LD	L,A
	LD	A,(insert_mode_flag)
	AND	00010000B	;b4
	XOR	L	;[insert_mode_flag]＝FFHなら、ブリンク
	OUT	(C),A
	RET


;カーソルを消去します
;入力	[locate_of_cursol_overlap_character]、[insert_mode_flag]参照
;出力	なし
;破壊	AF，HL，DE，BC
erase_cursol:
	CALL	get_cursol_XY_entity
	CALL	CUROFS
	LD	C,L
	LD	A,20H	;アトリビュートVRAM先頭（2000H）
	ADD	A,H
	LD	B,A	;BC←アトリビュートVRAMアドレス
	IN	A,(C)
	XOR	00001000B	;b3を反転
	AND	11101111B	;b4をクリア
	OUT	(C),A
	RET


;表示色を変更します
;入力	[foreground_color]、[background_color]、[BDRCLR]参照
;出力	[attribute_data]←アトリビュート･データ
;破壊	AF，HL，DE，BC
change_color:
	LD	A,(foreground_color)
	CALL	CCLSUB
	LD	L,A	;L←前景色
	LD	A,(background_color)
	CALL	CCLSUB
	LD	H,A	;H←後景色
	OR	A
	JR	Z,CCLBK0	;背景色が0の場合
	LD	A,H
	CP	7
	JR	Z,CCLBK7	;反転色指定

;	後景色が0の場合
CCLBK0:	LD	A,L
CCLRET:	LD	(attribute_data),A
	RET

;	反転で、色を指定します
CCLBK7:	LD	A,L
	XOR	111B
	OR	1000B	;色反転
	JR	CCLRET

;色コードを0～7に圧縮します
;入力	Acc←色コード
;出力	Acc←色コード（0～7）
;破壊	AF
CCLSUB:	CP	8
	RET	C
	LD	A,7
	RET


;===============================
;スクリーン制御転送（機種依存）
;===============================



;===============================
;ジョイスティック（機種依存）
;===============================


;ジョイスティック1、2を読みます
;入力	なし
;出力	L←ジョイスティック1のフィジカル･データ（ビットが1でオン）、
;	H←ジョイスティック2のフィジカル･データ（ビットが1でオン）、
;破壊	AF，HL，DE，BC
;〈出力のフォーマット（正論理）〉
;0,0,B,A,→,←,↓,↑
;〈X1の生データ（負論理）〉
;0,B,A,0，→,←,↓,↑
;注：割り込み禁止して実行してください。
GETJXF:
	RET

;X1のフォーマットを、MSXのフォーマットに変換します
; 負論理「?BA?RLDU」→正論理「00BARLDU」。
;入力	Acc←X1フォーマットのジョイスティックの生データ（オン＝0）
;出力	Acc←MSXフォーマットのジョイスティックのデータ（オン＝1）
;破壊	AF，BC
GJXFSB:
	RET


;===============================
;グラフィック（機種依存）
;===============================


;グラフィック表示をオン、オフします
;入力	[GRAFLG]参照
;出力	なし
;破壊	AF，HL，DE，BC
;注：割り込み禁止して実行してください。
GRAONF:
	LD	A,(GRAFLG)
	OR	A
	JR	Z,GRAOFF
;	JR	GRAON


;グラフィック表示をオンします
;入力	なし
;出力	なし
;破壊	AF，HL，DE，BC
;注：割り込み禁止して実行してください。
GRAON:
	LD	BC,1000H
	LD	A,10101010B
	OUT	(C),A
	INC	B	;BC←1100H
	LD	A,11001100B
	OUT	(C),A
	INC	B	;BC←1200H
	LD	A,11110000B
	OUT	(C),A
	RET


;グラフィック表示をオフします
;入力	なし
;出力	なし
;破壊	AF，HL，DE，BC
;注：割り込み禁止して実行してください。
GRAOFF:
	LD	BC,1000H
	LD	A,3

GOFLP:	OUT	(C),C
	INC	B
	DEC	A
	JR	NZ,GOFLP

	RET


;GRAMをクリアします
;入力	なし
;出力	なし
;破壊	AF，HL，DE，BC
;〈レジスタ･マップ〉
;BC	現在GRAMアドレス
;H	ループ･カウンタ
;L	クリア･データ00H（定数）
;注：割り込み禁止して実行してください。
GRACLR:
;	同時アクセス･モードにします
	LD	BC,1A03H
	LD	A,00001011B	;b5セット
	OUT	(C),A
	DEC	A	;b5リセット
	OUT	(C),A

;	GRAMをクリアします
	LD	HL,4000H	;H←ループ･カウンタ，L←クリア･データ
	LD	C,L
	LD	B,L	;BC←0000H '同時アクセス･モードGRAM白先頭

;	18.5ts／バイト
GRCLP:	OUT	(C),L	;12ts
	INC	C	; 4ts
	OUT	(C),L	;12ts
	INC	C	; 4ts
	OUT	(C),L	;12ts
	INC	C	; 4ts
	OUT	(C),L	;12ts
	INC	C	; 4ts
	JP	NZ,GRCLP	;10ts
	INC	B
	DEC	H
	JR	NZ,GRCLP

;	同時アクセス･モードを解除します
	IN	A,(C)
	RET


;===============================
;特殊ルーチン（機種依存）
;===============================


;60分の1秒単位で時間待ちします
;入力	Acc←カウンタ
;出力	なし
;破壊	AF
;注：割り込み禁止して実行してください。
WAIT60:
	PUSH	BC
	LD	B,A

W60LP:
	CALL	VBLANK
	DJNZ	W60LP

	POP	BC
	RET


;垂直帰線信号の立ち下がりを待ちます
;入力	なし
;出力	なし
;破壊	AF
;注：割り込み禁止して実行してください。
VBLANK:
; 垂直帰線信号が無効になる場合があるので、CPU実行速度依存に書き直します。
; 1／60秒、66,667ステートの15／16、62,500ステート待ちます。
	PUSH	BC	;11ts
	LD	BC,2402	;10ts

;	1ループ26ts
VBLLP:	DEC	BC	; 6ts
	LD	A,C	; 4ts
	OR	B	; 4ts
	JR	NZ,VBLLP	;12ts

	POP	BC	;10ts
	RET		;10ts


;-----------------------
;機種固有ルーチン
;-----------------------


;===============================
;スクリーン制御補助（機種固有）
;===============================


;カーソルのテキストVRAMアドレスを求めます
;入力	L←x座標、H←y座標
;出力	BC←テキストVRAMアドレス
;破壊	AF，HL，BC
TEXADR:
	CALL	CUROFS
	LD	C,L
	LD	A,30H	;テキストVRAM先頭（3000H）
	ADD	A,H
	LD	B,A	;BC←テキストVRAMアドレス
	RET


;=======================
;CRTC（機種固有）
;=======================


;CRTCのレジスタにデータを書き込みます
;入力	D←レジスタ番号、Acc←値
;出力	Dはカウント･アップされます
;破壊	AF，D
;注：割り込み禁止して実行してください。
WRCRTC:
	PUSH	BC
	LD	BC,1800H
	OUT	(C),D	;レジスタ
	INC	D
	INC	C	;BC←1801H
	OUT	(C),A	;データ
	POP	BC
	RET


;CRTCを初期化します
;入力	[RESMOD]←解像度（0～3）
;	[X1TFLG]、[LRSDAT～]、[HRSDAT～]参照
;出力	[RESFLG]←解像度の状態、turbo以降でなければ[RESMOD]←1
;破壊	AF，HL，DE，BC
;注：割り込み禁止して実行してください。
CRTINI:
;	turbo以降でなければ、強制低解像モード
	LD	A,(X1TFLG)
	OR	A
	JR	NZ,$+6
	INC	A	;Acc←1
	LD	(RESMOD),A

;	40桁モードにします
	LD	A,00001101B	;b6セット
	LD	BC,1A03H
	OUT	(C),A	;画面クロック切り換え

;	解像度の判定
	LD	A,(RESMOD)	;0：スイッチ，1：低解像度，2：高解像度，3：疑似高解像度
	DEC	A
	JR	Z,CRTILW	;低解像度
	DEC	A
	JR	Z,CRTIHG	;高解像度
	DEC	A
	JR	Z,CRTIMD	;疑似高解像度
;
	; CALL	LOKRES
	OR	A
	JR	NZ,CRTIHG	;高解像度

;	低解像度
CRTILW:	LD	DE,0000H
	LD	HL,LRSDAT
	JR	CRISUB

;	疑似高解像度
CRTIMD:	LD	DE,0004H	;16ラスタ文字
	LD	HL,LRSDAT
	CALL	CRISUB
	LD	D,8	;R#8
	LD	A,00000011B	;インターレース･シンク＆ビデオ･モード
	CALL	WRCRTC
	LD	A,00001110B	;1行のラスタ数－1（あるいは－2）
	JP	WRCRTC

;	高解像度
CRTIHG:	LD	DE,0FF03H	;24KHzモード、グラフィック疑似200ライン
	LD	HL,HRSDAT
;	JR	CRISUB

;CRTCなどを初期化します
;入力	E←I／O 1FD0Hに出力する値、D←[RESFLG]に書き込む値、
;	HL←CRTC初期化データの先頭アドレス
;出力	[IO1FD0]←入力E、[RESFLG]←入力D
;破壊	AF，HL，DE，BC
;〈レジスタ･マップ〉
;E	現在CRTCレジスタ番号
;HL	現在初期化データのアドレス
;BC	I／Oアドレス
;Acc	ループ･カウンタ
CRISUB:	LD	A,E
	LD	(IO1FD0),A
	LD	BC,1FD0H
	OUT	(C),A
	LD	A,D
	LD	(RESFLG),A
;
	LD	D,0	;R#0
	LD	B,14

CRISLP:	LD	A,(HL)
	INC	HL
	CALL	WRCRTC
	DJNZ	CRISLP

	RET

;CRTC低解像初期化データ（40桁用）
LRSDAT:	DB	 55	;水平周期（文字単位）
	DB	 40	;表示桁数
	DB	 45	;水平同期信号出力位置（文字単位）
	DB	 34H	;同期信号パルス幅
	DB	 31	;垂直周期（文字単位）
	DB	  2	;垂直周期調整（ラスタ単位）
	DB	 25	;垂直表示文字数
	DB	 28	;垂直同期信号出力位置（文字単位）
	DB	00000000B	;インターレース･スキュー
	DB	  7	;1行のラスタ数－1
	DB	 00H	;カーソル･スタート･ラスタ？
	DB	 00H	;カーソル･エンド･ラスタ？
	DB	 00H	;表示先頭アドレス上位
	DB	 00H	;表示先頭アドレス下位

;CRTC高解像初期化データ（40桁用）
HRSDAT:	DB	 53	;水平周期（文字単位）
	DB	 40	;表示桁数
	DB	 45	;水平同期信号出力位置（文字単位）
	DB	 84H	;同期信号パルス幅
	DB	 27	;垂直周期（文字単位）
	DB	  0	;垂直周期調整（ラスタ単位）
	DB	 25	;垂直表示文字数
	DB	 26	;垂直同期信号出力位置（文字単位）
	DB	00000000B	;インターレース･スキュー
	DB	 15	;1行のラスタ数－1
	DB	 00H	;カーソル･スタート･ラスタ？
	DB	 00H	;カーソル･エンド･ラスタ？
	DB	 00H	;表示先頭アドレス上位
	DB	 00H	;表示先頭アドレス下位




;===============================
;グラフィック（機種固有）
;===============================


;プライオリティを初期化します
; プライオリティはテキスト優先になります。
;入力	なし
;出力	なし
;破壊	AF，HL，DE，BC
;注：割り込み禁止して実行してください。
PRIINI:
	LD	BC,1300H
	OUT	(C),C
	RET



;---------------
;汎用ルーチン
;---------------


;文字列から文字を取り出します（スペースはスキップ）
;入力	DE←文字列の先頭アドレス
;出力	Acc←文字
;	DEはカウント･アップ
;破壊	AF，DE
;注：小文字を大文字に変換します。
GETLTR:
	CALL	SPSKIP
	LD	A,(DE)
	OR	A
	RET	Z	;文字列の終わりの達した
	INC	DE
	JP	TOUPR


;文字列のスペース･キャラをスキップします
;入力	DE←文字列の先頭アドレス
;出力	DE←カウント･アップ
;破壊	AF，DE
SPSLP:
	INC	DE

SPSKIP:
	LD	A,(DE)
	CP	' '
	JR	Z,SPSLP
	CP	09H	;TAB
	JR	Z,SPSLP

	RET


;小文字を大文字に変換します
;入力	Acc←アスキー･コード
;出力	Acc←変換したアスキー･コード
;破壊	AF
TOUPR:
	CP	'a'
	RET	C
	CP	'z'+1
	RET	NC
	SUB	20H
	RET


;ASCNUM V1.00  Copyright (C) T.Chikushi  1994-06-18
;10進文字を数値に変換します
;入力	Acc←文字
;出力	AL←数値、CY←変換状態
;CF=0	AL←数値（0～9）
;CF=1	10進文字ではなかった（ALは、呼び出し前の値）
;破壊	AF
ASCNUM:
	CP	'0'
	RET	C
	CP	'9'+1
	CCF
	RET	C
;	「0」～「9」
	SUB	'0'	;Acc←0～9，CY←0
	RET


;Copyright (C) T.Chikushi  1991-01-04
;HL÷Acc→商HL...余りAcc
;入力	HL←被除数、Acc←除数
;出力	HL←商、Acc←余り
;破壊	AF，HL，DE，BC
DIV68:
	PUSH	BC
	LD	C,A	;C←除数
	XOR	A
	LD	B,16

DIV68L:	ADD	HL,HL
	RLA
	CP	C
	JR	C,DIV681
	SUB	C
	INC	L
DIV681:	DJNZ	DIV68L

	POP	BC
	RET


;Copyright (C) T.Chikushi  1990
;DEHL÷BC→商DEHL...余りBC
;入力	DEHL←被除数、BC←除数
;出力	DEHL←商、BC←余り
;破壊	インデックス･レジスタ以外
;	min 3,452ts max 3,600ts s1
DIV26:
	PUSH	BC
	EXX
	POP	BC	;BC'←除数
	LD	HL,0	;HL'←0
	EXX
	LD	B,32
DIV26L:	ADD	HL,HL
	EX	DE,HL
	ADC	HL,HL
	EX	DE,HL
	EXX
	ADC	HL,HL	;HL'DEHLを左シフト
	JR	C,DIV262	;必ず引けます
	SBC	HL,BC	;HL←HL－BC
	JR	NC,DIV263	;引けた
	ADD	HL,BC	;引けない場合はHL'を元に戻します
	EXX
	DJNZ	DIV26L
DIV261:	EXX
	PUSH	HL
	EXX
	POP	BC
	RET
;	必ず引ける場合
DIV262:	OR	A
	SBC	HL,BC
;	引けた場合
DIV263:	EXX
	INC	L	;INC HL'DEHL
	DJNZ	DIV26L
	JR	DIV261


;-----------------------
;割り込みルーチン
;-----------------------


; 省メモリのため、テーブル･エリアに移動しました。


;-----------------------
;オリジナル･モニタ
;-----------------------


;#MON（1F8EH）の本体
;CY＝0でリターンします（ディスク･モジュールのため）
MON:
	LD	(MONRSP),SP
	LD	HL,(_MEMAX)
	LD	DE,3000H
	OR	A
	SBC	HL,DE
	LD	(MONFRE),HL	;ユーザー･エリアのサイズ

;	コマンド待ちループ
MON1:	LD	SP,0100H	;オリジナル･モニタのスタック･トップ
	LD	A,'*'
	CALL	_PRINT
	LD	DE,(_KBFAD)
	CALL	_GETL
	CALL	GETLTR

; コマンドを解析して、それぞれの処理ルーチンへ。
;出力	DE←次の文字のアドレス
MON2:
	CP	':'
	JP	Z,MONEDT	;メモリ･エディト
	CP	'*'
	CALL	Z,GETLTR
	CP	'R'
	JP	Z,MONRET	;モニタを終えます
	CP	'#'
	JP	Z,MONWCH	;桁チェンジ
	CP	'D'
	JP	Z,MONDMP	;ダンプ
	CP	'F'
	JP	Z,MONFIN	;サーチ
	CP	'A'
	JP	Z,MONGRA	;グラフィックのオン、オフ
	CP	'G'
	JP	Z,MONGO	;ジャンプ
	CP	'I'
	JP	Z,MONIDS	;ディスク初期化
	CP	'M'
	JP	Z,MONMST	;メモリ･セット
	CP	'L'
	JP	Z,MONLD	;機種依存Lコマンド
	CP	'S'
	JP	Z,MONSV	;機種依存Sコマンド
	CP	'C'
	JP	Z,MONCOL	;機種依存Cコマンド
	DS	4,00H	;ダミー
	CALL	_BELL
	JP	MON1


;オリジナル･モニタを終えます
MONRET:
	XOR	A	;CY←0（Acc←0）
	LD	SP,(MONRSP)
	RET


;オリジナル･モニタ サブルーチン･コール
MONGO:
	CALL SPSKIP
	CALL _HLHEX
	JR	C,MONGOE
	LD	BC,MON1
	PUSH	BC	;スタック←MON1
	JP	(HL)

MONGOE:
	CALL _BELL
	JP	MON1


;オリジナル･モニタ 桁数チェンジ（行数チェンジ）
MONWCH:
	CALL MONWCE	;拡張桁チェンジ
	LD	A,(screen_width)
	CPL		;FFH，00H
	AND	40	; 40， 0
	ADD	A,40	; 80，40
	CALL	_WIDCH
	JP	MON1


;オリジナル･モニタ グラフィック、オン、オフ
MONGRA:
	CALL	SPSKIP
	LD	A,(DE)
	CALL	TOUPR
	OR	A
	JR	Z,MNGRTO
	CP	'C'	;グラフィックのクリア
	JR	Z,MNGRCL
	CP	'0'
	JR	C,MNGRER
	CP	'1'+1
	JR	NC,MNGRER

;	「G0」「G1」の場合
; グラフィックをオン、またはオフします。
	SUB	'0'	;「0」：0 ，「1」：1
	DEC	A	;「0」：FFH，「1」：00H
	CPL		;「0」：00H，「1」：FFH
MNGRGN:
	LD	(GRAFLG),A
	DI
	CALL GRAONF
MNGRRT:
	EI
	JP	MON1

;	「G」の場合
; グラフィックのオン、オフを切り換えます。
MNGRTO:
	LD	A,(GRAFLG)
	CPL
	JR	MNGRGN

;	「GC」の場合
; グラフィックをクリアします。
MNGRCL:
	DI
	CALL GRACLR	;GRAMをクリアします
	JR	MNGRRT

MNGRER:
	CALL _BELL
	JR	MNGRRT


;オリジナル･モニタ サーチ･ルーチン
;〈使用法〉
;「F 先頭アドレス 最終アドレス データ…」
;〈サーチするデータ列〉
;keyboard_buffer～
MONFIN:
;	アドレス情報を取り出します
	CALL SPSKIP
	CALL _HLHEX
	JR	C,MONFIE
	LD	(MONFTP),HL	;先頭アドレス
	CALL SPSKIP
	CALL _HLHEX
	JR	C,MONFIE
	INC	HL
	LD	(MONFEN),HL	;最終アドレス＋1

;	データの取り出します
	LD	HL,keyboard_buffer	;データ列の先頭

MONFL1:
	CALL SPSKIP
	CALL _2HEX
	JR	C,MNFL1E
	LD	(HL),A	;←データ
	INC	L	;現在アドレス＆現在データ数
	JR	MONFL1

MNFL1E:	LD	A,L
	OR	A
	JR	Z,MONFIE	;データがなかった
	LD	(MONFCT),A	;データ数（1～）
	LD	HL,(MONFEN)
	LD	DE,(MONFTP)
;	OR	A
	SBC	HL,DE
	DEC	HL	;HL←サイズ－1 '0～65,535
	LD	E,A
	LD	D,0
	DEC	DE	;DE←データ数－1 '0～
	OR	A
	SBC	HL,DE	;HL←サイズ－データ数
	JR	C,MONFIE
	INC	HL
	LD	(MONFSZ),HL	;検索カウンタ（1～）

;	検索します
	LD	HL,(MONFTP)	;先頭アドレス
	LD	BC,(MONFSZ)	;検索カウンタ
	LD	A,(keyboard_buffer)	;最初の検索バイト

MONFL2:	CPIR
	PUSH	AF
	PUSH	HL
	PUSH	BC
	CALL	Z,MONFSB	;最初のバイトが一致しました
	POP	BC
	POP	HL
	POP	AF
	JP	PE,MONFL2

MONFES:
	LD	A,0DH
	CALL	_PRINT
MONFRT:
	JP	MON1

MONFIE:
	CALL	_BELL
	JR	MONFRT


;最初のバイト以降を比較し、一致すれば、そのアドレスを表示します
;入力	HL←最初のバイトが一致した次のアドレス
;出力	なし
;破壊	全レジスタ
MONFSB:
	PUSH	HL	;スタック←比較されるアドレス＋1
	LD	DE,keyboard_buffer+1	;データ列先頭＋1
	LD	A,(MONFCT)
	LD	B,A
	DEC	B	;B←チェックする残りのバイト数
	JR	Z,MNFSBR	;比較は1バイトのみで、一致しました

MNFSBL:
	LD	A,(DE)
	INC	E
	CP	(HL)
	INC	HL
	JR	NZ,MNFSBB
	DJNZ	MNFSBL

MNFSBR:
	CALL	_PAUSE
	DW	MONFES
	LD	A,' '
	CALL	_PRINT
	POP	HL	;HL←比較されるアドレス＋1
	DEC	HL
	JP	PRTHL

MNFSBB:
	POP	HL
	RET


;	サーチ･コマンド用ワーク
MONFTP:	DS	2	;検索先頭アドレス
MONFEN:	DS	2	;検索最終アドレス＋1
MONFSZ:	DS	2	;検索バイト数（[MONFEN]－[MONFTP]－[MONFCT]＋1）
MONFCT:	DS	1	;データ数


;オリジナル･モニタ ダンプ（可変行、可変桁対応）
;〈ダンプの桁数〉
; ダンプの桁数は、「横バイト数×4＋7」文字。
;72桁以上、71文字
;「:AAAA=HH HH HH HH HH HH HH HH HH HH HH HH HH HH HH HH /CCCCCCCCCCCCCCCC」
;40桁以上、39文字
;「:AAAA=HH HH HH HH HH HH HH HH /CCCCCCCC」
;24桁以上、23文字
;「:AAAA=HH HH HH HH /CCCC」
;〈レジスタ･マップ〉
;HL	メモリのアドレス
;B	汎用カウンタ
;C	横バイト数
;DE	縦表示数
;注：DIV26（インデックス･レジスタ以外破壊）を呼び出します。
MONDMP:
	CALL	SPSKIP
	CALL	_HLHEX
	JR	C,$+5
	LD	(MONADR),HL
	CALL	SPSKIP
	CALL	_HLHEX
	LD	(MONDE),HL
	CCF
	SBC	A,A	;最終アドレスが指定されていたらAcc＝FFH
	LD	(MONDF),A
	CALL	MNDINI	;初期化
	JP	C,MON1	;初期化失敗
	CALL	MNDILC	;表示ライン数の設定
	EX	DE,HL	;DE←縦ライン数
	LD	A,(MONDX)
	LD	C,A	;C←横バイト数

;入力	C←横バイト数、DE←縦ライン数
;	[MONADR]参照
;出力	[MONADR]更新
;破壊	AF，HL，DE，B
;〈レジスタ･マップ〉
;HL	現在メモリのアドレス
;B	横ループ･カウンタ
;DE	縦ループ･カウンタ
MDPLP1:
	LD	A,':'
	CALL	_PRINT
	LD	HL,(MONADR)
	PUSH	HL	;スタック←アドレス（行頭）
	CALL	_PRTHL
	LD	A,'='
	CALL	_PRINT
	LD	B,C	;B←横バイト数

;入力	HL←メモリのアドレス、B←横バイト数
;出力	HLはカウント･アップされます
;破壊	AF，HL，B
;〈レジスタ･マップ〉
;HL	現在メモリのアドレス
;B	ループ･カウンタ
MDPL21:
	LD	A,(HL)	;Acc←メモリのデータ
	INC	HL
	CALL	_PRTHX
	LD	A,' '
	CALL	_PRINT
	DJNZ	MDPL21

	LD	A,'/'
	CALL	_PRINT
	POP	HL	;HL←アドレス（行頭）
	LD	B,C	;B←横バイト数

;入力	HL←メモリのアドレス、B←横バイト数
;出力	HLはカウント･アップされます
;破壊	AF，HL，B
;〈レジスタ･マップ〉
;HL	現在メモリのアドレス
;B	ループ･カウンタ
MDPL22:
	LD	A,(HL)	;Acc←メモリのデータ
	INC	HL
;	CP	7FH
;	JR	Z,$+6	;DELコードだった
	CP	20H
	JR	NC,$+4	;コントロール･コードだった
	LD	A,' '	;Acc←「 」
	CALL	_PRINT
	DJNZ	MDPL22

	LD	(MONADR),HL
	CALL	_LTNL
	CALL	_PAUSE
	DW	MON1
	DEC	DE
	LD	A,E
	OR	D
	JR	NZ,MDPLP1

	JP	MON1


;表示ライン数を得ます
;入力	[MONDE]←最終アドレス、[MONDF]←[MONDE]有効のフラグ
;出力	HL←ライン数
;破壊	全レジスタ
MNDILC:
	LD	A,(MONDF)
	OR	A
	JR	NZ,MNDLC1

;	最終アドレスが設定されていない場合
	LD	A,(MONDY)
	LD	L,A
	LD	H,0	;HL←縦ライン数（1画面分）
	RET

;	最終アドレスが設定されている場合
MNDLC1:
	LD	A,(MONDX)
	LD	C,A
	LD	B,0	;BC←横バイト数（2～）
	LD	HL,(MONDE)
	LD	DE,(MONADR)
	XOR	A
	SBC	HL,DE	;HL←ダンプするバイト数－1
	ADD	HL,BC
	RLA		;Acc←CY
	LD	E,A
	LD	D,B	;DEHL←ダンプするバイト数＋横バイト数－1
	JP	DIV26


;ダンプ･コマンドの初期化処理
;入力	[_MXLIN]、[_WIDTH]参照
;出力	[MONDX]、[MONDY]設定
;	CY＝1なら初期化に失敗しました
;破壊	全レジスタ
MNDINI:
;	[MONDXの設定]
	LD	A,(_WIDTH)
	SUB	8	;アドレスなどの8文字を除きます
	RET	C
	CP	4*2
	RET	C	;2バイト分の表示にも足りない
	AND	11111100B
	RRCA
	RRCA		;Acc←表示可能横バイト数
	CALL	MNDN2
	LD	(MONDX),A	;[MONDY]←横バイト数（2～）

;	[MONDYの設定]
	LD	A,(_MXLIN)
	SUB	1	;1行のアキを作るため
	RET	C
	CP	2
	RET	C	;2行分の表示にも足りない
	CALL	MNDN2
	LD	(MONDY),A	;[MONDY]←縦ライン数（2～）

	XOR	A
	RET


;データをn^2化します
;入力	Acc←処理するデータ（0～255）
;出力	Acc←n^2化されたデータ（8、16など）
;破壊	全レジスタ
MNDN2:
	LD	BC,8*100H	;B←8，C←0

MNDN21:
	RLCA
	INC	C	;カウント･アップ
	JR	C,$+4
	DJNZ	MNDN21

	LD	A,0	;CYA←1_00000000B
	LD	B,C

MNDN22:
	RRA
	DJNZ	MNDN22

	RET


;	ダンプ･コマンド用ワーク
MONDE:	DS	2	;ユーザーが指定したダンプの最終アドレス
MONDF:	DS	1	;＝FFHで、[MONDE]が有効
MONDX:	DS	1	;ダンプする横バイト数（2～）
MONDY:	DS	1	;ダンプする縦バイト数（2～）


;オリジナル･モニタ メモリ･セット
MONMST:
	CALL	SPSKIP
	CALL	_HLHEX
	JR	C,$+5
	LD	(MONADR),HL

MMSLP:	LD	A,':'
	CALL	_PRINT
	LD	HL,(MONADR)
	CALL	_PRTHL
	LD	A,'='
	CALL	_PRINT
	LD	A,(HL)
	CALL	_PRTHX
	LD	A,1DH	;Acc←「←」
	CALL	_PRINT
	CALL	_PRINT
	CALL	MEMEDT
	JP	C,MON2
	JR	MMSLP


;オリジナル･モニタ メモリ･エディト
MONEDT:
	CALL	MEMED1
	JP	C,MON1

MONELP:	CALL	MEMEDT
	JP	C,MON2
	JR	MONELP


;1行メモリ･エディト･ルーチン
;入力	[MONADR]参照
;出力	CY＝1ならエディトを終了しました
;破壊	AF，HL，DE
MEMEDT:
	LD	DE,(_KBFAD)
	CALL	_GETL
	CALL	GETLTR

;	既に先頭1文字を取り出した時のエントリ
MEMED1:
	CP	':'	;メモリ･エディト用ヘッダ
	SCF
	RET	NZ	;ヘッダが不正
	CALL	SPSKIP
	CALL	_HLHEX
	RET	C	;アドレスが不正
	CALL	GETLTR
	CP	'='
	SCF
	RET	NZ	;セパレータが不正

MEMELP:	CALL	SPSKIP
	LD	A,(DE)
	CP	'.'
	SCF
	RET	Z	;エディト終了
	CALL	_2HEX
	CCF
	RET	NC	;入力終了
	LD	(HL),A
	INC	HL
	LD	(MONADR),HL
	JR	MEMELP


;===============================================
;オリジナル･モニタ Ok、Errorメッセージ
;===============================================


;処理が正常終了しました
MONOK:	CALL	_MPRNT
	DB	'Ok',0DH,00H
MNOKRT:	JP	MON1


;処理が異常終了しました
MONERR:	CALL	_MPRNT
	DB	'Error !',0DH,00H
	JR	MNOKRT


;=======================================
;オリジナル･モニタ･ディスク初期化処理
;=======================================


;S-OSディスク･イメージの初期化
MONIDS:
	CALL	SPSKIP
	CALL	MONDEV
	OR	A
	JR	NZ,MONIDI

;	S-OSディスク･イメージのクローズ
	CALL SOSSF
	JP	C,MONERR
	JP	MONOK

;	論理フォーマット
MONIDI:	DEC	A	;Acc←ユニット番号
	LD	(disk_unit_number),A
	ADD	A,'A'
	LD	C,A	;C←デバイス名
	CALL	_MPRNT
	DB	'ﾃﾞﾊﾞｲｽ ',00H
	LD	A,C
	CALL	_PRINT
	CALL	_MPRNT
	DB	': ｦ ｼｮｷｶ ｼﾃ ﾖﾛｼｲ ﾃﾞｽｶ(Y/N)?',00H
	CALL	_FLGET
	CALL	TOUPR
	CP	'Y'
	JR	Z,MONIDY

;	初期化しません
	LD	A,'N'
	CALL	_PRINT
	LD	A,0DH
	CALL	_PRINT
	JP	MON1

;	初期化します
MONIDY:
	CALL	_PRINT
	LD	A,0DH
	CALL	_PRINT

	CALL	SOSDI
	JP	NC,MONOK

;	物理的フォーマット（論理フォーマットに失敗しました）
	CALL	SOSDF
	JP	NC,MONOK

;	物理的フォーマットにも失敗しました
	JP	MONERR


;=======================================
;オリジナル･モニタ･ディスク･ルーチン
;=======================================


;ファイル名からデバイスを抜き出します
;入力	DE←ファイル名の先頭アドレス
;出力	Acc←デバイス（0，1～）、DE←カウント･アップ
;破壊	AF，DE
;注：デフォルト･デバイスは0、ドライブAは1に対応します。
MONDEV:
	LD	A,(DE)
	OR	A
	RET	Z	;文字列の終わりに達していました

	INC	DE
	LD	A,(DE)
	DEC	DE
	CP	':'
	LD	A,0	;Acc←デフォルト･デバイス
	RET	NZ	;デバイスが指定されています

;	デバイスが指定されています
	LD	A,(DE)
	CALL	TOUPR
	SUB	'A'-1	;Acc←1～
	INC	DE
	INC	DE
	RET


;-------------------------------
;オリジナル･モニタ 機種依存部分
;-------------------------------


;拡張桁チェンジ
;入力	DE←コマンドの次の文字のアドレス
;出力	なし
;破壊	全レジスタ
MONWCE:
	LD	A,(DE)
	CALL	TOUPR
	LD	C,0
	CP	'S'	;スイッチ依存
	JR	Z,MNWCE1
	INC	C	;C←1
	CP	'L'	;低解像度
	JR	Z,MNWCE1
	INC	C	;C←2
	CP	'H'	;高解像度
	JR	Z,MNWCE1
	INC	C	;C←3
	CP	'M'	;疑似高解像度
	RET	NZ

MNWCE1:
	LD	A,C	;Acc←解像度モード（0～3）
	LD	(RESMOD),A
	DI
	CALL	CRTINI
	EI
	LD	A,(_WIDTH)
	CALL	_WIDCH
	JP	MON1


;モニタ Lコマンド
;入力	DE←コマンドの次の文字のアドレス
;出力	なし
;破壊	全レジスタ
MONLD:
	JP	MON1
	DS	1


;モニタ Sコマンド
;入力	DE←コマンドの次の文字のアドレス
;出力	なし
;破壊	全レジスタ
MONSV:
	JP	MON1
	DS	1


;モニタ Cコマンド
;オリジナル･モニタ 文字色変更処理
;入力	DE←コマンドの次の文字のアドレス
;出力	なし
;破壊	全レジスタ
;〈使用法〉
;「Cmn」	カラーを（m，n）とします。
;「Cm」		カラーを（m，）とします。
;「C」		前景色と背景色を交換します。
;〈レジスタ･マップ〉
;DE	現在の文字列のアドレス
;HL	foreground_colorまたはbackground_colorのアドレス
;BC	ワーク
MONCOL:
	LD	HL,foreground_color
;
	CALL	SPSKIP
	LD	A,(DE)
	OR	A	;文字列の最後
	JR	Z,MNCOXC	;前景色と背景色の交換
	CALL	ASCNUM	;Acc←数値
	JR	C,MNCOER	;数字ではなかった
	LD	(HL),A	;前景色
	INC	DE
;
	CALL	SPSKIP
	LD	A,(DE)
	OR	A
	JR	Z,MNCOOK	;前景色のみ
	CALL	ASCNUM	;Acc←数値
	JR	C,MNCOER	;数字ではなかった
	INC	L	;HL←background_color
	LD	(HL),A	;後景色
;
MNCOOK:
	CALL	change_color
	LD	A,0CH
	CALL	_PRINT
MNCORT:
	JP	MON1

;	前景色と背景色を交換します
MNCOXC:
	LD	A,(HL)	;Acc←前景色
	INC	L	;HL←background_color
	LD	C,(HL)	;C←後景色
	LD	(HL),A	;後景色←前景色
	DEC	L	;HL←foreground_color
	LD	(HL),C	;前景色←後景色
	JR	MNCOOK

MNCOER:
	CALL	_BELL
	JR	MNCORT


;-------------------------------
;オリジナル･モニタ ワーク
;-------------------------------


MONADR:	DW	0	;操作アドレス
MONRSP:	DW	0	;SPの保存
MONFRE:	DW	0	;ユーザー･エリアの大きさ


;---------------------------------------
;SWXCDIOを使わないための処理
;---------------------------------------


SOSSI:
SOSSF:
	OR	A
	RET
SOSDI:
SOSDF:
	SCF
	RET
DIOETP:
	DS	2


;	フィジカル･ディスクI／Oルーチン組み込み
;	INCLUDE	SWEMDIO2
	; INCLUDE	SWXCDIO
	; INCLUDE	SWXCRIO
	ORG	2B00H
	; JP	RDSUB	;RAMディスク･ドライバ用パッチ
	; JP	WTSUB	;RAMディスク･ドライバ用パッチ


;	RUN＆SUBMITルーチン組み込み
	; INCLUDE	SWEMRS

;　ファイルの先頭が３０００Ｈで、サイズが７Ｋバイト（１Ｃ００Ｈ）
;以内のファイルは、ＲＡＭディスク（デバイスＥ:）に、
;メモリの３０００Ｈ～４ＢＦＦＨの内容が待避されます。
;その場合は、ＲＡＭディスクのレコード０～１３、１８～３１が使用されます。
;よって、ＲＡＭディスクのディレクトリ領域は２レコードしか使えません。
;このことは、ＲＡＭディスク（デバイスＥ:）を６４Ｋバイト以内とみなしています。

	ORG	1CC0H

;	Ｓ-ＯＳエントリ
; _HOT	EQU	1FFAH
; _PRINT	EQU	1FF4H
; _MPRNT	EQU	1FE2H
; _LPTON	EQU	1FD9H
; _LPTOF	EQU	1FD6H
; _GETL	EQU	1FD3H	;未使用
; _GETKY	EQU	1FD0H
; _BRKEY	EQU	1FCDH
; _INKEY	EQU	1FCAH
; _BELL	EQU	1FC4H
; _HEX	EQU	1FB8H	;未使用
; _RDD	EQU	1FA6H
; _FILE	EQU	1FA3H
; _DRDSB	EQU	2000H
; _DWTSB	EQU	2003H
; _ROPEN	EQU	2009H
; _CSR	EQU	2018H
; _SCRN	EQU	201BH
; _FLGET	EQU	2021H	;未使用
; _ERROR	EQU	2033H	;未使用
; _HL	EQU	1F81H

;	Ｓ-ＯＳワーク
; _USR	EQU	1F7EH
; _LPSW	EQU	1F7CH
; _IBFAD	EQU	1F74H
; _SIZE	EQU	1F72H
; _DTADR	EQU	1F70H
; _EXADR	EQU	1F6EH
; _MEMAX	EQU	1F6AH	;未使用
; _FATPS	EQU	1F5EH
; _DSK	EQU	1F5DH

;	ＤＯＳモジュール内部エントリ
ERROR	EQU	286CH

;	バッチ処理バッファ
BATBF	EQU	2D00H	;バッチ･ファイル用リード･バッファ（2D00H～2DFFH）
BPRBF	EQU	204BH	;バッチ変数バッファ（204BH～20FEH）


;ＤＯＳモジュール、2152H番地よりジャンプしてきます（コマンドの拡張）
EXCOM:
	CP	';'	;ＲＥＭコマンド
	RET	Z
	CP	'P'	;ポーズ･コマンド
	JR	Z,RSPAU
	CP	' '	;ＲＵＮコマンド
	JR	Z,RUN
	LD	A,13	;Syntax Error
	SCF
	RET


;モニタ 「;」コマンド処理
RSPAU:
	CALL	_MPRNT
	DB	'HIT KEY',0DH,00H

;	キーがはなされるまで待ちます
PAU0:	CALL	_GETKY
	OR	A
	JR	NZ,PAU0

;	CALL	_INKEY
	CALL	PAU1	;バッチ･ファイルなどからキー入力させないため
	CP	1BH	;ＥＳＣ
	JP	Z,BOFF	;[BATFLG]をクリアします
	OR	A
	RET


;モニタ Ｒコマンド処理
;注：ＤＥは、コマンドまたはバッチ変数の次のアドレスを示しています。
RUN:
	LD	A,1
	CALL	_FILE
	LD	A,(DE)
	OR	A
	JR	Z,RUN0
	INC	DE	;パラメータの区切りをとばします
RUN0:	PUSH	DE
	CALL	_ROPEN
	JP	C,BATCH	;ファイル属性が違った（バッチ･ファイル）かも知れない
;	CALL	CMNDQ	;コマンド･ファイルならＲＡＭディスクにメモリを待避します
	DS	3,00H
	CALL	_RDD
	POP	DE
	JR	C,RUN1
	LD	HL,(_EXADR)
	CALL	_HL
RUN1:	PUSH	AF
	LD	A,(COMF)	;メモリ待避フラグ
	OR	A
	CALL	NZ,CWRT	;待避したメモリを元に戻します
	POP	AF
	RET


;コマンド･ファイル（先頭3000Hで、サイズ７Ｋバイト以下）ならＲＡＭディスクにメモリを待避します
;入力	[_DTADR]、[_SIZE]参照
;出力	なし
;破壊	ＡＦ，ＨＬ，ＤＥ，ＡＦ'
CMNDQ:
	XOR	A
	LD	(COMF),A	;メモリ待避フラグ
	LD	HL,(_DTADR)
	LD	DE,3000H
	SBC	HL,DE
	RET	NZ	;先頭アドレスが3000H以外だった

;	先頭アドレスが3000H
	LD	HL,(_SIZE)
;	LD	DE,-1C00H
	LD	DE,-1C01H	;深谷崇さんより
	ADD	HL,DE
	RET	C	;サイズが1C00Hより大きい

;	サイズが７Ｋバイト（1C00H）以下
;	メモリを待避します
	LD	A,(_DSK)
	PUSH	AF
	CALL	SET1	;アクセスするデバイスをＲＡＭディスクにして、メモリ待避用のパラメータ（前半）を得ます
	CALL	_DWTSB
	CALL	SET2	;メモリ待避用のパラメータ（後半）を得ます
	CALL	_DWTSB
	POP	AF
	LD	(_DSK),A
	LD	A,1
	LD	(COMF),A	;メモリ待避フラグ
	RET


;待避したメモリを元に戻します
;入力	なし
;出力	[_DSK]←「E」、ＨＬ←3000H、ＤＥ←０、Ａｃｃ←１４
;破壊	ＡＦ，ＨＬ，ＤＥ，ＡＦ'
CWRT:
	CALL	SET1	;アクセスするデバイスをＲＡＭディスクにして、メモリ待避用のパラメータ（前半）を得ます
	CALL	_DRDSB
	CALL	SET2	;メモリ待避用のパラメータ（後半）を得ます
	JP	_DRDSB


;アクセスするデバイスをＲＡＭディスクにして、メモリ待避用のパラメータ（前半）を得ます
;入力	なし
;出力	[_DSK]←「E」、ＨＬ←3000H、ＤＥ←０、Ａｃｃ←１４
;破壊	Ａ，ＨＬ，ＤＥ
SET1:
	LD	A,'E'
	LD	(_DSK),A
	LD	HL,3000H
	LD	DE,0
	LD	A,14
	RET


;メモリ待避用のパラメータ（後半）を得ます
;入力	なし
;出力	ＨＬ←3E00H、ＤＥ←１８、Ａｃｃ←１４
;破壊	Ａ，ＨＬ，ＤＥ
SET2:
	LD	HL,3E00H
	LD	DE,18
	LD	A,14
	RET


;=======================
;#HOT（1F7EH）のっとり
;=======================


;AUTOEXEC.BATの自動実行
AUTOEX:
	LD	HL,_HOT
	LD	(_USR),HL
	LD	DE,AUTNAM
	CALL	_BRKEY
	CALL	NZ,RUN
	JP	_HOT


;モニタ Ｒコマンド処理の続き（バッチ･ファイル）
;入力	スタック←ファイル名のあとにあるパラメータのアドレス
;注：
;　バッチ変数があれば、バッチ変数バッファに格納します。
;　ＤＥは、コマンドまたはバッチ変数の次のアドレスを示しています。
BATCH:
	POP	DE	;ＤＥ←パラメータのアドレス
	CALL	BOFF	;[BATFLG]をクリアします
	CP	6	;ファイル属性の不一致
	SCF
	RET	NZ

;	０１Ｈ以外のファイル属性のファイル
	LD	HL,(_IBFAD)
	LD	A,(HL)	;Ａｃｃ←ファイル属性
;注：
;　ここはソースとコメントのリセットするビットが違います。
;ソースはb6（書き込み禁止属性）、コメントはb5（ベリファイＯＮ属性）。
	AND	0BFH	;「1101 1111」←オリジナルのコメント（多分間違い）
	CP	4
	LD	A,6	;Bad File Mode
	SCF
	RET	NZ	;アスキー･ファイルでなかった

;	アスキー･ファイルだった
	LD	BC,1EH
	ADD	HL,BC	;ＨＬ←ＦＣＢバッファのクラスタ番号の部分
	CALL	STTRK	;[BTRK]と[BREC]を設定します
	CALL	STPARA	;バッチ変数をバッチ変数バッファを読み込みます
	LD	A,(_DSK)
	LD	(BDEV),A	;バッチ･ファイルのあるデバイス
	LD	A,16+1
	LD	(BCNT),A	;バッチ･ファイルの現在クラスタの残りレコード数＋１
	XOR	A
	DEC	A	;Ａｃｃ←FFH
	LD	(BTPNT),A	;バッチ･ファイルのバッファの前回のリード位置
	LD	(BATFLG),A	;＝FFH（０以外）でバッチ･ファイル実行中
	RET


;[BTRK]と[BREC]を設定します
;入力	[HL]←クラスタ番号
;出力	[BTRK]←クラスタ番号、[BREC]←レコード番号
;破壊	ＡＦ，ＨＬ
STTRK:
	LD	A,(HL)	;Ａｃｃ←クラスタ番号
	LD	(BTRK),A	;バッチ･ファイルの現在クラスタ番号
	LD	L,A
	LD	H,0	;ＨＬ←クラスタ番号
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL	;ＨＬ←クラスタ番号×１６
	LD	(BREC),HL	;バッチ･ファイルのあるレコード番号
	RET


;バッチ変数をバッチ変数バッファを読み込みます
;入力	ＤＥ←パラメータのアドレス
;出力	[BPRBF～]←バッチ変数
;破壊	ＡＦ，ＨＬ，ＤＥ，ＢＣ
STPARA:
;	バッチ変数バッファをクリアします
	LD	HL,BPRBF	;バッチ変数バッファ
	LD	(HL),0
	PUSH	DE
	PUSH	HL
	LD	D,H
	LD	E,L
	INC	DE	;ＤＥ←BPRBF＋１
	LD	BC,179
	LDIR		;[BPRBF～BPRBF＋１７９]をクリア
	POP	HL	;ＨＬ←BPRBF
	POP	DE	;ＤＥ←パラメータのアドレス

	LD	A,(DE)	;Ａｃｃ←パラメータの先頭
	CP	':'
	JR	NZ,STP0
	INC	DE	;「:」をスキップ
STP0:	LD	C,9	;バッチ変数は￥１～￥９の９個

STPAR0:	LD	B,19	;バッチ変数１個につき２０バイト

;	バッチ変数をバッチ変数バッファに転送します
STPAR1:	LD	A,(DE)
	OR	A
	RET	Z
	CP	' '	;バッチ変数の区切り
	JR	Z,STPAR3	;区切りに達した
	LD	(HL),A
	INC	HL
	INC	DE
	DJNZ	STPAR1

STPAR2:	INC	HL
	DEC	C
	JR	NZ,STPAR0

	RET

;	アドレスをスキップします
STPAR3:	INC	DE
STPAR4:	INC	HL
	DJNZ	STPAR4
	JR	STPAR2


;バッチ･ファイルから1文字を得ます
;入力	なし
;出力	ＣＹ＝０ならバッチ･ファイル実行中でＡｃｃ←キャラ
;	ＣＹ＝１ならバッチ･ファイル実行中でないか、バッチ変数￥０が来た
;破壊	ＡＦ，ＡＦ'
BGET:
	LD	A,(BATFLG)	;＝FFH（０以外）でバッチ･ファイル実行中
	OR	A
	SCF
	RET	Z

;	バッチ･ファイル実行中
	PUSH	BC
	PUSH	HL
	LD	A,(PARAF)	;＝１（０以外）でバッチ変数アクセス中
	OR	A
	JR	Z,BGET0	;バッチ変数アクセス中でない

;	バッチ変数アクセス中
BPARA:	LD	HL,(BTPNT2)	;バッチ変数の現在アドレス
	LD	A,(HL)
	OR	A
	JR	NZ,BPARA0	;バッチ変数の終わりに達していない

;	バッチ変数の終わりに達した（[PARAF]のクリア）
	LD	(PARAF),A	;＝１（０以外）でバッチ変数アクセス中

;	バッチ･ファイルから１バイト取り出します
BGET0:	CALL	get_one_byte_fro_batch_file	;バッチ･ファイルから１バイト取り出します
	OR	A
	JR	Z,BEND	;バッチ･ファイルからリード終了
	CP	'\\'	;バッチ変数
	JR	NZ,BGET1

;	バッチ変数
	CALL	PARAQ	;バッチ変数のアクセスを設定
	JR	NC,BPARA	;バッチ変数だった

;	リターンします（Ａｃｃ←キャラ）
BGET1:	OR	A	;ＣＹ←０
	POP	HL
	POP	BC
	RET

;	バッチ変数バッファより１バイト取り出してリターンします
BPARA0:	INC	HL
	LD	(BTPNT2),HL	;バッチ変数の現在アドレス
	JR	BGET1

;	バッチ･ファイルを終わります
;出力	ＣＹ←１、Ａｃｃ←０
BEND:	CALL	BOFF	;[BATFLG]をクリアします
	SCF
	POP	HL
	POP	BC
	RET


;バッチ･ファイルから１バイト取り出します
;入力	なし
;出力	Ａｃｃ←キャラ
;	Ａｃｃ＝０なら、バッチ･ファイルから読み込めなかった
;破壊	ＡＦ，ＨＬ，ＡＦ'
get_one_byte_fro_batch_file:
	CALL	_BRKEY
	LD	A,0
	RET	Z	;ブレイク･キーを押されていた

	LD	HL,BTPNT	;バッチ･ファイルのバッファの前回のリード位置
	INC	(HL)
	JR	NZ,read_one_byte_from_buffer_of_batch_file	;バッチ･ファイルのバッファから読み込み可能

;	バッチ･ファイルのリード･バッファが空
	LD	HL,BCNT	;バッチ･ファイルの現在クラスタの残りレコード数＋１
	DEC	(HL)
	JR	NZ,read_next_record_from_batch_file	;次のレコードを読みます

;	次のクラスタを読みます
	LD	(HL),16	;[BCNT]←１６
	PUSH	DE
	LD	DE,(_FATPS)
	LD	HL,BATBF	;バッチ･ファイル用リード･バッファ（2D00H～2DFFH）
	CALL	RSREAD	;バッチ･ファイルを読みます
	JR	C,error_read_from_buffer_of_batch_file	;リード･エラー
	LD	A,(BTRK)	;バッチ･ファイルの現在クラスタ番号
	LD	E,A
	LD	D,0	;ＤＥ←バッチ･ファイルの現在クラスタ番号
	ADD	HL,DE	;ＨＬ←バッチ･ファイルのバッファの次のクラスタ番号の部分
	CALL	STTRK	;[BTRK]と[BREC]を設定します
	POP	DE

;	次のレコードを読みます
read_next_record_from_batch_file:
	PUSH	DE
	LD	DE,(BREC)	;バッチ･ファイルの現在レコード番号
	LD	HL,BATBF	;バッチ･ファイル用リード･バッファ（2D00H～2DFFH）
	CALL	RSREAD	;バッチ･ファイルを読みます
	JR	C,error_read_from_buffer_of_batch_file	;リード･エラー
	INC	DE
	LD	(BREC),DE	;バッチ･ファイルの現在レコード番号
	POP	DE

;	バッチ･ファイルのバッファより、１バイト取り出します
read_one_byte_from_buffer_of_batch_file:
	LD	HL,(BTPNT)	;バッチ･ファイルのバッファの前回のリード位置
	LD	A,(HL)
	RET

;	バッチ･ファイルから読み込めなかった
error_read_from_buffer_of_batch_file:
	POP	DE
	XOR	A	;Ａｃｃ←０
	RET


;バッチ･ファイルを読みます
;入力	ＨＬ←読み込みアドレス、ＤＥ←レコード番号
;出力	ＣＹ＝１（Ａｃｃ←エラー･コード）ならエラー
;破壊	ＡＦ，ＡＦ'
RSREAD:
	LD	A,(_DSK)
	PUSH	AF	;スタック←もとのデバイス
	LD	A,(BDEV)	;バッチ･ファイルのあるデバイス
	LD	(_DSK),A	;一時的にバッチ･ファイルのデバイスに
	LD	A,1	;１レコード
	CALL	_DRDSB
	EX	AF,AF'
	POP	AF	;Ａｃｃ←もとのデバイス
	LD	(_DSK),A	;デバイスをもとに戻します
	EX	AF,AF'
	RET


;バッチ変数のアクセスを設定
;入力	なし
;出力	ＣＹ＝１ならバッチ変数でなかった（Ａｃｃ←キャラ）
;破壊	ＡＦ，ＨＬ，ＢＣ，ＡＦ'
PARAQ:
	CALL	get_one_byte_fro_batch_file	;バッチ･ファイルから１バイト取り出します
	CP	'0'
	RET	C
	CP	'9'+1
	CCF
	RET	C

;	バッチ変数￥０～￥９
	SUB	'0'
	JR	Z,PAR00	;「\0」だった

;	バッチ変数￥１～￥９
	LD	L,A
	LD	H,0	;ＨＬ←１～９
	ADD	HL,HL
	ADD	HL,HL	;ＨＬ←(１～９)×４
	LD	B,H
	LD	C,L	;ＢＣ←(１～９)×４
	ADD	HL,HL
	ADD	HL,HL	;ＨＬ←(１～９)×１６
	ADD	HL,BC	;ＨＬ←(１～９)×２０
	LD	BC,BPRBF-20	;バッチ変数バッファ
	ADD	HL,BC	;ＨＬ←バッチ変数に対応するバッファのアドレス
	LD	(BTPNT2),HL	;バッチ変数の現在アドレス
	XOR	A	;ＣＹ←０
	INC	A	;Ａｃｃ←１
	LD	(PARAF),A	;＝１（０以外）でバッチ変数アクセス中
	RET

;	バッチ変数￥０（BGETルーチンを呼び出したルーチンにＣＹ＝１で戻ります）
PAR00:	CALL	get_one_byte_fro_batch_file	;バッチ･ファイルから１バイト取り出します
	OR	A
	JR	Z,PAR01
	CP	0DH	;RET
	JR	NZ,PAR00	;ＣＲコードのスキップ
PAR01:	POP	HL	;戻り番地のキャンセル

;	BGETルーチンのスタックに保存したレジスタをもとに戻します
	POP	HL
	POP	BC

	CALL	_BELL
	SCF
	RET


;[BATFLG]をクリアします
;破壊	なし
BOFF:
	PUSH	AF
	XOR	A
	LD	(BATFLG),A	;＝FFH（０以外）でバッチ･ファイル実行中
	POP	AF
	RET


;===============================
;#FLGET（2021H）のっとり
;===============================


BFLGET:
	CALL	BGET	;バッチ･ファイルから１文字を得ます
	RET	NC
;	ここのジャンプ先は、機種によって違います
;	JP	1CA0H	;本来の#FLGETルーチンへ（バグ処理ルーチン経由）
	JP	_INKEY


;=======================
;#GETL（1FD3H）のっとり
;=======================


;1F2CH番地よりジャンプして来る（バグ回避のため）
;破壊	ＡＦ，ＢＣ
BGETL:
;	論理行頭にカーソルがあるかを、カーソルｘ座標でチェックします（少し問題あり）
	PUSH	DE
	PUSH	HL
	CALL	_CSR
	LD	A,L
	OR	A
	JR	Z,BGETL0	;ｘ座標が０

;	ｘ座標が０でなかった
	LD	B,A	;Ｂ←文字数
	LD	L,0	;Ｌ←０（ｘ座標）

;	画面からカーソル位置までのキャラを1行入力バッファに転送します
BGTLL:	CALL	_SCRN
	LD	(DE),A
	INC	DE
	INC	L
	DJNZ	BGTLL

;	バッチ･ファイルからの入力
BGETL0:	CALL	BGET	;バッチ･ファイルから１文字を得ます
	JR	NC,BGETL1	;バッチ･ファイルから入力があった
	POP	HL
	POP	DE
;	ここのジャンプ先は機種によって違います
;	JP	1610H	;本来の#GETL
	JP	_GETL

;
BGETL1:	CALL	RSPRNT	;画面に１文字表示します（プリンタには出力しません）
	CP	0DH	;ＲＥＴ
	JR	Z,BGETL2
	LD	(DE),A	;１行入力バッファ←キャラ
	INC	DE
	JR	BGETL0

;	１行入力された
BGETL2:	XOR	A	;Ａｃｃ←ターミネータ
	LD	(DE),A	;１行入力バッファ←ターミネータ
	POP	HL
	POP	DE
	RET


;画面に１文字表示します（プリンタには出力しません）
;入力	Ａｃｃ←キャラ
;出力	なし
;破壊	Ｆ，ＡＦ'
RSPRNT:
	EX	AF,AF'
	LD	A,(_LPSW)
	EX	AF,AF'
	CALL	_LPTOF
	CALL	_PRINT
	EX	AF,AF'
	OR	A
	CALL	NZ,_LPTON
	EX	AF,AF'
	RET


;===============================
;#ERROR（2033H）のっとり
;===============================


RSERR:
	CALL	BOFF	;[BATFLG]をクリアします
	OR	A
	RET	Z	;Ａｃｃ＝０ならエラー表示をしません
	JP	ERROR


;=======
;フラグ
;=======


COMF:	DS	1	;＝１で、ＲＡＭディスクへメモリ3000H～4BFFHの待避が行われた
BDEV:	DS	1	;バッチ･ファイルのあるデバイス
BTRK:	DS	1	;バッチ･ファイルの現在クラスタ番号
BREC:	DS	2	;バッチ･ファイルの現在レコード番号
BCNT:	DS	1	;バッチ･ファイルの現在クラスタの残りレコード数＋１
BTPNT:	DW	BATBF	;下位はバッチ･ファイルのバッファの前回のリード位置
BTPNT2:	DS	2	;バッチ変数の現在アドレス
BATFLG:	DS	1	;＝FFH（０以外）でバッチ･ファイル実行中
PARAF:	DS	1	;＝１（０以外）でバッチ変数アクセス中
;AUTNAM:	DB	'A:AUTOEXEC.BAT'	;自動実行ファイル名
;	DS	4
AUTNAM:	DB	'AUTOEXEC.BAT',00H	;自動実行ファイル名（カレント･ドライブより）
	DS	5


;===============
;バグ回避
;===============


;#GETL（1FD3H）のっとり
;1F2CH
BGETLX:
	PUSH	BC
	EX	AF,AF'
	PUSH	AF
	EX	AF,AF'
	CALL	BGETL
	EX	AF,AF'
	POP	AF
	EX	AF,AF'
	POP	BC
	RET


;#FLGET（2021H）のっとり
;1F38H
BFLGTX:
	EX	AF,AF'
	PUSH	AF
	EX	AF,AF'
	CALL	BFLGET
	EX	AF,AF'
	POP	AF
	EX	AF,AF'
	RET


;バッチ･ファイルなどからキー入力させないため（キーが押されるまで待ちます）
PAU1:	CALL	_GETKY
	OR	A
	JR	Z,PAU1
	RET


;=======================
;S-OSワーク･エリア
;=======================


	ORG	1F5BH
_MXLIN:	DB	24	;1F5BH
_WIDTH:	DB	80	;1F5CH
_DSK:	DB	'A'	;1F5DH
_FATPS:	DW	000EH	;1F5EH
_DIRPS:	DW	0010H	;1F60H
_FATBF:	DW	2E00H	;1F62H '2E00H～2EFFH
_DTBUF:	DW	2F00H	;1F64H '2F00H～2FFFH
_MXTRK:	DB	80	;1F66H '80トラック
_DIRNO:	DS	1	;1F67H
_WKSIZ:	DW	0	;1F68H '256バイト単位
_MEMAX:	DS	2	;1F6AH 'メモリの上限
_STKAD:	DW	0100H	;1F6CH '通常のスタック
_EXADR:	DS	2	;1F6EH
_DTADR:	DS	2	;1F70H
_SIZE:	DS	2	;1F72H
_IBFAD:	DW	fcb_buffer	;1F74H
_KBFAD:	DW	keyboard_buffer	;1F76H
_XYADR:	DW	display_cursol_XY_not_use	;1F78H 'ダミー
_PRCNT:	DW	number_of_character_after_CR	;1F7AH '未使用
_LPSW:	DB	0	;1F7CH
_DVSW:	DB	0	;1F7CH 'S-OS 2400bps 'ダミー
_USR:	DW	_HOT	;1F7EH '通常_HOTが入ります
_GETPC:	POP	HL	;1F80H
_HL:	JP	(HL)	;1F81H
;NEXT	1F82H


;===============================
;S-OSジャンプ･テーブル
;===============================


	DS	3	;1F82H 'MSXでは「MBIOS」
	DS	3	;1F85H
	DS	3	;1F88H
BPRNT:	JP	BPRNT0	;1F8BH

	ORG	1F8EH
_MON:			JP	MON		;1F8EH
_peek_entity:	JP	peek_entity	;1F91H
_PEEK:			JP	PEEK	;1F94H
_poke_entity:	JP	poke_entity	;1F97H
_POKE:			JP	POKE	;1F9AH
_FPRNT:			JP	FPRNT	;1F9DH
_FSAME:			JP	FSAME	;1FA0H
_FILE:			JP	FILE	;1FA3H
_RDD:			JP	RDD		;1FA6H
_FCB:			JP	GETFCB	;1FA9H 'MACE #RDI
_WRD:			JP	WRD		;1FACH
_WOPEN:			JP	WOPEN	;1FAFH 'MACE #WRI
_HLHEX:			JP	HLHEX	;1FB2H
_2HEX:			JP	AHEX	;1FB5H
_HEX:			JP	HEX		;1FB8H
_ASC:			JP	ASC		;1FBBH
_PRTHL:			JP	PRTHL	;1FBEH
_PRTHX:			JP	PRTHX	;1FC1H
_BELL:			JP	BELL	;1FC4H
_PAUSE:			JP	PAUSE	;1FC7H
_INKEY:			JP	INKEY	;1FCAH
_BRKEY:			JP	BRKEY	;1FCDH
_GETKY:			JP	GETKY	;1FD0H
_GETL:			JP	GETL	;1FD3H
_LPTOF:			JP	LPTOF	;1FD6H
_LPTON:			JP	LPTON	;1FD9H
_LPRNT:			JP	LPRNT	;1FDCH
_TAB:			JP	TAB		;1FDFH
_MPRNT:			JP	MPRNT	;1FE2H
_MSX:			JP	MSX		;1FE5H
_MSG:			JP	MSG		;1FE8H
_NL:			JP	NL		;1FEBH
_LTNL:			JP	LTNL	;1FEEH
_PRNTS:			JP	PRNTS	;1FF1H
_PRINT:			JP	PRINT	;1FF4H
_VER:			JP	VER	;1FF7H
_HOT:			JP	DOSHOT	;1FFAH
_COLD:			JP	COLD	;1FFDH
;	SWORDで拡張された部分
_DRDSB:			JP	read_disk	;2000H
_DWTSB:			JP	write_disk	;2003H
_DIR:			JP	DIR		;2006H
_ROPEN:			JP	ROPEN	;2009H
_SET:			JP	SETP	;200CH
_RESET:			JP	RESET	;200FH
_NAME:			JP	NAME	;2012H
_KILL:			JP	KILL	;2015H
_CSR:			JP	CSR		;2018H
_SCRN:			JP	SCRN	;201BH
_LOC:			JP	LOC		;201EH
_FLGET:			JP	FLGET	;2021H
_RDVSW:			JP	RDVSW	;2024H
_SDVSW:			JP	SDVSW	;2027H
_INP:			JP	INP		;202AH
_OUT:			JP	OUTP	;202DH
_WIDCH:			JP	WIDCH	;2030H
_ERROR:			JP	RSERR	;2033H
_BOOT:			JP	BOOT	;2036H
;NEXT	2039H
GTPRC:			JP	GTPRC0	;2039H
LINCH:			JP	LINCH0	;203CH
;NEXT	203FH


;	204BH～20FEHはバッチ変数バッファ


;	_ETRK（20FFH）はデバイス「E:」のクラスタ数


;	共通DOSモジュール組み込み（20FFH～28CCH）
	; INCLUDE	SWEMDOS

	ORG	20FFH
_ETRK:	DS	1	;ＲＡＭディスクのクラスタ数

	ORG	2100H

;〈注意〉
;　仕様と違い、ディスクをアクセスするファンクションは、ＡＦ'が破壊されます。


;〈セーブ動作〉
;　「_FILE」「_WOPEN」「_WRD」の順で呼び出します。


;〈ロード動作〉
;　「_FILE」「_ROPEN」「_RDD」の順で呼び出します。


;	各機種ディスクＩ／Ｏ
; DREAD	EQU	2B00H
; DWRITE	EQU	2B03H
; disk_unit_number	EQU	2B06H


;	Ｓ-ＯＳエントリ
; _MON	EQU	1F8EH
; _BELL	EQU	1FC4H
; _LPTOF	EQU	1FD6H
; _BRKEY	EQU	1FCDH	;未使用
; _HLHEX	EQU	1FB2H
; _PRINT	EQU	1FF4H
; _PRNTS	EQU	1FF1H
; _PRTHX	EQU	1FC1H
; _PRTHL	EQU	1FBEH
; _MSG	EQU	1FE8H
; _MSX	EQU	1FE5H
; _MPRNT	EQU	1FE2H
; _LTNL	EQU	1FEEH
; _NL	EQU	1FEBH
; _PAUSE	EQU	1FC7H
; _FPRNT	EQU	1F9DH
; _FILE	EQU	1FA3H
; _GETKY	EQU	1FD0H
; _GETL	EQU	1FD3H
; _WRD	EQU	1FACH
; _WOPEN	EQU	1FAFH
; _RDD	EQU	1FA6H
; _DIR	EQU	2006H
; _ROPEN	EQU	2009H
; _SET	EQU	200CH
; _RESET	EQU	200FH
; _NAME	EQU	2012H
; _KILL	EQU	2015H
; _RDVSW	EQU	2024H
; _SDVSW	EQU	2027H
; _WIDCH	EQU	2030H
; _ERROR	EQU	2033H
; _BOOT	EQU	2036H
;
; _DSK	EQU	1F5DH
; _IBFAD	EQU	1F74H
; _DIRNO	EQU	1F67H
; _FATBF	EQU	1F62H
; _DTBUF	EQU	1F64H
; ; _FATPS	EQU	1F5EH
; _DIRPS	EQU	1F60H
; _MXTRK	EQU	1F66H
; _SIZE	EQU	1F72H
; _DTADR	EQU	1F70H
; _EXADR	EQU	1F6EH
; _DVSW	EQU	1F7DH
; _STKAD	EQU	1F6CH
; _KBFAD	EQU	1F76H
; _WIDTH	EQU	1F5CH


;	Ｓ-ＯＳ内部エントリ
; _RDI	EQU	2900H
; _TROPN	EQU	2903H
; _WRI	EQU	2906H
; _TWRD	EQU	2909H
; _TRDD	EQU	290CH
; _TDIR	EQU	290FH
; _DVCHK	EQU	2915H
; _OPNFG	EQU	291EH
; _FTYPE	EQU	291FH
; _DFDV	EQU	2920H
; _PARSC	EQU	292AH
; _PARCS	EQU	293FH


;===============
;モニタ処理
;===============


DOSHOT:
	LD	SP,(_STKAD)
	CALL	_LPTOF
	LD	A,'#'
	CALL	_PRINT
	LD	DE,(_KBFAD)
	CALL	_GETL
	CALL	MCOM
	CALL	C,_ERROR
	JR	DOSHOT


;コマンド･ライン･ルーチン
;出力	ＣＹ＝１でエラー
MCOM:
	LD	A,(DE)
	CP	'#'
	JR	Z,$+4
	OR	A
	RET
;	INC	DE
;	LD	A,(DE)
;	INC	DE
	CALL	MCOM1
	OR	A
	RET	Z
	CP	'!'
	JP	Z,_BOOT	;ブート
	CP	'J'
	JP	Z,JUMP	;ジャンプ
	CP	'L'
	JP	Z,LOAD	;ロード
	CP	'K'
	JP	Z,MKILL	;デリート
	CP	'N'
	JP	Z,MNAME	;リネーム
	CP	'M'
	JP	Z,DOSMON	;モニタ
	CP	'W'
	JP	Z,MWIDTH	;表示桁
	CP	'S'
	JR	Z,CMDSB1	;プロテクト（ＳＴ），セーブ（Ｓ）
	CP	'D'
	JR	Z,CMDSB2	;デフォルト･デバイス（ＤＶ），ディレクトリ（Ｄ）
;	LD	A,13	;Syntax Error
;	SCF
;	RET
	JP	EXCOM
	DS	1


;モニタ Ｓｘコマンド処理
CMDSB1:
	LD	A,(DE)
	CALL	TOUPER	;小文字→大文字変換
	INC	DE
	CP	'T'
	JP	Z,MSET	;モニタ ＳＴコマンド処理
	DEC	DE
	JP	SAVE	;モニタ Ｓコマンド処理


;モニタ Ｄｘコマンド処理
CMDSB2:
	LD	A,(DE)
	CALL	TOUPER	;小文字→大文字変換
	INC	DE
	CP	'V'
	JP	Z,DEVST	;モニタ ＤＶコマンド処理
	DEC	DE
	JP	MDIR	;モニタ Ｄコマンド処理


;モニタ Ｊコマンド処理
JUMP:	CALL	SPCUT	;文字列の空白を読み飛ばします
	CALL	_HLHEX
	LD	A,13	;Syntax Error
	RET	C
;	6バイト
	; IF	0
	; EX	DE,HL
	; LD	HL,DOSHOT
	; EX	(SP),HL
	; EX	DE,HL
	; JP	(HL)
	; ENDIF
;	ＤＥ保存のための改定
	EX	(SP),HL	;スタック←ジャンプ先
	LD	HL,DOSHOT
	EX	(SP),HL	;スタック←DOSHOT，ＨＬ←ジャンプ先
	JP	(HL)
	DS	1


;モニタ Ｍコマンド処理
DOSMON:	JP	_MON


;モニタ Ｄコマンド処理
MDIR:
	CALL	SPCUT	;文字列の空白を読み飛ばします
	CALL	GETDEV	;文字列からデバイス名を得ます
	LD	(_DSK),A
	CALL	_DIR
	RET


;モニタ Ｓコマンド処理
SAVE:
	CALL	SPCUT	;文字列の空白を読み飛ばします
	LD	A,1
	CALL	_FILE
	LD	A,(DE)
	CP	':'
	JR	NZ,SNERR
	INC	DE

	CALL	_HLHEX
	JR	C,SNERR
	LD	(_DTADR),HL	;先頭アドレス
	LD	(_EXADR),HL	;仮実行アドレス
	INC	DE	;「:」をスキップ

	CALL	_HLHEX
	JR	C,SNERR
	PUSH	DE
	LD	DE,(_DTADR)
	OR	A
	SBC	HL,DE
	POP	DE
	JR	C,SNERR
	INC	HL
	LD	(_SIZE),HL	;サイズ
	INC	DE	;「:」などをスキップ

;	実行アドレスが指定されているときだけ
	CALL	_HLHEX
	JR	C,SAVE1
	LD	(_EXADR),HL	;実行アドレス

SAVE1:	CALL	_WOPEN
	RET	C	;エラー
	CALL	_WRD
	RET	C
	CALL	_NL
	LD	DE,OK
	CALL	_MSG
	JP	_NL
SNERR:	LD	A,13	;Syntax Error
	SCF
	RET


;モニタ Ｌコマンド処理
LOAD:
	LD	A,1
	CALL	_FILE
	LD	A,(DE)
	OR	A
	LD	(LDWORK+2),A	;ロード･アドレス存在フラグ
	JR	Z,LOAD1	;ロード･アドレスの指定なし
;	ロード･アドレスの指定あり
	INC	DE
	CALL	_HLHEX
	JR	C,SNERR	;ロード･アドレスが不正
	LD	(LDWORK),HL	;←ロード･アドレス

LOAD1:	CALL	_ROPEN
	RET	C	;エラー
	CALL	NZ,SKPRT	;テープのスキップしているファイル名を表示します
	JR	NZ,LOAD1

	CALL	_MPRNT
	DB	'Loading ',00H
	CALL	_FPRNT
	CALL	_NL

;	ロード･アドレスの設定
	LD	A,(LDWORK+2)
	OR	A
	JR	Z,LOAD3
	LD	HL,(LDWORK)
	LD	(_DTADR),HL

;	ロードします
LOAD3:	JP	_RDD

LDWORK:	DS	2	;ロード･アドレス
	DS	1	;ロード･アドレス･フラグ（＝０でロード･アドレスが無効）


;テープのスキップしているファイル名を表示します
;破壊	ＤＥ
SKPRT:
	PUSH	AF
	CALL	_MPRNT
	DB	'Found   ',00H
	CALL	_FPRNT
	CALL	_NL
	POP	AF
	RET


;モニタ Ｋコマンド処理
MKILL:
	CALL	SPCUT	;文字列の空白を読み飛ばします
	CALL	_FILE
	RET	C	;エラー
	CALL	_KILL
	RET


;モニタ ＳＴコマンド処理
MSET:
	CALL	SPCUT	;文字列の空白を読み飛ばします
	CALL	_FILE
	INC	DE
;	CALL	SPCUT	;文字列の空白を読み飛ばします
;	LD	A,(DE)
	CALL	MSET1	;小文字受け付けのため
	NOP
	CP	'P'
	JP	Z,_SET
	CP	'R'
	JP	Z,_RESET
;	パラメータが「P」でも「R」でもない
	LD	A,13	;Syntax Error
	SCF
	RET


;モニタ ＤＶコマンド処理
DEVST:
	CALL	SPCUT	;文字列の空白を読み飛ばします
	LD	A,(DE)
	CALL	TOUPER	;小文字→大文字変換
	CALL	_DVCHK	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	JR	NC,DEVST1
	LD	A,3	;Bad File Descripter
	RET
DEVST1:	LD	(_DSK),A
	JP	_SDVSW


;モニタ Ｎコマンド処理
MNAME:
	CALL	SPCUT	;文字列の空白を読み飛ばします
	CALL	_FILE
	LD	A,(DE)
	INC	DE
	CP	':'
	JP	Z,_NAME
	LD	A,13	;Syntax Error
	SCF
	RET


;モニタ Ｗコマンド処理
;注：８０桁モード以外なら４０桁モードにしています。
MWIDTH:	LD	A,(_WIDTH)
	CP	80
	JR	NZ,MWDTH1
	LD	A,40
	JP	_WIDCH
MWDTH1:	LD	A,80
	JP	_WIDCH


;文字列の空白を読み飛ばします
;入力	ＤＥ←文字列の先頭アドレス
;出力	ＤＥ←カウント･アップ
;破壊	ＡＦ，ＤＥ
	INC	DE
SPCUT:
	LD	A,(DE)
	CP	' '
	JR	Z,SPCUT-1
	RET


;=======================================
;拡張されたＳ-ＯＳファンクション本体
;=======================================


;文字列からデバイス名を得ます
;入力	ＤＥ←文字列のアドレス
;出力	Ａｃｃ←デバイス名、ＤＥ←カウント･アップ
;破壊	ＡＦ，ＤＥ
;注：
;　小文字は大文字に変換されます。
;　デバイス名が省略された場合、デフォルト･デバイスが採用されます。
GETDEV:
	CALL	SPCUT	;文字列の空白を読み飛ばします
;	INC	DE
;	LD	A,(DE)	;Ａｃｃ←２文字目
;	DEC	DE
	CALL	GDVPAT	;GETDEVのバグ回避
	CP	':'
	JR	Z,$+5
	JP	RDVSW	;＝#RDVSW（2024H）

	LD	A,(DE)
	INC	DE
	INC	DE


;小文字→大文字変換
;入力	Ａｃｃ←アスキー･コード
;出力	Ａｃｃ←変換されたアスキー･コード
;破壊	ＡＦ
TOUPER:
	CP	'a'
	RET	C
	CP	'z'+1
	RET	NC
	AND	11011111B	;b5リセット
	RET


;#WOPEN（1FAFH）の本体
;注：
;　仕様と違いＡＦ'が破壊されます。
;　テープではインフォメーション･ファイルを書き込み、
;ディスクでは空きエリアをチェックします。
;　正常終了ＣＹ＝０（Ａｃｃ←０）。
WOPEN:
	CALL	CLOSE	;[_OPNFG]←０
	LD	A,(_DSK)
	CALL	DEVCHK	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	RET	C	;エラー
	JP	Z,_WRI	;カセットにインフォメーション･ファイルをセーブします

;	テープ以外
	CALL	DSKCHK	;デバイス名がＦＤかチェックします
	JR	NC,WOPEN1
	RET		;エラー（テープ，ディスク以外）

WOPEN1:	CALL	FATRED	;ＦＡＴを読みます
	RET	C	;エラー
	CALL	FCBSCH	;ファイルを検索します（属性は無視）
	JR	NZ,WOPEN2

;	同じファイル名のファイルがあった
	LD	A,(HL)
	CALL	WPCHK	;ファイルのライト･プロテクトのチェック
	RET	C	;エラー
	CALL	FMCHK	;属性をチェックします
	RET	C	;エラー
;
	PUSH	HL
	LD	BC,30
	ADD	HL,BC
	LD	A,(HL)	;Ａｃｃ←ファイルの開始クラスタ
	POP	HL
	CALL	ERAFAT	;ＦＡＴバッファから指定のクラスタ･チェインをカットします
	RET	C	;エラー
	JR	WOPEN3

;	同じファイル名のファイルがなかった
WOPEN2:	CALL	FRESCH	;ディスクに空きエリアがあるかチェックします
	LD	A,9	;Bad Record
	RET	C	;エラー

WOPEN3:	LD	(DEBUF),DE	;アクセスするレコード番号の一時保存場所
	LD	(HLBUF),HL	;参照ＦＣＢのアドレスの一時保存場所
	CALL	_PARCS	;Ｓ-ＯＳのカセットのアドレス情報を、機種依存のワークに転送します
	CALL	OPEN	;[_OPNFG]←１
	XOR	A	;ＣＹ←０，Ａｃｃ←０
	RET


;#ROPEN（2009H）の本体
;注：
;　仕様と違いＡＦ'が破壊されます。
;　テープではインフォメーション･ファイルの読み込み、
;ディスクではファイルの存在のチェック。
;　正常終了ＣＹ＝０（Ａｃｃ←０）。
ROPEN:
	CALL	CLOSE	;[_OPNFG]←０
	LD	A,(_DSK)
	CALL	DEVCHK	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	RET	C	;エラー
	JP	Z,_TROPN	;テープのリード･オープン

;	テープ以外
	CALL	DSKCHK	;デバイス名がＦＤかチェックします
	JR	NC,ROPEN1
	RET		;エラー（テープ，ディスク以外）

;	ディスクの場合
ROPEN1:	CALL	FCBSCH	;ファイルを検索します（属性は無視）
	RET	C	;エラー
	LD	A,8	;File not Found
	SCF
	RET	NZ	;エラー（ファイルが見つからなかった）

;	一致したＦＣＢを、ＦＣＢバッファに転送します
	PUSH	HL
	LD	DE,(_IBFAD)
	LD	BC,32
	LDIR
	POP	HL

;	属性を比較します
	LD	A,(HL)
	CALL	FMCHK	;属性をチェックします
	RET	C	;エラー

;	アドレス情報の転送など
ROPEN2:	CALL	_PARSC	;機種依存のカセットのアドレス情報を、Ｓ-ＯＳのワークに転送します
	CALL	OPEN	;[_OPNFG]←１
	XOR	A	;ＣＹ←０，Ａｃｃ←０
	RET


;#WRD（1FACH）の本体
;注：
;　仕様と違いAF'が破壊されます。
;　正常終了ＣＹ＝０（Ａｃｃ←０）。
WRD:
	LD	A,(_DSK)
	CALL	DEVCHK	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	RET	C	;エラー
	JP	Z,_TWRD	;カセットにデータ･ファイルをセーブします

;	テープ以外
	LD	A,(_OPNFG)
	OR	A
	JR	NZ,WRD1
	SCF
	LD	A,12	;File not Open
	RET		;オープンされてなかった
WRD1:	CALL	CLOSE	;[_OPNFG]←０
	LD	A,(_DSK)
	CALL	DSKCHK	;デバイス名がＦＤかチェックします
	RET	C	;エラー（テープ，ディスク以外）

;	ディスクの場合
	CALL	DSAVE	;ディスクにファイルを書き込みます
	RET


;#RDD（1FA6H）の本体
;注：
;　仕様と違いＡＦ'が破壊されます。
;　正常終了ＣＹ＝０（Ａｃｃ←０）。
;　[_DIRNO]、[RETPOI]をクリアします。
RDD:
	LD	A,(_DSK)
	CALL	DEVCHK	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	RET	C	;エラー
	JP	Z,_TRDD	;カセットのデータ･ファイルをロードします

;	テープ以外
	XOR	A
	LD	(_DIRNO),A	;クローズ処理
	LD	(RETPOI),A	;以前正しいＦＣＢがロードされたかのフラグ
	LD	A,(_OPNFG)
	OR	A
	JR	NZ,RDD1
	SCF
	LD	A,12	;File not Open
	RET		;オープンされてなかった
RDD1:	CALL	CLOSE	;[_OPNFG]←０
	LD	A,(_DSK)
	CALL	DSKCHK	;デバイス名がＦＤかチェックします
	RET	C	;エラー（テープ，ディスク以外）

;	ディスクの場合
	CALL	FATRED	;ＦＡＴを読みます
	RET	C	;エラー
	CALL	DLOAD	;ディスクからファイルを読み込みます
	RET


;#FCB（1FA9H）の本体
;〈解説〉
;　ＥＳＣキーが押されていれば、ＣＹ＝１（Ａｃｃ←８）で戻ります
;（[_DIRNO]はクリア）。
;　ＲＥＴキーが押されていれば、[_DIRNO]をカウント･ダウン
;（以前正しくロードされたＦＣＢ）。
;注：
;　仕様と違いＡＦ'が破壊されます。
;　ファイルのオープンと同等。
;　正常終了ＣＹ＝０（Ａｃｃ←０）。
GETFCB:
	CALL	CLOSE	;[_OPNFG]←０
	LD	A,(_DSK)
	CALL	DEVCHK	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	RET	C	;エラー
	JR	NZ,GETFC1	;テープ以外

;	テープの場合
	CALL	TRDVSW	;#DVSWからテープのデバイス名を求めます
	LD	(_DSK),A
	JP	_RDI	;カセットのインフォメーション･ファイルをロードします

;	テープ以外
GETFC1:	CALL	_GETKY
	CP	1BH	;ＥＳＣ
	JP	Z,DEND	;[_DIRNO]と[RETPOI]をクリアしてエラーＮｏ.８でリターン
	CP	0DH	;ＲＥＴ
	JR	NZ,GETFC2

;	ＲＥＴキーが押された場合
	LD	A,(RETPOI)	;以前正しいＦＣＢがロードされたかのフラグ
	OR	A
	JR	NZ,DECPOI	;[_DIRNO]をカウント･ダウンして、[RETPOI]をクリアしてエラーＮｏ.８でリターン

;	[_DIRNO]に対応するレコードを読み込みます
GETFC2:	LD	A,(_DIRNO)
	LD	C,A	;Ｃ←[_DIRNO]
	LD	B,3
SFR41:	SRL	A	;Ａｃｃ←[_DIRNO]÷８
	DJNZ	SFR41
	LD	HL,(_DIRPS)
	LD	D,0
	LD	E,A	;ＤＥ←[_DIRNO]÷８
	ADD	HL,DE
	EX	DE,HL	;ＤＥ←[_DIRNO]に対応するＦＣＢが存在するディスクのレコード番号
	LD	HL,(_DTBUF)
	LD	A,1
	CALL	read_disk	;=#DRDSB（2000H）
	JR	C,ERRRET	;[_DIRNO]と[RETPOI]をクリア（ＡＦ保存）

;	有効なＦＣＢかチェック
	LD	A,C	;Ａｃｃ←[_DIRNO]
	AND	00000111B
	LD	B,5
SFL51:	ADD	A,A	;Ａｃｃ←[_DIRNO]の下位３ビット×３２
	DJNZ	SFL51
	LD	HL,(_DTBUF)
	ADD	A,L
	LD	L,A
	JR	NC,$+3
	INC	H	;ＨＬ←[_DTBUF]＋[_DIRNO]の下位３ビット×３２
	LD	A,(HL)	;Ａｃｃ←[_DIRNO]に対応するＦＣＢの属性
	OR	A
	JR	Z,NEXT1	;未使用ＦＣＢ
	CP	0FFH	;最後のＦＣＢを通過したか
	JR	Z,DEND	;[_DIRNO]と[RETPOI]をクリアしてエラーＮｏ.８でリターン

	LD	DE,(_IBFAD)
	LD	BC,32
	LDIR
	CALL	INCPOI	;[_DIRNO]をカウント･アップして、[RETPOI]に[_DIRNO]をコピーします
	JP	ROPEN2	;アドレス情報の転送など

;	未使用ＦＣＢだった
NEXT1:	CALL	INCPOI	;[_DIRNO]をカウント･アップして、[RETPOI]に[_DIRNO]をコピーします
	JR	NC,GETFC1
	RET


;[_DIRNO]をカウント･アップして、[RETPOI]に[_DIRNO]をコピーします
;入力	なし
;出力	ＣＹ＝１なら、[_MXTRK]に達した、
;	[_DIRNO]と[RETPOI]をクリアしてエラーＮｏ.８でリターン
;破壊	ＡＦ，ＨＬ
INCPOI:
	LD	HL,_DIRNO
	INC	(HL)
	LD	A,(HL)
	LD	HL,_MXTRK
	CP	(HL)
	JR	Z,DEND	;[_DIRNO]と[RETPOI]をクリアしてエラーＮｏ.８でリターン
	LD	(RETPOI),A
	OR	A
	RET


;[_DIRNO]と[RETPOI]をクリア（ＡＦ保存）
;入力	なし
;出力	[_DIRNO]←０、[RETPOI]←０
;破壊	なし
ERRRET:
	PUSH	AF
	CALL	DEND	;[_DIRNO]と[RETPOI]をクリアしてエラーＮｏ.８でリターン
	POP	AF
	RET


;[_DIRNO]をカウント･ダウンして、[RETPOI]をクリアしてエラーＮｏ.８でリターン
;入力	なし
;出力	[_DIRNO]をカウント･ダウン、[RETPOI]←０
;破壊	ＡＦ，ＨＬ
DECPOI:
	LD	HL,_DIRNO
	LD	A,(HL)
	OR	A
	JR	Z,$+3
	DEC	(HL)
	XOR	A
	JR	DEND1


;[_DIRNO]と[RETPOI]をクリアしてエラーＮｏ.８でリターン
;入力	なし
;出力	[_DIRNO]←０、[RETPOI]←０
;破壊	ＡＦ
DEND:
	XOR	A
	LD	(_DIRNO),A
DEND1:	LD	(RETPOI),A
	LD	A,8	;File not Found
	SCF
	RET

;注：
;　00H以外で、以前に正しいＦＣＢがロードされたことをあらわします。
;　#RDDを実行すると、クリアされます。
RETPOI:	DB	0	;以前正しいＦＣＢがロードされたかのフラグ


;#DIR（2006H）の本体
;注：仕様と違いＡＦ'が破壊されます。
DIR:
	LD	A,(_DSK)
	CALL	DEVCHK	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	RET	C	;正しくなかった
	JP	Z,_TDIR	;テープのディレクトリを表示します

;	テープ以外
	CALL	DSKCHK	;デバイス名がＦＤかチェックします
	RET	C	;エラー（テープ，ディスク以外）

;	ディスク
	CALL	FATRED	;ＦＡＴを読みます
	RET	C	;エラー
	LD	A,'$'
	CALL	_PRINT
	CALL	FRECLU	;空きクラスタ数を得ます
	CALL	_PRTHX
	LD	DE,CSTMES	;「 Clusters Free」
	CALL	_MSX
	LD	B,16
	LD	DE,(_DIRPS)

DIRL:	LD	HL,(_DTBUF)
	LD	A,1
	CALL	read_disk	;=#DRDSB（2000H）
	RET	C	;エラー
	CALL	DIRPRT	;ディレクトリを１セクタ分表示します
	RET	Z
	INC	DE
	DJNZ	DIRL

	XOR	A
	RET


;ディレクトリを１セクタ分表示します
;入力	ＨＬ←ディレクトリのアドレス（２５６バイト)
;出力	ＺＦ＝１ならブレイクされた
;破壊	ＡＦ，ＨＬ
DIRPRT:
	PUSH	BC
	PUSH	DE
	LD	B,8

DIRPL:	LD	A,(HL)
	OR	A	;＝00Hで未使用
	JR	Z,DIRN
	CP	0FFH	;＝FFHで未使用領域
	JR	Z,DIRPE
	CALL	PFNAM	;ファイル情報を表示します
	CALL	_LTNL
	CALL	_PAUSE
	DW	DIRPE
DIRN:	LD	DE,20H
	ADD	HL,DE
	DJNZ	DIRPL

	DB	3EH
DIRPE:	XOR	A
	POP	DE
	POP	BC
	OR	A
	RET


;#KILL（2015H）の本体
;注：仕様と違いＡＦ'が破壊されます。
KILL:
	LD	A,(_DSK)
	CALL	ALCHK	;デバイス名がＦＤかチェックします
	RET	C
	CALL	DSKCHK	;デバイス名がＦＤかチェックします
	RET	C

;	ＦＡＴを読みます
	CALL	FATRED	;ＦＡＴを読みます
	RET	C

;	ファイル名を検索
	CALL	FCBSCH	;ファイルを検索します（属性は無視）
	RET	C
	LD	A,8	;File not Found
	SCF
	RET	NZ	;ファイルが見つからない
	LD	A,(HL)
	CALL	WPCHK	;ファイルのライト･プロテクトのチェック
	RET	C	;エラー

;	ディレクトリ･バッファとＦＡＴバッファを書き換えます
	LD	(HL),0	;未使用をあらわします
	PUSH	HL
	LD	BC,30
	ADD	HL,BC
	LD	A,(HL)	;Ａｃｃ←ファイルの開始クラスタ
	POP	HL
	CALL	ERAFAT	;ＦＡＴバッファから指定のクラスタ･チェインをカットします
	RET	C	;エラー

;	ディスクを書き換えます（先にディレクトリを）
	LD	HL,(_DTBUF)
	LD	A,1
	CALL	write_disk	;=#DWRSB（2003H）の本体
	CALL	NC,FATWRT	;ＦＡＴを書き込みます
	RET


;#NAME（2012H）の本体
;注：仕様と違いＡＦ'が破壊されます。
NAME:
	LD	A,(_DSK)
	CALL	ALCHK	;デバイス名がＦＤかチェックします
	RET	C
	CALL	DSKCHK	;デバイス名がＦＤかチェックします
	RET	C

;	変更前のファイル名を検索
	PUSH	DE
	CALL	FCBSCH	;ファイルを検索します（属性は無視）
	LD	(DEBUF),DE	;アクセスするレコード番号の一時保存場所
	LD	(HLBUF),HL	;参照ＦＣＢのアドレスの一時保存場所
	POP	DE
	RET	C	;エラー
	LD	A,8	;File not Found
	SCF
	RET	NZ	;ファイルが見つからない
	LD	A,(HL)
	CALL	WPCHK	;ファイルのライト･プロテクトのチェック
	RET	C	;エラー

;	変更後のファイル名を検索
	LD	A,(_DSK)
	PUSH	AF
	CALL	_FILE
	POP	AF
	LD	(_DSK),A
	CALL	FCBSCH	;ファイルを検索します（属性は無視）
	RET	C	;エラー
	LD	A,10	;File Already Exists
	SCF
	RET	Z	;変更しようとしたファイル名が既に存在した

;	ディレクトリを再読み込み（変更後のファイル名検索で、バッファ破壊のため）
	LD	DE,(DEBUF)	;アクセスするレコード番号の一時保存場所
	LD	HL,(_DTBUF)
	LD	A,1
	CALL	read_disk	;=#DRDSB（2000H）
	RET	C	;エラー

;	ディレクトリ･バッファのファイル名を変更します
	LD	HL,(_IBFAD)
	INC	HL
	LD	DE,(HLBUF)	;参照ＦＣＢのアドレスの一時保存場所
	INC	DE
	LD	BC,17
	LDIR

	LD	DE,(DEBUF)	;アクセスするレコード番号の一時保存場所
	LD	HL,(_DTBUF)
	LD	A,1
	CALL	write_disk	;=#DWRSB（2003H）の本体
	RET


;#SET（200CH）の本体
;注：仕様と違いＡＦ'が破壊されます。
SETP:
	LD	A,(_DSK)
	CALL	ALCHK	;デバイス名がＦＤかチェックします
	RET	C
	CALL	DSKCHK	;デバイス名がＦＤかチェックします
	RET	C

;	ファイル名を検索
	CALL	FCBSCH	;ファイルを検索します（属性は無視）
	RET	C
	LD	A,8	;File not Found
	SCF
	RET	NZ	;ファイルが見つからない

;	ディレクトリ･バッファを書き換えます
	SET	6,(HL)	;属性b6←１

;	ディレクトリを書き換えます
	LD	HL,(_DTBUF)
	LD	A,1
	CALL	write_disk	;=#DWRSB（2003H）の本体
	RET


;#RESET（200FH）の本体
;注：仕様と違いＡＦ'が破壊されます。
RESET:
	LD	A,(_DSK)
	CALL	ALCHK	;デバイス名がＦＤかチェックします
	RET	C
	CALL	DSKCHK	;デバイス名がＦＤかチェックします
	RET	C

;	ファイル名を検索
	CALL	FCBSCH	;ファイルを検索します（属性は無視）
	RET	C
	LD	A,8	;File not Found
	SCF
	RET	NZ	;ファイルが見つからない

;	ディレクトリ･バッファを書き換えます
	RES	6,(HL)	;属性b6←０

;	ディレクトリを書き換えます
	LD	HL,(_DTBUF)
	LD	A,1
	CALL	write_disk	;=#DWRSB（2003H）の本体
	RET


;#DRDSB（2000H）の本体
;入力	ＨＬ←読み込みアドレス、ＤＥ←レコード番号、Ａｃｃ←レコード数
;出力	ＣＹ＝０(Ａｃｃ←０)なら成功、
;	ＣＹ＝１（Ａｃｃ←エラー･コード）なら失敗
;破壊	ＡＦ，ＡＦ'
read_disk:
	EX	AF,AF'	;ＡＦ'
	LD	A,(_DSK)
	CALL	ALCHK	;デバイス名がＦＤかチェックします
	RET	C
	CALL	DSKCHK	;デバイス名がＦＤかチェックします
	RET	C
	SUB	'A'
	LD	(disk_unit_number),A	;ディスクのユニット番号（０～）
	EX	AF,AF'
	CALL	DREAD	;ディスク読み込み
	RET


;#DWRSB（2003H）の本体
;入力	ＨＬ←書き込みアドレス、ＤＥ←レコード番号、Ａｃｃ←レコード数
;出力	ＣＹ＝０（Ａｃｃ←０）なら成功、
;	ＣＹ＝１（Ａｃｃ←エラー･コード）なら失敗
;破壊	ＡＦ，ＡＦ'
write_disk:
	EX	AF,AF'	;AF'
	LD	A,(_DSK)
	CALL	ALCHK	;デバイス名がＦＤかチェックします
	RET	C
	CALL	DSKCHK	;デバイス名がＦＤかチェックします
	RET	C
	SUB	'A'
	LD	(disk_unit_number),A	;ディスクのユニット番号（０～）
	EX	AF,AF'
	CALL	DWRITE	;ディスク書き込み
	RET


;[_OPNFG]←１
;入力	なし
;出力	[_OPNFG]←１
;破壊	なし
OPEN:
	PUSH	AF
	LD	A,1
	JR	CLOSE1


;[_OPNFG]←０
;入力	なし
;出力	[_OPNFG]←０
;破壊	なし
CLOSE:
	PUSH	AF
	XOR	A
CLOSE1:	LD	(_OPNFG),A
	POP	AF
	RET


;ファイルのライト･プロテクトのチェック
;入力	Ａｃｃ←属性（b6）
;出力	ＣＹ＝１ならライト･プロテクト（Ａｃｃ←４）
;破壊	Ｆ，（ＡＦ）
WPCHK:
	OR	A	;ＣＹ←０
	BIT	6,A
	RET	Z
	LD	A,4	;Write Protected
	SCF
	RET


;属性をチェックします
;入力	Ａｃｃ←属性（b7b2b1b0）
;	[_FTYPE]参照
;出力	ＣＹ＝１（Ａｃｃ←６）なら一致しない
;破壊	ＡＦ
FMCHK:
	PUSH	HL
	AND	10000111B
	LD	HL,_FTYPE
	CP	(HL)
	POP	HL
	RET	Z
	LD	A,6	;Bad File Mode
	SCF
	RET


;デバイス名がＦＤかチェックします
;入力	Ａｃｃ←デバイス名
;出力	ＣＹ＝１ならＦＤでない
;破壊	Ｆ（ＡＦ）
DSKCHK:
	CP	'A'
	JR	C,DSKCH1
;	CP	'D'+1
	CP	'E'+1	;ＲＡＭディスク対応のための改定
	CCF
	RET	NC
DSKCH1:	LD	A,11	;Reserved Feature
	RET


;デバイス名がＦＤかチェックします
;入力	Ａｃｃ←デバイス名
;出力	ＣＹ＝１ならＦＤでない
;破壊	Ｆ（ＡＦ）
;注：デバイス名が不正なら、Ａｃｃ←エラー･コード。
ALCHK:
	CALL	DEVCHK	;デバイス名が正しいか（A～L，S，T，Q）かチェックします
	RET	C
	CALL	TPCHK	;デバイス名がテープ（ＱＤ）かチェックします
	JR	NZ,$+6
	LD	A,3	;Bad File Descripter
	SCF
	RET
	CALL	DSKCHK	;デバイス名がＦＤかチェックします
	RET


;#RDVSW（2024H）の本体
RDVSW:
	LD	A,(_DFDV)	;デフォルト･デバイス
	CALL	TPCHK	;デバイス名がテープ（ＱＤ）かチェックします
	RET	NZ	;テープ以外ならそのままリターン


;#DVSWからテープのデバイス名を求めます
;入力	なし
;出力	Ａｃｃ←テープのデバイス名
;破壊	ＡＦ
TRDVSW:
	LD	A,(_DVSW)
	OR	A
	JR	NZ,$+4
	LD	A,'T'	;Ｓ-ＯＳ ２４００ｂｐｓ
	CP	1
	JR	NZ,$+4
	LD	A,'S'	;システム依存
	CP	3
	JR	NZ,$+4
	LD	A,'Q'	;ＱＤ
	RET


;#SDVSW（25C9H）の本体
SDVSW:
	PUSH	AF
	LD	(_DFDV),A	;デフォルト･デバイス
	CP	'T'	;0
	JR	NZ,$+3
	XOR	A
	CP	'S'	;1
	JR	NZ,$+4
	LD	A,1
	CP	'Q'	;3
	JR	NZ,$+4
	LD	A,3
	LD	(_DVSW),A
	POP	AF
	RET


;ディスクからファイルを読み込みます
;入力	[_IBFAD]～,[_FATBF]～ｅｔｃ参照
;出力	ＣＹ＝０（Ａｃｃ←０）なら成功、
;	ＣＹ＝１（Ａｃｃ←エラー･コード）なら失敗
;破壊	ＡＦ，ＨＬ，ＤＥ，ＢＣ，ＡＦ'
DLOAD:
	LD	HL,(_IBFAD)
	LD	BC,30
	ADD	HL,BC
	LD	A,(HL)	;Ａｃｃ←ファイルの開始クラスタ
	LD	(NXCLST),A	;アクセスするクラスタの一時保存場所
	LD	BC,(_SIZE)
	LD	HL,(_DTADR)

;	ロード･ループ
DLOAD1:	PUSH	HL
	LD	A,(NXCLST)	;アクセスするクラスタの一時保存場所
	LD	HL,(_FATBF)
	LD	E,A
	LD	D,0	;ＤＥ←アクセスするクラスタ番号
	ADD	HL,DE	;ＨＬ←ＦＡＴバッファのアクセスするクラスタの位置
	LD	A,(HL)	;次のクラスタへのチェイン情報
	LD	(NXCLST),A	;アクセスするクラスタの一時保存場所
	EX	DE,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	EX	DE,HL	;ＤＥ←アクセスするレコード位置（空きクラスタ番号×１６）
	POP	HL	;ＨＬ←[_DTADR]
	OR	A
	JR	Z,DLOAD2	;ＦＡＴが不正
	CP	80H
	JR	NC,DLOAD3	;最後のクラスタ
	LD	A,16	;４Ｋバイト読み込みます
	CALL	read_disk	;=#DRDSB（2000H）
	RET	C	;エラー
	LD	DE,1000H
	ADD	HL,DE	;メモリのカウント･アップ
	PUSH	HL
	LD	L,C
	LD	H,B
	OR	A
	SBC	HL,DE
	LD	C,L
	LD	B,H	;サイズのカウント･ダウン
	POP	HL	;ＨＬ←次のメモリ
	JR	NC,DLOAD1

;	エラー
DLOAD2:	LD	A,7	;Bad Allocation Table
	SCF
	RET

;	最後のクラスタ
DLOAD3:	SUB	7FH	;Ａｃｃ←読み込みセクタ数
	CP	16+1
	JR	NC,DLOAD2	;ＦＡＴが不正
	DEC	A	;Ａｃｃ←読み込みセクタ数－１（０～１５）
	DEC	BC	;Ｂ←読み込む最後のセクタ－１（０～１５）
	CP	B
	JR	NZ,DLOAD2	;ＦＡＴが不正
	LD	B,0
	INC	BC	;ＢＣ←最後のセクタのバイト数
	OR	A
	JR	Z,DLOAD4	;最後のクラスタは、セクタを１つだけ使用

;	最後のセクタ以外を読み込みます
	PUSH	AF
	CALL	read_disk	;=#DRDSB（2000H）
	JR	C,DLOAD5
	POP	AF	;Ａｃｃ←読み込みセクタ数－１（０～１５）

DLOAD4:	PUSH	DE
	LD	E,0
	LD	D,A	;ＤＥ←次に読み込むアドレスの変移
	ADD	HL,DE	;メモリのカウント･アップ
	EX	(SP),HL	;ＨＬ←最後のクラスタの先頭レコード番号，スタック←最後に読み込むメモリのアドレス
	LD	E,A
	LD	D,0	;ＤＥ←次に読み込むレコードの変移
	ADD	HL,DE

;	最後のセクタ以外を読み込みます
	EX	DE,HL	;ＤＥ←最後に読み込むレコード番号
	LD	HL,(_DTBUF)
	LD	A,1
	CALL	read_disk	;=#DRDSB（2000H）
DLOAD5:	POP	DE	;ＤＥ←最後に読み込むメモリのアドレス
	RET	C

;	[_DTBUF]～から最後のセクタの内容を正しいメモリに転送します
	LDIR
	XOR	A	;Ａｃｃ←０
	RET


;ディスクにファイルを書き込みます
;入力	[DEBUF]、[HLBUF]、[_FATBF]～ｅｔｃ参照
;出力	ＣＹ＝０（Ａｃｃ←０）なら成功、
;	ＣＹ＝１（Ａｃｃ←エラー･コード）なら失敗
;破壊	ＡＦ，ＨＬ，ＤＥ，ＢＣ，ＡＦ'
DSAVE:
	LD	DE,(DEBUF)	;アクセスするレコード番号の一時保存場所
	LD	HL,(HLBUF)	;参照ＦＣＢのアドレスの一時保存場所
	LD	BC,(_SIZE)
	PUSH	BC
	DEC	BC
	SRL	B
	SRL	B
	SRL	B
	SRL	B
	INC	B	;Ｂ←占有クラスタ数
	CALL	FRECLU	;空きクラスタ数を得ます
	CP	B
	POP	BC	;ＢＣ←[_SIZE]
	LD	A,9	;Device Full
	RET	C	;空き領域が足りない

;	タイム･スタンプとクラスタ値をクリア
	LD	HL,(_IBFAD)
	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	DE,24
	ADD	HL,DE
	LD	E,L
	LD	D,H
	INC	DE
	LD	(HL),0
	LD	BC,7
	LDIR
	POP	BC	;ＢＣ←[_SIZE]
	POP	DE	;ＤＥ←[DEBUF]
	POP	HL	;ＨＬ←[_IBFAD]

;	ＦＣＢのクラスタ値の設定
	LD	A,30
	ADD	A,L
	LD	L,A
	JR	NC,$+3
	INC	H	;ＨＬ←[_IBFAD]＋３０
	CALL	FCGET	;空きクラスタを得ます
	LD	(HL),A	;ＦＣＢのクラスタ値←空きクラスタ番号
	LD	HL,(_DTADR)

;	セーブ･ループ
DSAVE1:	PUSH	HL
	LD	HL,(_FATBF)
	LD	E,A
	LD	D,0	;ＤＥ←空きクラスタ番号
	ADD	HL,DE	;ＨＬ←ＦＡＴバッファの空きクラスタの位置
	EX	DE,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	EX	DE,HL	;ＤＥ←空きレコード位置（空きクラスタ番号×１６）
	DEC	BC
	LD	A,B
	INC	BC
	CP	16
	JR	C,DSAVE3	;最後のクラスタ
	LD	(HL),80H	;FCGETルーチンでスキップさせるため
	CALL	FCGET	;空きクラスタを得ます
	LD	(HL),A	;次のクラスタへのチェイン情報
	POP	HL	;ＨＬ←[_DTADR]
	PUSH	AF
	LD	A,16	;４Ｋバイト書き込みます
	CALL	write_disk	;=#DWRSB（2003H）の本体
	JR	C,DSAVE2	;エラー
	LD	DE,1000H
	ADD	HL,DE	;メモリのカウント･アップ
	PUSH	HL
	LD	L,C
	LD	H,B
	OR	A
	SBC	HL,DE
	LD	C,L
	LD	B,H	;サイズのカウント･ダウン
	POP	HL	;ＨＬ←次のメモリ
	POP	AF	;Ａｃｃ←次のクラスタ
	JR	DSAVE1

;	エラー
DSAVE2:	POP	HL	;スタック位置調整のため
	RET

;	最後のクラスタ
DSAVE3:	INC	A	;Ａｃｃ←書き込みセクタ数
	PUSH	AF
	ADD	A,7FH	;Ａｃｃ←８０Ｈ～８ＦＨ
	LD	(HL),A	;チェインの終わりを示す
	POP	AF	;Ａｃｃ←書き込みセクタ数
	POP	HL	;ＨＬ←メモリのアドレス
	CALL	write_disk	;=#DWRSB（2003H）の本体
	RET	C	;エラー

;	ＦＡＴの更新
	CALL	FATWRT	;ＦＡＴを書き込みます
	RET	C	;エラー

;	ディレクトリの更新
	LD	HL,(_IBFAD)
	LD	DE,(HLBUF)	;参照ＦＣＢのアドレスの一時保存場所
;	INC	DE	;無意味？
	LD	BC,32
	LDIR
	LD	HL,(_DTBUF)
	LD	DE,(DEBUF)	;アクセスするレコード番号の一時保存場所
	LD	A,1
	CALL	write_disk	;=#DWRSB（2003H）の本体
	RET	C
	XOR	A	;Ａｃｃ←０
	RET


;ＦＡＴを読みます
;入力	[_FATPS]、[_FATBF]参照
;出力	ＣＹ＝０（Ａｃｃ←０）なら成功、
;	ＣＹ＝１（Ａｃｃ←エラー･コード）なら失敗
;破壊	ＡＦ，ＡＦ'
FATRED:
	PUSH	DE
	PUSH	HL
	LD	DE,(_FATPS)
	LD	HL,(_FATBF)
	LD	A,1
	CALL	read_disk	;=#DRDSB（2000H）
	POP	HL
	POP	DE
	RET


;ＦＡＴを書き込みます
;入力	[_FATPS]、[_FATBF]～参照
;出力	ＣＹ＝０（Ａｃｃ←０）なら成功、
;	ＣＹ＝１（Ａｃｃ←エラー･コード）なら失敗
;破壊	ＡＦ，ＡＦ'
FATWRT:
	PUSH	DE
	PUSH	HL
	LD	DE,(_FATPS)
	LD	HL,(_FATBF)
	LD	A,1
	CALL	write_disk	;=#DWRSB（2003H）の本体
	POP	HL
	POP	DE
	RET


;空きクラスタ数を得ます
;入力	[_FATBF]～参照
;出力	Ａｃｃ←空きクラスタ数
;破壊	ＡＦ
FRECLU:
	PUSH	BC
	PUSH	HL
	LD	B,80H
	LD	C,0
	LD	HL,(_FATBF)

FRECL1:	LD	A,(HL)
	OR	A	;00Hが未使用
	JR	NZ,FRECL2
	INC	C
FRECL2:	INC	HL
	DJNZ	FRECL1

	LD	A,C
	POP	HL
	POP	BC
	RET


;空きクラスタを得ます
;入力	なし
;出力	Ａｃｃ←空きクラスタ番号
;	ＣＹ＝１なら空きクラスタがない
;破壊	ＡＦ
FCGET:
	PUSH	BC
	PUSH	HL
	LD	B,80H
	LD	HL,(_FATBF)

FCGET2:	LD	A,(HL)
	OR	A	;00Hは未使用クラスタ
	JR	Z,FCGET3
	INC	HL
	DJNZ	FCGET2

	SCF
	JR	FCGET4
FCGET3:	LD	A,80H
	SUB	B	;Ａｃｃ←空きクラスタ番号
	OR	A
FCGET4:	POP	HL
	POP	BC
	RET


;ＦＡＴバッファから指定のクラスタ･チェインをカットします
;入力	Ａｃｃ←ファイルの開始クラスタ
;出力	ＣＹ＝０（Ａｃｃ←０）なら正常終了、ＣＹ＝１（Ａｃｃ←７）ならエラー
;破壊	ＡＦ，ＤＥ
ERAFAT:
	PUSH	DE
	PUSH	HL
	LD	DE,(_FATBF)

ERAFA1:	LD	L,A
	LD	H,0	;ＨＬ←ファイルの開始クラスタ
	ADD	HL,DE	;ＨＬ←対応するＦＡＴバッファのアドレス
	LD	A,(HL)	;Ａｃｃ←チェインしているクラスタ番号
	LD	(HL),0
	CP	80H
	JR	C,ERAFA1	;チェインしていた

;	チェイン終了
	POP	HL
	POP	DE
	CP	90H
	JR	NC,ERAFA2	;９０Ｈ～のデータがあった
;	正常終了
	XOR	A
	RET

;	存在するはずのない数値があった
ERAFA2:	LD	A,7	;Bad Allocation Table
	SCF
	RET


;ファイルを検索します（属性は無視）
;入力	[_IBFAD]参照
;出力	ＺＦ＝１なら一致した
;	ＨＬ←一致したＦＣＢのあるアドレス、ＤＥ←一致したＦＣＢのあるレコード番号
;	ＣＹ＝１ならエラー（Ａｃｃ←エラー･コード）
;破壊	ＡＦ，ＨＬ，ＤＥ，ＡＦ'
FCBSCH:
	PUSH	BC
	LD	C,16
	LD	DE,(_DIRPS)

FCBSC1:	LD	HL,(_DTBUF)
	LD	A,1
	CALL	read_disk	;=#DRDSB（2000H）
	JR	C,FCBSC6	;エラー
	LD	B,8

FCBSC2:	LD	A,(HL)
	CP	0FFH
	JR	Z,FCBSC4
	OR	A
	JR	Z,FCBSC3
	PUSH	DE
	LD	DE,(_IBFAD)
;	CALL	FCOMP	;ファイル名を比較します
	CALL	FCOMPW	;ファイル名を比較します
	POP	DE
	JR	Z,FCBSC5	;一致した
FCBSC3:	PUSH	DE
	LD	DE,32
	ADD	HL,DE
	POP	DE
	DJNZ	FCBSC2

	INC	DE
	DEC	C
	JR	NZ,FCBSC1

FCBSC4:	DB	3EH	;「LD A,」
FCBSC5:	XOR	A
	OR	A
FCBSC6:	POP	BC
	RET


;ディスクに空きエリアがあるかチェックします
;入力	なし
;出力	ＨＬ←一空きＦＣＢのあるアドレス、ＤＥ←空きＦＣＢのあるレコード番号
;	ＣＹ＝１ならエラー（Ａｃｃ←エラー･コード）
;破壊	ＡＦ，ＨＬ，ＤＥ，ＡＦ'
FRESCH:
	PUSH	BC
	LD	C,16
	LD	DE,(_DIRPS)

FRESC1:	LD	HL,(_DTBUF)
	LD	A,1
	CALL	read_disk	;=#DRDSB（2000H）
	JR	C,FRESC3
	LD	B,8

FRESC2:	LD	A,(HL)
	OR	A
	JR	Z,FRESC4
	CP	0FFH
	JR	Z,FRESC4
	PUSH	DE
	LD	DE,32
	ADD	HL,DE
	POP	DE
	DJNZ	FRESC2

	INC	DE
	DEC	C
	JR	NZ,FRESC1

FRESC3:	DB	3EH	;「LD A,」
FRESC4:	XOR	A
	POP	BC
	RET


; 	IF	0
; ;ファイル名を比較します
; ;入力	ＨＬ←比較されるＦＣＢの先頭アドレス、
; ;	ＤＥ←比較するＦＣＢの先頭アドレス
; ;出力	ＺＦ＝１なら一致した
; ;破壊	ＡＦ
; FCOMP:
; 	PUSH	BC
; 	PUSH	DE
; 	PUSH	HL
; 	LD	B,16

; FCOMP1:	INC	DE
; 	INC	HL
; 	LD	A,(DE)
; 	CP	(HL)
; 	JR	NZ,FCOMP2	;不一致
; 	DJNZ	FCOMP1

; FCOMP2:	POP	HL
; 	POP	DE
; 	POP	BC
; 	RET
; 	ENDIF


;	FCOMPWの一部
FCMPW2:	LD	A,(DE)
	CP	C	;CP ' '
	RET	Z
FCMPW1:	LD	A,(DE)
	CP	'?'	;ワイルド･カード
	RET	Z
	CALL	TOUPER	;小文字→大文字変換
	LD	C,A
	LD	A,(HL)
	CALL	TOUPER	;小文字→大文字変換
	CP	C	;ＺＦ＝１なら一致
	RET


NXCLST:	DS	1	;アクセスするクラスタの一時保存場所（ロード･ルーチンで使用）
DEBUF:	DS	2	;アクセスするレコード番号の一時保存場所
HLBUF:	DS	2	;参照ＦＣＢのアドレスの一時保存場所


;P%FNAM（2912H）の本体
;ファイル情報を表示します
;入力	Ａｃｃ←属性、ＨＬ←ファイル情報の先頭アドレス
;出力	なし
;破壊	ＡＦ
PFNAM:
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	DE,(_IBFAD)
	LD	BC,0020H
	LDIR
	CALL	ATRPRT	;属性情報を表示します
	LD	A,(_DSK)
	CALL	_PRINT
	LD	A,':'
	CALL	_PRINT
	CALL	_FPRNT
ADRPRT:	CALL	_PARSC	;機種依存のカセットのアドレス情報を、Ｓ-ＯＳのワークに転送します
	LD	BC,(_SIZE)
	LD	HL,(_DTADR)
	LD	DE,(_EXADR)
	CALL	PHEX	;インナー･コール
	ADD	HL,BC
	DEC	HL
	CALL	PHEX	;インナー･コール
	EX	DE,HL
	CALL	PHEX	;インナー･コール
	POP	HL
	POP	DE
	POP	BC
	RET

PHEX:	LD	A,':'
	CALL	_PRINT
	CALL	_PRTHL
	RET


;属性情報を表示します
;入力	Ａｃｃ←属性
;出力	なし
;破壊	ＡＦ，ＨＬ，ＤＥ
ATRPRT:
	PUSH	AF
	LD	DE,ATRMES
	BIT	7,A
	JR	Z,ATRP1
;	ディレクトリの場合
	LD	A,8
	DB	11H	;「LD DE,」
ATRP1:	AND	07H	;Ａｃｃ←０～８
	LD	L,A
	LD	H,0
	ADD	HL,HL
	ADD	HL,HL
	LD	DE,ATRMES
	ADD	HL,DE
	EX	DE,HL
	CALL	_MSX
	POP	AF
	BIT	6,A
	LD	A,'*'
	JR	NZ,ATRP2
	LD	A,' '
ATRP2:	CALL	_PRINT
	CALL	_PRNTS
	RET


;%DEVCHK（2851H）の本体
;デバイス名が正しいか（A～L，S，T，Q）かチェックします
;入力	Ａｃｃ←デバイス名（小文字不可）
;出力	ＺＦ＝１ならテープ、ＣＹ＝１なら不正
;破壊	Ｆ（ＡＦ）
;注：デバイス名が不正なら、Ａｃｃ←エラー･コード。
DEVCHK:
	CALL	TPCHK	;デバイス名がテープ（ＱＤ）かチェックします
	RET	Z
	CP	'A'
	JR	C,DEVCH1	;「A」未満
;	「A」～
	CP	'L'+1
	CCF
	JR	C,$+4
	OR	A
	RET

DEVCH1:	LD	A,3	;Bad File Descripter
	RET


;%TPCHK（2918H）の本体
;デバイス名がテープ（ＱＤ）かチェックします
;入力	Ａｃｃ←デバイス名（小文字不可）
;出力	ＺＦ＝１ならテープ
;破壊	Ｆ
TPCHK:
	CP	'T'
	RET	Z
	CP	'S'
	RET	Z
	CP	'Q'
	RET


; ;#ERROR（2033H）の本体
; ERROR:
; 	DEC	A
; 	CP	14
; 	JR	C,ERROR1
; 	INC	A
; 	LD	DE,ER15
; 	PUSH	AF
; 	CALL	_MSG
; 	LD	A,'$'	;１６進数ヘッダ
; 	CALL	_PRINT
; 	POP	AF
; 	CALL	_PRTHX
; 	JR	ERROR2
; ERROR1:	LD	HL,MESTBL
; 	ADD	A,A
; 	LD	E,A
; 	LD	D,0
; 	ADD	HL,DE
; 	LD	E,(HL)
; 	INC	HL
; 	LD	D,(HL)
; 	CALL	_MSG
; ERROR2:	CALL	_BELL
; 	CALL	_NL
; 	RET


;	空きクラスタ表示用メッセージ
CSTMES:	DB	' Clusters Free',0DH,00H

;	属性メッセージ
ATRMES:	DB	'Nul',00H	;000
	DB	'Bin',00H	;001
	DB	'Bas',00H	;010
	DB	'???',00H	;011
	DB	'Asc',00H	;100
	DB	'???',00H	;101
	DB	'???',00H	;110
	DB	'???',00H	;111
	DB	'Dir',00H	;1xxxxxxx


;GETDEVルーチンのバグ回避処理
;ファイル･ディスクリプタのセパレータの位置の文字を得ます
GDVPAT:
	LD	A,(DE)
	OR	A
	RET	Z	;文字列の最後に達していた
	INC	DE
	LD	A,(DE)
	DEC	DE
	RET


;モニタ･コマンドで小文字を受け付けるため
MCOM1:	INC	DE
	LD	A,(DE)
	INC	DE
	JP	TOUPER	;小文字→大文字変換


;STコマンドで小文字を受け付けるため
MSET1:	CALL	SPCUT	;文字列の空白を読み飛ばします
	LD	A,(DE)
	JP	TOUPER	;小文字→大文字変換


;ファイル名を比較します（小文字、拡張子なしでも一致させるため）
;入力	ＨＬ←比較されるＦＣＢの先頭アドレス、
;	ＤＥ←比較するＦＣＢの先頭アドレス
;出力	ＺＦ＝１なら一致した
;破壊	ＡＦ
FCOMPW:
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	B,13

FCPWL1:	INC	DE
	INC	HL
	CALL	FCMPW1
	JR	NZ,FCMPWE
	DJNZ	FCPWL1

	LD	B,3

FCPWL2:	INC	DE
	INC	HL
	LD	C,' '
	CALL	FCMPW2
	JR	NZ,FCMPWE
	DJNZ	FCPWL2

FCMPWE:	POP	HL
	POP	DE
	POP	BC
	RET


	ORG	2A00H
MESTBL:	DW	ER1,ER2,ER3,ER4,ER5,ER6,ER7,ER8
	DW	ER9,ER10,ER11,ER12,ER13,ER14

ER1:	DB	'Device I/O Error',0DH
ER2:	DB	'Device Offline',0DH
ER3:	DB	'Bad File Descripter',0DH
ER4:	DB	'Write Protected',0DH
ER5:	DB	'Bad Record',0DH
ER6:	DB	'Bad File Mode',0DH
ER7:	DB	'Bad Allocation Table',0DH
ER8:	DB	'File not Found',0DH
ER9:	DB	'Device Full',0DH
ER10:	DB	'File Already Exists',0DH
ER11:	DB	'Reserved Feature',0DH
ER12:	DB	'File not Open',0DH
ER13:	DB	'Syntax '
ER15:	DB	'Error ',0DH
ER14:	DB	'Bad Data',0DH
OK:	DB	'Complete !',0DH


;=======================================
;内部ワーク＆内部ジャンプ･テーブル
;=======================================


	ORG	2900H
;%RDI（2900H）
;テープのインフォメーション･ファイルをロードします
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
_RDI:	JP	RDI


;%TROPN（2903H）
;テープのリード･オープン
;入力	[_DSK]←デバイス名
;出力	ZF＝1（Acc←0）ならファイルが見つかった
;	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
;注：
; ファイル名解析後呼び出すこと。
; ファイル名の先頭が20Hか0DHの場合は、常に一致とみなします。
_TROPN:	JP	TROPN


;%WRI（2906H）
;テープにインフォメーション･ファイルをセーブします
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
_WRI:	JP	WRI


;%TWRD（2909H）
;テープにデータ･ファイルをセーブします
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
_TWRD:	JP	TWRD


;%TRDD（290CH）
;テープのデータ･ファイルをロードします
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
_TRDD:	JP	TRDD


;%TDIR（290FH）
;テープのディレクトリを表示します
;入力	なし
;出力	CY＝1ならエラー（Acc←エラー･コード）
;破壊	AF，HL，DE，BC
_TDIR:	JP	TDIR


;P%FNAM（2912H）
;ファイル情報を表示します
;入力	Acc←ファイル属性、HL←ファイル情報の先頭アドレス
;出力	なし
;破壊	AF
_PFNAM:	JP	PFNAM


;%DVCHK（2915H）
;デバイス名が正しいか（A～L，S，T，Q）かチェックします
;入力	Acc←デバイス名（小文字不可）
;出力	ZF＝1ならテープ
;	CY＝1なら不正（Acc←エラー･コード）
;破壊	AF
_DVCHK:	JP	DEVCHK


;%TPCHK（2918H）
;デバイス名がテープ（QD）かチェックします
;入力	Acc←デバイス名（小文字不可）
;出力	ZF＝1ならテープ
;破壊	F
_TPCHK:	JP	TPCHK


;	291BH～291DHは未使用
	DS	3


;%OPNFG（291EH）
;ファイルのオープンの状態（＝0でクローズ,＝1でオープン）
_OPNFG:	DB	0


;%FTYPE（291FH）
;ファイル属性（ファイル名の解析でセットされます）
_FTYPE:	DS	1


;%DFDV（2920H）
;デフォルト･デバイス（初期値「A」）
_DFDV:	DB	'A'


;	2921H～2929Hは未使用
	DS	9


;%PARSC（292AH）
;機種依存のテープのアドレス情報を、S-OSのワークに転送します
;入力	なし
;出力	なし
;破壊	全レジスタ保存
_PARSC:
	PUSH	HL
	LD	HL,(fcb_buffer+18)
	LD	(_SIZE),HL
	LD	HL,(fcb_buffer+20)
	LD	(_DTADR),HL
	LD	HL,(fcb_buffer+22)
	LD	(_EXADR),HL
	POP	HL
	RET


;%PARCS（293FH）
;S-OSのテープのアドレス情報を、機種依存のワークに転送します
;入力	なし
;出力	なし
;破壊	全レジスタ保存
_PARCS:
	PUSH	HL
	LD	HL,(_SIZE)
	LD	(fcb_buffer+18),HL
	LD	HL,(_DTADR)
	LD	(fcb_buffer+20),HL
	LD	HL,(_EXADR)
	LD	(fcb_buffer+22),HL
	POP	HL
	RET


;=======================================
;フィジカル･ディスクI／Oエントリ
;=======================================
;注：本体は、サイズが大きいため、メイン部後ろ移転しました。


;	2D00H～2DFFHはバッチ･ファイル読み込みバッファ


	ORG	2D00H
;=======================
;ブート･プログラム
;=======================


START:
	DI
	LD	SP,0100H	;仮スタック

;	機種の判別
	LD	BC,37FFH
	IN	E,(C)	;E←テキストVRAMデータ
	LD	B,3FH	;BC←3FFFH
	IN	D,(C)	;D←漢字VRAMデータ
	LD	A,D
	CPL		;Acc←漢字VRAMデータの反転
	OUT	(C),A	;漢字VRAM←反転データ
	LD	B,37H	;BC←37FFH
	OUT	(C),E	;テキストVRAMを元に戻します
	LD	B,3FH	;BC←3FFFH
	IN	E,(C)	;E←書き込んで読み出したデータ
	OUT	(C),D	;漢字VRAMを元に戻します
	SUB	E	;X1：00H以外、turbo：00H
	ADD	A,0FFH	;X1：CY＝1、turbo：CY＝0
	SBC	A,A	;X1：FFH、turbo：00H
	CPL		;X1：00H、turbo：FFH
	LD	(X1TFLG),A

;	vram_address_of_topの初期化
	LD	HL,3000H
	LD	(vram_address_of_top),HL

;	デフォルト･ドライブの設定
	LD	A,(0FF87H)	;立ち上がったドライブ番号（下位ニブル）
	AND	1111B
	CP	4
	JR	NC,STADVS
	ADD	A,'A'	;Acc←立ち上がったドライブ名
	LD	(_DFDV),A	;デフォルト･ドライブ
STADVS:

;	[vram_size]の設定（VRAMのサイズ÷100H）
;〈VRAMのサイズ〉
;00C000Hバイト
	LD	HL,00C0H	;00C000H
	LD	(vram_size),HL

;	[top_of_special_work_of_vram]の設定（VRAM上の特殊ワークの先頭÷100H）
;〈VRAM特殊ワークの先頭アドレス〉
;004000H番地
	LD	HL,0040H	;004000H
	LD	(top_of_special_work_of_vram),HL

;	[size_of_special_work_of_vram]の設定（VRAM上の特殊ワークのサイズ÷100H）
;〈VRAM特殊ワークのサイズ〉
;4000Hバイト
	LD	A,40H	;4000H
	LD	(size_of_special_work_of_vram),A

;	[top_of_ram_disk_of_vram]の設定（VRAM上のRAMディスクの先頭÷100H）
;〈VRAM上のRAMディスクの先頭〉
;008000H番地
	LD	HL,0080H	;008000H
	LD	(top_of_ram_disk_of_vram),HL

;	[size_of_ram_disk_of_vram]の設定（VRAM上のRAMディスクのサイズ÷100H）
;〈VRAM上のRAMディスクのサイズ〉
;008000Hバイト
	LD	HL,0080H	;008000H
	LD	(size_of_ram_disk_of_vram),HL

;	[top_of_special_work_of_memory]、[size_of_special_work_of_memory]の設定
;〈メモリ特殊ワークの先頭とサイズ〉
;使用しません
	LD	A,00H	;0000H
	LD	(top_of_special_work_of_memory),A
	LD	A,00H	;0000H
	LD	(size_of_special_work_of_memory),A

;	クリック音とジョイスティック
	LD	A,0FFH
	LD	(CLKFLG),A
	LD	A,0FFH
	LD	(JOYFLG),A

;	コールド･スタートします
	LD	HL,0100H	;仮スタック
	LD	(_STKAD),HL
	LD	HL,_COLD
	LD	(0001H),HL
	LD	(0067H),HL
	JP	0000H



	END
